- kuma/wiki/tests/test_views.py
- kuma/wiki/views.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1115767
Spot-check instructions are the same as https://github.com/mozilla/kuma/pull/2966, but check for the custom SMTP headers too.
I'm not super-happy with this code so I could use a critical review on it.
> fix bug 1115767 - SMTP headers for url & username

- kuma/wiki/tasks.py
- kuma/wiki/tests/test_views.py
- kuma/wiki/views.py
This fixes a bad isolation of the send_first_edit_email task that was introduced in bug 1115767.
This prevents passing in the pre-made email object which may contain stateful information.
> Fix bug 1119348 - Moved rendering of first edit email to Celery task

- kuma/wiki/tests/test_views.py
- kuma/wiki/views.py
Spot-check: Delete a document, then go back to its url. Make sure net console shows 410.
> fix bug 1118318 - return 410 for deleted docs

- kuma/actioncounters/migrations/0003_update_unique_hashes.py
Spot-check == `vagrant provision` should work without errors.
> bug 957802 - import actioncounters.utils from kuma

- .gitmodules
- kuma/dashboards/templates/dashboards/includes/revision_dashboard_body.html
- kuma/dashboards/templates/dashboards/revisions.html
- kuma/dashboards/tests/test_views.py
- requirements/prod.txt
- settings.py
- settings_test.py
- vendor/kuma.pth
:disappointed: to add another dependency via submodule, but ...
This will help us fight spammers more efficiently. We can ban IP addresses ourselves with the django admin site interface rather than filing a NetOps bug every time.
To check:
1. `git submodule update --init` to get `django-banish` into `vendor/src`
2. `vagrant provision` to run `syncdb` to create the `banish` models
3. Activate the `store_revision_ips` [waffle switch](https://developer-local.allizom.org/admin/waffle/switch/)
4. Make a revision
5. Go to [the revision dashboard](https://developer-local.allizom.org/en-US/dashboards/revisions)
6. [ ] Click the "Toggle IPs" button
7. [ ] Click "Ban IP"
8. [ ] Enter a reason for the ban
9. [ ] Click Save
10. You should get "Permission Denied" errors for every request
Now, to …
> bug 1113260 - add django-banish to ban by IP

- kuma/wiki/templates/wiki/includes/document_macros.html
- media/redesign/js/wiki.js
Our research shows that more people click the edit button, view the edit
page, and submit completed edits when the page buttons are sticky [1].
Even with this change, page buttons will only be sticky on pages with
tables of content due to bug 1124215 [2].
[1] https://groups.google.com/forum/#!msg/mozilla.dev.mdn/MV1rPgAfTnI/MkC1WAn9JMcJ
[2] https://bugzilla.mozilla.org/show_bug.cgi?id=1124215
> Fix bug 1124199: Page buttons sticky by default

- settings.py
The `sys.maxint` value for `BANISH_ABUSE_THRESHOLD` doesn't seem to work. :disappointed: 
So, disabling django-banish completely until we can sort it out.
> bug 1126412 - disable banish to un-ban KumaScript

- kuma/authkeys/migrations/0003_remove_authkeys.py
- kuma/authkeys/templates/authkeys/list.html
- kuma/authkeys/tests/test_views.py
- kuma/authkeys/views.py
- kuma/users/helpers.py
- kuma/users/templates/users/profile.html
This puts the Add & Delete auth keys views behind the respective permissions. It also includes a data migration to delete all existing authkeys.
> bug 1121918 - put authkeys behind permission

- README.rst
Small fix to the "What's Deployed" link now that we've dropped the dev server.
> bug 957802 - update whatsdeployed link

- kuma/wiki/templates/wiki/includes/document_macros.html
- media/redesign/js/wiki.js
This reverts commit d9369db700f2f1e1e226b5fb57936582fe5c418c.
After turning sticky page buttons on by default, a number of bugs were
discovered. This commit turns the sticky page buttons back off by
default so that the bugs can be fixed.
> Bug 1124199: Revert default sticky buttons

- kuma/search/tests/test_utils.py
- kuma/search/utils.py
This prevents a hard exception on the search page when given a query parameter that doesn't have a value.
> Fix bug 1035569 - Clean out query parameters that are empty.

- settings.py
This increases the logging threadshold to just errors and reintroduces
the RequireDebugFalse filter for the admin email log handler.
> Bug 756533 - Slightly revert logging changes from 96d0d221bb3d297b4af1bcb9e66ebe614f351533.

- kuma/languages.json
- settings.py
Azerbaijani Language for MDN
Bug 1125648
https://bugzilla.mozilla.org/show_bug.cgi?id=1125648
Have no idea about orders in languages.json
+ Documentation for kuma (http://kuma.readthedocs.org/en/latest/localization.html#adding-a-new-locale) should be changed, adding new locale to settings.py is not enough and will give error. It should be added to kuma/languages.json too
> fix bug 1125648

- kuma/users/admin.py
I *think* that this does what is expected in the main bug description. It adds a field Date Joined to the admin display of users, along with a Filter to narrow the result down by date. The details are in https://bugzilla.mozilla.org/show_bug.cgi?id=1084503
> Fix bug 1084503: extend UserAdmin to allow sorting in admin/auth/user view

- kuma/wiki/templates/wiki/document_revisions.html
- media/redesign/js/wiki.js
- media/redesign/stylus/components/wiki/revision-list.styl
This is to address the feature requested in https://bugzilla.mozilla.org/show_bug.cgi?id=1108474 - make the compare revisions button sticky when scrolling the page.
> Fixes bug 1108474: Make compare revisions button on history page sticky

- media/redesign/stylus/components/wiki/toc.styl
Switched from `ol ol` to `li li` to make any type of list item indented (MDN uses `ol` but readthedocs/sphinx uses `ul`).
> Add indentation to toc sub items.

- kuma/wiki/constants.py
- kuma/wiki/managers.py
- kuma/wiki/models.py
- kuma/wiki/tasks.py
This resets the cached document zone remaps when saving documents instead just deleting them when saving the zone.
> Fix bug 1104119 - Cache refill instead of invalidation for document zone remaps.

- media/redesign/stylus/base/elements/typography.styl
- media/redesign/stylus/components/syntax/base.styl
- media/redesign/stylus/components/wiki/content/warning.styl
- media/redesign/stylus/includes/mixins.styl
- media/redesign/stylus/includes/vars.styl
- Beefed up comments in syntax/base.styl
- Added an explicit text-color declaration to the code-block mixin (it's good practice to declare text and bgcolor together)
- Switched to variables for a few things
- Moved margin-bottom declaration off code and moved it to just pre (as code sometimes appears as an inline element)
A page to help with testing: https://developer.mozilla.org/en-US/docs/User:stephaniehobson:code
> Fix Bug 1130026: Code styling in .warning messages

- kuma/search/fields.py
- kuma/search/tests/test_filters.py
- kuma/search/tests/test_serializers.py
- kuma/wiki/search.py
- media/redesign/stylus/search.styl
Quoting MDN...
The HTML <mark> Element represents highlighted text, i.e., a run of
text marked for reference purpose, due to its relevance in a
particular context. For example it can be used in a page showing
search results to highlight every instance of the searched for word.
-- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark
> Fix bug 1132962: Use <mark> for matched terms

- media/redesign/stylus/components/components.styl
- media/redesign/stylus/components/syntax/example.styl
- media/redesign/stylus/includes/mixins.styl
- media/redesign/stylus/includes/vars.styl
- media/redesign/stylus/wiki-syntax.styl
Add styling for good and bad code examples.
Colour blind friendly but not screen reader friendly. Needs to be used in combination with headings.
- added .example-good and .example-bad to be used on code examples
- made some code-block stuff into variables for reuse in new classes
- moved colours from components.styl into vars.styl
- polished comments
Testing: add .example-good or .example-bad to a `<pre>` or `<code>` tag that also has `class="brush:html"` declared on it (needs both the example class AND the prism styling to work).
> Bug - 1125803 - Good & bad code examples.

- media/redesign/js/wiki.js
Now checks button exists before trying to act on it.
Stuff further down in the file has probably been broken since this pushed - youTube tracking and anything relying on debounce :/
> Fix Bug 1134718: JS typeerror

- kuma/users/providers/persona/views.py
- kuma/users/templates/persona/auth.html
- settings.py
To spot-check using the Persona stage server, add this to your `settings_local.py` file:
```
PERSONA_VERIFIER_URL = 'https://verifier.login.anosrep.org/verify'
PERSONA_INCLUDE_URL = 'https://login.anosrep.org/include.js'
```
Then, when you sign in with Persona, make sure the `include.js` asset is coming from `login.anosrep.org`. When you sign in with Persona, you'll probably need to make a new account on the stage server. And if you use a gmail account, you'll be using the new OAuth bridge.
> fix bug 1136293 - move persona host to settings.py

- docs/feature-toggles.rst
- docs/index.rst
- docs/installation-vagrant.rst
- kuma/users/adapters.py
- kuma/users/templates/account/signup_closed.html
- kuma/users/tests/test_templates.py
Supersedes https://github.com/mozilla/kuma/pull/3055 with new docs for all feature toggles, including the new `registration_disabled` flag.
> bug 1124419 - waffle user signup

- kuma/wiki/management/commands/generate_sphinx_template.py
Spot-check:
1. `./manage.py generate_sphinx_template > layout.html`
2. `git clone git@github.com:mozilla/mdn-sphinx-theme.git`
3. `cp layout.html /path/to/mdn-sphinx-theme/mdn_theme/mdn/`
4. `pip install -e /path/to/mdn-sphinx-theme`
5. `cd docs`
6. `make html`
7. `open _build/html/index.html`
> fix bug 1133585 - use prod server for sphinx template

- media/redesign/js/home.js
The easiest way to test this is to insert an `alert()` between lines 16 and 17. I can never seem to figure out how to test `trackEvent` locally, but I'm also not worried about it since it's just like other `trackEvent` calls.
> Bug 1137020: Track homepage search with Optimizely

- kuma/landing/templates/landing/homepage.html
This bug only manifests locally. The "home" bundle is attached to the
homepage asynchronously. The scripts in the bundle still need to be
loaded in order, however.
On production, the scripts *are* loaded in order because the are
concatenated before the whole thing is attached asynchronously.
Locally, each script within the bundle is individually attached
asynchronously, so they're sometimes loaded out of order, causing the
error.
> Fix bug 1139947: Fix homepage Owl Carousel error

- kuma/dashboards/forms.py
- kuma/dashboards/templates/dashboards/revisions.html
- kuma/dashboards/views.py
I think that this needs some i18n polish (because I don't know how that system works in Kuma), but it filters by hour/day/week/month per @a2sheppy's feature request.
> fix bug 1140436: add period url param & select box to revisions dashboard

- media/redesign/stylus/base/utilities.styl
Altered current .hidden class to display in editor and have a dotted black border around it and floating label.
This page already has some instances of .hidden on it and it helpful for testing: https://developer-local.allizom.org/en-US/docs/Web/API/Canvas_API/Tutorial/Basic_animations
I had trouble getting the editor to pull the newly generated stylesheets. Sometimes running `./manage.py compress_assets` helped.
> Fix Bug 931377: Add a class to hide when viewing article but show in editor

- media/redesign/stylus/components/wiki/quick-links.styl
I had a heck of a time testing this one, the macro that generates the quick-links has changed since the last database dump and I was getting timeouts once I updated the macro templates.
1) get everything up and running with the new style sheet compiled and being served (so, a hard refresh).
2) find/create a page with a left sidebar (maybe https://developer-local.allizom.org/en-US/docs/Web/API/AnimationEvent but don't do your hard refresh on this page or you lose the sidebar)
3) copy the HTML for #quick-links as generated on prod on https://developer.mozilla.org/en-US/docs/Web/API/AnimationEvent/pseudoElement
4) using dev tools paste the #quick-links HTML in.
> Fix Bug 1137652:  Add padding for current page in quick links

- .gitmodules
- kuma/actioncounters/utils.py
- kuma/contentflagging/utils.py
- kuma/core/admin.py
- kuma/core/jobs.py
- kuma/core/management/commands/delete_old_ip_bans.py
- kuma/core/managers.py
- kuma/core/migrations/0002_auto__add_ipban.py
- kuma/core/models.py
- kuma/core/tasks.py
- kuma/core/tests/test_models.py
- kuma/core/utils.py
- kuma/dashboards/templates/dashboards/includes/revision_dashboard_body.html
- kuma/wiki/managers.py
- kuma/wiki/tasks.py
- kuma/wiki/tests/test_views.py
- kuma/wiki/views.py
- requirements/prod.txt
- settings.py
- vendor/kuma.pth
**DNM** Sanity-check PR. Here's the approach so far:
* Adding a new `IPBan` model to `kuma.core` (like `UserBan` in `kuma.users`)
* Decorate views with `ratelimit` of a new `limit_banned_ip_to_0` util function
Pro: Simpler code that uses `django-ratelimit` (a well-supported popular library) as its designed
Con: Have to decorate each view (or add mixin to CBV's)
Overall I'm liking this approach more than `django-banish` or any others we've tried so far.
> bug 1113260 - use django-ratelimit for ip bans

- configs/htaccess
We need to redirect from /media/redesign to /media. This htaccess
redirect won't have any affect locally (because we alias /media in
mozilla-kuma-apache.conf), but it might work on production where the
alias isn't active.
Unfortunately, the only way to know for sure is to try it out. If this
doesn't do the trick, we can revert this change and work with WebOps to
set up the redirects in whatever form their configuration requires.
> Bug 1139508: Redirect media/redesign with htaccess

- kuma/core/admin.py
- kuma/core/models.py
Spot check:
0. Make sure you're running the `python2.6 manage.py celery worker --events --beat --autoreload --concurrency=4` process
1. Activate [waffle switch](https://developer-local.allizom.org/admin/waffle/switch/) `store_revision_ips`
2. Make an edit
3. Go to [the revisions dashboard](https://developer-local.allizom.org/en-US/dashboards/revisions), click "Toggle IPs" and then click "Ban IP from Editing"
4. [ ] Go back to the edit page, verify you get permission denied error page
5. Go to [the IP Bans admin page](https://developer-local.allizom.org/admin/core/ipban/), click the IP Ban, click "Delete" and then "Yes, I'm sure"
6. [ ] Go back to the edit page, verify you get the edit page
> bug 1113260 - manual IP ban & un-ban

- kuma/wiki/tests/test_views.py
- kuma/wiki/views.py
The initial title and slug for a new cloned page should not default to "original_title" and "original_title_clone," respectively, but instead remain blank (requiring manual user entry) to avoid the accidental creation of confusing, seemingly duplicate entries.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1086519.
> Bug 1086519 - Leave new title and slug for cloned pages blank [take 2]

- media/stylus/components/wiki/customcss.styl
- media/stylus/components/wiki/quick-links.styl
- Consolidated quick links code into one file.
- Moved p and div declaration outside of the icon selector.
- Consolidated link style declarations
- Moved .see-also declaration inside of .title declaration so relationship between the two is clearer.
- Restricted toggle icon styles to toggle icon so they don't have to be over-written by sidebar-icon styles anymore
- Altered sidebar-icon styles to be more RTL friendly
- Moved some things into variables or made use of existing ones
- Instead of absolute positioning, icons are placed in the gutter by having a negative margin on the first icon. Subsequent icons appear inline so they don't overlap anymore.
Testing pages:
- https://developer.mozilla.org/en-US/docs/Web/API/AnimationEvent/initAnimationEvent
- …
> Fix Bug 1137656: Overlapping icons in quick links

- media/js/wiki.js
- media/stylus/components/wiki/page-buttons.styl
I'm setting a different `position` on the `small-desktop`, like we do for the TOC, to signal the buttons should not follow if on a smaller screen.
I've also eased up on the debounce.  All the scroll functionality is taxing right now.
> fix bug 1126461 - Don't sticky buttons when on smaller screens

- configs/htaccess
We added this redirect to .htaccess experimentally. We knew it had no
effect locally and were wondering if it would have any effect on our
stage and production servers.
This ultimately had no effect on our servers, so we asked WebOps [1] to
define this redirect in our main Apache config instead.
[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1145793
> Bug 1145793: Remove .htaccess redesign redirect

- media/js/home.js
The search box code will actually always run because `length` isn't checked, but I've made all of the code shorter.
> fix bug 1149681 - Optimize the homepage JS

- kuma/wiki/templates/wiki/document.html
- media/js/wiki.js
Should've just used the full URL in the `data-` attribute in the first place.
> fix bug 1115071 - Ensure correct addresses for context menu items

- scripts/chief_deploy.py
This addresses bug 1139291 (issue originally raised in bug 1129604).
> Update supervisorctl command restarting celery to escape wildcard 

- kuma/wiki/templates/wiki/document.html
- kuma/wiki/templates/wiki/includes/document_macros.html
- media/stylus/components/share-link.styl
- media/stylus/components/share.styl
- media/stylus/wiki.styl
Styling for 3 different types of buttons going in 3 different places.
Classes:
.share
.share.share-group
.share.share-thin
All hidden by default at the moment, show by adding class `show` to the element with class `share`
Here's a screen shot of the `share.share-thin` positioned under the title, `share.share-group` positioned in the TOC, and the default `.share` under the article.
> Bug 1145630: Social Sharing A/B tests

- kuma/wiki/tests/test_views.py
- kuma/wiki/views.py
See https://bugzilla.mozilla.org/show_bug.cgi?id=1152191#c1
> Fix bug 1152191: Properly serve error json for non-existent docs in children api

- media/stylus/base/elements/typography.styl
- media/stylus/components/content.styl
- media/stylus/components/fellowship/cta.styl
- media/stylus/components/fellowship/pullquote.styl
- media/stylus/components/wiki/customcss.styl
- media/stylus/components/wiki/edit/first-contrib-welcome.styl
- media/stylus/components/wiki/topicpage-table.styl
- media/stylus/includes/vars.styl
- media/stylus/wiki-wysiwyg.styl
Some clean up in anticipation of changes to font stuff:
- Use variable to set font family
- Use mixin to set font size
- Added Arial to fallback list (more size appropriate than Helvetia which is Mac sans-serif default)
- Line-height and letter-spacing should be relative to font-size not pixels
> Bug 1150118 - Lazy load fonts

- media/stylus/components/wiki/intrinsic.styl
- media/stylus/wiki.styl
Using the switch to the macro for youtube imbeds to take this opportunity to improve how the videos display at different screen sizes.
Works in concert with https://developer.mozilla.org/en-US/docs/Template:EmbedYouTube
Here's some content with videos you can alter to test: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Work_with_animations
Testing:
- create the macro on your local test environment
- fire up kumascript
- embed some videos like so `{{ EmbedYouTube('mDHtLK88ZW4') }}`
- resize your browser window and watch the ratio be maintained
> Bug 1151523 - intrinsic ratio youtube iframes

- kuma/wiki/templates/wiki/includes/document_macros.html
I think this "Google +" is strange, usually "Google+" or "Google Plus".
Related pull requests: #3124, #3142.
> "Google +" to "Google+"

- kuma/wiki/templates/wiki/select_locale.html
The parens look wonky in RTL in this list.  Fixing it.
> fix bug 1149282 - Ensure proper paren placement in locales list

- media/stylus/components/wiki/customcss.styl
- media/stylus/components/wiki/summary-box.styl
- media/stylus/wiki.styl
- made styles applicable to both ul and table for all colours of summary box
- standardized styles for both ul and table to match
- moved summary box classes into separate .styl file
- converted declarations to pre-processor syntax (variables! nesting! FTW!)
- RTL bugs
Supersedes #3179
Testing: 
Old style summary box made on a list: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/b
New style summary box made on a table: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr
Testing page with both side by side: https://developer.allizom.org/en-US/docs/User:stephaniehobson:summary-box
> Fix Bug Bug 1154283: Use summary box on tables

- media/js/main.js
- media/stylus/components/structure.styl
- templates/base.html
Supercedes https://github.com/mozilla/kuma/pull/3181
Added a change so that the link doesn't display until tabzilla has loaded.
> Lazyload Tabzilla Stylesheet

- kuma/wiki/templates/wiki/document.html
- media/stylus/components/wiki/page-buttons.styl
A recent A/B test showed that around 31% more people click the edit
button when it's a darker shade of blue.
Full results: http://optimize.ly/~KSOEmr?token=63f0bef5c746e00caa31#view=2
Analysis: https://groups.google.com/d/msg/mozilla.dev.mdn/98GP_Vh30Cc/GSL_L-f-pJYJ
> Make edit button dark blue

- Vagrantfile
Spot-check:
```
vagrant halt
vagrant destroy
vagrant up
```
Should work as documented in [the vagrant docs](http://kuma.readthedocs.org/en/latest/installation-vagrant.html).
> bug 957802 - pin puppetlabs-apt module version

- media/stylus/components/syntax/syntaxbox.styl
White-space declaration wasn't being applied because the selector was too specific. This moves it up to a more general selector.
Supersedes #3143.
> Fix Bug 1148738 - Syntax boxes should wrap

- kuma/demos/templates/demos/flag.html
Changed document structure so button inherits correct styles.
To test:
1) go to [a demo](https://developer.mozilla.org/en-US/demos/detail/bananabread)
2) click "demo not working"
3) look for submit button. Is it white on light grey or white on blue?
> Fix Bug 1158614 - "flag content" button hard to read

- kuma/wiki/templates/wiki/ckeditor_config.js
- kuma/wiki/views.py
The first step in preventing IFRAMEs in CKEditor per the bug in the title.
Relevant:  http://docs.ckeditor.com/#!/guide/dev_disallowed_content
> bug 1151523 - Disallow IFRAMEs from CKEditor

- kuma/wiki/templates/wiki/ckeditor_config.js
This alternate configuration should explicitly allow classes and attributes for code samples.  To test:
- Add an iframe, ensure it doesn't display in content mode
-  Add an image, allow SRC
> fix bug 1151523 - Ensure allowedContent receives an object that allows classes and attribtues

- settings.py
When using percent-activated flags, django-waffle is supposed to
permanently group a user into one variation or another. Before this
change, this was not happening. The probability of a flag being active
was re-determined on every page load.
This change adds the django-waffle middleware to our stack. This gives
django-waffle the opportunity to set a cookie and, in turn, use
percent-activated flags as intended.
> Bug 1100690: Let django-waffle bucket users

- media/stylus/base/fonts/moztt.styl
- media/stylus/gaia.styl
- settings.py
Getting moztt to be included in Gaia 1.0 demos.
- changed declaration to pull font without CDN (I could not locate the fonts in the CDN, but this is how we include the font-face milk as well so I am copying an existent convention)
- created separate gaia.styl file to include global fonts for demos (just font faces at the moment)
Testing:
1) Edit line 12 of https://developer-local.allizom.org/en-US/docs/Template:FXOSUXLiveSampleSetup to be `@import url('/media/css/gaia.css');`
2) Start ALL THE PROCESSES. You're going to need kumascript for this one
3) Testing page: https://developer-local.allizom.org/en-US/Apps/Design/Firefox_OS_building_blocks/1.x/Confirmation/Coding You're looking to see that the font loads in the Gaia demos, identified by orange boxes. Compare to same page on prod, if …
> Fix Bug: 1143084 - moztt use

- kuma/wiki/templates/wiki/ckeditor_config.js
Implements Ctrl+0 (Cmd-0) as a key shortcut for the "Remove formatting" option in
CKEditor (bug 775569).
There are also some fixes which are parts of other general editing clean-up
bugs:
* Removed the "Right sidebar" and "Callout box" styles from
the Style drop-down menu.
* Added the key shortcut Ctrl+Shift+K (Cmd-Shift-K) for "Remove link".
> Bug 775569 and other small fixes

- media/js/fonts.js
Let's experiment with this for a week. It's not quite the "Can we just not swap out the fonts on first load" some people are asking for but it decreases how far someone can get before the swap happens, if it happens at all.
> Bug 1150118: Dropping time out to 2 seconds

- media/stylus/base/elements/typography.styl
- media/stylus/components/wiki/document-head.styl
Added word-wrap: break-word to auto-break when necessary. Added hyphens: auto to add hyphen at break for supporting browser/locale combos.
Moved line height 1 declaration to apply to all headings by default and over ride for h1 (instead of applying to all and being over ridden by all but h1).
Decreased line height on document head. Increased margins on document head to account for decreased line height.
Before:
After:
> Fix Bug 1148752 - CSS break long article titles.

- media/stylus/base/elements/typography.styl
- media/stylus/diff.styl
- media/stylus/includes/mixins.styl
- media/stylus/includes/vars.styl
- media/stylus/wiki-wysiwyg.styl
Changed `<code>` and `<kbd>` appearing outside of `<pre>` to use Courier New instead of Consolas. I tried to standardize on Consolas a while back but it's too hard to differentiate it from open-sans.
Also increased the weight of Courier New.
Test page: https://developer.mozilla.org/en-US/docs/User:stephaniehobson:code Only the inline tags in the first paragraph and heading should change (and they should get easier to spot).
> Fix Bug 1126320 - Increase Inline Code Tag Visibility

- kuma/wiki/content.py
- kuma/wiki/tests/test_content.py
This is actually @Elchi3's code & commit superseding https://github.com/mozilla/kuma/pull/3207 but git wouldn't let me cherry-pick the 2 file changes out of the commit without clobbering the commit author. :frowning:
> Fix bug 1156936: No longer escape section ids

- .travis.yml
- provisioning/travis.yml
- provisioning/vagrant.yml
- requirements/travis.txt
- tox.ini
- get rid of Python 2.6 task
- Set compiler flag in Travis
- Use Ubuntu's keyserver to get the MySQL PGP key as it's more reliable
> Bug 1116335 - Improve Travis config.

- scripts/anonymize.sql
This makes it easier for DBA to run the anonymize script.
> bug 1133709 - use '!' to blank password field

- scripts/anonymize.py
- scripts/chief_deploy.py
The syncdb command is deprecated in Django 1.7 (https://docs.djangoproject.com/en/1.7/ref/django-admin/#syncdb).
> Bug 1116335 - Don't run syncdb during deployment but only the new migrate command.

- media/stylus/base/elements/typography.styl
- media/stylus/includes/vars.styl
Dialing back the visibility a bit.
Changed font to Courier since Courier New is too fine at the regular weight. 
Removed default bold.
> Fix Bug 1126320 - Inline code tag visibility

- kuma/wiki/models.py
- kuma/wiki/tests/test_views.py
- kuma/wiki/views.py
When somebody completes Technical/Editorial review, Comment will be added automatically to database. 
-- What it was is: when ever somebody completes the Editorial/Technical review, it was adding "Editorial/Technical review completed" in "summary" column of  "wiki_revision" table leaving the comment field empty.
-- What i did is: I also added "Editorial/Technical review completed"  in "comment" column of "wiki_revision" table  when somebody review the document.
> fix bug 1158888 - Added comment "Technical/Editorial review completed"

- CONTRIBUTING.md
Fix the broken link to the documentation page on installing the
development environment in CONTRIBUTING.md.
> fix bug 1175873 - Fix broken link in CONTRIBUTING.md

- kuma/wiki/helpers.py
- kuma/wiki/tests/__init__.py
- kuma/wiki/tests/test_helpers.py
This basically works around the upstream issue in difflib, which is documented in the many 3rd party bug reports:
- https://bugzilla.redhat.com/show_bug.cgi?id=1221169
- https://github.com/wbsoft/frescobaldi/issues/674
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=784940
- https://bugzilla.mozilla.org/show_bug.cgi?id=1149667
> Fix bug 1173395 - Don't pass in non-ASCII pseudo filenames to difflib.

- kuma/wiki/views.py
This change seems to remove a number of duplicate queries to the `wiki_revision` table. According to New Relic, those queries add an average of 80-90ms to (20% of) our backend response time on document views.
> bug 1177264 - use doc.get_contributors in document view

- media/stylus/components/content.styl
Final word on striped tables. Stripes all tables with class .standard-table. Stripes can be removed by adding 'nostripe' class to table.
> fix bug 1156233 - zebra stripe tables

- media/stylus/base/elements/forms.styl
- media/stylus/components/components.styl
- media/stylus/components/content.styl
- media/stylus/components/home/home-contribute.styl
- media/stylus/components/home/home-demos.styl
- media/stylus/components/share-link.styl
- media/stylus/components/share.styl
- media/stylus/components/structure.styl
- media/stylus/components/tags.styl
- media/stylus/components/wiki/contributor-avatars.styl
- media/stylus/components/wiki/quick-links.styl
- media/stylus/components/wiki/reviews.styl
- media/stylus/components/wiki/summary-box.styl
- media/stylus/dashboards.styl
- media/stylus/includes/vars.styl
- media/stylus/zones.styl
Also fix bug 1177223: change list item spacing to margin instead of padding.
Created variables $content-horizontal-spacing and $content-vertical-spacing and attempted to replace references to 6px and 8px with them. Please note: I have attempted to replicate the most common current usage of these values, discussing if there is value in these design decisions is out of the scope of this PR.
Minor display changes in some places, no more than 2px difference, all of which I think are acceptable.
Test pages:
https://developer-local.mozilla.org/en-US/docs/User:teoli/In_content
- quick links
- specification tables (small change)
- summary boxes (small change, partially due to li change)
- there's also a few lists where you can see the effect of the switch from padding to margin
Your profile page …
> Fix Bug 1177571: Standardize and variablize item spacing 

- media/stylus/components/share.styl
- media/stylus/components/wiki/customcss.styl
- media/stylus/components/wiki/topicpage-table.styl
- media/stylus/includes/vars.styl
Makes breakpoints into variables outside of media queries, implements new variables in places where they'd be useful.
> Fix Bug 1175248: Move breakpoints into reusable variables.

- docs/installation.rst
Superseding https://github.com/mozilla/kuma/pull/3279 with bug # in commit message.
> bug 957802 - Remove bootcamp link 

- kuma/wiki/models.py
- kuma/wiki/tasks.py
- kuma/wiki/tests/test_models.py
This also fixes and reenables some deferred tests that were skipped.
> Fix bug 1178252 - Stop updated the json blob when a wiki document is logically deleted like when it's marked as spam.

- kuma/wiki/tasks.py
- kuma/wiki/tests/test_tasks.py
This does a bunch of things:
- limit the documents we want to write sitemap files for (by using an already existing model manager)
- stop fetching the html blob from the database
- split the sitemap building into tasks per locale to distribute load to all celery nodes
- use a chord to write the sitemap index after building all individual sitemap files
- write sitemap files that are above the 50k items per sitemap limit instead of just the first one
> Bug 1125850 - Optimize sitemap celery task

- kuma/wiki/templates/wiki/includes/document_macros.html
Eliminates another 3 db queries to `wiki_document` from `document_macros.html`
> bug 1177264 - use other_translations cache property

- kuma/wiki/jobs.py
- kuma/wiki/models.py
- kuma/wiki/templates/wiki/document.html
- kuma/wiki/tests/test_models.py
- kuma/wiki/views.py
In other words, the active user with the most recent edit shows up first.
This also moves the fetching of the contributors into a cacheback job to be able to invalidate the cache asynchronously.
> Bug 1177798 - Order contributors by recency of last edit.

- requirements/source.txt
This fixes a regression in e6940b8141ff1ce312ad7057d08d0b40af59465b.
> Bug 1054265 - Updated django-allauth to 0.21.0.

- .travis.yml
- README.rst
- requirements/travis.txt
The rational here is simple, [Codecov](https://codecov.io/#features) is a better UI for coverage.
> Bug 957802 - Switch to Codecov from coveralls.

- media/stylus/components/structure.styl
When viewing the mobile site with the header site search expanded it should appear centered.
Test in RTL as well.
> Fix Bug 1180280: Mobile search field

- kuma/users/tests/test_templates.py
- media/stylus/components/home/base.styl
- media/stylus/components/structure.styl
- media/stylus/includes/mixins.styl
- media/stylus/zones.styl
- templates/includes/login.html
- tests/ui/tests/auth.js
- tests/ui/tests/lib/login.js
Renamed user-state to oauth-logged-in to mirror oauth-login class as the two components swap places depending on user state. (I know this seems picky but it's to support some other more complex changes).
Testing:
- sign in, make sure signout widget displays correctly
> Bug 815693: Rename .user-state

- media/stylus/includes/vars.styl
After this change, the font used for `<code>` elements should be the same on Windows and Mac. On Linux, a better, easier-to-read font should be used instead.
> Fix bug 1177468: Improve <code> font on Linux

- kuma/core/context_processors.py
- kuma/core/i18n.py
- kuma/wiki/models.py
- kuma/wiki/templates/wiki/translate.html
- kuma/wiki/views.py
- settings.py
This should stop the intense memory/memcache usage.
This was basically code laziness gone wrong. Instead we'll populate the mapping now once per process as a global module variable and leave it there until we redeploy at which we run the product_details update management command anyway.
Also get rid of a few old and unused settings.
> Bug 1177264 - Stop LANGUAGES_DICT being populated on every request.

- kuma/wiki/tasks.py
This is a test to see if that reduces the memory/swap usage of the celery workers.
> Bug 1125850 - Reduce the chunk size for rendering stale documents by 50%.

- .gitmodules
- kuma/users/tests/test_tasks.py
- kuma/wiki/content.py
- kuma/wiki/tests/__init__.py
Updates for issues found when running tests (`./manage.py test`) in a new vagrant install, with just a `git submodule update` and a superuser:
* Some content tests failed due to attribute order.  Adjusted the content tool to alpha-sort attributes in tests, but leave them alone in regular content flow.
* Some submodules don't ignore *.pyc files, so I set them to ignore non-tracked files, so that `git status` is clean.
* A test required setting up translated strings.  Fixed the mock so it works w/o translations installed.
> bug 957802 - Fix issues running tests in new vagrant install

- kuma/core/urlresolvers.py
Per [the latest New Relic thread profile](https://rpm.newrelic.com/accounts/263620/applications/3172075/profiles/1711678), `kuma.core.urlresolvers.py.reverse` takes up as much as:
* 11% (in calls from `wiki_url` in `base.html`)
* 6.7% (during calls from `helpers.py.url` in `document_macros.html`)
* 4.7% (during calls from `Document.get_absolute_url` from `document.html` `extra_head` block)
* 4% (during calls from `Document.get_absolute_url` from `document.html` `lang_switcher` block)
* 1.3% (during calls from `wiki_url` in `base.html` `footer_copyright_redesign` block)
* A couple other areas of 0-1%
For a total of 27.7%+ of all back end execution time. The majority of the time spent in `reverse` is spent waiting on the `memcache.py._get` in the `DocumentZoneURLRemapsJob`. This job remaps …
> bug 1177264 - waffle switch for dumb doc urls

- kuma/wiki/content.py
- kuma/wiki/tests/test_content.py
Pyquery now uses cssselect which raises a syntax exception when using the `#<id>` shorthand instead of the more proper selector `[id="<id>"]`.
This is a regression of us updating pyquery.
Fix bug 1179525.
> Fix bug 1173170 - Fix code section extraction to work with updated pyquery.

- kuma/attachments/feeds.py
- kuma/dashboards/templates/dashboards/includes/revision_dashboard_body.html
- kuma/demos/feeds.py
- kuma/demos/templates/demos/elements/profile_link.html
- kuma/users/models.py
- kuma/users/templates/users/profile.html
- kuma/users/templates/users/profile_edit.html
- kuma/users/tests/test_models.py
- kuma/users/views.py
- kuma/wiki/events.py
- kuma/wiki/feeds.py
- kuma/wiki/helpers.py
- kuma/wiki/models.py
- kuma/wiki/templates/wiki/edit_document.html
- kuma/wiki/tests/test_models.py
- kuma/wiki/views.py
- settings.py
This does a bunch of things:
- Move revision helper to custom user model (ref bug 1180208).
- Use else clause for for loop for getting rid of slow count query.
- Prefetch revision documents to reduce related queries.
- Use a cached property for the previous revision for in-page load caching.
- Refactor the gravatar method with better caching.
> Fix bug 1179897 - Reduce number of db queries on profile page.

- provisioning/roles/geerlingguy.mysql/files/etc/init.d/mysql
- provisioning/roles/geerlingguy.mysql/tasks/setup-Debian.yml
/etc/init.d/mysql greps for the mysql process to determine if mysql is running.  When running, the process count includes the mysqld process and the grep for that process (count=2).  However, 5% - 10% of the time (and maybe more common under vagrant / ansible), the grep is not in the process list, causing false negatives when detecting the mysqld process is running.  When provisioning, this results in the utf8_distinct_ci coalition not being applied, migrations failing, and provision failing until mysql is restarted (maybe by rebooting the vagrant instance).
This new init script ignores the grep process, making the run detection more reliable.  Tested by cleanly running `vagrant up` from scratch.
> bug 957802 - Improve mysql init script

- kuma/core/urlresolvers.py
- kuma/wiki/tests/test_middleware.py
I [asked if the new behavior is an improvement in the bug about language-specific header links](https://bugzilla.mozilla.org/show_bug.cgi?id=1089537#c16) and [the original reporter verified the new behavior is better](https://bugzilla.mozilla.org/show_bug.cgi?id=1089537#c17).
So, this makes the change permanent to improve the UX **and** the response time.
> bug 1177264 - make dumb_doc_urls change permanent

- kuma/users/tests/test_views.py
This is a case of a monkeypatch in jingo being out of date and a regression from us updating to a current Django release while jingo hasn't been released yet.
This makes use of https://github.com/jbalogh/jingo/commit/0d293ae8aefa0419961ab6480f38a3d2dfbadc44 and its explicit monkey patching of the `django.forms.widgets.RadioChoiceInput` class that replaces the old `django.forms.widgets.RadioInput`.
Note: There is https://github.com/jbalogh/jingo/issues/67 to ask the maintainers to do a proper release with little results yet.
> Fix bug 1174804 - Fix rendering of choice fields with Django >=1.7.

- media/js/wiki.js
As we roll out the contributor bar, we want to record which contribution **position** is clicked so we know if users tend to click the contributors listed first. Not sure why this was changed in https://github.com/mozilla/kuma/commit/42a74bed25f578a05da32a12b32cb92eadf6c430
> bug 997788 - fix ga event label to track position clicked

- media/stylus/components/demos/studio.styl
- media/stylus/components/home/base.styl
- media/stylus/components/structure.styl
- media/stylus/includes/mixins.styl
- media/stylus/zones.styl
Also Fix Bug 1070048
Basic idea is all elements in header now inherit text and link colours from the #header.
Test:
Check that menu items and sign/out widget have correct colours on:
- home
- a zone
- profile
- a wiki article
> Bug 815693: Change main nav mixin to apply to header

- .gitignore
I always worry when copying the sanitized database dump to the project
root before importing it. Let's be sure it can never be committed.
> Bug 957802: Ignore sanitized database dump

- kuma/users/templates/users/profile_edit.html
- media/js/profile.js
Allowed space in interest tag and removed repeated insertion of JavaScript.
So the JS bundle "jquery-ui", "demostudio" and "profile" were repeatedly adding following JS file.
1) "js/libs/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.min.js"  AND
2)"js/moz-jquery-plugins.js"
That was creating the problem.
Also space needed to allowed in "tag-it" Library.
> bug 1038036

- kuma/users/templates/users/profile.html
Per https://bugzilla.mozilla.org/show_bug.cgi?id=1182627#c0, the Yahoo crawler is getting into `compare_revisions` and triggering slow transactions that are affecting python response times.
This adds `rel="nofollow"` to the last `compare_revisions` link on the site that was missing it. It should discourage more slow transactions from crawlers like Yahoo.
> bug 1182627 - add nofollow to profile compare link

- kuma/search/store.py
- kuma/search/templates/search/down.html
- kuma/search/tests/test_views.py
- kuma/search/utils.py
This shows a 404 for the search if it's not working because of a decoding error of search query parameters.
> Fix bug 1173178 - Catch Unicode decode errors in the search API.

- kuma/wiki/templates/wiki/document.html
- media/js/components.js
- media/js/helpfulness.js
- settings.py
This is an experiment to determine whether people use the feature and whether we use the data from it.
> [bug 1032455] Add helpfulness interface using GA

- media/js/wiki-samples.js
- media/stylus/base/elements/forms.styl
- settings.py
Supercedes https://github.com/mozilla/kuma/pull/3240
I needed to redo this due to the VM change -- things go weird.
How to test:
1.  Create a macro called `EmbedLiveSample`:  https://gist.github.com/darkwing/cbd69a8756081d482474  (this was changed)
2.  Create a macro called `LiveSampleURL`:  https://gist.github.com/darkwing/4b09b0b1d1e6e41a66d2  (this is unchanged)
3.  Create a document with the following content:  https://gist.github.com/darkwing/0dd8cdaba22497efb76c
You should see the "Open" buttons above the rendered sample
> Bug 1148743 - Open jsfiddle and CodePen for Samples

- media/js/fonts.js
Tabzilla is loading multiple times, changing the true/false evaluations back to this format stops it. Javascript FTW!
> Fix Bug 1184218: Tabzilla won't stay open

- media/stylus/components/mdn10/chapter.styl
- media/stylus/components/mdn10/quote.styl
Hide "Open in Codepen" button and prevent quotation mark from messing with text line height.
> Bug 1185627: MDN 10th - chapter audio and quote tweaks

- Vagrantfile
The call to `config.env.enable` was needed to be done before reading the env vars.
> Various Vagrant fixes.

- media/js/wiki.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1184601
> fix bug 1184601 - Remove YouTube video load tracking

- README.rst
Supersedes https://github.com/mozilla/kuma/pull/3361 with bug in commit message.
> bug 957802 - license badge

- .travis.yml
I guess we'll see if Travis still builds PRs even though they're not the master branch.
> bug 1118735 - only build master branch on push

- kuma/wiki/templates/wiki/includes/document_tag.html
Per [the latest New Relic profile](https://rpm.newrelic.com/accounts/263620/applications/3172075/profiles/1716288), 1.1% of app server time is spent in `django/db/models/query.py.exists` [called by `kuma/wiki/templates/wiki/includes/document_tag.html`](https://github.com/mozilla/kuma/blob/374c12e203f80ade3d77aa401e3b6a99b1fa1a36/kuma/wiki/templates/wiki/includes/document_tag.html#L1).
This check is superfluous, because:
1. Both calling templates: [`document.html`](https://github.com/mozilla/kuma/blob/374c12e203f80ade3d77aa401e3b6a99b1fa1a36/kuma/wiki/templates/wiki/document.html#L356-L357) and [`revision.html`](https://github.com/mozilla/kuma/blob/374c12e203f80ade3d77aa401e3b6a99b1fa1a36/kuma/wiki/templates/wiki/revision.html#L56-L57) call `tags.all()` anyway
2. Most requests are to …
> bug 1177264 - remove extra tags.exists() check (1.1% of app server time)

- kuma/landing/templates/landing/homepage.html
- kuma/landing/views.py
- settings.py
- templates/includes/config.html
Per [the latest New Relic profile](https://rpm.newrelic.com/accounts/263620/applications/3172075/profiles/1716288), at least 12.8% of app server time was spent in `kuma/search/context_processors.py.search_filters`.
On top of the fact that [the search filter feature is currently waffled off](https://developer.mozilla.org/admin/waffle/flag/65/), the `searchFilters` json is only needed on the home page, where search filter suggestions are displayed (when the feature is waffled on.)
So, I moved its logic into the `homepage` view to cut out the time spent processing this context during other views.
Spot-check:
* Go to home page
* Go to a document page
> bug 1177264 - remove search_filters context processor (12.8% of app server time)

- kuma/wiki/middleware.py
Redirecting POST $subscribe requests to zone urls causes a GET to $subscribe,
which has @require_POST decorator.
I'm not sold on this approach, though. :confused: 
Checks:
> fix bug 1189222 - $subscribe: skip zone middleware

- settings.py
Spot-check on this branch:
1. [Get the localizations](http://kuma.readthedocs.org/en/latest/localization.html#get-localizations) if you don't already have them.
2.
```
cd locale
svn up
./compile-mo.sh .
```
3. Go to https://developer-local.allizom.org/sv-SE/ and make sure it pulls up.
4. Translate a test document into Svenska.
> fix bug 1188297 - add sv-SE locale

- requirements/source.txt
As we [discussed in IRC and noted in the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1191497#c1), the python-memcached update introduced errors with the way cached inclusion tag output is stored into and/or retrieved out of memcache.
Rolling back to stop the 1000+ errors this is causing on the live site.
Spot-check:
* `git submodule update --init && find . -name "*.pyc" | xargs rm -f`
* Go to https://developer-local.allizom.org/en-US/demos/
* Refresh a few times
* Go to https://developer-local.allizom.org/es/demos/
* Refresh a few times
> fix bug 1191497 - roll back python-memcached update

- kuma/wiki/__init__.py
- kuma/wiki/apps.py
- kuma/wiki/events.py
- kuma/wiki/feeds.py
- kuma/wiki/helpers.py
- kuma/wiki/migrations/0006_revision_tidied_content.py
- kuma/wiki/models.py
- kuma/wiki/search.py
- kuma/wiki/tasks.py
- kuma/wiki/templates/wiki/edit_document.html
- kuma/wiki/templates/wiki/includes/document_macros.html
- kuma/wiki/templates/wiki/includes/revision_diff_table.html
- kuma/wiki/utils.py
- kuma/wiki/views.py
- settings.py
- Adds ratelimiting to the compare revision view.
- Refactors the signal handling to use new patterns and less confusing code.
- Prefetch revision tags and document for fewer queries.
- Denormalize the revision content in a separate field that is filled on save and uses tidy to do the CPU-intense work once instead of on every request.
> Bug 1190171 - Revision content denormalization and other cleanups of the compare revision view.

- media/stylus/includes/mixin_submenu.styl
Removed min-height from submenus.
> Bug 1190284 - Whitespace at the bottom of languages drop down menu

- kuma/users/templates/persona/auth.html
- kuma/users/templates/socialaccount/snippets/provider_list.html
- media/js/auth.js
- templates/includes/login.html
- tests/ui/tests/auth.js
- tests/ui/tests/lib/login.js
- tests/ui/tests/lib/poll.js
Before we added GitHub login support, we were lazyloading the (sometimes slow) Persona javascript file.  This restores said functionality.
> Make Persona login async

- kuma/wiki/templates/wiki/document.html
- templates/base.html
Neither of these resources require a fully loaded page so we can make them async
> bug 1193427 - Make 'social' and 'helpfulness' resources async

- docs/localization.rst
- kuma/core/helpers.py
- kuma/core/jobs.py
- settings.py
- templates/base.html
- templates/includes/config.html
- tox.ini
- urls.py
This makes use of the "javascript" domain name used by the non-standard i18n setup Mozilla uses.
Also move to using a cacheback job to profit from thundering herd protection etc.
> Fix bug 1193815 - Fixed rendering of JavaScript translation catalogs.

- settings.py
Spot-check on this branch:
1. [Get the localizations](http://kuma.readthedocs.org/en/latest/localization.html#get-localizations) if you don't already have them.
2.
```
cd locale
svn up
./compile-mo.sh .
```
3. Go to https://developer-local.allizom.org/mg/ and make sure it pulls up.
4. Translate a test document into Malagasy.
> fix bug 1190582 - add Malagasy locale

- kuma/wiki/tests/test_views.py
- kuma/wiki/views.py
We shouldn't throw 404s on the entire request just because we can't find a page's root document while generating the title for SEO purposes.
> fix bug 1190212 - no 404s from parent seo title

- media/js/wiki-samples.js
The `EmbedLiveSample` allows to embed a sample that comes from a remote page. This patch make sure that in such case the proper code is retrieve from the right page before sending it.
> bug 1194482 - Live sample don't send code to service if code comes from another page

- media/js/fonts.js
- settings.py
Since this is no longer waffled, we don't need to load the item via AJAX.  Save a request.
> fix bug 1193455 - Include font observer in main package

- docs/localization.rst
- settings.py
Also updating localization instructions with new `compilejsi18n` step.
Spot-check on this branch:
1. [Get the localizations](http://kuma.readthedocs.org/en/latest/localization.html#get-localizations) if you don't already have them.
2.
```
cd locale
svn up
./compile-mo.sh .
```
3. Go to https://developer-local.allizom.org/tn/ and make sure it pulls up.
4. Translate a test document into Tswana.
> bug 1192905 - add Tswana locale

- kuma/wiki/constants.py
- media/stylus/base/elements/sectioning.styl
- media/stylus/wiki-wysiwyg.styl
Added `<summary>` to allowed tags and `open` to allowed attributes on `<details>`. 
Added CSS to make `<summary>` look clickable and outline `<details>` in editor view.
@darkwing do I need to re-build CKEditor and commit those files to make these changes take effect?
> Bug 1189515 - Details and summary

- media/stylus/components/wiki/indicators.styl
Upping the specificity on this to override the cascade.
I want to fix the mess that is the 40 classes we're using quite badly.
> Bug 1144134 - editorial reviews should be yellow

- kuma/wiki/views/list.py
The template was moved from ``wiki/list_tags.html`` to ``wiki/list/tags.html``
> bug 1195335 - Fix path to wiki/list/tags.html

- .travis.yml
- scripts/travis-install
Alternative to https://github.com/mozilla/kuma/pull/3426: try using Travis CI's built-in elastic search service. Doesn't version-match to prod, but it's better than the all-out failures we have now.
> bug 1196342 - use Travis elasticsearch service

- settings_test.py
This drives me crazy when I'm trying to debug tests and have to scroll all the way up thru a bunch of `DEBUG` level output from `django.db.backends.schema`. I even [asked on Stack Overflow](https://stackoverflow.com/questions/32158773/how-do-i-disable-django-migration-debug-logging) and I wonder if this is an upstream bug in/between django or django-nose? (@jwhitlock - you do django-nose now right?)
> bug 957802 - set db logging to warn during tests

- kuma/wiki/templates/wiki/document.html
- media/stylus/components/wiki/indicators.styl
Adding language icon to in translation warning.
Removing first-line styling (beginning with a strong tag is a convention I would like the writers to follow but not one I should be enforcing with CSS)
> Bug 1144134 - indicator refinements

- kuma/wiki/tests/test_views.py
- kuma/wiki/views/revision.py
To help mitigate risk of [disruptions of service caused by previewing documents with a large number of macro calls](https://bugzilla.mozilla.org/show_bug.cgi?id=1197971#c1), skip KumaScript rendering when previewing a document with deferred rendering. ([We automatically set documents to defer rendering when they take too long to render.](https://github.com/mozilla/kuma/blob/1de4dd081432647c8eb3f8c519a6d141cbf24be5/kuma/wiki/models.py#L547-L553)
> bug 1197971 - dont render previews of deferred docs

- tests/performance/smoke.py
To by-pass the internal load balancer from the locust cluster to the stage web-heads, we run locust with: `--host=<IP of stage web server>`.
So, we need to add an explicit 'Host' HTTP header on the requests so Apache will respond to them on the correct vhost.
> bug 1189451 - add 'Host' header

- tests/ui/tests/wiki.js
Since we debounce scroll events, we should provide an allowance time before testing a given CSS property.
> bug 1184662 - Allow time for scrolling CSS to apply

- kuma/wiki/helpers.py
- kuma/wiki/templates/wiki/document.html
Assigning to @darkwing in case he can remember a reason to keep the `selector_content_find` helper?
> bug 1177264 - optimize zone root summary display

- media/stylus/components/wiki/summary-box.styl
Summary box border colour was being over-ridden by .text-content table declarations so I gave it more specificity.
> Bug 1144134: Summary box border colour.

- kuma/core/decorators.py
- kuma/core/tests/test_decorators.py
- kuma/wiki/views/create.py
- kuma/wiki/views/delete.py
- kuma/wiki/views/document.py
- kuma/wiki/views/edit.py
- kuma/wiki/views/list.py
- kuma/wiki/views/misc.py
- kuma/wiki/views/revision.py
- kuma/wiki/views/translate.py
- media/robots.txt
- settings.py
Not sure this `settings.BLOCKABLE_USER_AGENTS` approach is the best one. Need some r? on this overall approach ...
> bug 1199166 - block_user_agents decorator for views

- media/stylus/components/wiki/edit/move-page.styl
Fix Bug 1199840: white text on red background in move page error message.
> bug-1199840-style-move-error-message

- kuma/dashboards/templates/dashboards/includes/revision_dashboard_body.html
- kuma/dashboards/views.py
Superseding https://github.com/mozilla/kuma/pull/3467 with a better version, including:
aad6fce: Don't query for userbans unless it's a super-user looking at the dashboard (saves ~50 queries for non-super-users)
9fc6309: eliminate an expensive duplicate count query
> bug 1177264 - Revision dashboard optimizations

- media/js/wiki.js
Will help me figure out how important this is for the sake of mobile.
https://bugzilla.mozilla.org/show_bug.cgi?id=1203198
> fix bug 1203198 - Add crumb link clicks to Analytics tracking

- kuma/users/forms.py
- kuma/users/tests/test_forms.py
- kuma/users/tests/test_views.py
Add username back to UserEditForm as a required (non-blankable) field.  Replaces #3474
> Add edit username 1197779

- media/js/wiki-edit.js
Currently the most frequent JS error on the site, which doesn't happen very often.  \o/  But hey, let's fix it.
https://bugzilla.mozilla.org/show_bug.cgi?id=1203625
> Fix bug 1203625 - Prevent JS error in edit interface

- media/img
In commit 85754412, we moved images from media/img to kuma/static/img.
We also added a symlink from the former to the latter so that the images
would resolve at both paths between the time the code was pushed and the
time a permanent redirect was published.
Jake published the redirect, so we don't need the symlink any more.
> Bug 1197444: Remove the media/img symlink

- media/img/README
The compress_asset script fails when it cannot find the media/img
directory. This change restores the directory temporarily so that
compress_assets will continue to work until the switch to
django-pipeline is completed.
> Bug 1197444: Add empty img directory

- provisioning/roles/kuma/files/vagrant/settings_local.py
The ALLOWED_HOSTS setting needs to be set to disable debug mode and
emulate production locally.
> Bug 957802: Allow all hosts in settings_local.py

- kuma/wiki/templates/wiki/confirm_revision_revert.html
- kuma/wiki/tests/test_views.py
- kuma/wiki/views/delete.py
When a user reverts a document to an old revision, we want to catch the
IntegrityError if it collides with the document's redirect, so the user knows
they can fix it by deleting the redirect.
> fix bug 1174498 - error message for revert dupes

- kuma/wiki/models.py
- kuma/wiki/templates/wiki/includes/document_macros.html
- kuma/wiki/templates/wiki/includes/revision_diff_table.html
- kuma/wiki/tests/test_models.py
When a $compare request is made for a large revision,
we want to skip tidy_content and return a warning to the user,
so we don't block requests on the expensive tidy operation.
> bug 1205667 - get_tidied_content can return blank

- .coveragerc
- .gitignore
- Makefile
Add a 'make coverage' target.  If run from the host, it enters VM, runs tests with coverage, builds HTML coverage docs, and opens them in the browser.  If run from the VM, it runs coverage and prints coverage to console.
Opening browser works on OS X, needs confirmation on desktop Linux.
> Add "make coverage" target

- provisioning/roles/kuma/files/apache2/all-servers.conf
- provisioning/roles/kuma/files/vagrant/settings_local.py
spot-check: `vagrant provision` and then check a page that tries to load `compat-icons.woff`: the request should succeed instead of a 403.
> bug 957802 - serve fonts to local.allizom for devs

- .gitignore
The .gitignore file is updated to also match files named
devmo_sanitized.sql
> Bug 957802: Make DB ignore more generic

- docs/development.rst
- docs/index.rst
- docs/installation.rst
To replace [the corresponding wiki docs](https://developer.mozilla.org/en-US/docs/MDN/Kuma/Contributing/Getting_started), I've re-arranged and updated some of our Kuma docs so we can link wiki readers to our code docs rather than wiki docs.
> bug 957802 - re-arrange kuma docs and toc

- kuma/wiki/templates/wiki/create.html
- kuma/wiki/templates/wiki/edit.html
- kuma/wiki/templates/wiki/move.html
- kuma/wiki/templates/wiki/translate.html
- media/js/wiki-edit.js
- media/stylus/components/doc-title.styl
- media/stylus/components/wiki/edit/editing.styl
- media/stylus/components/wiki/edit/title.styl
- media/stylus/components/wiki/title.styl
- media/stylus/main.styl
- media/stylus/wiki-edit.styl
- media/stylus/wiki.styl
Fix bug 1201967 - Makes titles on new, edit, translate, and move pages match.
Created class to apply to all, added it to main.css, removed disparate jumble of classes that previously accomplished this.
> Bug 1201967: Make all doc titles match

- media/js/wiki-compat-tables.js
- media/js/wiki.js
Display api-driven compat tables to users with a waffle enabled on pages that have been identified as ready, hide old style comapt table.
Testing:
1) download PR
2) `./manage.py compress_assets`
3) create waffle flag named `compat-api` and enable it for yourself
4) make/update a local copy of: https://developer.allizom.org/en-US/docs/Template%3AEmbedCompatTable
5) make a local copy of: https://developer.allizom.org/en-US/docs/Web/CSS/background
5) embed the macro in the browser compatibility section as the last thing in the section `{{EmbedCompatTable('web-css-background')}}`
6) verify that new table appears and the old table does not
7) disable waffle flag
8) verify that new table does not appear and the old table does
Preserving skateboard gif from #3504, because gif:
> bug 1206309 - waffled api driven compat tables

- kuma/dashboards/templates/dashboards/revisions.html
There were 2 issues here:
1. The 'page=' parsing was picking up the page number plus the rest of
the query string resulting in an invalid page number on the server.
2. The query string args were sent twice to the server because the form
action was not set. It happened to work because the second set of
query string args overwrote the first set.
> Fix bug 1206429 - Fix pagination query string args in revision dashboard

- docs/tests-ui.rst
Updates and adds selenium test documentation for running on BrowserStack and/or Sauce Labs. This branch is also for automatically running the tests during deploys, but this can be merged independently.
> fix bug 1186899 - documentation for cloud providers

- kuma/static/stylus/components/wiki/section-edit.styl
- kuma/static/stylus/wiki.styl
- kuma/wiki/templates/wiki/ckeditor_config.js
- kuma/wiki/templates/wiki/document.html
- kuma/wiki/templates/wiki/edit.html
- templates/includes/google_analytics.html
Not ready but a rough prototype for "section editing" whereby:
1.  Finds headings, adds "edit" links
2.  Loads edit page, scrolls down to the relevant section.
> Add basic section editing buttons to MDN

- docs/tests-ui.rst
- tests/ui/_base.js
- tests/ui/intern-browserstack.js
- tests/ui/intern-sauce-labs.js
- tests/ui/tests/auth.js
- tests/ui/tests/dashboards.js
- tests/ui/tests/footer.js
- tests/ui/tests/lib/capabilities.js
- tests/ui/tests/lib/login.js
- tests/ui/tests/lib/poll.js
- tests/ui/tests/wiki.js
> bug 1184662 - Add support for Safari

- kuma/static/stylus/components/syntax/example.styl
- kuma/static/stylus/components/wiki/customcss.styl
Test page: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations (more details in bug).
The bottom margin on the ul/ol was being applied sporadically by Firefox and not at all by Chrome, by adding it to .index it should always be applied now, and collapse with the margins on the lists if/when they come into play.
> 1202115 .index bottom margin

- kuma/static/stylus/components/syntax/example.styl
Fix the bug appearing here: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/CSS_style_guide Where the happy and sad icons are up at the top of the document. Also repositioned to a place which looks good whether line numbers are present or not.
> Bug 1125803: Good/bad code example styling

- kuma/static/js/wiki.js
- kuma/wiki/helpers.py
- kuma/wiki/tests/test_helpers.py
- templates/includes/config.html
Add jingo helpers to get paths to bundled CSS and JS assets, and add to the in-page global mdn.assets. Use these paths rather than hard-coded values when dynamically loading JS and CSS.
In a development environment, style-prism.js is split into 5 files, and the first one has to be fully loaded before the rest will load correctly.
> bug 1197444 - Load just-in-time assets in development environment

- kuma/wiki/templates/wiki/includes/document_macros.html
- kuma/wiki/templates/wiki/includes/revision_diff_table.html
- kuma/wiki/tests/test_templates.py
@robhudson or @jwhitlock - can you help me figure out why this new test fails? For some reason, the `tidied_content = ''` I'm saving in the test isn't persisted in the code-under-test. I.e., when I debug `revision_from.tidied_content` and `revision_to.tidied_content` inside `compare` view, it shows the actual tidied content and not the `''` I expect. :confused:
> fix bug 1210394 - only diff_table with tidied_content

- tests/ui/tests/lib/POM.js
- tests/ui/tests/lib/config.js
Pulling this from my Safari PR.  Important we set a large timeout in case the site and/or BrowserStack are slow.
> bug 1197858 - Set larger test timeouts for remote runners

- Procfile
- settings.py
Work in progress; not sure this is the best (or even a good) way to do this, but ...
Uses `CELERY_ANNOTATIONS` setting to assign 1 of 4 queues to every celery task we have:
* `mdn_purgeable` - queue for low-priority tasks, and/or tasks that will automatically come back after a time period (e.g., cacheback refreshes, sitemap cron jobs, etc.). Any task assigned to this queue should always be safe to purge when we need to. Purging these tasks will not corrupt data and will cause trivial service disruption.
* `mdn_search` - queue for tasks related to search. Purging these tasks will not corrupt data (since we can rebuild the search index), but will cause service disruption (if the search indices are unavailable or fall grossly out-of-date).
* `mdn_emails` - queue for tasks that send emails - …
> bug 1211651 - assign tasks to certain queues

- kuma/static/stylus/components/wiki/properties.styl
Lists inside of the new table world order need to be properly styled, for now we just override the rules from the old list world order but eventually we can decrease the specificity of this.
Also added display improvements for small mobile screens.
Test page:
https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip
(easier to view source and copy the table markup to local dev than to try to migrate the macros)
> Fix bug 1212844 - Properties lists

- kuma/wiki/templates/wiki/includes/buttons.html
We currently have both pages and articles in this dropdown, needed to be standardized. Writers would like us to refer to articles instead of pages.
> Fix Bug 1203301: Standardize language in dropdown

- media/fonts
A permanent redirect from /media/fonts to /static/fonts is now active on
stage and prod, so we don't need the symlink any more.
> Fix bug 1197444: Remove media/fonts symlink

- kuma/static/stylus/components/wiki/properties.styl
Also moved some definitions around to decrease the number of lines in the complied Stylus files.
Test:
- using dev tools DOM inspector copy the HTML from this page into an article on your local instance: https://developer.mozilla.org/ja/docs/Web/CSS/flex-basis (There are several kumascript macros that need updating if you want to try to duplicate the output by actually editing the article.)
- check https://developer.mozilla.org/en-US/docs/User:teoli/In_content to make sure the other summery boxes are still displaying properly.
> Fix Bug 1213548: Min-width on .properties headings.

- kuma/static/js/wiki.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1177797
To test:
1.  Click on the "Show all" button....see no "larger" avatar
2.  Tab to "Show all" button, press `ENTER` key, see larger avatar
> fix bug 1177797 - Only focus on next avatar if enter key pressed

- kuma/static/js/wiki.js
To test:
1.  Click any breadcrumb link, should go to the page
2.  Command-click any breadcrumb link, original tab should go nowhere, new tab should open
> fix bug 1212518 - Don't forward users when control-clicking a link

- kuma/static/styles/base/fonts/compat-icons.styl
- kuma/static/styles/components/demos/backgrounds.styl
- kuma/static/styles/components/demos/gallery-head.styl
- kuma/static/styles/components/demos/paging.styl
- kuma/static/styles/includes/vars.styl
- kuma/static/styles/libs/font-awesome/css/font-awesome.css
- kuma/static/styles/libs/font-awesome/stylus/font-awesome.styl
collectstatic automatically updates stylesheets to cache-bust images and
other assets when their contents change, so these manual cache-busting
parameters are no longer needed.
> Bug 1139490: Remove cache-busting params in styles

- kuma/static/js/wiki-compat-tables.js
- kuma/static/styles/components/compat-tables/bc-table.styl
Browsers which don't support `@supports` no longer fall back to a display:block version when medium display conditions are met. Safari 8 and IE 9-11 will display the display:table version until small display conditions are met.
This simplifies the code and probably doesn't give them a much worse experience than the buggy display:block version gave them.
More fighting with styles inherited from .text-content about the borders.
> Bug 1206309: remove tablet/block display option

- kuma/demos/templates/demos/listing_tag.html
This addresses the following error:
https://errormill.mozilla.org/mdn/mdn/group/401204/
---
1. [Use production assets](https://kuma.readthedocs.org/en/latest/development.html#production-assets)
2. Visit [this page](https://developer-local.allizom.org/en-US/demos/devderby/2013/june)
500
Page loads
> Bug 1139490: Don't load tech icon on Derby pages

- kuma/users/middleware.py
- kuma/users/tests/test_middleware.py
This adds `private, no-cache` to the response when a banned user's request is caught by the `BanMiddleware`.
Assuming our load-balancer follows standard `Cache-Control` implementation, this should stop it from caching these responses.
In theory, `no-cache` alone can do this; `private` is an extra indicator to the cache that the response is meant for a single user.
We can deploy and test this ourselves to see if it fixes the problem before getting WebOps involved debugging the load balancer.
> fix bug 1221110 - private, no-cache ban responses

- .gitmodules
The only vendor module that seems to have a problem with this (because
they have .pyc files checked into their repo) is python-magic.
According to the git submodule docs:
"dirty" will ignore all changes to the submodules work tree and takes
only differences between the HEAD of the submodule and the commit
recorded in the superproject into account.
> Allow removal of all *.pyc files from root.

- kuma/static/js/wiki-samples.js
Fix bug 1195351:
Re-jigged when the sample sections are downloaded so they are parsed by the script to make sure there's matching sample code found before we add the buttons to the page, log errors with GA if something goes wrong there.
Fix bug 1198301:
Added user to a ga segment if they click on button.
Some pages with embedLiveSample for testing purposes:
https://developer.mozilla.org/en-US/docs/User%3Astephaniehobson%3Acode
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress
https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Drawing_DOM_objects_into_a_canvas
> Fix bugs 1195351 and 1198301: (Live Sample "open in" buttons)

- static/.htaccess
- static/fonts/.htaccess
1. Enable [production mode](https://kuma.readthedocs.org/en/latest/development.html#production-assets)
2. Verify that versioned assets (assets with an MD5 hash in the filename) are served up with an *Expires* header with a value of one year into the future
> Fix bug 1223560: Never expire versioned assets

- .gitignore
- Procfile
- build/assets/css/README.md
- docs/development.rst
- docs/troubleshooting.rst
- kuma/static/styles/includes/vars.styl
- provisioning/roles/kuma/files/apache2/vhosts.conf
- provisioning/roles/kuma/files/vagrant/settings_local.py
- scripts/chief_deploy.py
- scripts/compile-stylesheets
- settings.py
Kuma pages load very slowly locally when Pipeline kicks off compilation.
This change restores the old workflow, where the `stylus` executable
compiles individual stylesheets as needed.
More info:
https://github.com/mozilla/kuma/pull/3597#issuecomment-151984236
> Bug 1139490: Improve local Pipeline performance

- static/.htaccess
- static/fonts/.htaccess
Our stage and production servers use Apache 2.2, which does not support
the &lt;If&gt; directive used in this work. Let's forget about doing this with
Apache and move straight on to doing it at the application level with
WhiteNoise.
> Revert 3546e3550f3b0e2d5dd241087cb1934b4578d414

- kuma/dashboards/templates/dashboards/revisions.html
Per New Relic, many of our transaction response time spikes are coming from `kuma.dashboards.views:revisions` (green in the graph):
I profiled and debugged it down to extremely slow queries against the `wiki_revision` table.
I [filed a bug with DBA to help fix it](https://bugzilla.mozilla.org/show_bug.cgi?id=1210830). The problem seems to be poor performance of DB/MySQL `OFFSET` pagination on large tables. (Note: the same problem seems to affect `kuma.users.views:user_detail` [orange in the graph] too.)
I have [a branch ready to PR](https://github.com/mozilla/kuma/compare/revision-dashboard-pagination-1177264?expand=1) that removes the default Django `OFFSET`-based pagination with [an optimized pagination approach based on "last seen ID" of the auto-increment primary index …
> bug 1177264 - measure dashboard pagination usage

- kuma/wiki/templates/wiki/includes/document_macros.html
Fixes this display bug on pages where there are no watched parents ...
> bug 842340 - only show <ul> if there are items

- kuma/static/js/analytics.js
Try to avoid missing anything that happens before GA initializes.
> Bug 1218466: Queue errors before GA loads.

- kuma/wiki/admin.py
When a site admin sees a page that can't be translated, they need to update the is_localizable field on the page, so translators can translate it.
Also includes UI enhancements for the doc admin page.
> fix bug 1225159 - add is_localizable to admin site

- settings.py
When PIPELINE_DISABLE_WRAPPER is False (the default), Pipeline wraps all
JavaScript in an anonymous function:
(function(){
//JS output...
})();
We already wrap JavaScript manually, so this extra wrap is not needed.
> Bug 1139490: Don't use Pipeline to wrap JavaScript

- kuma/wiki/models.py
- kuma/wiki/tests/test_models.py
Re-based these commits on mozilla/django-1.8.
@robhudson if these look good to you too (@jezdez already gave a review in https://github.com/mozilla/kuma/pull/3660) feel free to merge or let me know and I'll push them up to the django-1.8 branch myself.
> bug 1209185 - ro-order related model saves

- kuma/static/styles/base/elements/forms.styl
- kuma/static/styles/components/content.styl
- kuma/static/styles/components/wiki/customcss.styl
- kuma/static/styles/includes/mixins.styl
- combine duplicate `bug` and `warning` declarations
- add dividers in comments
- remove unused `fa-trash` class
- better :last-child control in indicators
- remove RTL only styling for `page-content` (we should fix MDN styles if there's a specific problem rather than over-riding. I could not see a compelling reason for lists in the one place this was used to have their own special list styling)
- remove unused coloured icon classes `experimentalIcon`, `nonstandardIcon`, `obsoleteIcon`, `deprecatedIcon` (coloured icons not generated this way anymore)
- remove duplicate definitions for `#wikiArticle i.icon-beaker` and other coloured icons
- remove references to unused `#nav-sub-docs`
Testing:
- Random selection of [pages using Template:bug](https://developer.mozilla.org/en-US/search?locale= …
> Bug 1070001: Organizing custom CSS

- kuma/static/styles/components/structure/tabzilla.styl
- kuma/static/styles/components/wiki/quick-links.styl
- kuma/static/styles/components/wiki/section-edit.styl
- kuma/static/styles/includes/mixins_indicators.styl
- Tabzilla
- indicator borders
- section edit buttons
- more room for items in quick-links (not specifically RTL but spotted because looking at page from new angle makes different things stand out)
[Test page](https://developer.mozilla.org/ar/docs/Web/Apps/Quickstart/Design/%D9%85%D9%81%D9%87%D9%88%D9%85_%D8%AA%D8%B7%D8%A8%D9%8A%D9%82_%D8%B9%D8%B8%D9%8A%D9%85 )
> Fix Bug 1216296: RTL tweaks

- kuma/static/js/auth.js
- kuma/static/js/helpfulness.js
- kuma/static/js/main.js
- kuma/static/js/wiki-edit.js
Making local storage feature test more robust to solve problem of iOS identifying that is supports localStorage and then preventing usage in private browsing mode. (note that I was not able to duplicate this problem in my testing environment but I'm 90% sure this is the source of the problems identified by New Relic - details in bug)
Testing:
- save and recover draft
- helpfulness
- login with Persona
- check that GA event fires when login completes
- try to create a new account with a email address that matches an existing account, associate the accounts. Check you get confirmation notification. (I disconnected my git hub log in and then re-logged in with it).
> Fix Bug 1226283: Local Storage feature test

- kuma/static/js/wiki-samples.js
samples.js was raising console errors that looked like this: "Uncaught Error: Syntax error, unrecognized expression: h2[name=Usage example]" when used on pages where the code sample title was in an h3.
I tried to switch to just using $("#"+section) but it turns out we have characters in our IDs that, while legal in HTML5, throw jQuery for a loop. Plain JS FTW.
> Fix Bug 1226034: Console Error from Live Samples

- kuma/static/js/wiki.js
- kuma/static/styles/components/wiki/content/compact.styl
- kuma/static/styles/wiki.styl
- kuma/wiki/templates/wiki/includes/kumascript_errors.html
Add hooks to markup to identify errors and javascript to parse the errors and send to google analytics.
Depends on #3629 and #3608.
> Fix Bug 1222648: Track Kumascript Errors in GA

- kuma/static/styles/base/elements/typography.styl
This makes text in a `<code>` tag break so it doesn't overflow and create a huge amount of whitespace when on a mobile device (or small browser window)
> fix bug 1233441 - code tag overflow on mobile

- kuma/search/serializers.py
- kuma/search/templates/search/results.html
- kuma/search/tests/test_views.py
This simplifies the rendering dramatically and fixes a regression in the DRF 3.x update.
> Fix bug 1233185 - Remove explanation text from search results.

- docs/installation.rst
- kuma/wiki/management/commands/import_kumascript_modules.py
- kuma/wiki/views/misc.py
While working on #3631, I finally got tired enough of loading the KumaScript auto-load modules manually to write a command script to load them from the prod site automatically:
```
vagrant ssh
python manage.py import_kumascript_modules
```
I know @stephaniehobson has wanted this for a long time; sorry for taking this long to do it.
Updated the installation docs to include this too.
> bug 957802 - import_kumascript_modules command

- kuma/static/styles/components/structure/contentinfo.styl
- kuma/static/styles/components/tags.styl
- kuma/static/styles/components/wiki/content/card-grid.styl
- kuma/static/styles/includes/mixins.styl
Fixes for:
- footer (last line left aligned instead of right aligned)
- card-grid (too much padding)
- tags in footer of articles (large blank space)
- check box on profile page (overlapping text - no screen shot)
> Bug 1216296: RTL Fixes

- kuma/static/styles/components/content.styl
This commit removes the tip class from the https://github.com/mozilla/kuma/blob/36220986307fd18eeac275b9c3058d7ccae40565/kuma/static/styles/components/content.styl#L257
> Fix Bug 1217085: remove the class tip

- kuma/static/styles/components/content.styl
- kuma/static/styles/components/share.styl
- kuma/static/styles/components/wiki/content/pull-aside.styl
- kuma/static/styles/includes/mixins.styl
- kuma/static/styles/wiki.styl
Abstracted declaration we already had to pull callout-box aside and made reusable. Added .pull-right class so it could also be used as a wrapper around, for example, .readmore.
Testing:
https://developer.allizom.org/en-US/docs/User%3Astephaniehobson%3Aaside
Headsup: publish in CSS style guide once live.
> Fix Bug 1177227: Add way to pull content aside.

- kuma/static/js/wiki.js
- kuma/static/styles/components/wiki/contributor-avatars.styl
- kuma/wiki/templates/wiki/document.html
- kuma/wiki/views/document.py
Testing: 
- wiki page
- zone page
- zone landing
- RTL
- less than 6 avatars
- more than 6 avatars (show all button should appear)
- arriving on article from search (should not display)
- smaller screen sizes (should not display)
- long page title (title should wrap to avoid contributors)
Make sure it expands and collapses when "show all" clicked/tapped/keyed.
> Fix Bug 1232404: Contributor bar visual design

- kuma/static/styles/components/wiki/mega.styl
The macro has been transitioned to use the new classes outlined in https://github.com/mozilla/kuma/pull/3672 and there are no references* to the old class left on production. We can safely remove this.
* the search is turning up 3 references for some reason but I have viewed source on those pages and confirmed it is not in use. Caching?
> Bug 1070001: Remove addpage-button

- kuma/static/styles/components/wiki/quick-links.styl
Writers want to move to quick links menus as part of preparation to migrate off of zones, right now at tablet and smaller that means grey links end up on the blue background and are un-readable. 
Added a white background and a fake left border to account for the negative margin on the see-also heading. 
Test page:
https://developer.allizom.org/en-US/Add-ons
> Fix Bug 1232379 - Make .quicklinks workable on zone landings

- kuma/static/js/wiki-compat-tables.js
- kuma/static/styles/components/compat-tables/bc-beta.styl
- kuma/static/styles/components/compat-tables/bc-footnotes.styl
- kuma/static/styles/components/compat-tables/bc-history.styl
- kuma/static/styles/components/compat-tables/bc-legend.styl
- kuma/static/styles/components/compat-tables/bc-table.styl
- kuma/static/styles/components/compat-tables/vars.styl
- Style changes to accommodate heading in bc-history drop down
- Variablize $bc-grid-spacing
- Add "implementation notes" to title for button
- Fix problem with height of bc-history drop down in desktop display
Need to update embedCompatTable template for testing: https://gist.github.com/stephaniehobson/2b69ff6bb3be1a39b23a
Headsup: update staging when merged
> Bug 1206309: Heading in drop down.

- kuma/wsgi.py
whitenoise needs DJANGO_SETTINGS_MODULE to be set in the environment
otherwise it raises an ImproperlyConfigured exception.
This adds that variable to the environment for the vagrant vm. Doing
that causes the DJANGO_SETTINGS_MODULE hackery in manage.py to do the
wrong thing for the "./manage.py test", so this also updates the
Makefile rule and docs to specify
DJANGO_SETTINGS_MODULE=settings_test.
Feedback? This fixes one issue and creates new ones. I'm game for better
suggestions.
> Fix bug 1237072 - Fix issue with whitenoise and settings

- requirements/default.txt
This fixes the bug with sendfile.
Without this, doing "foreman start web" fails.
Quick r?
> Fix bug 1238175: Upgrade gunicorn to 19.4.5

- kuma/core/templatetags/jinja_helpers.py
- kuma/landing/jinja2/landing/newsfeed.html
This is currently used in only a single place and is overridden. Here
I've fixed the default value to remove it from the l10n strings and
provide a better default.
> Fix datetime format string

- docs/celery.rst
Spelling mistake -
`overriden` > `overridden`
> Fix typo in docs/celery.rst

- kuma/static/styles/base/elements/sectioning.styl
- kuma/static/styles/components/wiki/no-details.styl
Added a bottom margin to the `<details>` element to preserve horizontal spacing (especially before headings).
Moved the CSS generated elements added in browsers that don't support `<details>` to the right.
Testing:
https://developer.mozilla.org/en-US/docs/User:stephaniehobson:details
> Bug 1189515: Details and summary

- requirements/docs.txt
See https://github.com/rtfd/readthedocs.org/issues/1958 for a follow-up.
> Bug 957802 - Fix documentation build until RTD supports pip8 requirements files.

- kuma/static/js/analytics.js
- kuma/static/js/components.js
- kuma/static/js/wiki.js
- extracted logic for tracking links into separate function (trackLink)
- added logic to check for contentmenu when using trackLink
- updated .crumb, #toc, and .contributor-avatar link tracking to use trackLink
- added link tracking for #nav-access and #main-nav
- tracking generic KumaScript errors if no $kserrorsList present (usual because user not logged in) (Bug 1222648)
- added tracking event for when menus are opened (this is a little trigger happy, suggestions for fixing welcome)
Testing:
- events logged for: breadcrumbs, table of contents, contributor avatars, access nav, main nav (hover and link), kumascript error when logged out.
- mouse click, enter key, CMD+click, and context menu all open links that are in the list to be tracked and are: anchor, internal to MDN, and external …
> Bug 1218656: Track all the things

- kuma/wiki/tests/__init__.py
- kuma/wiki/tests/test_views.py
- kuma/wiki/views/document.py
Previously, MDN would return an HTTP 404 with an HTML document that
has some stuff on it and lets people restore the document. That's not
great because somehow those pages are getting indexed or otherwise
making search bots grumpy.
Instead of doing that, this changes MDN to return a straight-up
regular 404 page unless the user can restore documents in which case
they get the HTML page that lets them restore documents.
@jezdez r?
> Fix bug 1244308: Return 404 content if user can't restore the document

- docs/development.rst
- docs/elasticsearch.rst
- docs/installation.rst
In `docs/development.rst`
duriing - during
In `docs/elasticsearch.rst`
dropwdown - dropdown
recommmended - recommended
In `docs/installation.rst`
configration - configuration
> Bug 1247498 - Fix spellings in docs

- kuma/spam/forms.py
- kuma/spam/tests/test_forms.py
- kuma/wiki/tests/test_forms.py
This fixes a design issue in the spam package that was overlooked and never surfaced as part of the unittests since they only tests the error cases, and not specfically the success cases.
> Bug 1188029 - Fix API issue in Akismet spam check.

- scripts/compile-stylesheets
Add -p option in compile_stylesheets for mkdir to ensure recursive folder creation.
https://bugzilla.mozilla.org/show_bug.cgi?id=1248242
> Bug 1248242

- kuma/core/middleware.py
This fixes the wonky admin problem where the language of the admin would
change between refreshes.
What's going on is that Django 1.8 introduced a fix to
trans_real.activate where if you pass in '', it does nothing and
returns. The prefixer will set the locale to '' for /admin/, so then
the locale-aware middleware calls translation.activate('') and
suddenly we're all standing in a pool of goo in the middle ages with
flaming arrows aimed at us.
This fixes that.
r?
> Fix bug 1237661: Fix wonky admin

- kuma/wiki/tests/test_views.py
- kuma/wiki/views/document.py
When the $children API view is requested for a redirected page, return this error JSON:
```json
{"error": "Document has moved."}
```
Previously, a 500 error occurred due to ``JsonResponse`` refusing to encode a ``null``.
> bug 1201709 - /renamed$children returns error JSON

- kuma/static/js/wiki.js
- kuma/static/styles/components/wiki/contributor-avatars.styl
This is a quick fix that gets us away from "that looks broken" but could use more finesse.
Page with lots of users for testing:
https://developer-local.allizom.org/en-US/docs/Mozilla/Projects/Midas/Security_preferences
Page with fewer users:
https://developer.mozilla.org/en-US/docs/Glossary
Page with very few users:
https://developer-local.allizom.org/en-US/docs/Glossary/I18N
Page with fewer than minimum for button:
https://developer-local.allizom.org/en-US/docs/Glossary/ARIA
> Bug 1243741: Expanded contributor bar

- kuma/settings/common.py
- kuma/wiki/jinja2/wiki/document.html
Separated the helpfulness file back out of the wiki.js file and added it only to the document pages so we won't get asked on editing pages, etc anymore.
> Bug 1239757: Only ask helpful on wiki docs

- kuma/core/management/commands/fixaccount.py
This creates a django management command to fix MDN user accounts in
an anonymized database so you can log in with them in your dev
environment.
This only works with Persona accounts, but I'm pretty sure that's ok
since there's all this extra work to set up GitHub auth in a dev
environment. I think if that's important, someone can create a bug for
it and do it in a future PR.
To test, load an anonymized db, then run:
$ ./manage.py fixaccount <username> <email>
r?
> Fix bug 1253269: Add fixaccount command

- kuma/attachments/jinja2/attachments/includes/attachment_list.html
- kuma/wiki/management/commands/populate_attachments.py
- kuma/wiki/migrations/0022_remove_document_attachments_populated.py
- kuma/wiki/models.py
This tries to guess better which document an attachment was originally uploaded to.
If an attachment is included in multiple documents it:
- favors documents with smaller primary keys (denoting earlier creation)
- favors English documents as the orignal upload
> Bug 1077172 - Improve managment command to fix historical attachments.

- kuma/core/templatetags/jinja_helpers.py
- kuma/core/tests/test_helpers.py
- kuma/wiki/jinja2/wiki/email/spam.ltxt
This PR:
* Removes unused template functions and filters in kuma core.
* Adds a ``in_utc`` filter that converts datetimes to UTC
* Displays dates with UTC offsets (like ``2016-03-10 17:11:48.631245+00:00``) in the spam email.
* Collapses extra newlines from Jinja2 conditionals
> bug 1215199 - Display dates in spam email in UTC

- kuma/static/js/search-suggestions.js
This removes the unicode characters in place of their escape sequences
as the unicode was affecting some editors. This also fixes all jshint
errors and applies general js syntax reformatting.
> Fix bug 1257622 - Refactor search-suggestions.js

- jinja2/includes/login.html
- kuma/static/js/auth.js
- kuma/static/styles/components/components.styl
- kuma/static/styles/components/structure/oauth-login.styl
- add fixed width to login widget to prevent notice from pushing it too wide
- add notice to appear when registration_disabled waffle enabled
- switch to always using "sign in" label for sign in (simplifies code and makes label shorter to try to keep localization from running out of space in the widget)
Testing:
- home page and a wiki page (with a grey header)
- multiple locales
- RTL
- tablet and mobile views
- can still login
- can still
> Fix Bug 1258493: Account creation disabled notice

- kuma/wiki/migrations/0027_populate_document_uuid.py
- kuma/wiki/migrations/0028_require_document_uuid.py
- kuma/wiki/models.py
- kuma/wiki/tests/test_models.py
Add a UUID to the Document model, which can first be used as an external ID for identifying features in the https://github.com/mdn/browsercompat project.
Because this PR includes database migrations, it needs to be manually merged and deployed in four parts:
1. [x] Update Kuma migrations to match the state of the models. Then add Document.uuid to the database, nullable with a default of null. *(first commit)*
2. [x] Add uuid to document model, and expose it in the ``$json`` page API (like [Web/CSS/display$json](https://developer.mozilla.org/en-US/docs/Web/CSS/display$json)). *(middle commits)*
3. [x] Manually populate null Document.uuid columns with new [Version 4 (random) UUIDs] (https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_.28random.29). 
4. [ ] Run an automated …
> bug 1246967 - Add Document.uuid

- kuma/landing/jinja2/landing/homepage.html
- kuma/landing/test_templates.py
- kuma/landing/views.py
- kuma/search/admin.py
- kuma/search/filters.py
- kuma/search/managers.py
- kuma/search/migrations/0002_filter_default.py
- kuma/search/models.py
- kuma/search/tests/test_store.py
- kuma/search/views.py
- kuma/settings/common.py
- kuma/static/js/search-suggestions.js
This adds a default boolean field to the search filter model. Upon deploy no default will be set and search will be as it is now. Once we are ready to add defaults we can do so in the admin and enable them.
> Fix bug 1246459 - Prioritize web by default

- Makefile
- kuma/settings/common.py
- kuma/wiki/admin.py
- kuma/wiki/apps.py
- kuma/wiki/tasks.py
- kuma/wiki/tests/test_admin.py
- kuma/wiki/tests/test_templates.py
Fix issues with PR #3816:
* On the "dashboard" (the Django admin list view), the Document name is length-restricted, so that long names do not cause the list view to become overly long and require scrolling to get to the review dropdown.
* An email is sent to the "first edits" email list when an edit is blocked, but not again when the block is reviewed.
Also improves ``make coveragetest``, to generate the HTML coverage docs and to recreate the skeleton of the 'cleaned' ``build`` folder.
> bug 1255609 - Fixes for spam dashboard

- kuma/spam/forms.py
- kuma/spam/tests/test_forms.py
- kuma/wiki/forms.py
- kuma/wiki/jinja2/wiki/email/spam.ltxt
- kuma/wiki/migrations/0029_add_dsa_review_type_error.py
- kuma/wiki/models.py
- kuma/wiki/tests/test_forms.py
If Akismet returns an error from check-comment, continue to block the edit, but save the details of the error for debugging, and adjust the notification sent to the spam watchers list.
> bug 1188029 - Capture Akismet error data

- docs/feature-toggles.rst
- kuma/spam/constants.py
- kuma/spam/forms.py
- kuma/wiki/constants.py
- kuma/wiki/forms.py
- kuma/wiki/tests/test_forms.py
Updates the tests to:
* Use py.test's ``assert`` style instead of unittest's ``self.assertX`` style.
* Add ``_setup_akismet_post`` method to help setup a RevisionForm for Akismet testing
Adds some additional waffle flags to allow per-user alternate Akismet payloads:
* ``spam_admin_override`` - Sets ``"role=administrator"`` so Akismet never identifies changes as spam
* ``spam_spammer_override`` - Sets ``"username=viagra-test-123"`` so Akismet always identifies changes as spam
* ``spam_testing_mode`` - Sets ``"is_test=True"`` so Akismet doesn't train on the content
Adds one per-user flag to control the response:
* ``spam_training_mode`` - Don't block saving content if Akismet identifies as spam or returns an error (but still record as a ``DocumetSpamAttempt``).
See the [bug …
> bug 1259233 - Add more waffle flags for Akismet tuning

- kuma/users/tests/test_views.py
Update ``test_persona_signin_captcha`` to mock the network request to the ReCAPTCHA server to check the CAPTCHA attempt, continuing to return a "failed" response
> bug 1252697 - Mock CAPTCHA call during signup test

- jinja2/includes/error_list.html
- kuma/static/js/wiki-edit.js
- kuma/static/styles/components/doc-title.styl
- kuma/static/styles/components/errorlist.styl
- kuma/static/styles/components/wiki/edit/cke.styl
- kuma/static/styles/components/wiki/edit/draft-status.styl
- kuma/static/styles/components/wiki/edit/guide-links.styl
- kuma/static/styles/components/wiki/edit/save-state.styl
- kuma/static/styles/font-awesome.styl
- kuma/static/styles/wiki-edit.styl
- kuma/users/jinja2/users/user_edit.html
- kuma/wiki/jinja2/wiki/create.html
- kuma/wiki/jinja2/wiki/edit.html
- kuma/wiki/jinja2/wiki/includes/page_buttons.html
- kuma/wiki/jinja2/wiki/includes/spam_error.html
- kuma/wiki/jinja2/wiki/includes/translate_description.html
- kuma/wiki/jinja2/wiki/translate.html
- kuma/wiki/tests/test_templates.py
Fix Bug 1259151 - When edit is blocked as spam, save the draft content
Fix Bug 1259197 - Draft save notification does not appear on translation pages.
Fix Bug 1123616 - Allow to manually store a draft
- renamed page_buttons to support addition of draft button so no confusion over "save"
- moved localStorage checks around and abstracted a bit
- moved draft notifications to all be in one place above editor (and supporting HTML and CSS changes)
- added draft notification changes to translation pages
Testing:
- edit button (6x one each for en-US edit and new, non en-US edit and new, and a template edit and new)
- edit page title and properties still there
- no recovered draft, save draft button present but disabled
- type and click save button (in less than 3 seconds)
- local storage has …
> Save draft improvements.

- kuma/core/jobs.py
- kuma/core/tests/test_jobs.py
- kuma/wiki/models.py
- kuma/wiki/tasks.py
* Adds ``GenerationKeyJob.get_constructor_args``, so that the async refresh task can recreate the generation key
To do:
> bug 1263157, 1263163 - Async caching and task fixes

- kuma/static/js/wiki-edit.js
- kuma/static/styles/components/wiki/edit/draft-status.styl
When a draft was detected the code was still autosaving over top of it. This fixes that and exposes the autosave process to the user in the UI.
Testing:
no recovered draft, save draft button present but disabled
type and wait 3 seconds for auto save
local storage has correct content
type and click save button (in less than 3 seconds, got to be quick)
local storage has correct content
autosave disabled notification present
type and wait for 3 seconds, draft not autosaved
enable auto save
type and wait for 3 seconds, draft autosaved
hard refresh page
report draft to restore, no save button, no autosave
type and wait 3 seconds, no autosave
restore draft
restored correctly, autosave enabled
type and wait 3 seconds, autosave
hard refresh
draft to restore
discard draft
hard refresh
no draft …
> Bug 1259151: Restore draft regression fix

- kuma/core/jobs.py
- kuma/core/tests/test_jobs.py
- kuma/wiki/models.py
* Set ``GenerationKeyJob.lifetime``, so it isn't the 5 minute default
* Fix a bug added in PR #3831, where ``Revision.get_tidied_content()`` might leave ``.tidied_content`` with the invalid value of ``None``.
> bug 1263157, 1263163 - More async task fixes

- kuma/wiki/tasks.py
Omit the kwargs parameter to tidy_revision_content.retry, which causes the args and kwargs of the original call to be used.
This fixes a bug introduced in PR #3831, in commit 67b2d282a3802b
> bug 1263163 - Fix tidy_revision_content.retry

- kuma/users/admin.py
Adds groups to the Django admin list view for users, to allow admins to easily see user accounts assigned to a group.
> bug 1255608 - Add Groups to user filter

- jinja2/403.html
- kuma/settings/common.py
- kuma/users/fixtures/test_users.json
- kuma/users/tests/__init__.py
- kuma/wiki/constants.py
- kuma/wiki/jinja2/403-create-page.html
- kuma/wiki/managers.py
- kuma/wiki/migrations/0030_add_page_creators_group.py
- kuma/wiki/tests/__init__.py
- kuma/wiki/tests/test_views.py
- kuma/wiki/views/create.py
A user must have the ``wiki.add_document permission`` in order to add a page.
If this strategy works, then there is some follow-on tasks, including:
* Decide criteria for adding new users to Page Creators
* Automatically adding new users to Page Creators
* Adding an exception middleware to make it easier to return permission-based templates.
_Update 1_: Added a migration, manual steps are no longer needed
> bug 1264361 - Require wiki.add_document permission

- kuma/wiki/migrations/0030_add_page_creators_group.py
Iterate through the users looking for unbanned users, instead of making the database do the work to create the unbanned user list.
> bug 1264361 - Kinder Page Creators migration

- kuma/wiki/migrations/0030_add_page_creators_group.py
Call ``emit_post_migrate_signal`` with keyword parameters instead, so that ``interactive=False`` is correctly passed to the signal handlers.
> bug 1264361 - Fix wiki migration 30 (again)

- kuma/wiki/admin.py
- kuma/wiki/forms.py
- kuma/wiki/managers.py
- kuma/wiki/models.py
- kuma/wiki/templates/admin/wiki/revisionakismetsubmission/change_form.html
- kuma/wiki/tests/test_admin.py
- kuma/wiki/tests/test_forms.py
Rewrite the RevisionForm tests to setup forms for validation in the same way the views set them up (create, edit, and translate). Then:
Update the Akismet payload:
* Add HTTP headers
* Add ``blog`` parameter (front page of site), and fix default if omitted
* Add ``permalink`` parameter (page that is being edited
* Minimize ``comment_content`` to the changed and new content
Further improvements:
* Move payload generation to new ``AkismetRevisionData`` class, so the same logic can be used in the  ``RevisionForm`` as other places
* Save Akismet data in ``RevisionIP`` instance, and replay for ``submit-ham`` and ``submit-spam``.
* Add read-only displays of Akismet data to admin detail views.
This PR should be manually merged:
> Bug 1259173 - Adjust Akismet payload 

- kuma/wiki/forms.py
- kuma/wiki/tests/test_forms.py
A new translation is a little like an edit and a little like a new document, but not identical to either. This PR fixes the test code to setup the tests for new translations correctly, and implements a better process for creating an Akismet payload for new translations, fixing an ISE in the current code.
It also uses the previous revision's tags instead of the document tags, since document tags have different capitalization than revision tags in some cases.
> bug 1267713, bug 1259173 - Fix Akismet for new translations, plus tag fix

- Vagrantfile
- provisioning/roles/kuma/tasks/node.yml
* Disable the npm cache. It should make building a VM faster, but permission errors are breaking provisioning.
* Upgrade fibers. It is a C++ package, and must have broke with recent system package updates.
> bug 957802 - Vagrant build fixes

- kuma/wiki/forms.py
- kuma/wiki/tests/test_forms.py
Two fixes:
* [bug 1268511](https://bugzilla.mozilla.org/show_bug.cgi?id=1268511) - Sometime tags have quotes, sometimes they don't.
* [bug 1259870](https://bugzilla.mozilla.org/show_bug.cgi?id=1259870) - Templates are stored like pages, but shouldn't be checked by Akismet
> bug 1268511 and bug 1259870 - Akismet integration fixes

- Procfile
- Vagrantfile
- docs/installation.rst
- kuma/wiki/management/commands/import_kumascript_modules.py
Tested on OS X 10.11.4, Vagrant 1.8.1, VirtualBox 5.0.16r105871, and Ansible 2.0.2.0.
* Add an environment variable ``VAGRANT_CACHIER=false`` to disable the cachier plugin config. Currently still enabled, but may fix some Linux issues.
* Bump tested version numbers
* Use Ansible output in docs
* Fix ``./manage.py import_kumascript_modules``
* Run two web workers, so that KumaScript can make Kuma API requests at the same time Kuma is asking to render a document.
* Allow Kuma to defer async tasks (``CELERY_ALWAYS_EAGER=False``)
> bug 957802 - Vagrant install fixes

- docs/troubleshooting.rst
Adding information for Linux to the troubleshooting docs regarding statd and locks error.
This fix is required for Linux set-ups that see the following error after running ``foreman start`` and trying to load the website locally:
IOError: [Errno 37] No locks available
> Linux statd doc update

- jinja2/base.html
- kuma/core/translations/search/filter/b2g-os/name.py
- kuma/landing/jinja2/landing/homepage.html
- kuma/settings/common.py
* From PR #3844 - Update links on homepage so that localized homepage / toolbar will link to the localized variant of zones
* From PR #3857 - Update toolbar link from Firefox OS to B2G OS
* Update homepage link from Firefox OS to B2G OS
* Suggest "B2G OS" tag
> Bug 1267197 and bug 1270032 - Links to zones, Firefox OS->B2G OS

- kuma/dashboards/forms.py
- kuma/dashboards/jinja2/dashboards/revisions.html
- kuma/dashboards/tests/test_views.py
- kuma/dashboards/views.py
- kuma/users/fixtures/test_users.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1268040
This pull request creates an extra filter for authors on the revisions dashboard, allowing authors to be filtered into "All Authors", "Known Authors" (part of the Known Authors group), and "Unknown Authors" (excluding everyone in the Known Authors group).
> 1268040 dashboard filter known authors

- kuma/dashboards/jinja2/dashboards/includes/revision_dashboard_body.html
- kuma/dashboards/jinja2/dashboards/revisions.html
- kuma/dashboards/tests/test_views.py
- kuma/dashboards/urls.py
- kuma/dashboards/views.py
- kuma/users/models.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1268642
- Replaced Django admin links for Spam/Ham with form buttons that call a new view **submit_akismet_spam**
- New post view **submit_akismet_spam** that creates the spam/ham RevisionAkismetSubmission record with one click from the dashboard page. This new view checks that the user has the correct Akismet permissions before creating this record and redirecting back to the same dashboard page that they were on.
- Tests for this new view
- New model method on kuma.models.users.models.User, checks for Akismet permission: has_akismet_submission_permission
- This new method used in dashboard view to determine show_spam_submission
Possible TODO's:
- Switch Spam/Ham submission to AJAX view. Right now it's a post with a redirect.
- Look into …
> 1268642 mark spam/ham with one click (Akismet submission)

- media/robots.txt
Fix the robots.txt rule so that paths like this are indexed:
``en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json``
but the API endpoint is still not indexed:
``en-US/docs.json?slug=Mozilla``
> bug 1273007 - Fix indexing, paths ending in .json

- kuma/settings/local.py
- requirements/constraints.txt
- requirements/local.txt
In developer VMs, setting environment ``DEBUG_TOOLBAR=1`` will enable the Django Debug Toolbar, useful for tracking database requests, cache usage, etc.
> bug 957802 - Enable django-debug-toolbar

- kuma/dashboards/jinja2/dashboards/includes/revision_dashboard_body.html
- kuma/dashboards/tests/test_views.py
- kuma/dashboards/views.py
Refers to bug https://bugzilla.mozilla.org/show_bug.cgi?id=1272796
- Remove HAM option from form. 
- Don't check for the spam/ham option in the submit_akismet_spam view, default to spam. 
- Remove spam submit value from tests.
> bug 1272796 - Remove HAM option from dashboard

- kuma/dashboards/tests/test_views.py
- kuma/dashboards/views.py
- kuma/wiki/forms.py
- kuma/wiki/tests/test_admin.py
The code to submit missed spam to Akismet is in the form ``clean`` method, so the new "one-click" code doesn't submit to Akismet.
This PR:
* Moves the ``submit_akismet_spam`` tests into their own test class
* Converts ``submit_akismet_spam`` to use a form derived from ``RevisionAkismetSubmissionAdminForm``
* Verifies that Akismet is called in these and some other tests
* Update docstrings and drop an unused method
> bug 1268642 - Submit spam to Akismet when spam is clicked on the dashboard

- kuma/wiki/jinja2/wiki/email/spam.ltxt
This pull request removes 2 of the 3 admin links from the spam attempt email.
> bug 1272787 - remove 2 of the 3 admin links from email template

- kuma/wiki/admin.py
- kuma/wiki/tests/test_admin.py
This pull request changes the link in the Akimset submissions django admin view under “REVISION” from the revision’s admin page to the revision’s public page and updates the related test.
> bug 1272790 - akismet submission in admin make revision link to public site

- kuma/wiki/jinja2/wiki/includes/buttons.html
Fix for [bug 1012106](https://bugzilla.mozilla.org/show_bug.cgi?id=1012106) -- seems very straightforward.
> fix bug 1012106: use language icon for switching languages

- kuma/settings/common.py
- kuma/static/styles/user-banned.styl
- kuma/users/jinja2/users/ban_user.html
- kuma/users/templatetags/jinja_helpers.py
- kuma/users/tests/test_templates.py
- kuma/users/tests/test_views.py
- kuma/users/views.py
This pull request uses the previously-created-but-unused `users.ban_user` view. A GET to this url will display the UserBanForm (with only a 'reason' field) and several common reasons for banning users.
A POST to this url will attempt to save the `UserBan` and return the user to the profile page of the user being banned. Banning requires the `users.add_userban` permission.
> bug 1272793 - spam admins can ban users without django admin

- kuma/static/js/helpfulness.js
- kuma/static/js/wiki-edit.js
- kuma/static/js/wiki-samples.js
- kuma/wiki/jinja2/wiki/list/needs_review.html
I added localization for strings 'Thanks for your feedback!' and "We
won't bug you again."
> Fix bug 1265151 - Missing translation of some strings

- kuma/static/js/wiki-samples.js
While marking the text "Open in Codepen" for translation, the space between the text and the icon was lost. It doesn't really belong in the translated string, adding it as a literal string to the button.
[Live on MDN](https://developer.mozilla.org/en-US/docs/User:stephaniehobson:code#Code_sample_template):
With this change:
> bug 1265151 - Add space back to sample buttons

- kuma/wiki/jinja2/wiki/includes/spam_error.html
This addresses https://bugzilla.mozilla.org/show_bug.cgi?id=1275322 and https://tree.taiga.io/project/viya-mdn-durable-team/task/137.
Add a paragraph with a link to the admin to allow spam moderators to mark submissions as ham and try to submit again.
cc @stephaniehobson
> New issue 1275322 spam admin info on submission

- media/robots.txt
https://tree.taiga.io/project/viya-mdn-durable-team/task/59
This pull request follows up on the request make in https://docs.google.com/spreadsheets/d/1X-YLmIg8vVvDWlShLF-361Cz2KcUBnlaPXBHLMaYEaQ/edit#gid=0 to add several more lines to robots.txt.
@stephaniehobson
> robots.txt edits

- requirements/constraints.txt
- requirements/local.txt
- tox.ini
* flake8 2.5.4 -> 2.6.0: Update to pycodestyle, add F405
* mccabe 0.4.0 -> 0.5.0: flake8 3.0 support
* pep8 1.7.0 -> pycodestyle 2.0.0: Name change, unary operator checks
* pyflakes 1.0.0 -> 1.2.3: Fixes, more checks
The new pyflakes warning ``F405`` is raised when a star import is used (``from common import *``), such as in the Django environment-specific configuration files. These files are going away during the 12factor updates for AWS, so disable the warning for now.
> fix bug 1281038 - Update flake8 and other linters

- kuma/dashboards/views.py
- kuma/users/models.py
- kuma/users/views.py
- kuma/wiki/feeds.py
- kuma/wiki/forms.py
- kuma/wiki/jinja2/wiki/edit.html
Bring over the profile page cleanup from #3889, but retain the recent docs activity.
Switch to sorting by revision IDs instead of the ``created`` date for identifying recent documents. When tested against a local anonymized database, this gives the same result for every profile, but is much faster. In a worse-case scenario, sorting by ``created`` took 33 seconds, and by ``id`` 0.4 milliseconds.
Use this new sorting strategy on:
* The Recent Docs Activity section on the [user profile](https://developer.mozilla.org/en-US/profiles/jwhitlock)
* [The Revision Dashboard](https://developer.mozilla.org/en-US/dashboards/revisions)
* [Revision RSS feeds](https://developer.mozilla.org/en-US/feeds/rss/revisions)
There are additional places where sorting is done by ``created``, for example when …
> Bug 1279839 - Profile page cleanup, use IDs instead of created date for recent activity 

- kuma/wiki/forms.py
- kuma/wiki/jinja2/wiki/includes/spam_error.html
- kuma/wiki/tests/test_forms.py
When Akismet blocks an edit, show the admin link to the filtered ``DocumentSpamAttempt`` changelist, but only to spam moderators.
> bug 1275322 - Adjust message show to spam moderators when revision is blocked

- kuma/search/jinja2/search/results.html
If there's no pre-existing query we should provide a default value.
> Fix Bug 1274734: 'None' placeholder/default value

- Vagrantfile
Unset config.vm.hostname in the Vagrantfile.
Having this option set (currently) causes Vagrant to destructively
edit the guest's /etc/hosts file, removing the localhost alias for
127.0.0.1.
This option shouldn't be needed, since the kuma role is copying over
/etc/hostname anyway.
> fix bug 1276929 - Unset config.vm.hostname in the Vagrantfile

- jinja2/base.html
- jinja2/includes/login.html
- kuma/static/styles/components/structure/oauth-login.styl
- kuma/users/jinja2/account/login.html
- kuma/users/jinja2/socialaccount/snippets/provider_list.html
Adds banner across top of all pages when a user has logged in with persona "You logged in with Persona. [Persona is being turned off. Read more.](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Persona_Sign_In_on_MDN)"
Changes sign in drop down and sign in page to say account creation can only happen with Github (but there are no back end changes to enforce this).
Some things to test:
- Banner shows up when signed in with Persona and not when signed in with GitHub or signed out.
- I used "sign in" and "MDN profile" in all copy (not log in and MDN account).
- Create account with GitHub button works (probably good enough to test that you can sign in using that button)
- No spelling mistakes in copy.
- Sign in with Persona has not been broken.
- Other stuff I haven't thought of.
> Bug 1273028: Persona shutdown banner

- kuma/static/styles/components/content.styl
- kuma/static/styles/components/wiki/customcss.styl
- kuma/static/styles/components/wiki/properties.styl
Made .learn-box use the .properties styles but made it orange.
Removed old learn-box styles from customcss.styl
Updated .standard-table definition to exclude learn-boxes because .learn-box.standard-table is a very common combination.
Testing pages:
https://developer-local.allizom.org/en-US/Learn/HTML/Howto/Use_JavaScript_within_a_webpage
https://developer-local.allizom.org/en-US/Learn/HTML/Howto/Add_a_hit_map_on_top_of_an_image
https://developer-local.allizom.org/en-US/Learn/CSS/Using_CSS_in_a_web_page
https://developer-local.allizom.org/en-US/Learn/CSS/Basic_text_styling_in_CSS
When testing also edit a table to remove the standard-table class and make sure it displays properly.
> Fix Bug 1284584: Standardize learn-box

- kuma/static/js/wiki-samples.js
- kuma/wiki/content.py
- kuma/wiki/tests/test_content.py
Bug 1284781
Note : I haven't been able to fully reproduce the issue, I wasn't able to make the Codepen / JSFiddle buttons.
However, I think it should work.
PS : If someone knows how to make those buttons appear, I'm interested.
> Fix bug 1284781 Samples opened in JSFiddle will fail if CSS includes HTML escapes like &nbsp;

- kuma/wiki/constants.py
Add new authorized attributes for <meter> (max, min, value, low, high, optimum, form).
It should be good. However I seem to have a caching issue, preventing me to test it.
> Bug 1256189 : Add new authorized attributes for <meter>

- kuma/users/adapters.py
- kuma/users/jinja2/account/signup_closed.html
- kuma/users/tests/__init__.py
- kuma/users/tests/test_templates.py
- kuma/users/tests/test_views.py
- kuma/users/views.py
This PR is broken into two commits.
In the first, the social login tests have been refactored to use a a new mixin, ``SocialTestMixin``, that provides class functions ``persona_login()`` and ``github_login()`` to execute a mocked social authentication with good defaults, and the ability to override the defaults as needed.  These result in big changes to the test code, and an ugly diff.
The second commit changes the production code, in ``kuma/users/adapters.py``, which now forbids creating a new account with Persona, and in ``kuma/users/jinja2/account/signup_closed.html``, which has a custom message for Persona users:
Disabling Persona signups requires changing some tests and dropping others, but the test diff is a lot nicer due to the work in the first commit.
r @jgmize? @groovecoder?
> bug 1260257 - Disable signup with Persona

- kuma/static/js/libs/ckeditor/source/build.sh
I can not understand how this script was used to build release version.
BTW, the version we use is ``4.5.8`` not ``4.5.7``
In the past, we added the submodule and we checkout according to the git commit hash, and then run the script to build the editor.
But, later we have removed the submodule but there was a little bug in the script.
@jwhitlock r?
> [Bug 1275387] CKEditor build script uses dev version, not release

- kuma/wiki/jinja2/wiki/translate.html
Fix bug 1277388 : [Bug 1277388 - Missing space in French translation on edit pages ](https://bugzilla.mozilla.org/show_bug.cgi?id=1277388)
- I removed the comma.
- Translators will have to add it, I don't think we can (and if we can I don't know how) do a mass edit.
> Fix bug 1277388 :  Missing space in French translation on edit pages

- kuma/search/filters.py
- kuma/search/jinja2/search/results.html
- kuma/search/tests/test_filters.py
- kuma/static/js/search.js
Addresses https://bugzilla.mozilla.org/show_bug.cgi?id=1262541
Add an 'All Topics' filter that allows user to search all topics. 
Clear out that value when other topics are selected via search.js. 
Add a filter test.
Ready for review by @jwhitlock
> bug 1262541 - Add an "All Topics" filter that will clear out checkboxes on search page

- kuma/wiki/jinja2/wiki/includes/buttons.html
Fix bug 1289589 : [Bug 1289589 - Edit button shows up when user doesn't have edit permission for a page ](https://bugzilla.mozilla.org/show_bug.cgi?id=1289589)
- Remove edit button from templates if the user cannot edit them.
- Remove part of code which was forgot during a clean-up
I separated this into two different commits because removing the old code didn't seem to have a reason to be in the same commit, though I might be wrong.
> Fix bug 1289589 : Remove edit button from templates if the user cannot edit them

- kuma/core/templatetags/jinja_helpers.py
Bug 1243693 : HTML Tags are wrongly displayed in title's bar
For this bug, I didn't managed to find a "real" fix.
- I think the first escape happens when the Document is rendered and a second time when `page_title(title)` is called.
- To work around this bug, I unescaped the string using jinja2.Markup unescape() function which removes the escape.
To ensure it worked properly, I tried to trigger a `<script>` from the title and it wasn't triggered.
> Bug 1243693 : HTML Tags are wrongly displayed in title's bar

- kuma/wiki/jinja2/wiki/translate.html
[Bug 1138173](https://bugzilla.mozilla.org/show_bug.cgi?id=1138173): Escape tags in raw en-US version of an article while editing a local
I remove the |safe because the goal here is to have this string escaped to be able to copy/paste them inside when updating or making a translation.
> Bug 1138173 : Escape tags in raw en-US version of an article while editing a local

- jinja2/includes/google_analytics.html
- kuma/settings/common.py
- kuma/static/js/task-completion.js
- kuma/wiki/jinja2/wiki/document.html
- switching survey provider from iPerceptions to Survey Gizmo
- include task-completion file when user is randomly selected by waffle
- task-completion file checks for availability of local storage before popping up invitation using notifier
- url has query string to configure Survey Gizmo
- user will not be asked again for 30 days
Testing:
- enable `sg_task_completion` for yourself
- open dev tools console
- delete any Local Storage items relating to helpfulness
- visit an article 
- check you get notifier
- click on survey link, should open in a new window (CMD and right click should work too)
- fill out survey
-- should get 5 seconds of "please fill this out after" before questions are visible
-- clicking "I'm done" should also make questions visible
-- when submitted with errors check …
> Bug 1286541: Survey Gizmo task completion

- jinja2/includes/google_analytics.html
GA debug was complaining that the value for custom dimension 12 was expected to be a string, but instead was an integer. This fixes it.
> bug 1287644: Add quotes around GA dim12, revision

- kuma/users/adapters.py
- kuma/users/tests/test_adapters.py
- kuma/users/tests/test_templates.py
When signup fails (due to registration being closed, or an attempt to signup with Persona), clear the social login from the session, so that it doesn't later interpret a new social login as an attempt to link accounts.
Here's the tests I did locally:
**Test 1**: Verify [bug 1063830](https://bugzilla.mozilla.org/show_bug.cgi?id=1063830) is still fixed:
1. Create an account associated with Persona and Github, both of which share an email.
2. Disconnect the GitHub account, log out
3. Login with the GitHub account, get a banner that "A profile already exists with an email address below."
4. Click the link in the banner to start a Persona login.
5. Sign in with a new, different Persona account, get message "Could not find profile matching that account." (fix for bug 1063830)
6. Sign in with …
> bug 1291892 - Clear session on Persona signup fail

- kuma/attachments/tests/test_views.py
- kuma/attachments/views.py
[bug 1287806 : Syntax correction on X-Frame-Options header](https://bugzilla.mozilla.org/show_bug.cgi?id=1287806)
- Fix X-Frame-Options header syntax by removing an excedent ':'
> fix bug 1287806 : Syntax correction on X-Frame-Options header

- kuma/static/js/helpfulness.js
- kuma/static/js/wiki-edit.js
- kuma/static/js/wiki.js
- kuma/wiki/jinja2/wiki/document.html
- kuma/wiki/tests/test_views.py
- kuma/wiki/views/edit.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1268609
Remove call to clearDraft() method on save click.
Disable auto save on save click (which is part of the clearDraft() method).
Line 509 clears out this draft when we return to the edit page, after saving.
https://github.com/mozilla/kuma/compare/master...caktus:new-issue-1268609-save-draft-before-publish?expand=1#diff-e318b5ff8f27b6a7605c11e49310b1aaR509 
cc @stephaniehobson @jwhitlock
> bug 1268609 - Do not delete draft after save click, to prevent data loss

- kuma/dashboards/jinja2/dashboards/spam.html
- kuma/dashboards/jobs.py
- kuma/dashboards/tests/test_views.py
- kuma/dashboards/urls.py
- kuma/dashboards/utils.py
- kuma/dashboards/views.py
- kuma/static/styles/dashboards.styl
Adds a spam dashboard, displaying the trends of spam over time, and a list of the most recent spam revisions.
bug 1260264 (https://bugzilla.mozilla.org/show_bug.cgi?id=1260264)
Taiga user story 351 (https://tree.taiga.io/project/viya-mdn-durable-team/us/351)
> bug 1260264 - Spam dashboard

- kuma/static/js/wiki-edit.js
- kuma/wiki/forms.py
- kuma/wiki/jinja2/wiki/edit.html
- kuma/wiki/jinja2/wiki/includes/page_buttons.html
- kuma/wiki/jinja2/wiki/translate.html
- kuma/wiki/tests/test_forms.py
- kuma/wiki/tests/test_templates.py
- kuma/wiki/tests/test_views.py
- kuma/wiki/views/edit.py
- kuma/wiki/views/translate.py
Pull request begun by @stephaniehobson, which I continued.
https://bugzilla.mozilla.org/show_bug.cgi?id=1260197
When editing a document and clicking "Publish and Keep Editing" (ajax request) the user is no longer always told that the changes were saved successfully. Instead, upon an unsuccessful edit (spam edit, session timeout, midair collision, or something strange), an error message is shown to the user. Back-end errors (spam, midair collision) are returned as JSON and handled by front-end code. Feedback welcome from @jwhitlock and @stephaniehobson or others.
> bug 1260197 - Update "publish and keep editing" workflow

- kuma/core/decorators.py
- kuma/users/adapters.py
- kuma/users/tests/test_adapters.py
- kuma/users/urls.py
- provisioning/roles/Mayeu.RabbitMQ/tasks/install/debian.yml
Add a header to the [Account Connections page](https://developer.mozilla.org/en-US/users/account/connections) to prevent it from being cached:
```
Cache-Control: no-cache, no-store, must-revalidate
```
Also note that our custom ``never_cache`` decorator will not be needed after an upgrade to Django 1.9 or later.
> bug 1296305 - Don't cache the connections page

- kuma/wiki/admin.py
- kuma/wiki/templates/admin/wiki/revisionakismetsubmission/change_form.html
- kuma/wiki/tests/test_admin.py
In Django Admin, display Akismet data as a definition list (Unicode with escaped HTML) rather than as a JSON object. This will make it easier to read non-ASCII submissions. This is used in the admin for the wiki app:
* Akismet submissions
* Document spam attempts
* Revision IPs
> bug 1295310: Improve display of Akismet data

- kuma/core/utils.py
- kuma/settings/common.py
- kuma/wiki/tests/test_templates.py
After these changes, these requirements will be unused and can be removed:
* ``BeautifulSoup``
* ``bitly-api``
It will be safer to remove the requirements after there is no more code using them.
> bug 1277577: Stop using some deprecated requirements

- kuma/core/pipeline/cleancss.py
- kuma/settings/common.py
- requirements/default.txt
django-pipeline 1.5.4 -> 1.6.8: Config change, bug fixes
I generated static files under old and new system, and the output is identical.
This does not include the compressor change in #3852, since those will require updating Vagrant and the deployment environments.
> bug 1277577: Upgrade pipeline

- requirements/default.txt
With PR #3941 merged, these are now unused requirements and can be removed.
> bug 1277577 - Drop BeautifulSoup, bit.ly libraries

- jinja2/base.html
The options to "Report a bug" / "Report a content problem" open in a new browsing context because the content of the page you're currently on is very frequently needed in order to accomplish your goal.
> fix bug 1254630: Open new browsing context when reporting a problem

- jinja2/includes/lang_switcher.html
- kuma/core/tests/test_templates.py
- kuma/search/signals.py
- kuma/wiki/models.py
- kuma/wiki/tests/test_models.py
- kuma/wiki/tests/test_templates.py
So I have changed the way ``other_translations`` model function works. It should return a ``list``, but it was returning ``queryset``. It was done intentionally at #1953. Reading the conversation, got that it was changed because of hard to test. But, now I have seen some test for this function and I have changed the test to test the functionality with ``list`` instead of ``queryset``.
In order to change ``other_translations`` model function, I need to change the ``search/signals.py
`` so nothing will break.
Adding total 3 template tests so that we don't get regression in the future. I hope it works
Though the affect will be in the frontend, most of the changes are in the backend. so @jwhitlock r?
> [Bug 1294904] Language drop down menus should be sorted

- provisioning/roles/nodesource.node/Dockerfile
- provisioning/roles/nodesource.node/README.md
- provisioning/roles/nodesource.node/defaults/main.yml
- provisioning/roles/nodesource.node/meta/.galaxy_install_info
- provisioning/roles/nodesource.node/role.yml
- provisioning/roles/nodesource.node/tasks/main.yml
- provisioning/roles/nodesource.node/vars/main.yml
- provisioning/travis.yml
- provisioning/vagrant.yml
- provisioning/vars/node.yml
Update to the latest version of the ansible-galaxy role ``nodesource.node``, and then patch it to install the NodeSource apt GPG key from keyserver.ubuntu.com, since they switch to CloudFront and SNI for the old file server, and the old version of Python in Ubuntu 14.04 can't handle it.
> bug 957802 - Update node provisioning

- README.rst
- docs/documentation.rst
- docs/index.rst
- jinja2/base.html
- kuma/wiki/jinja2/wiki/sphinx.html
- kuma/wiki/management/commands/generate_sphinx_template.py
- requirements/docs.txt
* Fix the ``./manage.py generate_sphinx_template`` command
* Update the template to match the current MDN JS and CSS
* Omit some more items from the Sphinx template, such as social graph and Google Analytics
* Add generating the documentation to the documentation
* Update the docs to use the new version of the theme.
This PR is used to generate the changes in https://github.com/mdn/sphinx-theme/pull/10, which is necessary to release ``mdn-sphinx-theme`` version 2016.0 and fix some issues with the [current documentation](https://kuma.readthedocs.io/en/latest/).
@stephaniehobson I'd appreciate a code review, especially of ``base.html`` but I don't expect you to generate the docs locally unless you are looking to level up in backend development.
> Bug 950945: Fix and improve MDN Sphinx template

- requirements/docs.txt
Uses the [new theme](https://pypi.python.org/pypi/mdn-sphinx-theme) tagged from https://github.com/mdn/sphinx-theme/pull/10 and generated from #3954.
r? @stephaniehobson
> bug 950945: Update mdn-sphinx-theme to 2016.0

- Dockerfile-base
- requirements/constraints.txt
This builds on #3960 but installs setuptools 26.1.1 without hash verification in `Dockerfile-base` as a workaround for the `AttributeError: 'Requirement' object has no attribute 'project_name'` error we get when attempting to use hash verification.
> Setuptools 26.1.1

- .gitignore
- docs/installation-docker.rst
Update the Docker installation documents for the new Docker environment, and get them to the "view the homepage" step in the Vagrant documentation.
The double-installation of product details is not ideal (once in the image, once again with the ``git clone`` checkout), but documenting what it looks like now, while I work on a PR to change it ([bug 1302459](https://bugzilla.mozilla.org/show_bug.cgi?id=1302459))
@stephaniehobson can you try the instructions to make sure they are clear?  The empty database path is sufficient for the homepage test.
@jgmize can you do a sanity check?
> bug 1218563: Add basic install docs for Docker

- requirements/default.txt
After PR #3953 was deployed, this requirement is no longer used.
> bug 1277577: Remove django-smuggler

- Makefile
- docker-compose.yml
- docs/development.rst
- docs/installation-docker.rst
- kuma/settings/local.py
Update the [Development](https://kuma.readthedocs.io/en/latest/development.html) docs to run in either Vagrant or Docker.  It may be easier to review by letting GitHub [render the document](https://github.com/mozilla/kuma/blob/d5d7875b812a0225b34eb64f840f2b0efef90381/docs/development.rst).
This integrates some changes from other branches and PRs:
* Add ``make bash``, ``make up``, etc. from @jgmize jgmize's branch
* Add ElasticSearch from @safwanrahman PR #3976 
* Fix ``PIPELINE_ENABLED`` in Vagrant from PR #3972 
I'm trying to err on the side of an incremental change instead of a perfect fix. I'm omitting these tasks, documented in the [triage doc](https://docs.google.com/document/d/1cnuw2F25gtUPeHCXuu8zYf5H9v_UPdgmanJ7oVM6uoc/edit#):
* Nice to Have
- Method for using ``fswatch`` in host …
> Bug 1218563: Update Development docs for Docker

- docker-compose.yml
- kuma/settings/common.py
* Update KumaScript to current master, which includes setting the configuration from the command like.
* Add a new api service to handle KumaScript requests, allowing the docker-compose v1 linking to work correctly
* Allow environment override of the setting ``KUMASCRIPT_URL_TEMPLATE``
* Configure kumascript service for rendering pages and caching responses
r? @jgmize
> Bug 1218563: Enable page rendering in Docker

- kuma/static/styles/components/syntax/base.styl
- kuma/static/styles/includes/mixins.styl
Small code change to force LTR in code samples. Problem is most apparent in webkit browsers.
Useful testing pages:
https://developer.mozilla.org/en-US/docs/User:stephaniehobson:code
https://developer.mozilla.org/ar/docs/User:stephaniehobson:code (not actually translated but appears with RTL UI and styles.)
> Fix Bug 1305156: Code Samples are LTR

- kuma/static/styles/components/wiki/contributor-avatars.styl
- Makes button text right aligned (more noticeable on pages where button is 2 lines, like German)
- Also decreased specificity of li and a definitions.
- Removed background colour on avatars as it was interfering with transparent ones.
> Fix Bug 1295200: contributor button text right align

- kuma/static/styles/includes/mixins_indicators.styl
Over-rides the clear:both value assigned by using the clearfix() mixin.
> Fix Bug 1281855: Indicators shouldn't clear:both

- docs/development.rst
- docs/troubleshooting.rst
* Fix some header issues in the Development doc
* Refresh the Vagrant section on running individuals processes to reflect the current ``Procfile``, and how to adjust just one process.
* Update the Troubleshooting doc to include Docker. I think the Kuma Reset section, ``docker-compose build --pull``, would have fixed an [issue jgmize saw with MySQL](https://github.com/mozilla/kuma/pull/3975#pullrequestreview-463218).
r? @jgmize
> bug 1218563: Update Troubleshooting Doc

- docker-compose.yml
- docker/images/mysql-data/Dockerfile
- docs/development.rst
Switch ``docker-compose.yml`` from version 1 to version 2 format, picking up a few features:
* Version 2 constructs a network that all the containers share, so ``links`` is unneeded for communication. Switch from ``links`` to ``depends_on``, to still show dependencies between services.
* Define a named volume ``mysqlvolume`` to hold the database data, removing the data container ``mysql-data``.  This is now recommended by the [Docker community](http://stackoverflow.com/a/20652410/10612), even though the Docker docs haven't caught up yet.
You'll have to recreate ``mysql-data`` container to make this work.  I suggest:
```
docker-compose up  # Gives warnings, uses old volume
docker exec kuma_mysql_1 sh -c 'exec mysqldump --all-database -ukuma -pkuma' > dump.sql  # Save the data …
```
> bug 1218563: Upgrade to docker-compose v2 format

- requirements/default.txt
Django 1.8.14 -> 1.8.15: Security update, CSRF bypass w/ Google Analytics
> bug 1305550: Upgrade Django

- requirements/README.rst
> bug 1218563: Document building/updating base img

- docs/celery.rst
These docs appear to have been written when Celery was newly introduced to Kuma, and developers ran services on their host machine. Re-wrote the document to reflect the current usage, and to remove RabbitMQ installation instructions.
> bug 1218563: Update Celery docs for Docker

- Makefile
This is necessary due to the recent docker upgrade on our CI.
https://docs.docker.com/engine/deprecated/#/f-flag-on-docker-tag
@jwhitlock r?
> bug 1218563: remove deprecated docker tag -f

- kuma/wiki/tasks.py
[Bug 1292624 comment 2](https://bugzilla.mozilla.org/show_bug.cgi?id=1292624#c2) describes to reproduce the issue and check the feature. Unfortunately, due to [Bug 1301867](https://bugzilla.mozilla.org/show_bug.cgi?id=1301867), the page move does not work and the email is not generated if ``CELERY_ALWAYS_EAGER`` is ``True``. So you should add ``CELERY_ALWAYS_EAGER = False`` in the ``.env`` file in order to get the test email in ``/tmp/kuma-messages``
@jwhitlock r?
> [Bug 1292624] Suggest moving translated pages after moving an English page

- kuma/wiki/admin.py
When displaying Akismet data in the Django admin, display in an order that reflects the most interesting data for spam administrators:
1. The content diff
2. The page URL
3. The author's username
4. The author's email
5. Other data in the Akismet submission spec (alpha sort)
6. HTTP Headers and other metadata (alpha sort)
> bug 1295310: Adjust order of Akismet data in admin

- jinja2/base.html
- kuma/landing/jinja2/landing/homepage.html
- kuma/static/styles/components/home/base.styl
- kuma/static/styles/components/home/home-features.styl
- Web Platform -> Web Technologies
- Move WebExtentions under Web Technologies
- Remove Mozilla Docs and Contact from homepage
- Add Learning Area to homepage
- Remove HTML5 and CSS3 from homepage
- Add styles to vertically center single line headings in supporting browsers
> Bug 1260487: Remove obsolete items from nav & homepage.

- .travis.yml
- scripts/docker-compose.travis.yml
- scripts/travis-install
- tox.ini
All the test will pass after merging #3975 #3976 
I have tried and this is the [result](https://travis-ci.org/safwanrahman/kuma/jobs/160749971)
We must configure travis to build and run all the test in docker environment  so we can track if any of our patch make the docker environment broken.
Instead of pulling ``kuma_base`` image, I have configured to build the image locally so it will be possible to test against the ``Docker-base``. So in future we can avoid any regression and it will be easier to track.
Regarding travis CI, Docker is only supported in ``Ubuntu Trusty`` Environment and unfortunately, ``Elasticsearch`` service [is not available in the trusty environment](https://docs.travis-ci.com/user/trusty-ci-environment/#Data-Stores). So needed to configure the build script in order …
> [Bug 1218563] Run test in Docker environment with Travis CI

- .dockerignore
Add a .dockerignore that includes:
- Everything in .gitignore
- Everything in kumascript/.gitignore
- .git folders and others not needed in containers
This reduces my build context from 2 GB to about 50 MB.
> bug 1218563: Add .dockerignore

- kuma/static/js/task-completion.js
Increased the wait before prompting again to 32 days. The django waffle flag sorting lasts 31 days. This means people will be re-sorted randomly by waffle before the survey code can prompt them with the survey again.
> Bug 1286541: Task completion longer between prompts

- tox.ini
Improve on PR #3977 (test docker travis):
- Use environment variables to simplify ``docker-compose`` calls
- Eliminate some warnings by adding build steps, configuring ``tox``
- Start the ``mysql`` container while the ``web`` image is building, to eliminate ``sleep 60``
- _Formerly included "build and test the base image", but PR #3977 already does that_
See #4011 for an alternate implementation with less commands.
> bug 1218563: Improve TravisCI docker build and test

- kuma/wiki/content.py
- kuma/wiki/tests/test_content.py
* In wiki.content::Extractor.code_sample, escape the name of
the code sample when falling-back to the pyquery find.
* Add test for this case.
> bug 1269143: escape sample name

- kuma/wiki/tasks.py
- kuma/wiki/tests/test_templates.py
* update wiki.tasks.send_first_edit_email to add locale
to subject of the "first-edit" email
* update test_new_revision_POST_document_with_current
within wiki/tests/test_templates.py to reflect change
> bug 1308307: add locale to subject of email

- kuma/static/js/wiki.js
- kuma/static/styles/base/elements/typography.styl
Previously we've used the CSS property hyphens to break up long titles on short screens but it's not cross browser and it breaks stuff that doesn't need to be broken, obscuring meaning.
This small script targets only long article titles and adds a <wbr> tag to give the browser more accurate direction for where to break titles.
Testing pages:
https://developer-local.allizom.org/en-US/docs/Web/API/MediaStreamAudioDestinationNode/stream
https://developer-local.allizom.org/en-US/Add-ons/Firefox_for_Android/API/window.NativeWindow/window.NativeWindow.contextmenus/window.NativeWindow.contextmenus.remove
https://developer-local.allizom.org/en-US/docs/Web/CSS/:-moz-system-metric%28scrollbar-thumb-proportional%29
(make sure code escaping is working properly) …
> Fix Bug 1149205: Break long titles intelligently.

- kuma/wiki/content.py
- kuma/wiki/tests/test_content.py
* fix case when sample name contains null or control
characters (in general whenever a ValueError is
raised within the PyQuery.find method).
* add test case
> bug 1269143: fix for null/ctl chars in sample name

- docs/feature-toggles.rst
- jinja2/includes/newsletter.html
- kuma/landing/jinja2/landing/homepage.html
- kuma/settings/common.py
- kuma/static/js/newsletter.js
- kuma/static/styles/components/form.styl
- kuma/static/styles/components/home/home-features.styl
- kuma/static/styles/components/home/home-masthead.styl
- kuma/static/styles/components/newsletter.styl
- kuma/static/styles/main.styl
- kuma/users/jinja2/users/user_edit.html
- kuma/wiki/jinja2/wiki/document.html
Newsletter sign up form added behind waffle switch (``newsletter``) on homepage, article footers (+``newsletter_article``), and profile edit page. Plus associated styles and javascript. newsletter.js was copied from https://github.com/mozilla/basket-example and then modified.
Things to test:
- Use failure@example.com and success@example.com to test responses from the server on form submissions. An error message should display on screen.
- Google Analytics events should fire on: input focus, form submission, form success, form error, user clicking the close button on the form
- There's a close button on the form. It should only display on the article pages for browsers with local storage support. Clicking the close button should make the form go away and localStorage should prevent it from …
> Bug 1310322: Add Newsletter Sign-Up

- Dockerfile-base
- docker-compose.yml
It will add a without root privilege user named ``kumadev`` and adding ``USER`` parameters in docker file so all the shell access will be done with ``kumadev`` user. As per mentioned in [doc](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/user)
If anyone needs root access to the container, they can add ``--user root`` parameter to either ``docker exec`` or ``docker-compose run``.
like
``docker-compose run --rm --user root web bash``
@jwhitlock r?
> [Bug 1218563] Adding a user without root privillage in docker

- docker-compose.yml
- kuma/settings/local.py
- enable Django Debug Toolbar by adding in the container's IP address
- log gunicorn accesses to stdout, so that the docker logs catch them
> Adjust settings to improve debugging

- docker-compose.yml
- docker/images/mysql/Dockerfile
- docker/images/mysql/kuma.cnf
Move settings from `my.cnf` and `docker-compose.yml` to `/etc/mysql/conf.d/kuma.cnf`, and add some additional params to speed up test runs.
The big one is `innodb_flush_log_at_trx_commit=0`, which changes from writing to disk with each commit (`default of 1`) to writing once per second.  This was a 24% speed boost on Docker for Mac, from 1047 seconds to 745.
> bug 1218563: Tune MySQL for local development

- kuma/static/styles/base/elements/typography.styl
- kuma/static/styles/components/home/column-callout.styl
- kuma/static/styles/components/home/home-masthead.styl
- kuma/static/styles/components/wiki/communitybox.styl
- kuma/static/styles/includes/vars.styl
Fix Bug 924767 - text contrast
Bug 924583 - link contrast
Fix Bug 1306286 - homepage contrast
Subtle increase to contrast of body text since we were already meeting WCAG guidelines here.
Less subtle increase to link colour. Still don't met WCAG guidelines but significant improvement, especially on non-white backgrounds.
Homepage contrast issues should be fixed by combination of text contrast changes and changing colour of callout background.
> Bugs 924767, 924583, 1306286: Increase contrast on text and links

- kuma/wiki/middleware.py
- kuma/wiki/tests/test_middleware.py
~~by making use of the existing utility function `locale_and_slug_from_path`.~~
by checking to see if the requested url is '/docs/' + a zone root url and then dealing accordingly.
> bug 1267197: Change DocumentZoneMiddleware to deal with locale + zone redirects correctly

- .travis.yml
- scripts/travis-install
- tox.ini
Refresh the locales in TravisCI, to detect issues in templates and translations during the PR process. Run a diff of the changed strings, to make it easier to determine when to release a new string pack.
> bug 1314613: Add locale refresh as TravisCI task

- Makefile
- tox.ini
``cd --`` does the wrong thing inside the Docker container, and is also unnecessary, since each line of a Makefile is run in a separate process.
Also, ``less``, the default pager for ``git diff``, is interactive and does poorly in a TravisCI job, waiting for input that never happens. Instead, use ``cat`` as the git pager.
> bug 1314613: Fix "locales" job in TravisCI

- jinja2/includes/newsletter.html
I just surrounded the string with the usual pattern and checked that HTML attributes were also dealt the same way on https://github.com/mozilla/kuma/blob/752bfb9ec0e803655c88a5391bba92b86ef33bdc/jinja2/includes/login.html#L19. Hoping it's ok for such a minor matter.
> Escaping placeholder in template for bug 1315078

- kuma/static/styles/components/structure/main-header.styl
Slight tweak to logo placement at tablet (1024) size.
Before:
After:
> Bug 925460: Tweak mobile header logo placement

- kuma/static/js/newsletter.js
It confuses the analytics if people can dismiss the thank you message, so don't show close button with thank you message.
> Bug 1310322: Remove close button from thanks

- .travis.yml
- tox.ini
The new locales task includes running ``dennis`` to lint the locales, so it is no longer needed as a separate ``tox`` / TravisCI task.
> bug 1314613: Drop dennis from TravisCI tasks

- docker-compose.yml
- docker/images/mysql/kuma.cnf
- kuma/wiki/jinja2/wiki/document.html
- kuma/wiki/jinja2/wiki/includes/buttons.html
- kuma/wiki/tests/test_forms.py
So if there are ``fallback_reason``, we should show the ``parent document`` locale as choice also. As the ``document`` is replaced by ``parent_document`` from view, we can only use the ``document`` attributes.
@jwhitlock r?
> [Bug 1308168] non-translated page should have English link to button, banner

- kuma/dashboards/jinja2/dashboards/includes/revision_dashboard_body.html
- kuma/static/styles/components/banned.styl
- kuma/static/styles/users.styl
- kuma/users/jinja2/users/includes/user_title_info.html
- kuma/users/views.py
Displays ban info to users with ban permissions instead of super user permissions.
Adds ban date and moderator to user profile page.
> Bug 1259776: Display ban info on user profile

- kuma/wiki/tasks.py
- kuma/wiki/views/document.py
Use ``id`` instead of ``email``
@jwhitlock Small fix. r?
> [Bug 1308222] move page fails with multiple profile same email

- docker-compose.yml
Django 1.8.16 checks [ALLOWED_HOSTS](https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-ALLOWED_HOSTS) even when ``DEBUG=True``. This prevented the api container from accepting connections from the kumascript container, even though it allowed direct access with http://localhost:8001.
Added 'api' and 'web' as expected hostnames, and the other local names you get with the default ``ALLOWED_HOSTS``.  Django strips the port number from the request host, so 'localhost:8000' is always checked as 'localhost', and does not need to appear in the settings.
To check that kumascript is talking to the api container:
1. Log in to your local MDN (only logged-in users can request a page re-render)
2. Set constance variable ``KUMASCRIPT_TIMEOUT`` to 30 (default 0, disables rendering)
3. Set …
> bug 1314290: Fix ALLOWED_HOSTS for api in Docker

- requirements/constraints.txt
The click maintainers uploaded a new wheel for [6.6](https://pypi.python.org/pypi/click/6.6) (see https://github.com/pallets/click/issues/671), and pip is failing to install based on the new hash.  This PR adds the wheel's new hash.
> bug 1308322: Add wheel hash for click 6.6

- kuma/wiki/jinja2/wiki/ckeditor_config.js
Fix bug 1318821 — Change CKEditor config so the toolbar option to create a Syntax Box creates a ``<pre class=“syntaxbox”>`` instead of a ``<div class=“syntaxbox”>``. This makes it actually work right. While at it, I normalized the capitalization of the titles of options in the styles menu.
> Bug 1318821 - Fix syntaxbox to use <pre>

- kuma/core/migrations/0003_remove_unused_taggeditems.py
- kuma/core/migrations/0004_remove_unused_tags.py
This 2 migrations will remove the un used taggs as well as taggeditem without models from database
@jwhitlock r?
> [Bug 1239756] Purge taggit_tag table of dead tags

- kuma/users/models.py
- kuma/users/tests/test_models.py
Fix bug 1306087: if you have a stack overflow profile in another country/language such as `es.stackoverflow.com` the validation fails. 
I'm restricting anything before `stackoverflow.com` to two lowercase letters so any `meta.stackoverflow.com` type url fails. I didn't extend the regex to  handle usernames as suggested in the [comments on bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1306087#c5) - it's unnecessary for now and should be added for all profile urls or none.
> fix bug 1306087 - Update stackoverflow profile with regional domain

- docs/localization.rst
- kuma/core/management/commands/translate_locales_name.py
- kuma/settings/common.py
Update documentation to reflect the new process for adding a new locale. First, the locale is enabled for translation of UI strings in Pontoon, and second it is enabled as a possible language for wiki translations.
> bug 1321352: Add candidate languages

- docs/installation.rst
- docs/troubleshooting.rst
When the database is corrupted, the named volume must be removed and recreated. Add how-to instructions to the troubleshooting docs.
> bug 1218563: Add docs for resetting database

- docker-compose.yml
On MacOS, ``UID`` is unset, and the root is used by default. This causes the worker container to fail, since ``C_FORCE_ROOT`` is no longer used.  Change the default to UID 33, which is the ``www-data`` user, when UID is unset.  I believe most Linux systems (including the Jenkins build?) set a ``UID`` in the environment.
Message printed in the logs:
```
Running a worker with superuser privileges when the
worker accepts messages serialized with pickle is a very bad idea!
If you really want to continue then you have to set the C_FORCE_ROOT
environment variable (but please think about this before you do).
User information: uid=0 euid=0 gid=0 egid=0
```
> bug 1218563: Default to www-data user

- docs/tests-ui.rst
- tests/functional/test_article.py
- tests/functional/test_dashboard.py
- tests/functional/test_home.py
- tests/pages/admin.py
- tests/pages/base.py
- tests/pages/dashboard.py
- tests/pages/regions/notification.py
- testing usernames and passwords
- page object for logging into admin
- test "sign in" forwards to github
- tests for revision dashboard
Testing usernames will be part of sample database or can be configured manually on dev machines. They will not be on staging or production.
Use `-m "not login"` to exclude tests requiring a login.
Not all login tests are destructive.
> Bug 1314708: Add testing login credentials, add dashboard tests

- kuma/settings/common.py
- kuma/static/js/analytics.js
- kuma/wiki/tests/test_content.py
This builds on and replaces PR #4081 
* When edits are saved, detect the use of the ``data:`` protocol with leading spaces and remove from the content.
* When running ``trackOutboundLinks``, check for links using``data:`` protocol before the check for the ``no-track`` class.
The new detection pattern has been applied to stage and production.
> bug 1325125: Detect leading spaces in the data protocol

- kuma/wiki/constants.py
The quick redirect detection code depends on the class attribute being the first attribute. However, content sanitation may rearrange the attributes. Use a more forgiving quick detector, then do a full parse of the page.
> bug 1326384: Adjust redirect detection

- .env-dist
- docker-compose.yml
- docs/development.rst
Speed up local development by defaulting `DEBUG_TOOLBAR` to `False`.
> Disable debug toolbar to speed up local dev.

- kuma/users/jinja2/users/user_detail.html
- kuma/wiki/jinja2/wiki/document.html
- kuma/wiki/jinja2/wiki/includes/buttons.html
- kuma/wiki/jinja2/wiki/includes/document_tag.html
- kuma/wiki/jinja2/wiki/list/tags.html
- kuma/wiki/jinja2/wiki/translate.html
Based on the [Google search results](https://www.google.de/search?biw=1280&bih=1237&q=site:developer.mozilla.org#q=site:developer.mozilla.org&start=553&filter=0) posted in the [parent bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1316610), I *think* I've found all the links missing `rel="nofollow, noindex"`.
> Add rel="nofollow" to non-indexable links.

- .gitignore
More robust git ignore for build and static directories within kuma repo.
> bug 1332777: git ignore static directory

- README.rst
These sites moved from paas.allizom.org to new homes.
> bug 957802: Update links to PRs, What's Deployed

- .gitignore
- gulpfile.js
- package.json
After merging, need to run `npm install`, then `gulp`. With `gulp` running, any change to a file in `/kuma/kuma/static` should be logged to the console and copied to `/static`.
Page loads are a bit slower (~3.5s), but I'm guessing that's due to the pipeline recompiling assets each time. Still a workable delay, IMO.
> Add Gulp to front-end workflow.

- .travis.yml
Current cache documentation (https://docs.travis-ci.com/user/caching/) says:
* Use "cache: pip" instead of caching the directory
* Don't cache Debian packages
> bug 957802: Update TravisCI cache

- jinja2/includes/translate_locales.html
- kuma/settings/common.py
- kuma/settings/stage.py
* Add Bulgarian (bg) to the list of candidate languages for MDN.  This makes the string "Bulgarian" available for translation (next time we extract strings).
* Enable candidate languages in development and staging, so translators can see strings in context.
* Annotate languages list, so it is easier to identify locales
> Bug 1265891: Add Bulgarian to candidate languages, display in some environments

- kuma/static/js/syntax-prism.js
- kuma/static/styles/libs/prism/prism-line-numbers.css
This let's you do:
```
<pre class="brush: js no-line-numbers">
console.log("foo");
</pre>
```
Rendering with and without "no-line-numbers":
> Fix Bug 1332013: Allow syntax highlighting without line numbers

- scripts/chief_deploy.py
The celery nodes run kumascript, and are used for force-refresh document rendering.  Previously, celery's kumascript was restarted before the code was updated, so they always ran last deployment's code.  This didn't matter much over the last 5 years, when kumascript engine changes were rare.
Change deployment from:
* Update code on web machines
* Restart Apache on web machines
* Restart KumaScript on all machines
* Ping New Relic
* Update code on celery machines
* Restart Celery on celery machines
to:
* Update code on all machines
* Restart Apache on all machines
* Restart KumaScript on all machines
* Restart Celery on the celery machines
* Ping New Relic
> bug 1332886: Fix deployment

- docs/ckeditor.rst
Added that you need to build-static after building the editor to pick up the new version. Also added info about where to find the source for plugins and how to do a build to test changes to them.
> Update CKEditor doc to be more complete

- docker-compose.yml
It is a lesser wrapper on the native Date type, and is shadowing the native Date type after the node 6.x update.
> bug 1332828: Remove DekiWiki:Date from autoload

- Dockerfile-base
Get node-sass into the base image, so the quick tests (locales in TravisCI, tests in Jenkins) will pass for PR #4109.
> bug 1330838: Add node-sass to base image

- kuma/static/styles/base/utilities.scss
- kuma/wiki/jinja2/wiki/ckeditor_config.js
Add "Hidden When Reading" option to style dropdown in editor. In the menu, it has a similar appearance to when hidden content is displayed in the editor (that is, with a dotted outline around it). The small black area at the top-left is where the "hidden" tab is in the edit box; @stephaniehobson says this is not something we can easily fix and it isn't a significant issue anyway, so it should be fine as it is.
This is a rebase of PR #4057 after the Stylus → Sass change.
> bug 930102: Add "Hidden When Reading" style

- kuma/static/styles/base/elements/typography.scss
- kuma/static/styles/components/syntax/syntaxbox.scss
- kuma/static/styles/components/wiki/indicators.scss
Can't fix the Safari problem. Filed a bug, https://bugs.webkit.org/show_bug.cgi?id=166870
The IE problem is with an indicator that was a bit of a hack to begin with - we're styling based on inline styling. IE is changing the inline style from a hex to an rgb colour. So now we have a selector for the rgb value as well.
Text styling difference has to do with differing support for text-overflow: ellipsis. I don't think we want ellipsis here, since it could hide important information, so I removed it.
IE also has no default saying for abbr, so added that.
> Fix Bug 1329743: Compat bugs.

- kuma/wiki/jinja2/wiki/ckeditor_config.js
Enable multi-language spellchecking and adjust SCAYT settings.
This is a rebase of PR #4067, but without auto-loading of the SCAYT plugin.
> bug 1031910 - Multilingual spellcheck

- kuma/static/styles/components/content.scss
- kuma/static/styles/includes/_vars.scss
Updated the ``twocolumns`` and ``threecolumns`` classes so they draw with a pale blue dotted border around the columns when in the editor, for ease of layout work. The format is in a variable (``$editor-box-border``) so it can be reused in other similar cases if needed.
This is a rebase of PR #4080 after the Stylus → Sass update.
> bug 1325097: Make columns more visible in editor

- kuma/static/styles/components/wiki/customcss.scss
Essentially reverts back to the style prior to Stylus ➡️ Sass conversion. Combines redundant selectors.
> Bug 1335663. Remove black border around compat table heading.

- kuma/settings/common.py
The Jinja2 PipelineExtension can't render error CSS. This is tracked upstream in https://github.com/jazzband/django-pipeline/issues/614
Use the ``PIPELINE`` setting that raises an exception instead.
> bug 1330838: Raise exceptions on pipeline errors

- kuma/wiki/jinja2/wiki/ckeditor_config.js
The language detection regex worked for regular URLs, but not zone URLs (URLs that omit /docs/). The new code works on both kinds:
https://developer.mozilla.org/en-US/docs/Web/HTML
https://developer.mozilla.org/en-US/Add-ons/Themes
> bug 1031910: Fix language detection for zones

- kuma/core/managers.py
- kuma/core/tests/test_taggit_extras.py
- kuma/settings/common.py
- kuma/static/js/users.js
- kuma/users/views.py
- kuma/wiki/tests/test_models.py
- requirements/default.txt
With [bug 1293749](https://bugzilla.mozilla.org/show_bug.cgi?id=1293749) fixed (Add missing ``UNIQUE KEY`` indexes in production), some new issues have appeared:
* [bug 1330357](https://bugzilla.mozilla.org/show_bug.cgi?id=1330357) - ISE if profile interest tag is not lowercase in the database
* [bug 1331643](https://bugzilla.mozilla.org/show_bug.cgi?id=1331643) - ISE when adding two document tags that only differ in capitalization
Both appear to be caused by an issue with [django-taggit](https://github.com/alex/django-taggit) and MySQL with a case-insensitive collation and a unique index.  Adding two "case similar" tags, like "WEB" and "web", will result in attempting to add both, and raise an IntegrityError.
The issue is handled in this PR by querying the database for existing tags with …
> bug 1331643, 1330357: Avoid duplicate tags with TAGGIT_CASE_INSENSITIVE=True

- tox.ini
In TravisCI, show the locale diff only if the localizable string changes. This makes it clearer when a string update is needed.
> bug 957802: Show locale diff only on string change

- kuma/users/tests/__init__.py
- kuma/users/views.py
GitHub added a new parameter "[visibility](https://developer.github.com/v3/users/emails/#toggle-primary-email-visibility)" to reflect if a GitHub user's primary email address is visible on their profile.  Update the signup form to only load the expected variables.
> bug 1339375: Handle new params in GitHub emails

- kuma/core/tests/__init__.py
- kuma/users/tests/__init__.py
- kuma/wiki/tests/test_forms.py
Remove ``TransactionTestCase`` in order to run the test faster in OS X. @davedash [blogged it ](http://davedash.com/2010/03/16/making-our-tests-run-thrice-as-fast/) many years ago while working in ``zamboni`` and I think it is still valid today.
I believe this test was living there from the ``zamboni`` era as ``kitsune`` and ``zamboni`` shared code among each other.
> [Bug 1218563] Remove TransactionTestCase in order to make test faster

- contribute.json
* Move ``home`` link from old Platform dev page to MDN Durable Team homepage
* Update IRC handle list
* Fix ``mentored`` and ``goodfirstbug`` links
* Swap keyword ``vagrant`` for ``docker``
> bug 957802: Update contribute.json

- kuma/wiki/urls.py
This PR simply removes the "wiki.move_requested" endpoint (https://developer.mozilla.org/en-US/docs/move-requested) as it is a broken URL (always raises an ISE). It's view is a generic TemplateView, and it's template expects a context containing a document, but there's no way to inject a document into the context, either for example via GET params (they are not extracted even if provided) or POST data (POST's are not handled).
This endpoint was originally added via this commit https://github.com/mozilla/kuma/commit/b71558845015a11deab36a370a317bf4cc75fbff in 2013, and was originally used as a target for redirects from the "wiki.move" endpoint (as @jwhitlock suspected - amazing memory!). This is no longer the case. The endpoint is no longer used, and can be safely removed.
> bug 1342474: remove wiki.move_requested endpoint

- kuma/wiki/jinja2/wiki/list/needs_review.html
Fixed the capitalization of the Articles in need page title as specified by the styleguide here https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Writing_style_guide#Title_and_heading_capitalization
> Bug 1332882 Fix capitalization for Articles in need of review page

- kuma/static/styles/maintenance-mode-global.scss
- kuma/wiki/jinja2/wiki/includes/document_macros.html
- kuma/wiki/jinja2/wiki/list/revisions.html
- kuma/wiki/jinja2/wiki/revision.html
- "Edit page" from /profiles/Profile
- "Revert to this revision" from /docs/path/to/doc$revision/123456
- "Change revisions" from /docs/path/to/doc$compare?locale=whtvr&to=12345&from=67890
- "Add a translation" from most/all /docs pages (inside the "Languages" drop down)
> Hides the following links/buttons:

- Jenkinsfiles/demo.groovy
- Jenkinsfiles/dynamicmysql.yml
- Jenkinsfiles/import-demo-db.sh
- Makefile
- docs/development.rst
following the docs [here](https://kuma.readthedocs.io/en/latest/development.html#deis-workflow-demo-instances), the MySQL database should now be populated with sample data upon demo instance creation. 
Note: demo branch names must follow Deis naming conventions, hence the sad branch name so I could test an actual demo instance.
> Automatically import sample MDN db upon k8s demo instance creation

- Jenkinsfiles/content-exp.yml
- jinja2/base.html
- jinja2/includes/google_analytics.html
- kuma/settings/common.py
- kuma/static/js/experiment-framework-test.js
- kuma/static/js/experiment-wiki-content.js
- kuma/static/js/libs/mozilla.cookiehelper.js
- kuma/static/js/libs/mozilla.dnthelper.js
- kuma/static/js/libs/mozilla.trafficcop.js
- kuma/wiki/jinja2/wiki/base.html
- kuma/wiki/jinja2/wiki/includes/buttons.html
- kuma/wiki/tests/test_templates.py
- kuma/wiki/tests/test_views_document.py
- kuma/wiki/views/document.py
- media/robots.txt
Content experiments are A/B tests where some visitors see the Document content from a different page, based on a URL parameter. See [A/B Testing of wiki page content](https://docs.google.com/document/d/1CUe6-EqNbpSkLMLxfd0RWW6-TbPZFRtLc0rMh2Uu3G0/edit#) for the full spec.
This PR doesn't include functional tests, but should.  I plan to add those in a future PR, after PR #4150 is merged.
The first experiment will test out the framework. Anonymous users visiting [Web/JavaScript/Reference/Operators/Comparison_Operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators) will have a 50% / 50% chance of viewing the content from [Experiment:FrameworkTest/Comparison_Operators](https://developer.mozilla.org/en-US/docs/Experiment:FrameworkTest/Comparis …
> Bug 1341770: Add content experiments

- kuma/wiki/tasks.py
- kuma/wiki/utils.py
Use ``settings.LANGUAGES``, which includes ``CANDIDATE_LANGUAGES`` when enabled, instead of ``MDN_LANGUAGES``, which does not.  Two changes:
* ``kuma.wiki.utils.locale_and_slug_from_path`` - KumaScript requests raw pages in a interesting way, like [/en-US/docs/fr/Web/CSS?raw](https://developer.mozilla.org/en-US/docs/fr/Web/CSS?raw) instead of the expected [/fr/docs/Web/CSS?raw](https://developer.mozilla.org/fr/docs/Web/CSS?raw). Without this change, pages in candidate languages can't be rendered when enabled.
* ``kuma.wiki.tasks.build_sitemaps`` - Allow building candidate language sitemaps, found at http://localhost:8000/media/sitemaps/bg/sitemap.xml
> bug 1340003: More changes for candidate languages

- Jenkinsfiles/prod-integration-tests.yml
- Jenkinsfiles/stage-integration-tests.yml
- docs/tests-ui.rst
When running UI tests, omit the maintenance modes by default.
> bug 1313237: Omit Maintence Mode tests

- tests/functional/test_content_experiment.py
- tests/pages/article.py
- tests/pages/content_experiment.py
* Allow slug change for ArticlePage
* Add ArticlePage.has_edit_button
* Add VariantPage for content experiment variant pages, with helper methods.
* Test anonymous users are redirected on content experiment page
* Test logged-in users get regular experience
* Test GA parameters on content experiment variants
> bug 1341770: Add tests of content experiments

- docs/tests-ui.rst
Link to the [PyPOM docs](https://pypom.readthedocs.io/en/latest/).
> bug 957802: Link to PyPOM docs

- Jenkinsfiles/prod-integration-tests.yml
- Jenkinsfiles/stage-integration-tests.yml
- docs/development.rst
- docs/tests-ui.rst
- tests/conftest.py
- tests/functional/test_article.py
- tests/functional/test_article_edit.py
- tests/functional/test_article_new.py
- tests/functional/test_article_revision.py
- tests/functional/test_article_translate.py
- tests/functional/test_dashboard.py
- tests/functional/test_feedback.py
- tests/functional/test_home.py
- tests/functional/test_language_selector.py
- tests/functional/test_maintenance_mode_redirects.py
- tests/functional/test_notfound.py
- tests/functional/test_profiles.py
- tests/functional/test_report.py
- tests/functional/test_search.py
- tests/utils/decorators.py
This corrects a problem I introduced with the work I did that was added via https://github.com/mozilla/kuma/pull/4150. Specifically, I used the "maintenance_mode" pytest marker to mark not only tests that should only be run in maintenance mode, but also tests that should be run in both normal mode as well as maintenance mode. This made it impossible to specify the correct set of tests to run in normal mode, since we had to use ``-m "not maintenance_mode"`` to exclude the tests that ran only in maintenance mode, but that in turn excluded the set of tests that we want to run in both modes.
This fix adds a [new command-line switch](https://github.com/escattone/kuma/blob/fix-mm-functional-tests-1351403/tests/conftest.py#L13) (``--maintenance-mode``) to the ``py.test`` command and then uses …
> bug 1351403: fix functional tests for maintenance mode

- scripts/chief_deploy.py
* Drop the unused ``prime_app`` task
* Record the KumaScript revision on deployment.  This will allow a page like [What's Deployed](https://whatsdeployed.io/?owner=mozilla&repo=kuma&name[]=Stage&url[]=https://developer.allizom.org/media/revision.txt&name[]=Prod&url[]=https://developer.mozilla.org/media/revision.txt) for KumaScript.
> bug 1350014: Record KumaScript revision on deployment

- jinja2/includes/google_analytics.html
- kuma/wiki/tests/test_templates.py
- kuma/wiki/views/document.py
Add a few more custom dimensions that came up during the design discussion:
* ``dimension17`` - The English slug (for example, ``Learn/CSS``), so that performance can be tracked across translations of a page.
* ``dimension18`` - ``Yes`` if a user is staff, ``No`` if they are not.
> bug 1341770: More analytics 

- kuma/wiki/jinja2/wiki/list/revisions.html
- kuma/wiki/queries.py
- kuma/wiki/tests/test_views.py
- kuma/wiki/views/list.py
- kuma/wiki/views/revision.py
So its possible to compare with the english document. In order to compare, I have chosen the revision that the translation based on.
Also refactored the queryset because I think its overkilling and its possible to fetch the data with simple queryset.
@jwhitlock Should we add test for this change?
r?
> [Bug 1269104] Compare a new translation to the English document

- kuma/wiki/jinja2/wiki/includes/document_macros.html
We cannot add demarcations around the titles because they must be stored in plain text in `data` attributes to be swapped in/out as the user interacts.
However, I agree that it is difficult to understand what the menu items mean without a demarcation around the article title.
Given that the user already knows which page they are on, we do not need to repeat the article title, so I removed it.
I also optimized the link to subscribe to the original instead of the translation to remove the need for the `<bdi>` tags which have the same problems.
> Fix bug 1249492: Remove article title from watch menu

- kuma/static/js/wiki.js
Do people even use the sticky TOC? I ask myself this every time someone files a duplicate of [bug 1005977](https://bugzilla.mozilla.org/show_bug.cgi?id=1005977)
> Send GA event indicating position of TOC when it's clicked

- tests/pages/dashboard.py
The AJAX load for page=2 often takes more than 10 seconds ([4 out of 11 recent tests](https://ci.us-west.moz.works/view/MDN/job/mdn_multibranch_pipeline/job/stage-integration-tests/)). Rather than increase the timeout across the tests, selectively use a timeout of ~~20~~ 30 seconds for the AJAX load by diving down to the [Python Selenium](http://selenium-python.readthedocs.io/waits.html#explicit-waits) library.
> bug 1246164: Increase timeout for dashboard AJAX

- kuma/settings/content_experiments.json
The 'Array' page has had examples on top for years, and doesn't have a variant without them.
> bug 1356923: Exclude 'Array' from the experiment

- kuma/wiki/apps.py
- kuma/wiki/events.py
- kuma/wiki/models.py
- kuma/wiki/tasks.py
- kuma/wiki/tests/conftest.py
- kuma/wiki/tests/test_events.py
- kuma/wiki/tests/test_models.py
There are [several requested changes](https://bugzilla.mozilla.org/showdependencytree.cgi?id=1142533&hide_resolved=1) for notification emails, which should be trivial to fix, but are tricky because the tests are incomplete and the code is spread over several files.
This PR:
* Moves the logic for "first edit", "page watch", and "spam attempt" emails into kuma.wiki.events
* Rewrites the tests to py.test standards, and tests against the three main edit types: English page creation, page edits, and first translations.
* Rewrites the test for ``Revision.previous``, setting creation dates rather than sleeping.
* Fixes [bug 1142533](https://bugzilla.mozilla.org/show_bug.cgi?id=1142533), so that notification emails for first translations include a diff to the English revision they are based on. …
> bug 1269104: Refactor notification emails, provide diff for first translations

- jinja2/includes/google_analytics.html
- kuma/wiki/tests/test_templates.py
The "yesno" template filter also localizes the text, so visits on French pages get the values "Oui" / "Non". Use regular template logic so the values are only "Yes" / "No".  Found during manual testing of #4175.
> bug 1341770: Set Yes/No for "is_staff" GA dim

- kuma/wiki/forms.py
- kuma/wiki/tests/test_forms.py
If an edit does not change the content (such as settings or clearing the review requested flags), then do not submit the edit to Akismet to check for spam.
> fix bug 1265495: Skip spam check for some edits

- kuma/wiki/events.py
- kuma/wiki/tests/test_events.py
For new pages, there is no compare link, but it was being decorated with a Google Analytics campaign, so it was being included as a link to the homepage.  This was 154 of the 1,078 clicks (14%) from new edit and page watch emails over the last month.
> fix bug 1140091: Omit Compare link for new pages

- docs/localization.rst
Per jwhitlock, this is actually only done by the dev doing a production push, so in general contributors don't need to worry about it, and it shouldn't be done for a PR.
> Note updating localization strings is a prod process task

- docker-compose.yml
- docs/elasticsearch.rst
- kuma/wiki/search.py
We're preparing for an update to ElasticSearch 2.4 in SCL3, so I'm starting with the Docker environment.  The elasticsearch 1.x libraries are compatible with 2.x, sending deprecated but supported 1.x API commands.  Once all environments are updated, we can make the code changes for 2.x, and update to the 2.x libraries, which are not compatible with 1.x.
The changes are:
* Fix a typo in the wiki_document meta that 1.7 ignored and 2.4 doesn't.
* Update the docs to reflect the new version, to remove Vagrant references, and to refresh from a recent run.
Locally, a ``make up`` downloaded the ElasticSearch 2.4 image, and then restarted the elasticsearch and kuma containers.  ES 2.4 was able to update the 1.x search index in place.  I was able to create and promote a new index of the sample …
> bug 1357891: Update to ElasticSearch 2.4

- Jenkinsfiles/demo.groovy
While trying to do a demo deploy in #4197 I ran into [namespace not found errors](https://ci.us-west.moz.works/blue/organizations/jenkins/mdn_multibranch_pipeline/detail/meinheld-demo/6/pipeline) which at first didn't make sense as I repeatedly verified that the namespace did in fact exist. The problem appears to have been some sort of shell escaping issue in the Jenkinsfile, as this [fixes the issue](https://ci.us-west.moz.works/blue/organizations/jenkins/mdn_multibranch_pipeline/detail/meinheld-demo/7/pipeline).
> Rework kubectl apply to work around namespace issue

- Makefile
Use docker-compose so that ``make bash`` and ``make shell_plus`` will work even when your source directory is not named kuma.
> bug 1218563: Use docker-compose for make bash, etc

- kuma/conftest.py
- kuma/humans/management/commands/make_humans.py
- kuma/wiki/jobs.py
- kuma/wiki/management/commands/make_sitemaps.py
- kuma/wiki/tests/__init__.py
- kuma/wiki/tests/conftest.py
- kuma/wiki/tests/test_jobs.py
This PR updates maintenance mode such that it no longer requires Celery (Redis and at least one Celery worker) (per discussion in https://github.com/mozmar/infra/issues/134).
- remove need for Celery in maintenance mode (see https://github.com/mozmar/infra/issues/134#issuecomment-292581709)
- override ``DocumentContributorsJob.get`` to return an empty response when in maintenance mode
- add Django management command to make ``humans.txt`` (for calling as a post-deploy step for maintenance mode)
- add Django management command to make the sitemaps (for calling as a post-deploy step for maintenance mode)
- add and refactor tests for wiki jobs
- add high-level ``conftest.py`` that provides some fixtures helpful for refactoring
``KumaTestCase``-based tests
- refactor tests for wiki jobs and …
> Update maintenance mode

- kuma/users/jinja2/account/email.html
Remove a double-quote that is only visible for users with no email accounts, such as those created through the Django admin.
> Remove stray " on Email Addresses page

- kuma/settings/common.py
- kuma/static/styles/samples.scss
- kuma/wiki/jinja2/wiki/code_sample.html
- kuma/wiki/tests/test_views.py
- kuma/wiki/views/document.py
Live samples load in an iframe, and include [Template:CustomSampleCSS](https://developer.mozilla.org/en-US/docs/Template:CustomSampleCSS?raw) as a stylesheet. This PR coverts the contents to a regular asset styles.css, and used that in the samples iframe source.
The macros [LiveSampleURL](https://github.com/mozilla/kumascript/blob/master/macros/LiveSampleURL.ejs) creates the iframe source href, and will change the URL from http://localhost:8000 to the SSL version at https://localhost:8000. You'll need to change this macro to get live samples in your development environment.  There will be a KumaScript PR to fix this soon.
> bug 1328989: Move Template:CustomSampleCSS to CSS

- .eslintignore
- .eslintrc.js
- package.json
Hey @stephaniehobson 
This adds `eslint` to the project. If you use an `eslint` linter plugin for your editor, you should get real time linting feedback. There is also a lint target with:
`npm run lint`
I have marked most things as warnings so, the pre-commit hook introduced here will pass for the moment.
> Nobug : Adds eslint and husky for linting goodness

- .dockerignore
- .gitignore
- Makefile
``make clean`` cleans out Python 3 compiled folders, and covers the functional test directory as well.
``.gitignore`` has been updated to model [GitHub's sample for Python projects](https://github.com/github/gitignore/blob/master/Python.gitignore), and includes a few more patterns.  I've added some files that have been created from following the development instructions, as well as ones created by the SCL3 deployment process.
``.dockerignore`` gets a copy of ``.gitignore``, so this has been updated as well.
A couple of notable changes:
* There were some "Don't ignore" patterns in ``.gitignore`` which appear left-over from previous iterations, and have been removed.
* GitHub ignores ``.pot`` files, which are locale template files.  However, we use these in our TravisCI locale build to …
> Bug 1218563: Update "make clean", git and docker ignore lists

- kuma/wiki/events.py
- kuma/wiki/tests/test_events.py
- kuma/wiki/tests/test_templates.py
- kuma/wiki/tests/test_views.py
* [bug 1142545](https://bugzilla.mozilla.org/show_bug.cgi?id=1142545) - Add a ``[New]`` tag to first edit emails, and localize the subject of watch emails.
* [bug 1142576](https://bugzilla.mozilla.org/show_bug.cgi?id=1142576) - Add more headers to email for more mail client filtering
> bug 1142576, 1142545: Improve notification email tags

- jinja2/base.html
There's the occasional error when main.js loads faster then statici18n.js so I'm switching their order in the source.
> Move statici18n file ahead of main.js in page source

- .dockerignore
- .gitignore
There's multiple `static/` folders in the repo, we only want to ignore the one at the root.
> Bug 1218563: Only ignore /static/ in root

- docs/tests-ui.rst
- kuma/redirects/redirects.py
- kuma/settings/common.py
- requirements/test.txt
- tests/redirects/map_301.py
- tests/redirects/test_redirects.py
previously: https://github.com/mozilla/kuma/pull/4215
This PR uses @pmac's https://github.com/pmac/django-redirect-urls lib to implement SCL3 Apache httpd redirects in Python/Django. The complex rewrites retain original mod_rewrite rules as comments, while the remaining are uncommented simple static redirects. Test layout is similar to the [Bedrock redirect tests](https://github.com/mozilla/bedrock/tree/master/tests/redirects). 
The only rewrite rule that isn't implemented in this PR is as follows:
```
RewriteCond %{SERVER_NAME} ^developer\.mozilla\.com$
RewriteRule (.*) http://developer.mozilla.org$1 [R=301,L]
```
which redirects requests to `developer.mozilla.com/*` --> `developer.mozilla.org/*`
Tracked in [this infra issue](https://github.com/mozmar/infra/issues/180)
> implement SCL3 httpd redirects in Django

- kuma/settings/common.py
- kuma/wiki/tests/test_content.py
@schalkneethling had some trouble testing MDN-hosted samples, because our accepted iframe hosts did not include mdn.github.io.  This PR:
* Breaks up ``ContentSectionToolTests`` into smaller test cases, so that the iframe filter tests can be rewritten, and other tests can be re-written incrementally in the future.  Some tests were re-arranged, but not changed.
* Refactors the ``filterIframeHosts`` tests to pytest test functions
* Add tests to checks the default pattern for ``KUMA_WIKI_IFRAME_ALLOWED_HOSTS`` accepts and rejects patterns used in production
* Syncs ``KUMA_WIKI_IFRAME_ALLOWED_HOSTS`` with the custom value in production, and then removes some legacy patterns for vagrant and loading CDN assets in an iframe.
> bug 1360337: Test, update accepted iframe src regex

- .dockerignore
.dockerignore has a different syntax than .gitignore. Removed some additional files from the Docker build context:
* /static - Build static files, rebuilt on image creation, ~100MB
* Python compiled files, size varies
* Locale machine object (.mo) files, rebuilt, 3 MB
* KumaScript, not needed in Kuma, 3 MB
Context drops from 150 MB to 44 MB for me.
> bug 1218563: Omit built static, others in Docker

- kuma/wiki/jinja2/wiki/list/revisions.html
- kuma/wiki/tests/conftest.py
- kuma/wiki/tests/test_templates.py
Fix some issues introduced by PR #4144:
* Ensure the "view revision" link has the right URL
* Omit the "Revert to this revision" action for first translation, English source revision
* Add additional CSS classes to ease testing
> bug 1269104: Fix revision history

- kuma/wiki/jinja2/wiki/document.html
- kuma/wiki/jinja2/wiki/includes/approvals.html
- kuma/wiki/jinja2/wiki/revision.html
- kuma/wiki/managers.py
- kuma/wiki/models.py
- kuma/wiki/tests/__init__.py
- kuma/wiki/tests/test_models.py
- kuma/wiki/tests/test_views.py
- kuma/wiki/views/create.py
- kuma/wiki/views/delete.py
- kuma/wiki/views/document.py
- kuma/wiki/views/edit.py
- kuma/wiki/views/revision.py
- kuma/wiki/views/translate.py
There are some methods that can be simplified or removed when we assume ``Document.is_template`` is False:
* ``Document.allows_editing_by`` - Simplified to "change document" permissions
* ``Document.allows_revision_by`` - Always returns True, so removed
* ``Document.objects.allows_add_by`` - Always returns True, so removed
Some tests can be dropped, and some code paths are eliminated.  Reducing indent makes some diffs looks bigger than they are, enough to justify a PR for ease of review.
There are two more PRs planned.  [bye-templates-1328989](https://github.com/mozilla/kuma/compare/master...jwhitlock:bye-templates-1328989?expand=1) contains all the changes, but I think it's too overwhelming for a single PR.
> Bug 1328989: Simplify or remove allows_* methods

- kuma/static/js/wiki-helpful-survey.js
Change the variable 'ga' from implicit to explicit, to avoid an "Uncaught ReferenceError: ga is not defined" in local development. Tested with default of no Google Analytics account, and with a fake "UA-000000-0" settings for constance config "GOOGLE_ANALYTICS_ACCOUNT".
> bug 1330106: Add ga to context

- kuma/attachments/jinja2/attachments/includes/attachment_list.html
- kuma/dashboards/jinja2/dashboards/includes/revision_dashboard_body.html
- kuma/users/apps.py
- kuma/wiki/jinja2/wiki/confirm_document_delete.html
- kuma/wiki/jinja2/wiki/confirm_revision_revert.html
- kuma/wiki/jinja2/wiki/document.html
- kuma/wiki/jinja2/wiki/edit.html
- kuma/wiki/jinja2/wiki/includes/document_macros.html
- kuma/wiki/jinja2/wiki/list/revisions.html
- kuma/wiki/tests/test_jobs.py
* Refresh the document contributor list when a user is banned or un-banned, so that it is quickly updated.
* If a user is inactive (from a ban or otherwise), add ``rel="nofollow"`` to links to their profile page
Asking for review from @stephaniehobson for doing most of the research on [bug 1353134](https://bugzilla.mozilla.org/show_bug.cgi?id=1353134), feel free to reassign.
> Bug 1353134: Remove or nofollow banned user links

- kuma/attachments/jinja2/attachments/edit_attachment.html
- kuma/dashboards/jinja2/dashboards/macros.html
- kuma/dashboards/jinja2/dashboards/revisions.html
- kuma/dashboards/jinja2/dashboards/spam.html
- kuma/landing/jinja2/landing/maintenance-mode.html
- kuma/users/jinja2/users/ban_user_and_cleanup.html
- kuma/users/jinja2/users/ban_user_and_cleanup_summary.html
- kuma/users/jinja2/users/user_detail.html
- kuma/users/jinja2/users/user_edit.html
- kuma/wiki/jinja2/wiki/compare_revisions.html
- kuma/wiki/jinja2/wiki/confirm_document_delete.html
- kuma/wiki/jinja2/wiki/confirm_revision_revert.html
- kuma/wiki/jinja2/wiki/create.html
- kuma/wiki/jinja2/wiki/edit.html
- kuma/wiki/jinja2/wiki/list/documents.html
- kuma/wiki/jinja2/wiki/list/revisions.html
- kuma/wiki/jinja2/wiki/move.html
- kuma/wiki/jinja2/wiki/preview.html
- kuma/wiki/jinja2/wiki/revision.html
- kuma/wiki/jinja2/wiki/translate.html
For pages that we don't want indexed (based on robots.txt), set a head tag:
```
<meta name="robots" content="noindex, nofollow">
```
Remove some Jinja "set meta=" declarations that weren't doing anything.
> bug 1353079: Add meta tag to avoid search indexing

- kuma/health/tests/test_views.py
- kuma/health/urls.py
- kuma/health/views.py
- kuma/settings/common.py
- kuma/urls.py
This PR implements "liveness" and "readiness" endpoints as used by Kubernetes.
- They are implemented as Middleware and placed at the beginning of the middleware stack to avoid unnecessary processing (sessions, authentication, etc.) for endpoints that will be hit frequently.
- The philosophy of the "liveness" endpoint is to simply indicate whether the service itself is up and running, while the "readiness" endpoint goes one step further to also include whether its essential supporting services are also running and usable. I've made the decision for now that for Kuma "essential supporting services" means the database only, not the other supporting services (elasticsearch, Celery, memcached, kumascript), since Kuma can remain usable without them.
- The "readiness" endpoint checks the …
> bug 1363916: add liveness/readiness endpoints for k8s

- requirements/constraints.txt
- requirements/dev.txt
- requirements/travis.txt
Update [coverage](https://pypi.python.org/pypi/coverage/4.3.4) from 4.0.3 to 4.3.4, like in the development environment, and add notes to keep them in sync in the future.
> bug 1352492: Update coverage in TravisCI

- kuma/wiki/jobs.py
- kuma/wiki/tests/test_jobs.py
This PR addresses two problems introduced in #4209 (addressing bug [944186](https://bugzilla.mozilla.org/show_bug.cgi?id=944186)):
- it hopefully eases the spike in celery tasks (see bug [1366044](https://bugzilla.mozilla.org/show_bug.cgi?id=1366044))
- fixes an exception when getting the nearest-zone for a document whose parent-topic has been deleted (bug [1365960](https://bugzilla.mozilla.org/show_bug.cgi?id=1365960))
I wanted to prove (via a test case) that using ``None`` for the "empty" value for the ``DocumentNearestZoneJob`` class effectively bypasses the cache, along the lines of something like this:
```
assert not DocumentNearestZoneJob().get(doc.pk) 
with mock.patch.object(DocumentNearestZoneJob, 'fetch') as mock_fetch:
DocumentNearestZoneJob().get(doc.pk) …
```
> Nearest-zone-job adjustments 944186

- .travis.yml
- requirements/travis.txt
- scripts/docker-compose.travis.yml
- scripts/travis-install
- tox.ini
Don't use Ansible to install MySQL and ElasticSearch.  Instead:
* Use TravisCI's MySQL, without the custom collation or migrations.  Docker continues to test w/ ``utf8_distinct_ci`` and migrations.
* Install ElasticSearch as suggested by [TravisCI docs](https://docs.travis-ci.com/user/database-setup/#Installing-ElasticSearch-on-trusty-container-based-infrastructure)
* Install node packages needed by Django pipeline, so that ``make build-static`` will work for tests.
* Rewrite ``scripts/travis_install`` to use env variables like ``INSTALL_ELASTICSEARCH=1``, instead of targeting on ``TOXENV``, to make it easier to combine and customize.
All of these changes makes the ``py27`` target faster to build (8 minutes vs 11 min 30 seconds, 30% faster), and easier to customize.  I've added the first …
> bug 1352232: Remove Ansible from py27 build

- kuma/static/js/wiki-helpful-survey.js
Old method wasn't working reliably (race conditions?) This performs better in local testing.
> Check window.ga directly instead of passing it in

- docs/data.rst
- docs/elasticsearch.rst
- docs/index.rst
- kuma/scrape/__init__.py
- kuma/scrape/management/commands/__init__.py
- kuma/scrape/management/commands/scrape_user.py
- kuma/scrape/scraper.py
- kuma/scrape/sources/__init__.py
- kuma/scrape/sources/base.py
- kuma/scrape/sources/user.py
- kuma/scrape/storage.py
- kuma/scrape/tests/__init__.py
- kuma/scrape/tests/conftest.py
- kuma/scrape/tests/test_scraper.py
- kuma/scrape/tests/test_source.py
- kuma/scrape/tests/test_source_user.py
- kuma/scrape/tests/test_storage.py
- kuma/settings/common.py
Add a content scraping framework, for adding or updating data to a local Kuma instance. The first user of the framework is the management command ``scrape_user``, which can mirror a production user locally, using only public data on the user's profile.
Some things to try:
./manage.py scrape_user username
./manage.py scrape_user username --force
./manage.py scrape_user username --force --social
./manage.py scrape_user username --force --social --email name@example.com
Some of the framework may seem like overkill, but it's needed for the much more complex task of scraping a document, coming in the next PR.
> bug 1271509: Add scrape_user command and framework

- docs/data.rst
- kuma/scrape/__init__.py
- kuma/scrape/management/commands/__init__.py
- kuma/scrape/management/commands/scrape_document.py
- kuma/scrape/scraper.py
- kuma/scrape/sources/__init__.py
- kuma/scrape/sources/base.py
- kuma/scrape/sources/document.py
- kuma/scrape/sources/document_children.py
- kuma/scrape/sources/document_history.py
- kuma/scrape/sources/document_meta.py
- kuma/scrape/sources/document_rendered.py
- kuma/scrape/sources/revision.py
- kuma/scrape/sources/zone_root.py
- kuma/scrape/storage.py
- kuma/scrape/tests/conftest.py
- kuma/scrape/tests/test_scraper.py
- kuma/scrape/tests/test_source_document.py
- kuma/scrape/tests/test_source_document_base.py
- kuma/scrape/tests/test_source_document_children.py
- kuma/scrape/tests/test_source_document_history.py
- kuma/scrape/tests/test_source_document_meta.py
- kuma/scrape/tests/test_source_document_rendered.py
- kuma/scrape/tests/test_source_revision.py
- kuma/scrape/tests/test_source_user.py
- kuma/scrape/tests/test_source_zone_root.py
- kuma/scrape/tests/test_storage.py
Fix some stuff that should have been in the last PR (less user test fixtures, improve the scraper), and then add the ``./manage.py scrape_document`` command.  Some manual tests:
./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Archive/SAX # Will also add Archive zone
./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array --depth 1  # Will scrape child docs as well
./manage.py scrape_document https://developer.mozilla.org/fr/docs/Web/CSS/display  # Will scrape the English document as well
> bug 1271509: Add ./manage.py scrape_document

- scripts/chief_deploy.py
This PR is a companion to [Kumascript PR #194](https://github.com/mozilla/kumascript/pull/194).
This PR updates SCL3 deployment to use the [``npm update`` command](https://docs.npmjs.com/cli/update) to update any top-level npm packages listed in Kumascript's ``package.json``, while respecting each package's given [``semver``](https://docs.npmjs.com/getting-started/semantic-versioning).
This allows us to update to the latest ``mdn-browser-compat-data`` npm package allowed by its given ``semver`` in Kumascript's ``package.json``, via deployment only. No code changes would be required.
> bug 1328839: improve kumascript npm package updates

- requirements/README.rst
- requirements/dev.txt
* hashin 0.6.0 -> 0.9.0: Requirements is keyword (``-r requirements/common.txt``), and can pass multiple packages to upgrade. Case-insensitive matching of package names.
> bug 1352492: Upgrade hashin

- kuma/static/js/wiki.js
Firefox has made it so you need to set the location object with window.location instead of just location recently, so this changes the code to work again.
> Bug 1370965: Fix context menu to work again.

- kuma/settings/common.py
Swap editor to use old MDN files, not new redesign ones.
> Fix bug 1372752: Zilla shouldn't be in editor yet

- jinja2/includes/newsletter.html
- kuma/static/styles/components/newsletter.scss
- kuma/static/styles/includes/_vars.scss
- kuma/users/jinja2/users/user_edit.html
- kuma/wiki/jinja2/wiki/document.html
Things to test:
Notes:
- you will have to delete your local storage variable newsletterHide to see it again after submitting
Spec:
- form field and button adjustments are coming in later PR
- increased spacing is also coming in later PR
> Bug 1370594: Move and style newsletter for redesign

- kuma/static/styles/components/wiki/structure.scss
- kuma/static/styles/includes/_vars.scss
TOC aka right column "in this article" menu, now stays collapsed until screens are 1400px.
Shout out to @darkwing for getting the JS to watch the CSS for the cue to initiate the toggle behaviour. This change was ridiculously easy.
> Bug 1370594: TOC stays collapsed until 1400px

- kuma/static/js/wiki.js
- kuma/static/styles/components/wiki/structure.scss
Easier to remove it from both the old and new design than to fork the wiki.js file.
Ok'ed with Kadir and communicated on the mdc mailing list.
> Bug 1370594: Remove sticky TOC

- kuma/wiki/jobs.py
- kuma/wiki/tests/test_jobs.py
See [bugzilla 1373720](https://bugzilla.mozilla.org/show_bug.cgi?id=1373720).
* increase ``DocumentNearestZoneJob.refresh_timeout`` from 60 to 180 seconds
* change ``DocumentNearestZoneJob.lifetime`` from a constant to a property
that returns a random number of days between 1 and 10 (in seconds)
> bug 1373720: adjust DocumentNearestZoneJob cache staleness thresholds

- kuma/wiki/jinja2/wiki/includes/kumascript_errors.html
- kuma/wiki/kumascript.py
- kuma/wiki/tests/conftest.py
- kuma/wiki/tests/test_views.py
- kuma/wiki/tests/test_views_document.py
- kuma/wiki/views/document.py
- kuma/wiki/views/revision.py
See [bugzilla 1324092](https://bugzilla.mozilla.org/show_bug.cgi?id=1324092).
The fix was easy for this PR, but refactoring the tests proved painful. I added a new wiki-level test fixture ``ks_toolbox``. I placed it at the wiki level assuming it will be used by more than one file that we create as we refactor more of the tests within ``kuma/wiki/tests/test_views.py``. It's currently used by both ``test_views.py`` (imported, since the machinery for using fixtures within ``unittest.TestCase`` based classes is worse) and ``test_views_document.py`` .
> Fix display of KumaScript errors for document/preview endpoints

- docs/feature-toggles.rst
- jinja2/includes/redesign_notice.html
* Split text into smaller translation blocks with less inner HTML.
* Ensure redesign_beta and redesign_live notices aren't displayed at
the same time.
> bug 1370594: Split up translation in redesign notices

- kuma/static/styles/components/wiki/quick-links.scss
@stephaniehobson Saw the icons did not line up quite correctly on for example:
https://developer.allizom.org/en-US/docs/Web/HTTP
Tracked down the problem, and this fixes it.
> Fixes misspelling of relative in CSS rule

- jinja2/includes/redesign_notice.html
Change the beta notice to exclude a link to the user's profile for anonymous users.
> bug 1370594: Omit profile link for anonymous users

- kuma/settings/common.py
Use Django 1.8's default ``PASSWORD_HASHERS``, and drop support for custom ``Sha256Hasher``. When this has shipped to production and it is unused, the ``Sha256Hasher`` code can be removed in the next PR.
> bug 1356795: Use default PASSWORD_HASHERS

- kuma/static/styles/components/wiki/customcss.scss
- Remove commented out class .comment
- Remove .withoutBorder
- Tables should not be used for layout
- I removed this from the one pages outside of FxOS that was using it
- FxOS pages have been archived
- Remove horizontalLine, column, bottomPart, verticalText
- horizontalLine is not in use
- column, bottomPart, verticalText were used together and are being
phased out
- Remove unused class blockTable
- Remove class HTMLElmNav, used in unused macro
- Remove .method, only used in archived Jetpack docs
- Remove bannerWrapper & mozOnlyBanner, in unused macro
- Improve comments for deprecatedElement
> Remove unused customCSS classes

- jinja2/base.html
Just fixing a case typo in 'GitHub' (since I can't stand FireFox… ;))
Note: This PR  does not follow the contribution rule since this is a really minor issue. I can file a bug and reword this if necessary.
> Fixing a minor typo (s/Github/GitHub)

- kuma/static/styles/components/structure/nav-footer.scss
- kuma/static/styles/components/structure/submenu.scss
Footer hit areas are narrower but taller, conforming more to the
shape of the link but being forgiving if you're not exactly on it.
Header hit areas are full width of column and taller.
Bug 1375765 and bug 1375962. Better but not sure they're "fixed".
> Bug 1370594: Change hit area of header and footer links.

- scripts/chief_deploy.py
We'll need to update the puppet-controlled configuration settings to include an application ID. Disabling this feature for now so that pushes won't report errors.
> bug 1376606: Disable New Relic v1 API call

- kuma/attachments/jinja2/attachments/includes/attachment_list.html
- kuma/wiki/jinja2/wiki/edit.html
- kuma/wiki/jinja2/wiki/includes/revision_comment.html
- kuma/wiki/templatetags/jinja_helpers.py
- kuma/wiki/tests/test_helpers.py
> bug 1370514 - fixed links in editing mode

- docs/data.rst
- docs/installation.rst
- etc/sample_db.json
- kuma/scrape/__init__.py
- kuma/scrape/fixture.py
- kuma/scrape/management/commands/sample_mdn.py
- kuma/scrape/management/commands/scrape_document.py
- kuma/scrape/management/commands/scrape_links.py
- kuma/scrape/management/commands/scrape_user.py
- kuma/scrape/scraper.py
- kuma/scrape/sources/__init__.py
- kuma/scrape/sources/base.py
- kuma/scrape/sources/document.py
- kuma/scrape/sources/document_current.py
- kuma/scrape/sources/document_history.py
- kuma/scrape/sources/document_rendered.py
- kuma/scrape/sources/links.py
- kuma/scrape/sources/revision.py
- kuma/scrape/storage.py
- kuma/scrape/tests/conftest.py
- kuma/scrape/tests/test_fixture.py
- kuma/scrape/tests/test_source_document.py
- kuma/scrape/tests/test_source_document_current.py
- kuma/scrape/tests/test_source_document_history.py
- kuma/scrape/tests/test_source_document_rendered.py
- kuma/scrape/tests/test_source_links.py
- kuma/scrape/tests/test_source_revision.py
- kuma/scrape/tests/test_storage.py
- scripts/create_sample_db.sh
Now that PR #4245 and PR #4248 are merged, this PR is getting a little more sane:
* Adds a management command ``scrape_links`` to find document links on an MDN page. It is designed for the homepage, but can work on other pages as needed.
* Adds a management command ``sample_mdn`` that loads fixtures and scrapes production data from a JSON spec.
* Adds a script to create an empty but migrated database, load it with fixtures and scraped data, and export a SQL dump for development and testing. Since the data is scraped from public interfaces, avoids issues with exposing personally identifiable information.
A recent generated sample database is at http://mdn-downloads.s3-website-us-west-2.amazonaws.com/mdn_sample_db.sql.gz
To Do:
Not this PR:
* Extract attachment data from documents
* Render …
> Bug 1271509: Sample database and production scraper

- kuma/wiki/jinja2/wiki/includes/document_macros.html
The Jinja macro ``revision_diff`` has parameters ``revision_from_header``, ``revision_to_header``, and ``show_picker``, that are unused in the current code.
> bug 1269104: Drop unused params from revision_diff

- kuma/wiki/jinja2/wiki/compare_revisions.html
- kuma/wiki/jinja2/wiki/includes/document_macros.html
- kuma/wiki/jinja2/wiki/translate.html
This fixes three issues you can see on https://developer.mozilla.org/fr/docs/user:jwhitlock$compare?locale=fr&to=1269259&from=1249101
* When clicking on "Changer de révision", you see the history page for the **English** document with a French UI. You should see the history for the **French** document with a French UI.
* When clicking on "Changer de révision", and then select "Comparer les révisions sélectionnées" (Compare selected revisions), you start **translating the document**. Instead, you should be back at **the revision comparison interface**.
* When clicking on "Révision 1249101" (the left-side English revision), you are taken to [fr/docs/user:jwhitlock$revision/1249101](https://developer.mozilla.org/fr/docs/user:jwhitlock$revision/1249101), the **French page**. You should be …
> bug 1269104: Fix issues when comparing first translation to English revision

- kuma/wiki/jinja2/wiki/includes/kumascript_errors.html
- kuma/wiki/tests/conftest.py
* add case to the "ks_toolbox" fixture that mimics a DocumentParsingError (adds regression test for this case going forward)
* fix "kumascript_errors.html" such that it tries to get the information it needs from "error_meta" in a safer manner
It turns out that this issue is caused by a combination of two things:
1. The document actually contains an error that causes KumaScript to report a `DocumentParsingError` (e.g., https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/HTML_basics is missing a double quote at line 88 column 65, which should be `htmlelement("head")` instead of `htmlelement(head")`)
2. The `kumascript_errors.html` template contained a bug such that `DocumentParsingError` errors raised an exception.
So in addition to this fix, all of the following …
> bug 1375869: fix ISE when KumaScript returns DocumentParsingError

- kuma/wiki/tests/test_templates.py
- kuma/wiki/tests/test_views_revision.py
Convert existing ``CompareRevisionTests`` to ``py.test``, and split them between view tests (``test_view_revision.py``) and template tests (``test_templates.py``).  Add regression tests for using the view to compare a translation revision to the English source, as requested in PR #4304.
> bug 1269104 - Refactor compare_revisions tests, add translation tests

- kuma/static/styles/components/wiki/interactive.scss
- kuma/static/styles/wiki-blue.scss
- kuma/static/styles/wiki.scss
Resizes the interactive example iframe based on classes passed through to the macro.
Macro changes are in: https://github.com/mozilla/kumascript/pull/239 (but this PR is not dependent on that)
> Bug 1362025: Add classes to resize interactive examples

- kuma/static/js/analytics.js
Adds a `message` event listener for `postMessage` messages from the interactive code examples.
The `event` object passed to the `interactiveExamplesEvent` function will contain the following:
`event.origin` ~ Origin of the window that sent the message (here it is the iframe)
`event.data` ~ The data sent via `postMessage`. This will contain a category, action and label associated with the event that is then passed to `trackEvent`
For example:
```
{
  category: 'js-examples',
  action: 'Clicked run',
  label: 'Interaction Events'
}
```
> Adds post message listener for interactive examples

- kuma/landing/jinja2/landing/homepage.html
- kuma/users/jinja2/users/user_detail.html
- kuma/wiki/jinja2/wiki/edit.html
- kuma/wiki/jinja2/wiki/translate.html
- kuma/wiki/templatetags/jinja_helpers.py
A recent ``wiki_url`` change by me is causing some links to Project:MDN to break (see [bug 1380045](https://bugzilla.mozilla.org/show_bug.cgi?id=1380045)).  This fixes ``wiki_url`` so they will work. 
However, all of these pages have been moved, such as Project:MDN/Contributing moving to [MDN/Contribute](https://developer.mozilla.org/en-US/docs/MDN/Contribute). Updating the templates to point to the new location.
> bug 1380045: Change Project:MDN links

- kuma/static/js/analytics.js
This resolved the `this.trackEvent` undefined error on staging.
> Call trackEvent explicitly on mdn.analytics

- kuma/static/styles/components/structure/_mixin_nav.scss
- kuma/static/styles/components/structure/nav-main-search.scss
- kuma/static/styles/components/structure/nav-main.scss
- kuma/static/styles/components/structure/nav-sec.scss
- kuma/static/styles/components/structure/submenu.scss
- kuma/static/styles/includes/_vars.scss
- Tweak media queries to flip 1px sooner (so iPad portrait users get
tablet display)
- Add a tablet optimized navigation
- logo, secondary nav, and profile on top line
- main navigation on second line
- Submenus now styled properly at every screen size
- overrides made for mobile .nav-main and .nav-sec exceptions
Fix bug 1376980, fix bug 1379737.
> Fix bugs 1376980 & 1379737: Tablet nav and submenus

- kuma/static/styles/base/utilities.scss
- kuma/static/styles/components/wiki/structure.scss
- kuma/static/styles/includes/_vars.scss
Content was sitting too close to the footer on non-article pages (e.g. $history or profile edit page).
Moved the padding from the article wrapper to the content wrapper and increased it a bit because new design has more white space and this mirrors the space on top.
> Fix Bug 1375947: Add spacing after page content

- kuma/static/styles/components-blue/home/column-callout.scss
Remove more ``.callout-devel`` CSS styles, to eliminate unused style and reference to ``promos/sauce-labs-home-high-res.png``.
> bug 1367098: Remove more DevRel Survey CSS

- Jenkinsfile
Docker commands that generate files need to run as ``UID=1000`` (jenkins), so that Jenkins can delete them when the branch is deleted.
> Set UID=1000 for Jenkins jobs

- scripts/chief_deploy.py
This worked locally for being able to checkout the repository after switching to locales in a subfolder. It did not work on the SCL3 deployment server. Instead, manually replacing ``locales/`` with an empty folder, and then running deployment script, for the one-time transition.
> bug 1385405: Remove transitional deploy step

- kuma/static/styles/search.scss
Noticed that the links on the search results page are very light, making them almost impossible to read.
> Fixes link colors on search results page

- kuma/core/middleware.py
- kuma/core/tests/test_locale_middleware.py
- kuma/wiki/tests/test_middleware.py
We should redirect the visitor with 302 redirect rather than 301
@jwhitlock r?
> [Bug 1385315] Use 302 not 301 for locale based redirect

- kuma/settings/common.py
This PR allows the MEDIA_ROOT setting to be overridden from the environment, as a convenience for the MDN->AWS work (see https://github.com/mozmeao/infra/issues/197#issuecomment-321411851). Currently it is hard-wired to the `media` folder under the application-root directory, and that directory within Kubernetes would be ephemeral since it's part of the container. This will allow us to point the MEDIA_ROOT to a location on the shared PVC (EFS).
> bug 1388933: allow MEDIA_ROOT to be overridden from the environment

- docker-compose.yml
- kuma/settings/common.py
- kuma/settings/local.py
- kuma/settings/prod.py
- kuma/settings/stage.py
Allow the ATTACHMENT_HOST to be set from the environment, which helps with MDN->AWS development.
> bug 1390267: allow ATTACHMENT_HOST to be set from env

- Makefile
Push the kumascript image from the kuma project as well. This should be done when the kumascript master branch is updated, not when the kuma master branch is update, so it is not included in ``make push``.
> bug 1340342: Add make target push-kumascript

- kuma/static/js/analytics.js
- kuma/static/js/wiki.js
This will listen for a `postMessage` event from the interactive editor with the `scrollHeight` of the CSS editor container [1]. 
To ensure arbitrary code is not run, this code checks
1. That the origin match and
2. That the message data contains the property `iFrameHeight`
If this is satisfied, the height of the `iframe` will be updated to the passed value. The editor will send a follow up `postMessage` when a specific `matchMedia` breakpoint[2] is reached.
[1] https://github.com/mdn/interactive-examples/blob/master/js/editor-libs/mce-utils.js#L77
[2] https://github.com/mdn/interactive-examples/blob/master/js/editor-libs/mce-utils.js#L86
> Set interactive editor iframe height based on postMessage from editor

- kuma/settings/common.py
- kuma/urls.py
This PR gives Kuma the ability to serve the legacy diagrams, presentations, and samples, and it's target use is for MDN in AWS. By default it is not enabled, so it will not affect the SCL3 deployment which already serves these legacy files via Apache. The legacy files are so rarely requested, and hopefully will be removed from MDN altogether in the future, so it doesn't seem worth the effort to serve these files in a more production-like manner.
For the AWS work, this feature can be enabled by setting two environment variables:
```
SERVE_LEGACY=True
LEGACY_ROOT=/mdn/www
```
> bug 1391092: add ability to serve legacy files from Django (for AWS)

- docker-compose.yml
Adding `:z` so that SELinux labels are properly updated and docker-compose succeeds for systems based on Fedora/RHEL.
> bug 1391986

- kuma/static/styles/base/utilities.scss
The hidden class is now displayed in the "english" panel when editing a translation of an article.
> Fix bug 1389934

- kuma/static/styles/components/wiki/sample-code.scss
- kuma/static/styles/wiki.scss
Add a border around live sample code.
- This content looks different from other page content because it is in an iframe, there should be signal  for that
- Borrowed the border colour from the interative-examples
- Renamed .scss file to better indicate what it pertains to
> Bug 1370594: Outline sample code

- kuma/settings/common.py
- kuma/wiki/tests/test_content.py
Add https://interactive-examples.mdn.mozilla.net to the allowed sources for iframes.  Re-arrange the long regex string so it is easier to add new items at the end.
> bug 1362026: Add interactive-examples to iframes

- kuma/wiki/migrations/0034_utf8_general_ci_tags.py
- kuma/wiki/migrations/0035_utf8_general_ci_collation.py
- kuma/wiki/tests/test_templates.py
Drops the one test that depends on ``utf8_distinct_ci`` custom collation, and then:
1. Migrates tag names that would collide. The oldest tag retains its name, and the newer tags have  `(2)`, `(3)` appended to their name.
2. Migrates ``name`` columns to use ``utf8_general_ci`` instead of ``utf8_distinct_ci``
This migration runs in 7-10 seconds locally, so I don't think we need to schedule downtime to run it.  I've placed the output of the forwards and reverse migrations in [a gist](https://gist.github.com/jwhitlock/7b18b62fef27fc77a3b71a25d4bf3a71).
> bug 1391084: Switch tag names from utf8_distinct_ci to utf8_general_ci 

- kuma/settings/local.py
- kuma/urls.py
- requirements/constraints.txt
- requirements/default.txt
- requirements/dev.txt
Move sqlparse from contraints to default, because it is needed for RunSQL data migrations. Also update it and some other requirements:
* sqlparse 0.1.19 → 0.2.3 - Cleanup, refactoring, bug fixes
* django-debug-toolbar 1.4 → 1.8 - sqlparse 0.2 compat, Django 1.11 compatibility, manual setup required (with code changes)
* hashin 0.9.0 → 0.11.2 - Update how latest version is determined
> bug 1391084: Upgrade sqlparse and related reqs

- kuma/settings/common.py
- kuma/static/js/interactive.js
- kuma/static/js/wiki.js
- kuma/static/styles/components/wiki/interactive.scss
- kuma/static/styles/wiki.scss
Ok so, I have tried a bunch of different things with regards to the iframe and Kuma trying to get to a happy place where things respond in concert. I have reached that point but, I had to make a call to get to this place.
Basically, while the right sidebar is still visible, the CSS editor will display side-by-side. Once the viewport become narrow enough, and the right sidebar drop to the bottom, it changes to stacked.
This is one part of it. The other side is, to not have to continuously fight with heights, I defined a `max-height`. The maximum height allows for ~6 lines of examples, which is one more than our "rule" of 5. If the specific example goes beyond this, then the examples area aka left side of the editor, will be scrollable to reveal the additional examples.
It ended up …
> Updates for iframe display behaviour

- kuma/settings/common.py
- kuma/static/js/interactive.js
As the title suggests. This ensures that the `mediaQuery` viewport related code only executes for CSS examples.
I also added `interactive.js` to the `wiki-skinny` block on `common.py`. Seems like it was missing from there, or was it left out intentionally? @stephaniehobson
> Fix issue #242, only run mediaQuery code for CSS examples

- .coveragerc
There's a lot of dead code in the tests, which is invisible because the tests are hidden from code coverage.
> bug 957802: Add coverage of tests

- configs/htaccess
- kuma/redirects/redirects.py
- kuma/settings/common.py
- tests/redirects/map_301.py
- tests/redirects/test_redirects.py
Apache in SCL3 handles some legacy paths from earlier versions of MDN, and many of these are incorrect. This PR updates the Apache rules, and creates Django-based redirects for some.
A fuller analysis of these URLs is on [PR 4231](https://github.com/mozilla/kuma/pull/4231#issuecomment-324359728).
AWS blocker, tracked in https://github.com/mozmeao/infra/issues/436
> bug 1362438: Change handling of some legacy paths

- configs/htaccess
- kuma/settings/common.py
- kuma/wiki/tests/test_views.py
- kuma/wiki/views/legacy.py
There could be more generic fix for the locale with underscore. Like `bn_BD` should redirect to `bn-BD`. But for avoiding the complexity, I think this patch is good enough to fix the burning issue.
As we handle the language redirect already from settings, I believe we do not need to add this rule to `kuma/redirects/redirects.py`
@jwhitlock r?
> [Bug 962148] URL with 'en' locale don't redirect to 'en-US'

- kuma/static/js/interactive.js
As not all wiki pages will have the interactive editor, this bails out early if there is no `iframe` present.
> Fix issue #248, test for precense of iframe in interactive.js

- kuma/static/styles/components-skinny/home/home-hacks.scss
- kuma/static/styles/components/home/home-hacks.scss
@stephaniehobson So, this fixes the layout problem with the header section of the "Get Involved" card on the landing page. Also, when it break to `$mq-mobile-and-down` I did some experiments but:
1. Seeing we only have a `jpeg`
2. And even if we get a high-res `png` or even SVG
Sizing and placement of the globe becomes a real fight to ensure, it looks good, and the copy does not flow out of the bound rendering it unreadable.
Seeing that right below this card, there is the "Help improve MDN" section with links on how to get involved:
I thought it best to not fight with the card, and simply completely hide it.
> Fixes layout of get involved card on landing page

- kuma/static/styles/zones/components/subnav.scss
This was happening on `docs/Games`
> Fix obscured drop down menu on game dev page

- kuma/static/styles/components/components.scss
- kuma/static/styles/components/content.scss
- kuma/static/styles/components/wiki/communitybox.scss
- kuma/static/styles/components/wiki/content/moreinfo.scss
- kuma/static/styles/components/wiki/properties.scss
- kuma/static/styles/components/wiki/toc.scss
- kuma/static/styles/includes/_mixins.scss
- kuma/static/styles/includes/_mixins_indicators.scss
Changed notes, indicators, ect to be narrow. The only things that should
be wide now are code samples and tables.
> Bug 1370594: More stuff is narrow by default

- Makefile
- docker-compose.yml
- docker/images/kuma/Dockerfile
- docker/images/kumascript/Dockerfile
Persist the git commit hash for HEAD within the kuma and kumascript Docker images as the environment variable `REVISION_HASH`.
For local development:
- if you use `make up` instead of doing the `docker-compose up -d` directly, the kuma-based containers (`web`, `api`, etc.) will have an accurate `REVISION_HASH`, otherwise its value will be "undefined"
- since the `kumascript` container uses the kumascript Docker image, an accurate `REVISON_HASH` will always be baked into it
Thanks to @safwanrahman  for the idea of using docker build arguments!
> bug 1395684: persist revision hash in docker images

- kuma/static/styles/base/elements/typography.scss
- kuma/static/styles/components-skinny/wiki/indicators.scss
- kuma/static/styles/components-skinny/wiki/quick-links.scss
- kuma/static/styles/components/wiki/indicators.scss
- kuma/static/styles/components/wiki/quick-links.scss
- kuma/static/styles/includes/_mixins.scss
Fix bug 1376770.
Testing notes:
`kbd` in a heading on [this page](https://developer.mozilla.org/en-US/docs/User:stephaniehobson:code#This_is_a_heading_with_a_code_tag_in_it_%3Chtml%3E._Lorem_codeipsum_kbd_dollar_sit_amet)
Code problem reported on [this page](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes#A_prototype-based_language).
Code looks a lot like the serif font in the notes now. Not sure how I feel about that. I'm wondering if we should add a background colour `like github does`.
> Typography tweaks for kbd and code in indicators

- jinja2/base.html
- jinja2/includes/config.html
- kuma/settings/common.py
- kuma/static/js/analytics.js
- kuma/static/js/interactive.js
@jwhitlock This should be sufficient to expose the needed URLs to the JS in kuma and, make available a `postMessage` target call for the editor to get its parent URL.
Anything here that concern you security wise? Anything you would do different? Thanks!
> Fix issue #255, exposes site url and editor url to JS and editor

- kuma/scrape/sources/revision.py
- kuma/scrape/tests/test_source_revision.py
- kuma/wiki/jinja2/wiki/revision.html
- kuma/wiki/tests/test_templates.py
* Convert the one revision detail template test to pytest standard.
* Add ``data-name`` attributes to ``<span>`` elements, and use them when  scraping a document revision.
* Add ``data-value`` attribute to the "Is Current" element, so that its  value is the same when translated ([bug 1393845](https://bugzilla.mozilla.org/show_bug.cgi?id=1393845))
* Drop classes used for ease of testing rather than styling.
> bug 1393845: Make revision detail view easier to scrape

- .env-dist.dev
- docker-compose.yml
- kuma/settings/common.py
Pass ``INTERACTIVE_EXAMPLES_BASE`` to both the kuma and kumascript containers.  Whitelist the interactive examples host used for local development. Builds on #4404.
This requires the changes in https://github.com/mdn/kumascript/pull/306 to work. Local development of interactive examples on MDN pages will be:
1. Clone and ``npm install`` https://github.com/mdn/interactive-examples
2. Change ``https://developer.mozilla.org`` to ``http://localhost:8080`` in ``analytics.js`` and ``events.js``
3. ``npm run build`` and ``npm start`` to run it, such as http://localhost:8080/pages/js/array-filter.html
3. Add ``INTERACTIVE_EXAMPLES_BASE=http://localhost:8080`` in ``.env``
4. ``make up`` to restart containers with the new environment, and maybe ``docker-compose restart memcache`` to clear the …
> bug 1308630: Set Interactive Examples URL from env

- docs/feature-toggles.rst
- etc/sample_db.json
- kuma/static/js/wiki-samples.js
- kuma/static/styles/base/elements/forms.scss
- kuma/static/styles/components-skinny/structure/search-form.scss
- kuma/static/styles/components-skinny/wiki/sample-code.scss
- kuma/static/styles/components/structure/search-form.scss
- kuma/static/styles/components/wiki/sample-code.scss
- kuma/static/styles/includes-skinny/_mixins.scss
- kuma/static/styles/includes/_mixins.scss
- kuma/static/styles/wiki-wysiwyg.scss
- kuma/wiki/jinja2/wiki/document.html
- Remove `wiki_samples` waffle flag, this feature is now permanent.
- Lint wiki-samples.js.
- Capitalize CodePen and JSFiddle names.
- Convert button-link to a mixin and apply to `.open-in` buttons.
- Added top margin to `.cta-link` mixin
- Decrease margin on homepage search form to account for that.
- Add `sample_frame` waffle
- Make width 100% by default
- Make border match code examples by deafult
- Change buttons to use `.cta-link` styles as recommended by Brigade ages ago.
Also:
- Remove outdated summary styles from wysiqyg style sheet.
Testing notes:
I waffled this feature a little differently. I didn't want to duplicate the styles sheets *again* so I added a class to the body if the `sample_frame` waffle is enabled. This means we can roll this feature into production independent of …
> Bug 1370594: Sample output, border and buttons changes

- .travis.yml
The env variable ``ES_VERSION`` was used to define the env variable ``ES_DOWNLOAD_URL``. It appears TravisCI has changed the way it processes environment variables, and this method can't be used anymore.
> bug 1399154: Fix ES_DOWNLOAD_URL

- kuma/settings/common.py
- kuma/settings/prod.py
This PR, as part of the AWS work, is another step towards allowing all settings to be configured from the environment, in this case the `MEDIA_URL` and `STATIC_URL` settings.
> bug 1308630: allow setting MEDIA_URL & STATIC_URL from env

- kuma/static/js/interactive.js
I did not think this one through all the way :-/ So, there is no way to use this functionality from the interactive editor without opening it up with `*` in terms of the `targetOrigin`. We definitely do not want to do that.
Without that, it is basically a loop de loop/catch22[what have you]. The interactive editor needs to know the `targetOrigin` in order to post a message asking for the URL, and should Kuma push the URL down on load, the interactive editor will need to know the trusted origin, before accepting the message.
I am therefore removing this code as it will not be used.
In terms of a solution. I am thinking the biggest challenge is having this work on staging and production. Local development would be great, but there are most likely not going to a lot of instances where all …
> Removes siteUrl postMessage to interactive editor

- requirements/constraints.txt
This library is used by our ElasticSearch libraries. We're currently not using SSL for ES connections inside of SCL3, but we're going to start using it for AWS (https://github.com/mozmeao/infra/issues/383).
[urllib3 1.17](https://github.com/shazow/urllib3/blob/master/CHANGES.rst#117-2016-09-06) added checking the SSL certificate against the OS certificate chain. There was an issue that required a security release in [urllib3 1.18.1](https://github.com/shazow/urllib3/blob/master/CHANGES.rst#1181-2016-10-27), where validation was silently skipped. I believe this is why requires.io is showing us as [insecure](https://requires.io/github/mozilla/kuma/requirements/?branch=master) for being on urllib3 1.14, which is why it came up in my inbox today.
Now is a good time to upgrade, and make sure …
> bug 1399639: Upgrade urllib3

- kuma/settings/prod.py
- kuma/settings/stage.py
This PR fixes some env overrides for AWS where the `config()` calls were not carried into the `kuma/settings/prod.py` file. I carried the `config()` calls into the `kuma/settings/stage.py` file as well.
> bug 1308630: fix some env overrides

- kuma/settings/common.py
Enable [Django's security middleware](https://docs.djangoproject.com/en/1.11/ref/middleware/#module-django.middleware.security), and some of the headers provided:
* ``X-Content-Type-Options: nosniff ``- always on
* ``X-XSS-Protection: 1; mode=block`` - always on
* ``Strict-Transport-Security: max-age=63072000`` - configured from environment
> bug 1308630: Add some security headers

- jinja2/base.html
I've tested this in a local Kuma instance and it looks all right.
One thing I wasn't sure about was case: I've used "Browser Extensions" here, to match the name in the standard: https://browserext.github.io/browserext/, but the title of the linked page is actually "Browser extensions". I think probably the title of the page should be changed to match the name of the standard.
> Fix bug 1400331: Rename WebExtensions link in main nav.

- etc/sample_db.json
* Add the Interactive Editor content experiment
* Add waffle flags ``wiki_samples``, ``redesign_beta``, ``redesign_live``, ``line_length``, and ``sample_frame``
* Remove waffle flag ``iperceptions``
* Add waffle switches ``foundation_callout`` and ``helpful-survey-2``
This was used to generate a new sample database, which also reflects removing the custom collation, disambiguating tags, and the homepage with fewer links to Mozilla-specific documentation.
> bug 1391084: Update sample database resources

- .travis.yml
- docker/images/kuma_base/Dockerfile
- kuma/core/pipeline/cleancss.py
- kuma/settings/common.py
- scripts/travis-install
SCL3 uses ``clean-css`` 3.4.23. This changes from ``cssmin`` to ``clean-css`` 3.4.23
for Docker and TravisCI as well.
**Update**: ``clean-css`` in SCL3 is 3.4.23, not 2.2.16 as I previously reported.
> bug 1301102: Switch from cssmin to clean-css

- kuma/core/pipeline/cleancss.py
Default SCL3 to ``'cleancss'`` as the binary, and assume it is in the executable path.
Using ``'/usr/bin/env cleancss'`` doesn't work, because it looks for an executable with a space in the name. This can wait for the django-pipeline PR, where the string is split by whitespace.
> bug 1301102: Fix default cleancss binary

- tests/functional/test_article.py
- tests/functional/test_home.py
- tests/functional/test_search.py
- tests/pages/base.py
* Look for data-ffo-opensans, not opensanslight
* The Mozilla Platform menu is gone, use the Tech menu
* The privacy URL now starts with https:// instead of //
* Disable the helpfulness survey for search input test
* Trigger opening search on the hourglass span
I've added the same branch https://github.com/mozilla/kuma/tree/functional-1394480, but with an extra commit to [run the tests in Jenkins](https://ci.us-west.moz.works/job/mdn_multibranch_pipeline/job/functional-1394480/).
> bug 1394480: Update functional tests for new design

- kuma/landing/views.py
This PR changes the service of the robot files, such that they're always served, in all contexts (SCL3, AWS, etc.), from where they currently reside, in the `media` sub-directory of the repo. This allows us to override `MEDIA_ROOT` in AWS to something other than the repo's `media` directory, without disturbing the service of these files.
> bug 1308630: always serve robots files from media dir of repo

- kuma/settings/common.py
Update copyright statement, add task completion survey.
There's nothing much to review here (the new strings have been sent to https://github.com/mozilla-l10n/mdn-l10n and Pontoon), but we've prevented merging to master without a PR. This should be merged before the next production push.
> Update strings 2017.16

- etc/newrelic.ini
- requirements/default.txt
Update the ``newrelic`` package, and add a config file suitable for k8s.
The following environment variables will need to be set:
* ``NEW_RELIC_APP_NAME`` - appropriate for the deployment
* ``NEW_RELIC_LICENSE_KEY`` - for our New Relic account (secret)
* ``NEW_RELIC_MONITOR_MODE`` - ``1`` for prod and stage, ``0`` for dev and demo deployments
* ``NEW_RELIC_CONFIG_FILE`` - ``/app/etc/newrelic.ini``
We'll also need to update the scripts to [run under newrelic_admin](https://docs.newrelic.com/docs/agents/python-agent/installation/standard-python-agent-install#install), like:
```
gunicorn -w=4 --access-logfile=- --worker-class=meinheld.gmeinheld.MeinheldWorker kuma.wsgi:application
```
becoming
```
newrelic_admin run-program gunicorn -w=4 --access-logfile=- …
```
> bug 1110799: Add New Relic config

- kuma/settings/common.py
- requirements/default.txt
``raven`` is the Python Sentry client.  This PR:
* Updates raven from 5.10.2 → 6.2.1 (no gotchas in the [changelog](https://github.com/getsentry/raven-python/blob/master/CHANGES))
* Sends the revision hash, for release tracking
* Sets a syncronous transport, which may be more compatible with meinheld
* Sets the repos name, which may make tracebacks more useful
* Ignores DisallowedHost exceptions, which happen in AWS
This extra config won't happen in AWS. It will just get ``SENTRY_DSN`` set by the local settings override file, which [continues to work as a way to specify the dsn](https://github.com/getsentry/raven-python/blob/24c0ecd44617d9fc916bf4c9c4a0ce4ef18ea05e/raven/utils/conf.py#L49).
> bug 1110799: Update raven, expand configuration

- docker-compose.yml
- kuma/core/middleware.py
- kuma/core/tests/test_middleware.py
- kuma/settings/common.py
- kuma/settings/testing.py
- kuma/urls_untrusted.py
- kuma/wiki/urls_untrusted.py
- kuma/wsgi.py
- requirements/default.txt
This PR address at least part of [bugzilla 1402708](https://bugzilla.mozilla.org/show_bug.cgi?id=1402708) and https://github.com/mozmeao/infra/issues/529. Currently in SCL3, there are three domains in use: **main** (developer.mozilla.org), **untrusted** (mdn.mozillademos.org), and **cdn** (developer.cdn.mozilla.net). Here's a sample of what each of the domains in SCL3  returns for specific endpoints:
- should NOT serve sample endpoints (https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals$samples/Color) and should redirect on file-attachment endpoints (https://developer.mozilla.org/files/12984/web-font-example.png)
- no new code needed since these endpoints already check for the proper HOST header and redirect if necessary (must be `ATTACHMENT_HOST` for file …
> Restrict endpoints (bug 1402708)

- kuma/redirects/redirects.py
Redirect requests for /favicon.ico to the (current) static file. Cache header is the default of 12 hours.
I thought about a redirect test for this, but the result depends on the static file configuration of the target server, and the current hash of the favicon.ico file in hosted URLs. I'm not sure this is testable that way.
> bug 1402497: Redirect requests for /favicon.ico

- kuma/landing/test_views.py
- kuma/landing/urls.py
- kuma/landing/views.py
- kuma/redirects/redirects.py
- kuma/settings/common.py
The redirect pattern fails when hashed assets are enabled, such as building the production Docker images. Instead, wait until runtime to compute the favicon.ico path.
> bug 1402497: /favicon.ico redirect, try #2

- tests/functional/test_dashboard.py
- tests/pages/dashboard.py
Move the sometimes-failing check for details overflow on the search dashboard to its own test. Rewrite the assertion so that the traceback will be better someday (although the traceback is skipped for xfailed tests...). 
Discussed on https://github.com/mozmeao/infra/issues/527. [bug 1405690](https://bugzilla.mozilla.org/show_bug.cgi?id=1405690) is unlikely to be fixed by staff, because of low priority of layout bugs that only affect wiki moderators.
> bug 1405690: Move overflow to own xfail test

- tests/functional/test_home.py
- tests/functional/test_report.py
- tests/pages/base.py
* When opening links in a new tab, wait for the tab to open.
* When opening GitHub in the same window, wait for the URL to change.
This helps address some tests that are flakier in Firefox than Chrome.
> bug 1402950: Be patient for external links

- jinja2/403.html
- jinja2/404.html
- jinja2/500.html
- jinja2/base.html
- jinja2/includes/config.html
- kuma/urls_untrusted.py
This PR addresses [bug 1405519](https://bugzilla.mozilla.org/show_bug.cgi?id=1405519 ) and, at least partially, https://github.com/mozmeao/infra/issues/558. I decided to keep going with a common set of handlers, selectively avoiding specific parts of the current `jinja2/base.html`, `jinja2/403.html`, `jinja2/404.html`, `jinja2/500.html`, and `jinja2/includes/config.html` templates depending upon whether the **untrusted** domain (used for file attachments and code samples, e.g., `mdn.mozillademos.org`) is used. Here's a screenshot of what the 404 would look like:
I did the following in order to test this in my local Docker development environment:
- changed `/etc/hosts` by adding a `demos` alias to `127.0.0.1`
```
##
#
##
127.0.0.1	localhost demos
255.255.255.255	broadcasthost
::1 …
```
> bug 1405519: handle 403/404/500 errors when domain is untrusted

- kuma/attachments/tests/conftest.py
- kuma/attachments/tests/test_views.py
- kuma/attachments/utils.py
- kuma/attachments/views.py
- kuma/conftest.py
- kuma/settings/common.py
- kuma/wiki/tests/conftest.py
* use Django-supplied decorators to add "Cache-Control" header as well as handle "Last-Modified" and its related request headers like "If-Modified-Since"
* allow the "max-age" caching-header value for file attachments to be configured from the environment via `ATTACHMENTS_CACHE_CONTROL_MAX_AGE`
* block Django's `SessionMiddleware` from adding the "Vary: Cookie" header
* move some generally-useful pytest fixtures from `kuma/wiki/tests/conftest.py` to the top level
`kuma/conftest.py`
* add `file_attachment` fixture to `kuma/attachments/tests/conftest.py`
* convert/modify some of the old-style tests in `kuma/attachments/tests/test_views.py` to the
pytest style and add one new test for the file-attachments endpoint
* add `convert_to_utc()` function to `kuma/attachments/utils.py`
> bug 1407806: improve caching for file attachments

- docker-compose.yml
We haven't used ``PROD_DETAILS_DIR`` since [bug 1244853](https://bugzilla.mozilla.org/show_bug.cgi?id=1244853) was fixed two years ago.
> bug 1244853: Remove PROD_DETAILS_DIR

- CONTRIBUTING.md
- README.rst
- contribute.json
- docker/images/mysql/Dockerfile
- docs/troubleshooting.rst
- kuma/settings/common.py
- kuma/users/jinja2/users/email/welcome/html.ltxt
- kuma/users/jinja2/users/email/welcome/plain.ltxt
* Change dev-mdc and dev-mdn links to Discourse
* Change dev-mdn email gateway to admin email
* Fix some other keywords in [contribute.json](https://github.com/mozilla/contribute.json)
> bug 1397786: Update mailing list links to Discourse

- Makefile
This PR ensures that the "npm update" command is always freshly run when building the Kumascript Docker image.
> bug 1409119: do not use cached layers when building ks image

- kuma/conftest.py
- kuma/wiki/tests/conftest.py
This PR is meant to be a follow-on to https://github.com/mozilla/kuma/pull/4461 to address the review comments. Without getting into the details, all of the requested changes were problematic except for the change in this PR (limit root-level `conftest.py` to fixtures that are actually needed at that level).
> return unused fixtures from root to wiki conftest

- Jenkinsfiles/stage-integration-tests.yml
- Makefile
- README.rst
- contribute.json
- docs/data.rst
- docs/deploy-scl3.rst
- docs/localization.rst
- docs/tests-ui.rst
- kuma/settings/common.py
- kuma/wiki/tests/test_content.py
- tests/conftest.py
- tests/performance/smoke.py
Replace developer.allizom.org with stage.mdn.moz.works in various places, including the default domain for integration and performance tests and in the documentation.
I'm not disabling the SCL3 sites yet. When I do, I'd like it in one PR / commit, so that we can revert if we  need SCL3 back in the next few weeks.
> bug 1408460: Use stage.mdn.moz.works as stage site

- kuma/wiki/tests/test_templates.py
The path of the experiment JS can change due to STATIC_URL, which can now be set from the environment.
> Use current STATIC_URL setting in test

- kuma/wiki/jinja2/wiki/document.html
Adds `dns-prefetch` and `preconnect` for the editor `iframe` to test the performance impact.
> Fix issue #283, add dns-prefetch, preconnect for editor iframe

- jinja2/base.html
I overlooked conditioning `untrusted` in the `base.html` template with the `ENABLE_RESTRICTIONS_BY_HOST` setting, which broke the default local development environment 😞. This PR fixes that.
> bug 1409894: fix header/footer for dev env

- kuma/attachments/tests/test_views.py
- kuma/attachments/views.py
- kuma/settings/common.py
- kuma/wiki/tests/test_views_code.py
- kuma/wiki/views/code.py
This PR ensures that all of the remaining untrusted-domain endpoints appropriately set (or not) the `Cache-Control` header:
1. `attachments.raw_file` (e.g., https://mdn.mozillademos.org/files/12984/web-font-example.png)
- The appropriate cache-control headers (public, 5-minute default max age that can be modified from settings) and handling (last-modified) have already been applied.
1. `attachments.mindtouch_file_redirect` (e.g., https://developer.mozilla.org/@api/deki/files/2926/=AudioTest_(1).ogg)
- The response is always a permanent redirect (to the `attachments.raw_file` endpoint). There is no need for cache-control headers since the response will always be permanently cached.
1. `wiki.code_sample`(e.g., https://mdn.mozillademos.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals$sample …
> bug 1407806: add cache-control header to untrusted wiki endpoints

- kuma/attachments/views.py
- kuma/core/middleware.py
- kuma/core/utils.py
- kuma/settings/common.py
This PR adds a new setting that allows the use of a CDN for the untrusted-domain endpoints. Companion to https://github.com/mozmeao/infra/pull/623.
> bug 1411675: add setting for ATTACHMENT_ORIGIN

- kuma/static/styles/components/content.scss
- kuma/static/styles/components/wiki/content/alllinks.scss
- kuma/static/styles/components/wiki/content/bug.scss
- kuma/static/styles/components/wiki/content/callout-box.scss
- kuma/static/styles/components/wiki/content/columns.scss
- kuma/static/styles/components/wiki/content/directory-tree.scss
- kuma/static/styles/components/wiki/content/footnote.scss
- kuma/static/styles/components/wiki/content/originaldocinfo.scss
- kuma/static/styles/components/wiki/content/readable-line-length.scss
- kuma/static/styles/wiki.scss
Separating the large content.scss into smaller files.
Re-ordered includes to be alphabetical.
Testing:
- I have not changed any of the code, please do not comment on the code.
- look for: 
- stuff I have deleted from content.scss and not included somewhere else
- stuff that doesn't work in its new location
- no need for cross-browser testing, it should work or be broken in all of them
You can edit this URL to search for pages that uses specific classes on MDN (example uses `callout-box` as search term):
https://developer.mozilla.org/en-US/search?locale=*&topic=none&css_classnames=callout-box
> Bug 1070001: Separate large file into small ones

- jinja2/base.html
This PR fixes an omission introduced in https://github.com/mozilla/kuma/pull/4479. When I added `ATTACHMENT_ORIGIN` as an untrusted domain, I neglected to add it as well to the `base.html` jinja2 template.
In order to test:
- add `demos` and `demos-origin` to `/etc/hosts` (as aliases to the 127.0.0.1 entry)
- configure your `.env`:
```
ENABLE_RESTRICTIONS_BY_HOST=True
ATTACHMENT_HOST=demos:8000
ATTACHMENT_ORIGIN=demos-origin:8000
STATIC_URL=http://localhost:8000/static/
DEBUG=False
```
- add `ATTACHMENT_ORIGIN` to the `environment` section of the worker
- `docker-compose up -d`
- try loading a missing page both ways, both should show the 404 page without error:
- http://demos:8000/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started)
- …
> bug 1411675: fix base.html jinja2 template to check for untrusted-cdn origin

- kuma/settings/testing.py
Set two config options in test that default to DEBUG (True in tests):
* ``WHITENOISE_AUTOREFRESH`` - When ``True``, it stores the ``STATIC_ROOT`` path without further processing (fast). When ``False``, it reads and processes all the files in the ``STATIC_ROOT`` with each call to the Django test client (very slow).
* ``WHITENOISE_USE_FINDERS`` - When ``True``, it uses Django's static finders, which uses django-pipeline's test-optimized finder. When ``False``, it scans the ``STATIC_ROOT`` path itself (slow).
This is a 10x speed-up for Docker for MacOS for me.
> bug 1402708: Speed up tests w/ whitenoise 3.3.1

- kuma/static/styles/components-skinny/tagit.scss
- kuma/static/styles/components-skinny/wiki/wiki-helpful-survey.scss
- kuma/static/styles/components/tagit.scss
- kuma/static/styles/components/wiki/wiki-helpful-survey.scss
- kuma/static/styles/includes/_vars.scss
- kuma/static/styles/zones/components/promo10.scss
- kuma/static/styles/zones/components/quote.scss
- repair zilla fallback font declaration
- switch to mixin for all font-family declarations
Looking into this after @schalkneethling noted fonts were loading before other stuff, and they should be async.
The Zilla fallback font declaration was broken :( It should work now.
Our font loading system needs the fonts to be declared in a specific way. In a perfect world this would be enforced by something like Post-CSS but we don't have a perfect world. There used to be two ways to do this but this PR switches to the mixin only.
> Bug 1150118: Fix lazy loading fonts

- kuma/landing/test_views.py
- kuma/urls_untrusted.py
This PR adds a `/robots.txt` endpoint (which disallows everything) to the untrusted domains:
- `ATTACHMENT_HOST`(e.g., `mdn.mozillademos.org`)
- `ATTACHMENT_ORIGIN` (e.g., `mdn-demos-origin.moz.works`)
This is part of work involved in https://github.com/mozmeao/infra/issues/590.
> bug 1402708: add robots.txt endpoint to untrusted domains

- kuma/attachments/tests/test_views.py
- kuma/attachments/views.py
This PR simply increases the `max-age` portion of the `Cache-Control` header for the file-attachment endpoints from 5 minutes to 15 minutes. The [cache-hit rate for the most popular file-attachment endpoints](https://console.aws.amazon.com/cloudfront/home?region=us-west-2#popular_urls:) is currently hovering roughly around 50%. The goal is to significantly increase that, and this should give us more data we can use to find the sweet spot.
> bug 1407806: increase caching max-age for file attachments

- Jenkinsfile
- Jenkinsfiles/stage-push.groovy
- Jenkinsfiles/utils.groovy
- scripts/irc-notify.sh
This PR is the initial pass at the blueprint for deploying Docker images to K8s. For now, it focuses solely on pushing to stage (stage.mdn.moz.works), and borrows from the Jenkins code and bash scripts used in [bedrock](https://github.com/mozilla/bedrock). The PR https://github.com/mozmeao/infra/pull/629 is a prerequisite for successful operation.
> bug 1406546: enable deploy of Kuma images to AWS

- kuma/wiki/jinja2/wiki/document.html
@stephaniehobson So, I am not sure whether this will explicitly add the preloaded files to browser cache seeing that the `Cache-Control` headers are not set at the moment. If not, which I kinda think will be the case, this will not have an impact but, worth getting into production?
> Conditionally adds preload link tag for codemirror and html document

- kuma/users/migrations/0007_user_is_github_url_public.py
Add the column ``User.is_github_url_public``. We'll need to deploy and run migrations before merging the rest of #4346.
> bug 1360294: Add user.is_github_url_public

- requirements/constraints.txt
- requirements/default.txt
* bleach 2.0.0 → 2.1.1: Convert control characters to entities, restrict clean and linkify to unicode or utf8-encoded strings.
* six 1.10.0 → 1.11.0: with_metaclass fixes, more moves
> bug 1399639: Update to bleach 2.1.1, deps

- kuma/settings/common.py
- kuma/wiki/content.py
Protocol filtering has been handled by Bleach since 1.5 (Nov 2016). ``AHrefProtocolFilter`` and the associated code hasn't been used since January 2017.
[bug 1326384](https://bugzilla.mozilla.org/show_bug.cgi?id=1326384) was a security bug, with no public pull request. In theory, this PR's change could have been included in the Jan 2017 changes, but we try to minimize changes in security updates, and it was forgotten until now. The relevant commits were:
* https://github.com/mozilla/kuma/commit/020b9ccdc289de85b75f629353fb677dcbcc21cb - Filter iframes after bleach
* https://github.com/mozilla/kuma/commit/729fe608b4a0bb1a67982a63e54ba29470833f67 - Update to Bleach 1.5.0
* https://github.com/mozilla/kuma/commit/5f602dc5937966d326c31c3355d80553bc164945 - Switch to Bleach for protocol …
> bug 1326384: Remove deprecated protocol filtering

- kuma/wiki/jinja2/wiki/list/documents.html
- kuma/wiki/managers.py
- kuma/wiki/tests/test_managers.py
- kuma/wiki/views/list.py
Improve special views that return a list of documents:
* Reduce data returned from database to that used in the page
* Eliminate second ``COUNT(*)`` query
* Remove redirects, user pages, and archive pages from the "needs review" and "needs translation" lists.
To Do:
This was originally PR #4378. These views are even slower post-AWS.
> bug 1392457, 1274874: Improve document list views

- kuma/static/styles/components/compat-tables/_vars.scss
- kuma/static/styles/components/compat-tables/bc-history.scss
- kuma/static/styles/components/compat-tables/bc-icons.scss
- kuma/static/styles/components/compat-tables/bc-table.scss
Reduce the amount of complied code we're outputting to just what we need for the 3 different kinds of tables we're publishing.
- create map with 3 table types and configuration options
- change all classes relying on number of browsers to rely on table type
- increase padding on mobile feature names
- add margin between icons
Testing notes:
- the macro branch has not been updated with these classes yet, you can test by swapping in `bc-table_web`, `bc-table_js`, and `bc-table_ext` on the web, javascript, and webextentions tables respectively using browser tools.
> Restrict code to 3 table types

- kuma/static/js/wiki.js
- kuma/static/styles/base/elements/typography.scss
- kuma/static/styles/components/wiki/customcss.scss
- kuma/static/styles/components/wiki/quick-links.scss
- kuma/static/styles/includes/_vars.scss
- kuma/wiki/jinja2/wiki/includes/document_macros.html
- tweak function adding intelligent breakpoints to long titles
- add break before `[`
- don't add break before first letter of title
- don't run if there are child elements
- remove background colour from `<code>` elements
- brighten strike through items when hovered (to make them readable)
- change heading to "related topics"
- make links blue
- group headings with their subcategories
- tweak what's hidden while js loads
Test pages:
http://localhost:8000/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array
http://localhost:8000/en-US/docs/Learn/HTML/Introduction_to_HTML
http://localhost:8000/en-US/docs/Web/CSS/border-radius
http://localhost:8000/en-US/Add-ons/Firefox_for_Android/API/window.NativeWindow/window.NativeWindow.contextmenus/window.NativeWindow.contextmenus.remove …
> Bug 1414107: New styles for quick-links

- kuma/wiki/jinja2/wiki/document.html
- kuma/wiki/jinja2/wiki/includes/document_macros.html
Note: This has the caveat that we are still loading the CSS and JS from the interactive examples domain.
> Adds document macro to add the js interactive editor

- kuma/static/styles/zones/components/parent.scss
- make landing page icon same size as sub page icons (in preparation for breadcrumbs to be removed and document head to shrink)
- keep zone parent text on separate line from document title until tablet breakpoint
- make zone parent font size match document title font size
Testing notes:
- some zones have an icon ([Learn](https://developer.mozilla.org/en-US/docs/Learn)) and some have text ([Extensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions))
- the zone landing page and the interior pages used to have different size icons but this PR changes that
> Bug 1414107: Display tweaks for zone-parent

- kuma/static/js/highlight.js
- kuma/static/styles/base/elements/sectioning.scss
- kuma/static/styles/base/elements/typography.scss
- kuma/static/styles/components/components.scss
- kuma/static/styles/components/content.scss
- kuma/static/styles/components/newsletter.scss
- kuma/static/styles/components/structure.scss
- kuma/static/styles/components/wiki/content/card-grid.scss
- kuma/static/styles/components/wiki/content/landingPage.scss
- kuma/static/styles/components/wiki/content/originaldocinfo.scss
- kuma/static/styles/components/wiki/indicators.scss
- kuma/static/styles/components/wiki/topicpage-table.scss
- kuma/static/styles/components/wiki/wiki-helpful-survey.scss
- kuma/static/styles/includes-skinny/_mixins.scss
- kuma/static/styles/includes-skinny/_vars.scss
- kuma/static/styles/includes/_mixins.scss
- kuma/static/styles/includes/_vars.scss
- add separator variables
- add separator to h2s
- add separator to end of articles
- make hr match separator
- collapse separator lines when appearing next to each other:
- summaries, blockquotes, top of the page, hrs
- move highlight to h3 and h5
- font size and margin changes to all headings
- remove empty p and div tags from article bodies
- adjust card-grid to appear better as full-width-content
- tweaks to components that use headings in them to accommodate new
margins and typography on headings
> Bug 1414107: Update typography hierarchy

- kuma/static/styles/components/structure/document-head.scss
- kuma/static/styles/components/wiki/crumbs.scss
- kuma/wiki/jinja2/wiki/document.html
- kuma/wiki/jinja2/wiki/includes/document_macros.html
- kuma/wiki/tests/conftest.py
- kuma/wiki/tests/test_templates.py
- remove crumbs from document-head
- add crumbs to left column
- change from rdf to schema.org encoding on crumbs
- add intelligent break points to long page titles
- tweak flow of document-title and document-actions on mobile and tablet
- update look of crumbs
- including larger hit area on mobile and tablet
> Bug 1414107: Move breadcrumbs to left column

- kuma/static/styles/components/compat-tables/_vars.scss
- kuma/static/styles/components/compat-tables/bc-supports.scss
- Add gradient background to colours to give them a pattern for colour
blind users to tell them apart
- change colours to reference global variables
> Add gradient background to status colours

- docker/images/integration-tests/Dockerfile
- docker/images/kuma_base/Dockerfile
- docker/images/kumascript/Dockerfile
Per https://github.com/mozmeao/infra/issues/641, this PR replaces the base images for MDN:
- Builds the `kuma_base` and `kumascript` images upon ~~`mozmeao/base:pythode-2.7-6.11`~~ `python:2.7-slim`
- Builds the `integration-tests` image upon ~~`mozmeao/base:python-2.7`~~ `python:2.7-slim`
- ~~Replaces the `kuma` and `kumascript` users with the `webdev` user provided by the new base image~~
> bug 1415358: replace base images

- docker/images/kumascript/Dockerfile
@safwanrahman made a [good suggestion](https://github.com/mozilla/kuma/pull/4506#discussion_r150239403) to use the `node:6.12-slim` base image for kumascript instead of the `python:2.7-slim` image, since kumascript is primarily a `Node.js` project. The only complication was that since the `node:6.12-slim` image creates a less-safe user with a UID of 1000, I had to remove the `node` user before creating a safer `kumascript` user.
Tested by doing the following:
```
make build-kumascript
cd kumascript
make lint
make lint-macros
make test
make test-macros
make shrinkwrap
make run (then try `http://localhost:9080/revision` in browser)
```
> bug 1415358: use node:6.12-slim base image for kumascript

- kuma/static/styles/base/elements/typography.scss
- kuma/static/styles/components-skinny/syntax/base.scss
- kuma/static/styles/components-skinny/syntax/error.scss
- kuma/static/styles/components-skinny/syntax/example.scss
- kuma/static/styles/components-skinny/syntax/syntaxbox.scss
- kuma/static/styles/components/syntax/base.scss
- kuma/static/styles/components/syntax/error.scss
- kuma/static/styles/components/syntax/example.scss
- kuma/static/styles/components/syntax/syntaxbox.scss
- kuma/static/styles/includes-skinny/_mixins.scss
- kuma/static/styles/includes-skinny/_vars.scss
- kuma/static/styles/includes/_mixins.scss
- kuma/static/styles/includes/_vars.scss
- re-work how backgrounds, borders, and padding are added to prism blocks
- colours are now added to parent 
- this means we can use a single class on the parent to target them
- and that **class can be re-used on other elements** to add the same border background and padding
- and `example-good` and `example-bad` now show up in CKEditor
- add generic `example` class
- consolidate code block styling in %code-block placeholder
- review prism over-rides
- remove `syntaxbox-help`, the feature this styled has been removed
- changes are added to both waffled and non-waffled files
Some pages to help with testing:
https://developer.mozilla.org/en-US/docs/User:stephaniehobson:code
https://developer.mozilla.org/en-US/docs/User:stephaniehobson:examples
> Fix Bug 1415698: Example classes for non-code blocks

- kuma/wiki/jinja2/wiki/includes/document_macros.html
Replacing #4519.
Removing requireJS and loading the 2 files directly so we can take advantage of HTTP2.
> Removing requirejs from the mix to see how HTTP2 handles the requests

- kuma/static/styles/components/compat-tables/_vars.scss
Tweaks to status colours to try to address poor contrast for colour blind users, as identified here: https://github.com/mozilla/kuma/pull/4511#issuecomment-343078774
> Tweak colours, better for colour blind users

- jinja2/includes/config.html
- kuma/settings/common.py
Testing:
Typography changes should show up in editor only when waffle is enabled. You will have to do a `docker-compose restart web` to pick up the new settings in common.py.
Blue lines are not showing up in editor even when other type changes are displayed. Working on a separate PR for that.
> Bug 1415969: Waffle typography changes on in editor

- requirements/default.txt
Prerequisite for the GZip work.
> bug 1409523: add django-debreach to default requirements

- scripts/irc-notify.sh
Fix the build URL displayed by `scripts/irc-notify.sh` such that it can handle multiple pipelines (it was locked to the `mdn_multibranch_pipeline`).
> bug 1406546: fix irc-notify.sh to handle multiple pipelines

- kuma/attachments/tests/test_views.py
- kuma/search/views.py
- kuma/settings/common.py
- kuma/wiki/tests/test_views_code.py
This PR adds GZIP compression handling to all requests that can accept GZIP encoding, and all endpoints with a response greater than 200 bytes that are not already content-encoded. It also adds BREACH attack mitigation via `django-debreach` and rate-limiting (the search page only). It does not add Brotli compression handling, which can be in another PR.
> bug 1409523: add gzip compression + BREACH-attack mitigation

- jinja2/base.html
Previously we had different coloured favicons for different servers so we could make changes on dev and staging fearlessly. Since the move to AWS the red favicon has been displaying on all servers. This is bad because it's the colour of "it's safe to recklessly make changes". Until https://github.com/mozmeao/infra/issues/585 is fixed all servers should display the "Be careful!" colour.
> All servers get blue favicon

- Jenkinsfiles/default.groovy
- Jenkinsfiles/master.groovy
- Jenkinsfiles/utils.groovy
- Makefile
This PR addresses https://github.com/mozmeao/infra/issues/650 and https://github.com/mozmeao/infra/issues/602, as well as https://github.com/mozmeao/infra/issues/595.
* use `docker-compose down` to ensure a clean context both before and after the Kuma tests (I'm hoping this addresses the symptoms of https://github.com/mozmeao/infra/issues/602)
* notify `#mdndev` in IRC on failure
I also added IRC notification on failure to the `default` case, but I would be happy to remove that if we'd rather not clutter `#mdndev` with failure notifications for random branches.
> bug 1406546: potential fix for kuma test reliability issue in jenkins

- kuma/wiki/content.py
- kuma/wiki/tests/test_content.py
Under MySQL's utf8_general_ci collation, some slugs like ``Glossaire/Recursion`` and ``Glossaire/Récursion`` match (``e``=``é``), but the lowercase versions do not. Fall back to checking each slug one at a time, which includes checking missing slugs twice.
> bug 1413289: Handle collation-matching slugs

- kuma/settings/common.py
- kuma/static/js/wiki-toc.js
- kuma/static/js/wiki.js
- kuma/static/styles/components/structure/document-head.scss
- kuma/static/styles/components/structure/main-header.scss
- kuma/static/styles/components/structure/nav-access.scss
- kuma/static/styles/components/structure/nav-main.scss
- kuma/static/styles/components/structure/nav-sec.scss
- kuma/static/styles/components/structure/submenu.scss
- kuma/static/styles/components/wiki/content/collapsible.scss
- kuma/static/styles/components/wiki/properties.scss
- kuma/static/styles/components/wiki/toc.scss
- kuma/static/styles/includes-skinny/_vars.scss
- kuma/static/styles/includes/_vars.scss
- kuma/static/styles/wiki.scss
- kuma/wiki/jinja2/wiki/document.html
- kuma/wiki/models.py
- kuma/wiki/tests/test_views.py
- Move TOC to below document title
- Add sticky TOC styles
- Don't show TOC if the screen is too small
- Add JS to improve TOC user experience
- Scrolling to anchor links accounts for height of TOC
- Don't make TOC sticky if it's too big
- Collapse sections by default on mobile
- open by default if user arrives via an anchor link
- Change code block formatting to avoid FOUT on `<pre>` blocks (the page
should jump around less when Prism loads now)
Fix bug 1416983
> Fix Bug 1414107: Sticky TOC and mobile collapsed

- kuma/static/styles/components/wiki/quick-links.scss
- kuma/static/styles/includes-skinny/_mixins.scss
- kuma/static/styles/includes-skinny/_vars.scss
- kuma/static/styles/includes/_mixins.scss
- Copy fix from #4482 into the waffled "skinny" styles files
- Switch to mixin for all header-font-family declarations
The page title should display immediately in the fallback font. Then Zilla should either be swapped in or not in 2 seconds. On the next page load the heading should display in Zilla immediately.
The font-loading script relies on session storage to do this so a hard refresh can confuse it. Empty your session storage before testing.
Fix bug 1418010
> Fix bug 1418010: Fix lazy loading fonts

- kuma/static/styles/components/wiki/edit/translate/translate-document.scss
- kuma/wiki/jinja2/wiki/translate.html
- add padding to the top of the English display matching approximate
height of the toolbar on the translation side
- move `.text-content` to different element so headings identifying
English and French translations match style
> Bug 1040595: Add padding to top of English

- kuma/users/models.py
GitHub has a capital H (also it is already written like this for every other occurence in the codebase)
> Fix bug 1419289 (most minor typo)

- kuma/wiki/jinja2/wiki/document.html
Updates the `preload` urls to the new endpoints. I removed the `as="document"` as it seems this is not supported in Chrome release either so, we are not getting any benefit from this.
> Fix Bug 1418301, updates preload urls

- docs/installation.rst
Add `curl -O` as an alternative to `wget -N` in *docs/installation.rst* for *macOS* users
> Fix bug 1387505:Add curl as an alternative to wget

- jinja2/includes/translate_locales.html
- kuma/settings/common.py
- kuma/settings/languages.json
[bug 984149](https://bugzilla.mozilla.org/show_bug.cgi?id=984149) is an older bug, and a lot of the UI is already translated. It should be a quick turn as a candidate language.
Some additional files included from following instructions on https://kuma.readthedocs.io/en/latest/localization.html#add-a-new-locale-to-pontoon
> bug 984149: Enable Telugu (te) as candidate locale

- kuma/users/jinja2/users/email/welcome/html.ltxt
- kuma/users/jinja2/users/email/welcome/plain.ltxt
As specified on [bug 1397786](https://bugzilla.mozilla.org/show_bug.cgi?id=1397786#c9)
- Mozilla Developer Network -> MDN Web Docs
- Drop link to unused blog
- Remove Jean-Yves
- Update Janet's IRC handle
> bug 1397786: Update welcome email

- docker/images/kumascript/Dockerfile
node-gyp is the compiler for binary node.js packages, needed to compile the optional New Relic native-metrics package. node-gyp requires Python, and looks for it at /usr/bin/python by default. This location doesn't exists, because Ubuntu is transitioning to Python 3 and wants users to be explicit about Python 2 versus Python 3. This PR sets the Python path to the installed Python 2.7 binary.
> bug 1399639: Configure python for node-gyp

- kuma/wiki/models.py
- kuma/wiki/tests/test_models_document.py
Instead of prefering the current revision's comment, always use the SEO summary with inner HTML markup. 
It's unclear why the comment was preferred. It appears to have been this way for many years, perhaps even at the kitsune fork. KumaScript macros assume it is the SEO summary ([bug 1404684](https://bugzilla.mozilla.org/show_bug.cgi?id=1404684)).
> bug 1404684: Use HTML SEO summary as JSON summary

- kuma/settings/common.py
Send security messages to the console, instead of the default of mailing admins.
In development, these will be available from ``docker-compose logs -f web``, and look like:
```
web_1            | http_app_kuma: 2017-11-29 06:58:09,459 django.security.DisallowedHost:ERROR Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add u'127.0.0.1' to ALLOWED_HOSTS.: /usr/local/lib/python2.7/site-packages/django/core/handlers/base.py:204
```
To see this error locally, add ``DEBUG=False`` to ``.env``, change ``docker-compose.yml`` to set ``- ALLOWED_HOSTS=localhost,web,api``, ``make up`` to start containers with the new config, and then visit http://127.0.01:8000/en-US/.
In production, this should send the messages to Papertrail, where we can query and monitor them in bulk.
The default is to …
> bug 1421016: Log security messages to console

- kuma/static/styles/components/content.scss
- kuma/wiki/content.py
- kuma/wiki/models.py
- kuma/wiki/tests/test_content.py
- kuma/wiki/tests/test_models_document.py
Added a function to remove a section according to it's ID, existing function will remove the contents of a section but leave the wrapper.
> Bug 1414107: Remove empty Quick_Links section

- kuma/static/styles/includes/_mixins.scss
Our code base is old enough that we still have `<a name="linkToHere">Link to me!</a>` in the articles, link styles need to not apply to anchors used in this way.
I vaguely recall running into problems using `a:link` in the past but can't recall exactly what. My testing did not turn up any problems.
I've only applied the `:link` restriction to elements that appear in the body of an article, submenus, header, footer, etc where were have control of the content and can be sure there are no named anchors exist I left alone.
> Fix bug 1421790: a[name] should not get a:link styles

- kuma/search/jinja2/search/results.html
- Display "found in all locales" instead of "found in English(US)"
> Fix bug 1063560: Change search output with locale=*

- kuma/health/tests/test_views.py
- kuma/wiki/middleware.py
- kuma/wiki/tests/test_middleware.py
After a long day of looking into Kubernetes liveness and readiness probes, we decided to keep database connection tests in the readiness views for a bit longer (closing PR #4578), and instead adjust the probe settings in Kubernetes (https://github.com/mozmeao/infra/pull/665). There are some changes that we still want to apply. 
* Refactor the health probe tests, to show that the database is not needed for several tests
* Detect health probe URLs in the ``DocumentZoneMiddleware``, and exit early to avoid the (cached) database query.
> bug 1422009: Adjust liveness tests, avoid DB query in middleware

- etc/sample_db.json
Compat API project has ended. Long live Compat JSON project.
> Remove unused waffle from sample database

- requirements/dev.txt
Install the `urlwait` Python package as part of the `kuma_base` Docker image. Required for #4581.
> bug 1406546: make urlwait available in kuma_base image

- Jenkinsfiles/stage-push.groovy
- Jenkinsfiles/utils.groovy
- Makefile
The aim of this PR is to prevent a pitfall, when pushing to stage and production, that occurs when the image specified by the tag determined from the latest commit hash was not successfully pushed to the Docker image registry. The deployment succeeds, but the pods affected by the deployment loop in an image-pull error. This PR prevents that. I wanted to put this in place before we create the `prod-push` branch.
> bug 1406546: ensure image can be pulled prior to deployment

- kuma/core/middleware.py
- kuma/core/tests/test_middleware.py
- kuma/settings/common.py
This PR provides the ability to configure (via the environment) one or more "legacy" domains. All requests from any one of these "legacy" domains will be redirected to the configured `SITE_URL` with the same path and query parameters. See its companion PR https://github.com/mozmeao/infra/pull/672.
> bug 1110799: redirect legacy domains

- Jenkinsfiles/utils.groovy
This PR fixes a bug I introduced into the `stage-push` and `prod-push` branch-based push machinery. Stage and prod pushes of both kuma and kumascript via the `stage-push` and `prod-push` branches will be broken until this is merged.
> bug 1406546: fix call to sh_with_notify within utils.ensure_pull

- Jenkinsfiles/utils.groovy
This PR fixes a problem within the Groovy `utils.compose_test` function. Currently, when [this line](https://github.com/mozilla/kuma/blob/24744d780cb6a80f250a399feb2ed6f707cffbb5/Jenkinsfiles/utils.groovy#L138) is run, the exit code is NOT the exit code from the `test` container's command (`py.test ...`) as it should be. This resulted in Jenkins builds that failed the tests but would pass the stage, resulting in an "unstable" build (labelled with an exclamation point in yellow). This fixes that.
I like the approach in https://github.com/mozilla/kuma/pull/4585 a bit better, but the `docker-compose` upgrade in Jenkins is blocking that.
> bug 1406546: ensure Kuma tests return proper exit code

- tests/functional/test_dashboard.py
- tests/pages/base.py
- tests/pages/dashboard.py
These changes make Firefox run more reliably with the Remote driver in Selenium 3, and should still work in Selenium 2:
* To display the on-hover submenus, first move the mouse to the logo. This more reliably triggers the hover state on the article page.
* The hover is still unreliable, especially on the homepage. If the driver is Remote for Firefox, then allow hover tests to xfail.
* On the Revision Dashboard, it can take time to expose the revision diff after the other details are displayed. Be patient.
There was also an error in ``test_dashboard_overflow``, where the wrong attributes made it always ``xfail``. Now it can ``xpass`` as well.
> bug 1402950: Run tests more reliably with Firefox and Remote driver in Selenium 3.x

- Jenkinsfiles/utils.groovy
In Jenkins builds, every Kuma test that hit the database started to fail consistently with a `OperationalError: (1130, "Host '172.20.0.5' is not allowed to connect to this MySQL server")`. This was fixed by also tearing down the volumes (using `docker-compose down --volumes`) before running the tests. I also added the "--remove-orphans" option as well, so we start (and end) with a totally clean slate.
Thanks to this thread: https://github.com/docker-library/mysql/issues/275 for the idea.
> bug 1406546: fix kuma tests by tearing-down volumes as well

- jinja2/base.html
Per Bugzilla bug 1420354 change rel="copyright" to rel="license" at https://github.com/mozilla/kuma/blob/9d102e004e2fd9694704d9a08f145b3282a90ba9/jinja2/base.html#L16
Please let me know if I need to do anything else. Thanks!
> fix bug 1420354 - Use rel="license" instead of rel="copyright"

- kuma/static/js/wiki.js
- regex now only acts if there are 3 lowercase letters in a row before
a match
- removed `-` from list of matched characters (we should break after
dashes not before them and the browser sort of does this already)
- tried to improve comments
> Fix bug 1422422: No break after space open paren

- kuma/static/js/wiki-compat-tables.js
- kuma/static/styles/components/compat-tables/_vars.scss
- kuma/static/styles/components/compat-tables/bc-browser.scss
- kuma/static/styles/components/compat-tables/bc-history.scss
- kuma/static/styles/components/compat-tables/bc-icons.scss
- kuma/static/styles/components/compat-tables/bc-legend.scss
- kuma/static/styles/components/compat-tables/bc-supports.scss
Bit of compat table clean up.
- Remove no-support X from history drop down on unsupported features
- Center no-support X in mobile display
- Keep icons with feature text until desktop display
- Two columns for legend on tablet and up
- Speed up history tray animation
Bad:
Better:
> Display tweaks to compat tables

- kuma/static/js/wiki-compat-tables.js
The issue is that the link leads to en-US page even if generated for article in another language.
> Fixed l10n-aware link to New_Compatibility_Tables_Beta

- kuma/settings/common.py
The [Telugu team](https://pontoon.mozilla.org/te/) has translated [74% of the UI](https://pontoon.mozilla.org/te/mdn/), and has requested in [bug 984149](https://bugzilla.mozilla.org/show_bug.cgi?id=984149) that we enable ``te`` on MDN.
> bug 984149: Enable Telugu (te)

- etc/sample_db.json
This breaks the sample DB process, and is probably left over from a rebase for one of the many PRs for [bug 1136741](https://bugzilla.mozilla.org/show_bug.cgi?id=1136741).
> bug 1136741: Remove null entry from sample_db.json

- Jenkinsfiles/integration-tests.groovy
* Add Google Chrome to the integration test suite. In our selenium 2 version, this is Chrome 47, released December 2016.
* Run Chrome, Firefox, and headless (requests) tests in parallel. Add a browser prefix to distinguish between functional tests.
* Run parallel functionaltests equal to the number of selenium nodes
* Manually create and stop containers, to avoid a bug in auto-stopping containers in dockerRun
* Re-run tests on failure, to deal with flakiness of low-usage infrastructure like staging
* Be doubly verbose
* In several runs, a chrome node would become unresponsive, and the test would hang forever. Timeout the pytest run in 4 minutes, and enforce a Jenkins timeout of 5 minutes.
* Notify IRC on tests success or failure
> bug 1402950: Add Chrome to integration tests

- docker-compose.yml
- kuma/settings/common.py
Set the ``CELERY_RESULTS_BACKEND`` from the environment, and use Redis DB 1 ([namespacing feature](http://www.rediscookbook.org/multiple_databases.html) to distinguish from DB 0 for task queues) instead of the Django database in development. A similar change is planned in production to reduce database usage.
> bug 1268257: Results backend from env, use redis

- jinja2/403.html
- jinja2/429.html
- kuma/conftest.py
- kuma/core/decorators.py
- kuma/core/jobs.py
- kuma/core/models.py
- kuma/core/tests/test_views.py
- kuma/core/utils.py
- kuma/core/views.py
- kuma/settings/common.py
- kuma/wiki/tests/test_views.py
- kuma/wiki/tests/test_views_document.py
- kuma/wiki/tests/test_views_edit.py
- kuma/wiki/views/edit.py
Return a ``429 TOO MANY REQUESTS`` and custom error page when the rate limit is exceeded.
You can view the rate limit page by adding this to a view, such as ``kuma.landing.views.home``:
```
from ratelimit.exceptions import Ratelimited; raise Ratelimited()
```
It looks a lot like the 403 page:
> bug 1423738: Add 429 "Too Many Requests" response

- kuma/wiki/jinja2/wiki/includes/kumascript_errors.html
The issue is that the link leads to en-US page even if generated for article in another language.
> Fixed l10n-aware link to Troubleshooting article

- kuma/static/styles/components/compat-tables/ic.scss
This fixes the broken prefix icon on the new browser compatibility data tables.
> Fix Bug 1428118, prefix icon in new bcd table is broken

- kuma/search/views.py
A user was hitting the 10 per minute rate limit by adjusting the topic filters. Increase the rate to 25, so that all 22 filters can be flipped in one minute.
> bug 1426968: Adjust rate limit for search

- kuma/users/jinja2/users/user_detail.html
- kuma/wiki/jinja2/wiki/compare_revisions.html
- kuma/wiki/jinja2/wiki/document.html
- kuma/wiki/jinja2/wiki/includes/buttons.html
- kuma/wiki/jinja2/wiki/includes/document_macros.html
- kuma/wiki/jinja2/wiki/includes/document_tag.html
- kuma/wiki/jinja2/wiki/list/revisions.html
- kuma/wiki/jinja2/wiki/list/tags.html
- kuma/wiki/jinja2/wiki/revision.html
- kuma/wiki/jinja2/wiki/translate.html
Use ``rel="nofollow"`` for links that we don't want scrapers to follow, instead of ``rel="nofollow, noindex"``, which is not a valid value for the space-separated [rel attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types), but instead for [&lt;meta name="robots"&gt;](https://developers.google.com/search/reference/robots_meta_tag#handling-combined-indexing-and-serving-directives).
> bug 1425760: Use rel="nofollow" for links

- kuma/wiki/feeds.py
- kuma/wiki/tests/__init__.py
- kuma/wiki/tests/test_feeds.py
Re-write all the feeds tests, to use ``pytest`` and fixtures, for full code coverage of ``kuma/wiki/feeds.py``, and to avoid silly things like sleeping for a second to get a new timestamp.
Then, add some additional handling of our naive timestamps, to turn them into timezone-aware timestamps needed for the feeds. This avoid errors in the second half of the year when the US moves from Daylight Savings Time to standard time, and 1 AM happens twice. When these ambiguous times are encountered, they currently cause the feed to fail with an error. The change is to assume that it is the first 1 AM, avoiding the conversion error.
> bug 1173189: Force timezone-aware times for feeds

- docs/data.rst
- etc/sample_db.json
- kuma/scrape/scraper.py
- kuma/scrape/tests/test_scraper.py
Fix the sample database code and docs:
* ``spam_checks_enabled`` flag had an invalid attribute ``FORCE``
* Handle ``429 Too Many Requests`` by taking a nap
* Handle ``504 Gateway Timeout`` by counting to 10
* Try 33% harder
I used this to generate a new [sample database](https://mdn-downloads.s3-us-west-2.amazonaws.com/list.html?prefix=sampledb/) in a little over two hours. I suggest that manual testing isn't needed.
> bug 1423738: Fix sample DB process for squashed migrations, rate limiting

- kuma/static/styles/components/wiki/interactive.scss
This enables us to have a taller iframe size for JS examples that requires a taller editor.
@see https://github.com/mdn/interactive-examples/issues/408
> Fix issue #408, add styling for .taller class on interactive example iframe

- .travis.yml
- tox.ini
Add a test build for Django 1.11, which is expected to fail. I'd like to continue testing the latest versions of Django and other packages after we've finished this upgrade.
> bug 1401246: Add test build for Django 1.11

- docs/tests-ui.rst
- scripts/run_functional_tests.sh
Add a script ``scripts/run_functional_tests.sh``, that can run the functional test suite using the Docker images provided by Selenium.
This was valuable when testing Selenium 2 vs 3, Firefox 42 vs 57, and Firefox vs Chrome. It could be used to test Selenium updates locally, before pushing to Jenkins.
> bug 1402950: Run tests in Selenium Docker images

- Jenkinsfiles/utils.groovy
This PR addresses the issue where we don't want to perform a database migration when we're in a read-only mode. Currently, it assumes we're in "read-only mode" when `KUMA_MAINTENANCE_MODE` is true. This applies to all "push" branches: `stage-push`, `prod-push`, and `standby-push`.
> bug 1406546: only migrate db if not read only

- Jenkinsfiles/prod-integration-tests.yml
- Jenkinsfiles/stage-integration-tests.yml
- Jenkinsfiles/upgrade_pytest_1308322.yml
- requirements/constraints.txt
- requirements/test.txt
- scripts/run_functional_tests.sh
- tests/functional/test_dashboard.py
Builds on py.test updates in #4210 with Selenium updates:
* selenium 2.53.6 -> 3.4.1: Support for GeckoDriver 0.15.0+, Firefox 52+. Many fixes
* pytest-base-url 1.1.0 -> 1.3.0: specify by env, add to metadata
* pytest-html 1.10.1 -> 1.16.0: add metadata to report
* pytest-selenium 1.4.0 -> 1.9.1: Move cloud testing credentials from default config files to new files or environment. Re-write Firefox options method. Work with metadata.
* pytest-metadata==1.3.0: New dependency of pytest-selenium
Django tests and coverage worked for me.  I was able to run the functional tests locally with Chrome and Firefox.  I tried running the Selenium hub and remote locally, but wasn't able to get it working (``KeyError: 'moz:firefoxOptions'`` issue), and Jenkins has the same issue.
**Update Sep 19, 2017**: …
> Bug 1308322: Upgrade to selenium 3.x

- jinja2/includes/lang_switcher.html
- kuma/core/middleware.py
- kuma/core/tests/test_locale_middleware.py
- kuma/core/tests/test_views.py
- kuma/core/urlresolvers.py
- kuma/core/views.py
- kuma/settings/common.py
- kuma/static/js/lang-switcher.js
- kuma/static/js/wiki.js
- kuma/static/styles/components/wiki/indicators.scss
- kuma/urls.py
- kuma/wiki/jinja2/wiki/document.html
- kuma/wiki/jinja2/wiki/includes/buttons.html
**You need to clear your browser cache or using private browsing before testing this**
As the past code was redirecting permanently with http `301` status code, It should be return with temporary redirect with http `302`
It was fixed in kitsune long ago by James, But was not ported back to kuma.
The Implementation is based on kitsune, refactored some part of the code to increase readability. 
@jwhitlock @escattone r?
Need to be done:
> [Bug 1331729] Language preference cookie to stop site redirection

- docs/feature-toggles.rst
- kuma/static/js/wiki-compat-trigger.js
This removes the flag, but keeps the just-in-time loading of the JS and CSS. However, it may make sense to merge those into ``wiki.js`` / ``wiki.css``.
> bug 1136741: Make compat_data flag permanent

- kuma/conftest.py
- kuma/wiki/apps.py
- kuma/wiki/jinja2/wiki/document.html
- kuma/wiki/jinja2/wiki/includes/buttons.html
- kuma/wiki/jobs.py
- kuma/wiki/models.py
- kuma/wiki/templatetags/jinja_helpers.py
- kuma/wiki/tests/test_feeds.py
- kuma/wiki/tests/test_views.py
- kuma/wiki/tests/test_views_document.py
- kuma/wiki/tests/test_views_edit.py
- kuma/wiki/views/document.py
- kuma/wiki/views/utils.py
In the current platform, it seems like many more unneeded SQL queries that kills most of the time!
It can be more optimized, but for now I think small is also benefecial.
**Current Situation:**
**After this Patch:**
I was thinking about fetching all the translations data of the document using elasticsearch or cache. As making a sql queries just for showing the translation information is a bit tradeoff with the performance. What do you think @jwhitlock?
@jwhitlock @escattone Can you please review?
It partially fiexes https://github.com/mozmeao/infra/issues/677
> [Bug 1431139] Optimize Documents view of kuma

- contribute.json
- docs/ckeditor.rst
- jinja2/base.html
- kuma/landing/jinja2/landing/fellowship.html
- kuma/landing/jinja2/landing/homepage.html
- kuma/search/jinja2/search/plugin.html
- kuma/static/js/libs/ckeditor/build/ckeditor/samples/old/descriptionlist/descriptionlist.html
- kuma/static/js/libs/ckeditor/source/plugins/descriptionlist/samples/descriptionlist.html
- media/maintenance/index.html
I did not make the change in the following files as I believe that it will break functionality:
```
kuma/authkeys/jinja2/authkeys/list.html
kuma/users/jinja2/users/user_delete.html
kumascript/tests/fixtures/hacks.rss
```
Also, none of the `.po` files as this will be done by localisers.
> Fix Bug 1432370, change instances of Mozilla Developer Network to MDN Web Docs

- kuma/settings/common.py
Use persistent DB connections by setting ``CONN_MAX_AGE``, defaulting to 60 seconds.
AWS RDS [limits the maximum connections](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ConnectToInstance.html) as a factor of the instance size. Our current instance allows 1320 simultaneous connections. My estimate is that we use 1010 connections, and would be below this limit:
|    Deployment | Pod Count | Per Pod | Total |
| ------------- | --------- | ------- | ----- |
| api           |         2 |       4 |     8 |
| celery-beat   |         1 |       1 |     1 |
| celery-cam    |         1 |       1 |     1 |
| celery-worker |        10 |       4 |    40 |
| kumascript    |         6 |       0 |     0 |
| web           |        20 |       8 |   960 |
| **Total**  |  |  |  1010 |
Another …
> bug 1434296: Use persistent DB connections

- kuma/health/tests/test_views.py
- kuma/health/urls.py
- kuma/health/views.py
- kuma/settings/common.py
- kuma/version/tests/test_views.py
- kuma/version/views.py
- tests/conftest.py
- tests/functional/test_notfound.py
- tests/functional/test_search.py
- tests/pages/dashboard.py
- tests/pages/notfound.py
``/_kuma_status.json`` returns settings and services status. The settings can vary between deployments, and can be used either to confirm settings (for example, ``DEBUG`` should be ``False`` in production) or to modify functional test behavior (for example, ``DEBUG=True`` changes the content of the 404 page).
Tests are modified so that ``scripts/run_functional_tests.sh`` works against a fully setup local development environment:
* The 404 tests vary based on ``DEBUG``
* The filtered vs unfitted search test was failing against the sample database. Use the size of the search index to vary test behavior.
* The selenium tests run in Docker with ``scripts/run_functional_tests.sh``, against internal URL http://web:8000, but the search results (correctly) return the external URL, …
> bug 1431205: Add /_kuma_status.json, use for dynamic functional tests

- kuma/wiki/constants.py
- kuma/wiki/models.py
- kuma/wiki/views/utils.py
This PR removes the unused code related to the caching of the `Last-Modified` value for documents.
> bug 1431820: remove unused last-modified caching for docs

- tox.ini
The "git diff" command needs to run inside the locale submodule directory, or it won't see any differences.
> bug 1385405: Fix tox -e locales for submodule

- tests/pages/dashboard.py
In Jenkins, the functional test ``test_dashboard_open_details`` fails on Firefox with the exception:
```
ElementNotInteractableException: Message: Element <tr class="dashboard-row ">could not be scrolled into view
```
When this is detected, XFAIL the test.
I tried to verify a few things:
* The browser size, as set by the ``selenium`` fixture, is 1201 wide by 1024 tall, so it should be possible to view the row.
* ``first_row.location_once_scrolled_into_view`` returns ``{'x': 24.0, 'y': 0.0}``. This suggests that the row needs to be scrolled into view, since ``y`` is zero.
* The docs for ``ElementNotInteractableException`` suggests there is an element on top that would get this click. Maybe Firefox is displaying an overlay? It's hard to tell without a screenshot, and it doesn't reproduce …
> bug 1402950: test_dashboard_open_details: FF XFAIL

- kuma/attachments/tests/test_views.py
- kuma/attachments/views.py
- kuma/core/middleware.py
- kuma/core/tests/test_middleware.py
- kuma/settings/common.py
- kuma/wiki/tests/test_views_code.py
- kuma/wiki/tests/test_views_document.py
- kuma/wiki/views/code.py
- kuma/wiki/views/document.py
This PR does the following:
- Sets the `USE_ETAGS` setting to `True`. This enables the `ETag` functionality within Django's `CommonMiddleware`, which includes both computing/adding the `ETag` header to **all** responses (even responses to non-`GET` requests) as well as handling conditional GET requests made using the `IF-NONE-MATCH` header (the `IF-UNMODIFIED-SINCE` header is not handled here). The fact that the `ETag` header is added to **all** responses is a shortcoming of Django 1.8. Another shortcoming is that 304 ("Not Modified") responses due to an `ETag` match clear most of the headers, so headers like `Cache-Control`, `ETag`, `Last-Modified`, and `Vary` are lost. I don't think this will cause any issues, but I'm not certain. **When we move to Django 1.11, the `USE_ETAGS` setting …
> bug 1431820: use Django middleware for handling ETag/Last-Modified

- jinja2/404.html
- jinja2/500.html
This commit adds the extension of jinja2 for translating the "Not Found" in the jinja2/404.html file and in the jinja2/500.html page
> fix bug 1419466 - added jinja2 extension of translating the 404 page

- kuma/static/styles/components/compat-tables/bc-browser.scss
Shows correct icon for Firefox for Android on mobile view.
> Fix Bug 1436666, Firefox for android shown as ie for android

- requirements/README.rst
- requirements/constraints.txt
- requirements/default.txt
* Add a section explaining why our requirements are complex
* Make them more complex by adding URLs for code, docs, and changes.
* Swap regular requirements and constraints sections
* Update [django-tidings](https://github.com/mozilla/django-tidings) from [1.1 to 2.0](http://django-tidings.readthedocs.io/en/latest/changes.html), which includes support for Django 1.11 and beyond. 
I tested this locally by adding a watch and unsubscribing, but didn't send a watch email, which requires a second user. I think this can wait for staging, where I'm subscribed to [Ryan's test page](https://stage.mdn.moz.works/en-US/docs/Web/HTTP/ryanHeader).
> bug 1399639: Make requirements more complex, upgrade django-tidings

- kuma/wiki/jinja2/wiki/document.html
Use the ``absolutify`` filter for ``rel=canonical``, ``alternate links``. This uses the ``Sites`` object instead of the request domain, for consistent links across alternate domains on the same database.
This should change the ``<head>`` links on [prod.mdn.moz.works](https://prod.mdn.moz.works/en-US/docs/Web/Reference), so that they point to developer.mozilla.org instead.
> bug 801623: Use absolutify for <link rel=> URLs

- kuma/wiki/apps.py
- kuma/wiki/jobs.py
- kuma/wiki/tests/test_signals.py
- kuma/wiki/tests/test_views_document.py
There was some mistry in hashing the key of cache.
While creating the cache, the `pk` was explictly defined. So it was regarded as `kwargs`.
But while invalidating the cache, the `pk` was not explictly defined, so it was regarded as `args`
`django-cacheback` generate the cache key by hashing the parameters. But it hash differently while having `args` and `kwargs`.
As there were different hash while storing and invalidating, the old `tags` were not removed and kept serving.
Moreover, if the document has no tags, it was showing `None`. Fixed that also by excluding the `None`.
And the `refresh_timeout` need to be `0` because a document can be update continuously. So if we dont create task for every revision, updated tags will be missing.
Moreover, added some tests for this regression to not …
> [Bug 1437022] Tags dont get updated after document edit

- requirements/default.txt
* django-tidings 2.0 → 2.0.1: Bug fix for exception when running asynchronously with Celery
> bug 1399639: Update django-tidings 2.0.1

- kuma/authkeys/jinja2/authkeys/list.html
- kuma/users/jinja2/users/user_delete.html
Update links for product name change from "Mozilla Developer Network" to
[developer.mozilla.org](https://bugzilla.mozilla.org/describecomponents.cgi?product=developer.mozilla.org).
> bug 1439608: Update bugzilla links

- requirements/README.rst
- requirements/constraints.txt
- requirements/default.txt
- requirements/default_and_test.txt
- requirements/test.txt
Move ``pyquery`` and ``requests`` to the new file ``default_and_test.txt``, so that I don't rely on a ``TODO`` to keep the library versions in sync between environments.
Update ``requests`` from 2.9.1 (production) and 2.11.1 (tests) to 2.18.4, along with the new requirements in ``constraints.txt``. Our usage of ``requests`` is pretty basic, so I don't expect problems with this update. Unlike the ``pytest`` and ``pyquery`` updates, which I also tried, which broke so much...
> bug 1399639: Update requests

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Add the MDN Code of Conduct, and refresh CONTRIBUTING for current practices:
* Our process is much closer to GitHub flow than the old WebDev workflow
* We have a lot more to say about code style, expecially around tests
* Add more guidance around branch names and commit messages
* Add more about the code review and deployment processes
* Add expectations for a PR to be touched in 2 business days
* Drop requirement for two peers to review database changes
> bug 957802: Add Code of Conduct, Update Contributing doc

- kuma/conftest.py
- kuma/core/decorators.py
- kuma/core/tests/test_decorators.py
- kuma/core/tests/test_views.py
- kuma/core/views.py
- kuma/dashboards/tests/test_views.py
- kuma/dashboards/urls.py
- kuma/dashboards/views.py
- kuma/settings/common.py
- kuma/users/views.py
- kuma/wiki/tests/conftest.py
- kuma/wiki/views/create.py
- kuma/wiki/views/edit.py
- kuma/wiki/views/translate.py
This is the first of a series of PR's that add the appropriate caching headers and related tests to all Kuma endpoints as part of the effort of placing a CDN in front of MDN. This PR adds caching headers and tests for the `kuma.dashboards.urls`.
* add `shared_cache_control` decorator as a thin wrapper around Django's `cache_control` decorator to encapsulate default settings for shared caching
* add tests for `shared_cache_control` decorator
* delete custom `never_cache` decorator, and replace with Django's
* delete tests for custom `never_cache` decorator
* decorate the views for `kuma.dashboards.urls` and add tests
> bug 1431259: caching headers/tests for dashboards views

- kuma/health/tests/test_views.py
- kuma/health/views.py
This is another in a series of PR's that add the appropriate caching headers and related tests to all Kuma endpoints as part of the effort of placing a CDN in front of MDN. This PR adds caching headers and tests for the `kuma.health.urls`.
> bug 1431259: caching headers/tests for health views

- kuma/landing/tests/test_views.py
- kuma/landing/urls.py
- kuma/landing/views.py
This is another in a series of PR's that add the appropriate caching headers and related tests to all Kuma endpoints as part of the effort of placing a CDN in front of MDN. This PR adds caching headers and tests for the `kuma.landing.urls`.
The `maintenance_mode` endpoint is excluded from caching (it's decorated with `never_cache`). Whenever MDN is taken into or out-of maintenance mode, it seemed best for that endpoint to reflect the current reality immediately.
When #4676 is merged and it is re-based on master, the `not ready` label can be removed.
> bug 1431259: caching headers/tests for landing views

- kuma/users/jinja2/users/user_edit.html
This pull request fixes [951180](https://bugzilla.mozilla.org/show_bug.cgi?id=951180).
Feel free to tell me if I missed anything. I could only find two checkboxes on the edit page.
No styling changes should be needed. I tested my changes with Developer Tools and both versions behaved the same.
> bug 951180: Position labels after checkboxes

- kuma/users/forms.py
``RegexField.error_message`` is [deprecated](https://docs.djangoproject.com/en/1.8/_modules/django/forms/fields/#RegexField), and removed in Django 1.11. Replace it with the suggested ``error_messages={'invalid': msg}``.
> bug 1429933: Migrate to RegexField.error_messages

- kuma/attachments/migrations/0001_squashed_0008_attachment_on_delete.py
- kuma/attachments/models.py
- kuma/authkeys/migrations/0001_initial.py
- kuma/authkeys/models.py
- kuma/feeder/migrations/0001_initial.py
- kuma/feeder/models.py
- kuma/search/migrations/0001_squashed_0003_filter_tags.py
- kuma/search/models.py
- kuma/spam/models.py
- kuma/users/migrations/0001_squashed_0008_update_locales_tz_help.py
- kuma/users/models.py
- kuma/wiki/migrations/0001_squashed_0036_update_locales.py
- kuma/wiki/models.py
[on_delete](https://docs.djangoproject.com/en/2.0/ref/models/fields/#django.db.models.ForeignKey.on_delete) is a required attribute starting in Django 2.0, and is allowed in Django 1.8. Some values:
* CASCADE (the default): Delete this object when the referenced object is deleted.
* SET_NULL: Set the reference to NULL when the referenced object is deleted.
* PROTECT: Deny deletion of the referenced object, forcing this object to be deleted first.
The on_delete attribute must be set in the model as well as the initial migration.
> bug 1429933: Add on_delete specifications

- kuma/wiki/tests/conftest.py
- kuma/wiki/tests/test_templates.py
- kuma/wiki/tests/test_views.py
- kuma/wiki/tests/test_views_list.py
- kuma/wiki/tests/test_views_misc.py
- kuma/wiki/views/list.py
- kuma/wiki/views/misc.py
This is another in a series of PR's that add the appropriate caching headers and related tests to all Kuma endpoints as part of the effort of placing a CDN in front of MDN. This PR adds caching headers and tests for endpoints for the wiki views in `list.py` and `misc.py`.
> bug 1431259: caching headers/tests for wiki misc/list views

- requirements/default.txt
* django-constance 1.1.2 → 2.1.0: Add compatibility with Django 1.11, custom fields, signal for updates.
* django-picklefield 0.3.2 → 1.0.0: Drop old Django support
These updates don't appear to require any code changes, but improve compatibility with Django 1.11 and open some possible features in the future.
> bug 1399639: Update django-constance to 2.1.0

- kuma/wiki/tests/test_content.py
- requirements/constraints.txt
- requirements/default.txt
Upgrades bleach to 2.1.3 the hashes are for the 2.1.3 tgz and whl files respectively.
> bug 1442745: upgrade bleach to 2.1.3

- kuma/static/styles/includes/_mixins.scss
- kuma/static/styles/submission.scss
- kuma/users/jinja2/users/user_edit.html
This pull request fixes [1441210](https://bugzilla.mozilla.org/show_bug.cgi?id=1441210).
Looked at the difference between the labels in Edit Profile and the ones when editing a page and realized that there are [two different ways](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label) to use labels. I changed the ones in Edit Profile to be consistent with the latter, and now the appearance is consistent as expected.
It seems like this functionality was leftover from a previous attempt to get "checkboxes after labels" working, an unnecessary hack due to the nature of how [HTML](https://html.spec.whatwg.org/multipage/forms.html#the-label-element) and the [DOM](https://dom.spec.whatwg.org/#trees) work.
I tested the changes with Developer Tools, so everything should be good to go. …
> bug 1441210: Fix checkbox labels in Edit Profile

- requirements/default.txt
* Django 1.8.18 → 1.8.19: [Security release](https://www.djangoproject.com/weblog/2018/mar/06/security-releases/), mitigate denial-of-service attacks against catastrophic backtracking vulnerability in regular expressions. One of the affected functions (``truncatechars``) is used in the Django admin.
> bug 1399639: Upgrade to Django 1.8.19

- docker/images/kumascript/Dockerfile
Kumascript node.js engine version has been upgraded to 8.9.4 this
changes needs to be reflected in the docker image we use.
> bug 1413523: Upgrade node.js in our KS image to 8.10.0

- kuma/wiki/forms.py
- kuma/wiki/tests/test_views.py
- kuma/wiki/tests/test_views_akismet.py
- kuma/wiki/tests/test_views_code.py
- kuma/wiki/views/akismet_revision.py
- kuma/wiki/views/code.py
- kuma/wiki/views/legacy.py
This is another in a series of PR's that add the appropriate caching headers and related tests to all Kuma endpoints as part of the effort of placing a CDN in front of MDN. This PR adds/modifies caching headers and tests for the endpoints for the kuma wiki views in `akismet_revision.py`, `code.py`, and `legacy.py`.
- This PR replaces the old-style `AkismetRevisionTests` in `kuma/wiki/tests/test_views.py` with new pytest-style tests in `kuma/wiki/tests/test_views_akismet.py`. As part of that effort, I realized that the existing `AkismetRevisionTests.test_submit_akismet_spam_revision_dne` test was flawed. It did not actually test the case it was intended to test (making an Akismet submission on a non-existent revision). Deep within the form's `clean` method, the Akismet key verification …
> bug 1431259: caching headers/tests for wiki code/legacy/akismet views

- kuma/core/middleware.py
The current settings for Brotli compression level is too high and it's
increasing our average page load time as a side effect.
This patch put the compression level at a more reasonnable level to
lower the tradeoff.
> bug 1412891: Adjust Brotli compression level

- kuma/wiki/tests/test_templates.py
This test was passing when the xfail tag was added in PR #3757. It is unknown when it started passing.
> bug 1054271: Remove xfail from passing test

- kuma/core/tests/test_urlresolvers.py
- kuma/settings/common.py
Ensure (with tests) that:
* ``LOCALE_ALIASES`` is a map of alias locales to accepted locales
* ``RTL_LANGUAGES`` is a list of right-to-left languages in accepted locales
I'm not sure if these should be verified with a unit test, or with ``assert`` in the ``settings.py`` file.
There is an xfail test for Norwegian locales that was copied from [mozilla/kitsune](https://github.com/mozilla/kitsune) in PR #930, including some extra settings that do not apply to MDN. This test is removed.
> bug 1054271: Cleanup locale settings

- kuma/wiki/tests/test_templates.py
- kuma/wiki/tests/test_views.py
- kuma/wiki/views/translate.py
This is another in a series of PR's that add the appropriate caching headers and related tests to all Kuma endpoints as part of the effort of placing a CDN in front of MDN. This PR adds/modifies caching headers and tests for the endpoints for the kuma wiki translate views.
> bug 1431259: caching headers/tests for wiki translate views

- kuma/wiki/tests/test_templates.py
- kuma/wiki/tests/test_views.py
- kuma/wiki/tests/test_views_revision.py
- kuma/wiki/views/revision.py
This is another in a series of PR's that add the appropriate caching headers and related tests to all Kuma endpoints as part of the effort of placing a CDN in front of MDN. This PR adds/modifies caching headers and tests for the endpoints for the kuma wiki revision views.
> bug 1431259: caching headers/tests for wiki revision views

- kuma/core/views.py
- kuma/wiki/constants.py
- kuma/wiki/forms.py
- kuma/wiki/middleware.py
- kuma/wiki/tests/test_templates.py
- kuma/wiki/tests/test_views.py
- kuma/wiki/tests/test_views_code.py
- kuma/wiki/tests/test_views_create.py
- kuma/wiki/tests/test_views_delete.py
- kuma/wiki/tests/test_views_edit.py
- kuma/wiki/tests/test_views_translate.py
- kuma/wiki/urls.py
- kuma/wiki/views/create.py
- kuma/wiki/views/delete.py
- kuma/wiki/views/edit.py
This is another in a series of PR's that add the appropriate caching headers and related tests to all Kuma endpoints as part of the effort of placing a CDN in front of MDN. This PR adds/modifies caching headers and tests for the endpoints for the kuma wiki create/edit/delete views.
I made the mistake of trying to convert all of the tests for the `wiki.create` endpoint. In the end, I did convert many of them, but it's way too much and slowed down this PR considerably. Future CDN PR's will only create new-style tests if there are none for an endpoint. I could have easily converted the `test_parent_topic` test within the hated `kuma/wiki/tests/test_views.py`, but it didn't seem worthwhile to preserve as a test, since the whole approach of using `parent_topic` in the POST data (instead of …
> bug 1431259: caching headers/tests for wiki create/edit/delete views

- kuma/core/tests/test_views.py
- kuma/core/views.py
- kuma/version/tests/test_views.py
- kuma/version/views.py
This is another in a series of PR's that add the appropriate caching headers and related tests to all Kuma endpoints as part of the effort of placing a CDN in front of MDN. This PR adds/modifies caching headers and tests for the endpoints for the kuma version/set-language view.
> bug 1431259: caching headers/tests for version/set-language views

- kuma/attachments/tests/test_views.py
- kuma/wiki/tests/test_feeds.py
- kuma/wiki/urls.py
This is another in a series of PR's that add the appropriate caching headers and related tests to all Kuma endpoints as part of the effort of placing a CDN in front of MDN. This PR adds/modifies caching headers and tests for the endpoints for the kuma wiki feeds views.
> bug 1431259: caching headers/tests for wiki feeds views

- kuma/wiki/admin.py
- kuma/wiki/tests/test_views_admin.py
This PR depends on https://github.com/mozilla/kuma/pull/4701 for it's tests to pass.
This is another in a series of PR's that add the appropriate caching headers and related tests to all Kuma endpoints as part of the effort of placing a CDN in front of MDN. This PR adds/modifies caching headers and tests for the endpoints for the kuma wiki admin bulk-purge view.
> bug 1431259: caching headers/tests for purge view

- docker-compose.yml
Updates docker-compose.yml to set innodb_log_file_size to
100 megabytes, in order to ensure that it's at least 10x
the maximum size of BLOB/TEXT data in any one transaction,
per MySQL 5.6.20 release notes [1]. See bug 1447446 for
more information.
Resolves issues importing the anonymized database, and
probably random database errors that may occur when
dealing with very large transactions.
[1]  https://is.gd/wvSZzV
> Bug 1447446: Increase InnoDB log file size

- kuma/authkeys/tests/test_views.py
- kuma/core/tests/test_views.py
- kuma/urls.py
- kuma/users/tests/test_tasks.py
- kuma/users/tests/test_templates.py
- kuma/users/tests/test_views.py
- requirements/default.txt
This PR depends on #4701 for it's tests to pass.
This is another in a series of PR's that add the appropriate caching headers and related tests to all Kuma endpoints as part of the effort of placing a CDN in front of MDN. This PR adds/modifies caching headers and tests for various endpoints within kuma (e.g., `kuma.users.urls`).
It adds and uses a new dependency `django-decorator-include`, which provides the ability to decorate all views within an include tree. The version used is [1.3](https://pypi.python.org/pypi/django-decorator-include/1.3), which is the proper version to use with Django 1.8, but version [1.4.1](https://pypi.python.org/pypi/django-decorator-include/1.4.1) should be used when moving to Django 1.11.
> bug 1431259: caching headers/tests for various views

- kuma/wiki/tests/test_templates.py
- kuma/wiki/tests/test_views.py
- kuma/wiki/tests/test_views_document.py
- kuma/wiki/views/document.py
This PR depends on #4701 for it's tests to pass.
This is the last in a series of PR's that add the appropriate caching headers and related tests to all Kuma endpoints as part of the effort of placing a CDN in front of MDN. This PR adds/modifies caching headers and tests for the views within `kuma/wiki/views/document.py`.
> bug 1431259: caching headers/tests for wiki document views

- kuma/static/js/dashboard.js
To test this, I load up the initial activity history page, I then use the network panel in devtools to emulate offline mode. Click to go to the next page of results, you should now see an error shown in the Growl message instead of 'Updating filter.....'
> Fix Bug 1440908, show error message to users on 500 internal server error

- kuma/attachments/management/commands/empty_attachments_trash.py
- kuma/feeder/management/commands/update_feeds.py
- kuma/humans/management/commands/make_humans.py
- kuma/wiki/management/commands/make_sitemaps.py
- kuma/wiki/management/commands/populate_attachments.py
- requirements/constraints.txt
- requirements/default.txt
The management command class ``NoArgsCommand`` was [deprecated](https://docs.djangoproject.com/en/1.11/releases/1.8/#django-core-management-noargscommand) in Django 1.8, and removed in 1.10.  ``BaseCommand`` now takes no arguments by default, and acts as a replacement.
``NoArgsCommand`` was used by some libraries as well (grepped in the docker image to find them all), so there are some package updates for ``django-statici18n`` and ``django-extensions``, as well as their requirements ``django-appconf`` and ``typing``.
With this change, the "next" build gets to the point where [unit tests run](https://travis-ci.org/mozilla/kuma/jobs/359595579) (with many failures)
> bug 1429933: Migrate NoArgsCommand to BaseCommand

- kuma/wiki/jinja2/wiki/list/revisions.html
Here's a fix for hard-coded (non-translatable via pontoon.mozilla.org) strings on article history page.
Please have a look.
> Replaced hard-coded strings with translatable ones

- kuma/core/tests/test_views.py
- kuma/settings/common.py
Increase the max-age of the language preference cookie to one
year instead of only the current session.
This avoids to ask if people wants to keep their current locale
at each of their visits.
> bug 1443586: Make lang preference cookie persistent

- requirements/default.txt
Updates `django-constance` to version 2.2.0 which fixes a bug where the Constance configuration could not be modified/saved via the admin console (it would fail with a `CONSTANCE_CONFIG_FIELDSETS does not contain fields that exist in CONSTANCE_CONFIG.` error).
The fix was verified in my local dev environment (by first doing a `VERSION=latest make build-base`).
> bug 1449354: update django-constance from 2.1.0 to  2.2.0
