mdn/kuma

media/redesign/stylus/dashboards.styl
=> Fix bug 1115738 again: Select only outer cells

apps/authkeys/templates/authkeys/base.html, kuma/demos/templates/demos/detail.html, kuma/users/templates/socialaccount/signup.html, kuma/users/templates/users/profile.html, kuma/users/templates/users/profile_edit.html, kuma/users/tests/test_views.py, media/redesign/stylus/base/utilities.styl, media/redesign/stylus/components/components.styl, media/redesign/stylus/components/content.styl, media/redesign/stylus/components/demos/gallery-foot.styl, media/redesign/stylus/components/newsletter.styl, media/redesign/stylus/components/option-list.styl, media/redesign/stylus/components/profile/docs-activity.styl, media/redesign/stylus/components/profile/profile-edit.styl, media/redesign/stylus/components/profile/profile-head.styl, media/redesign/stylus/components/profile/profile-links.styl, media/redesign/stylus/components/profile/profile-newsletter-container.styl, media/redesign/stylus/components/profile/profile-photo.styl, media/redesign/stylus/components/profile/profile-section.styl, media/redesign/stylus/components/profile/profile-tags.styl, media/redesign/stylus/components/profile/profile-title.styl, media/redesign/stylus/components/profile/vars.styl, media/redesign/stylus/includes/mixins.styl, media/redesign/stylus/newsletter.styl, media/redesign/stylus/profile.styl, media/redesign/stylus/submission.styl
Depends on #2965.
- Mostly extracting components into individual files.
- Renamed classes to make them more modular.
- Changed profile display and edit pages to use column classes.
=> Bug 1070001 reorg profile

.gitmodules, apps/actioncounters/fields.py, requirements/prod.txt, vendor/kuma.pth
=> Fix bug 1121077 - Remove leftovers from django-cache-machine.

kuma/wiki/templates/wiki/confirm_document_delete.html, kuma/wiki/templates/wiki/document_revisions.html
According to https://github.com/mozilla/kuma/pull/3001#issuecomment-70185695.
=> Simplified title link generation

media/redesign/js/wiki.js
Fix link to CSS syntax article.
=> Fix Bug 1119010 - Link to CSS Syntax

.coveragerc, .travis.yml
Also prints the coverage report on Travis-CI.
=> Bug 756533 - Simplified test command for Travis.

kuma/users/templates/users/profile.html
Changed if statement that displays ban button to use same permission check that generates the ban button.
=> Fix Bug 1122997 - Ban user button display

media/redesign/js/wiki.js
=> Fix bug 1125295: Remove sticky A/B test activation

kuma/wiki/tasks.py
This is to work around a traceback:
```
======================================================================
ERROR: test_render_stale (kuma.wiki.tests.test_models.RenderExpiresTests)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/travis/build/mozilla/kuma/kuma/core/tests/__init__.py", line 60, in inner
return func(*args, **kwargs)
File "/home/travis/build/mozilla/kuma/vendor/packages/mock/mock.py", line 196, in patched
return func(*args, **keywargs)
File "/home/travis/build/mozilla/kuma/kuma/wiki/tests/test_models.py", line 1147, in test_render_stale
tasks.render_stale_documents()
File "/home/travis/build/mozilla/kuma/vendor/src/celery/celery/app/task.py", line 420, in __call__
return self.run(*args, **kwargs)
File …
```
=> Bug 1125850 - Explicitly use a task group for the header part of the chord.

kuma/core/utils.py, kuma/search/admin.py, kuma/search/management/commands/reindex.py, kuma/search/models.py, kuma/search/tasks.py, kuma/search/tests/__init__.py, kuma/search/tests/test_indexes.py, kuma/search/utils.py, kuma/wiki/search.py, kuma/wiki/tasks.py
This updates reindexing to parallelize the indexing tasks. It also updates the tests a little since a few failed when I did this.
I'm not sure if there's a pre-existing bug this should go to?
=> Fixes bug 1130378 - Faster reindexing

kuma/wiki/tasks.py, kuma/wiki/templates/wiki/sitemap.xml
That also reduces the risk of memory leakage when building all sitemaps.
=> Bug 1125850 - Use lxml to render sitemap XML.

kuma/landing/templates/landing/fellowship.html
Changed application deadline from March 31 to April 1.
Changed orientation to TBD.
=> Bug 1125683: Update deadline and orientation

media/redesign/stylus/components/wiki/customcss.styl
Matching .spec-CR except for letters.
=> Fix Bug 1139883: New styles for .spec-RC

kuma/landing/templates/landing/fellowship.html
=> Fix Bug 1126583: Reorder Fellowship

scripts/travis-install
See https://github.com/travis-ci/travis-ci/issues/3394#issuecomment-82483124
=> bug 1144213 - use curl to get elasticsearch

.travis.yml, requirements/dev.txt
Following the ideas in https://github.com/pypa/warehouse/blob/master/.travis.yml
=> Build wheel files on Travis and cache them.

.travis.yml
1.9.1 bug: https://bitbucket.org/hpk42/tox/issue/230/tox-191-ignores-package-versions-specified
=> bug 1144213 - pin tox version 1.9.0 for travis

docs/index.rst, docs/installation-vagrant.rst, docs/troubleshooting.rst, docs/ui-tests.rst
fix ui-tests headings
move badge below install instructions
=> bug 957802 - add Troubleshooting doc

kuma/users/models.py, kuma/users/tests/test_tasks.py, media/js/main.js
Supersedes https://github.com/mozilla/kuma/pull/3122 with a test fix.
=> fix bug 1060633 using django messaging framework and mdn notification system

kuma/wiki/templates/wiki/list_documents.html, kuma/wiki/templates/wiki/list_documents_for_review.html, kuma/wiki/templates/wiki/list_documents_with_localization_tags.html, media/stylus/components/structure.styl
Easy enough.  The double-bottom-spacing I created is eye-pleasing but I didn't use any science.
=> fix bug 886016 - Add pagination to the top and bottom of list pages

docs/installation-vagrant.rst, docs/troubleshooting.rst
Supersedes https://github.com/mozilla/kuma/pull/3154 with commit messages and more fixes.
=> bug 957802 - install docs cleanups

media/js/main.js
Does the same thing but the code is prettier.
=> bug 1050991 - Use more JS-like notification code

kuma/wiki/models.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1148820
=> Fix bug 1148820: Properly get the summary for translations in jsons

kuma/wiki/templates/wiki/move_document.html, media/stylus/components/wiki/edit/move-page-rules.styl, media/stylus/wiki-edit.styl
Supercedes https://github.com/mozilla/kuma/pull/3176
=> Move slug trailing slash 1145580

kuma/wiki/templates/wiki/revision.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1155300
=> fix bug 1155300 - Open revision content by default

settings.py
Spot-check on this branch:
1. [Get the localizations](http://kuma.readthedocs.org/en/latest/localization.html#get-localizations) if you don't already have them.
2.
```
cd locale
svn up
./compile-mo.sh .
```
3. Go to https://developer-local.allizom.org/ff/ and make sure it pulls up.
4. Translate a test document into Pulaar-Fulfulde
=> fix bug 1146711 - add Fulah to MDN

kuma/wiki/templates/wiki/ckeditor_config.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1157161
=> Fix bug 1157161: Add summary class to p instead of a creating a wrapping div

kuma/wiki/templates/wiki/includes/document_macros.html, tests/ui/_cli.js, tests/ui/tests/header.js, tests/ui/tests/lib/POM.js, tests/ui/tests/lib/config.js, tests/ui/tests/lib/login.js, tests/ui/tests/wiki.js
Adds testing for edit and translate screens, ensuring CKEditor loads
=> bug 1152386 - Adding tests for new, edit, and translate within the wiki

kuma/landing/templates/landing/homepage.html, kuma/search/serializers.py, kuma/search/tests/test_serializers.py, media/js/search-suggestions.js, media/stylus/base/elements/forms.styl, media/stylus/components/demos/buttons.styl, media/stylus/components/wiki/customcss.styl, media/stylus/home.styl, media/stylus/includes/vars.styl, media/stylus/search-suggestions.styl, media/stylus/zones.styl
=> Search filter improvements

tests/ui/tests/demos.js, tests/ui/tests/env.js, tests/ui/tests/header.js, tests/ui/tests/homepage.js, tests/ui/tests/lib/config.js
This will be a running PR, with several commits, which can be periodically merged.
=> Improve Intern Tests

templates/base.html
https://twitter.com/MozDevNet/status/596772683171246080
=> Rename @NewOnMDN to @MozDevNet

kuma/wiki/templates/wiki/document.html, kuma/wiki/templates/wiki/edit_document.html, kuma/wiki/templates/wiki/revision.html, kuma/wiki/templates/wiki/translate.html
https://bugzilla.mozilla.org/show_bug.cgi?id=859398
=> Fix bug 859398: Sort tag list alphabetically

docs/celery.rst
These commands need to be run as root.
=> Bug 1156930: Update rabbitmqctl commands in docs

media/js/analytics.js, media/js/wiki.js, templates/404.html
Better event tracking per @groovecoder
=> fix bug 1164032 - Update method for tracking errors

media/js/fonts.js
Reorganized the file:
-  Entire block was in one `if` statement; should avoid that with a simple `return`
-  Hoisted vars up
-  Moved main work block (starting with `getScript`) up to the top
=> bug 1150118 - JavaScript code quality updates

docs/tests-ui.rst, tests/ui/_cli.js, tests/ui/tests/fixtures/in-content.html, tests/ui/tests/lib/config.js, tests/ui/tests/lib/login.js, tests/ui/tests/wiki.js
Simply PR'ing this so WebQA can look.
=> Intern stability 1152386

tests/ui/tests/auth.js, tests/ui/tests/demos.js, tests/ui/tests/homepage.js
These helped me debug the intern tests on my local box while I was running them against the django 1.7 branch.
=> bug 1152386 - more descriptive test messages

docs/tests-ui.rst
Now that our options list has grown, it's probably better to lay it out as a ... list
=> fix bug 1171042 - Update the display of test options in the docs

.travis.yml
Following http://docs.travis-ci.com/user/caching/#Enabling-multiple-caching-features.
That should speed up our Travis runs.
=> Bug 1116335 - Fixed syntax in Travis config.

docs/installation.rst
Added dnf / yum installation step for Ansible for Fedora/RPM based distro
=> Add Fedora/RPM instruction for Ansible

kuma/wiki/content.py
To fix errors: https://rpm.newrelic.com/accounts/263620/applications/3172075/traced_errors/3066ef-1d471519-153e-11e5-9387-f8bc124250a8
=> fix bug 1175681 - use unicode format string

docs/feature-toggles.rst, docs/installation.rst, kuma/demos/templates/demos/home.html, kuma/demos/templates/demos/terms.html, kuma/landing/templates/landing/homepage.html, kuma/users/templates/socialaccount/snippets/provider_list.html, kuma/users/templates/users/profile.html, kuma/users/templates/users/profile_edit.html, media/js/fonts.js, media/js/main.js, templates/base.html, templates/includes/login.html, tests/ui/tests/auth.js
Makes a number of waffled features permanent:
* GitHub login
* Firefox 10th anniversary demo style
* Derby closed
* GA outbound link tracking
* Web font loader
=> bug 1136741 - Clean out waffle flags

kuma/wiki/helpers.py, kuma/wiki/templates/wiki/document.html
Some tweaks to document.html logic based on [New Relic profiling data](https://rpm.newrelic.com/accounts/263620/applications/3172075/profiles/1706748).
=> bug 1177264 - Optimize (some more) of document.html rendering

kuma/wiki/feeds.py, kuma/wiki/models.py
This is along the lines of #3245.
=> Bug 1169673 - Lower complexity for DocumentsFeed feeds.

kuma/users/templates/socialaccount/snippets/provider_list.html, kuma/users/tests/test_views.py, media/stylus/components/structure.styl
instead of an underscore.
Test:
- connect accounts page
- new account creation
=> Bug 1070001: Change socialaccount-providers to have a dash

kuma/core/jobs.py, kuma/core/tests/test_jobs.py, kuma/users/helpers.py, kuma/users/models.py, kuma/users/tests/test_helpers.py, kuma/wiki/feeds.py, kuma/wiki/jobs.py, kuma/wiki/models.py, kuma/wiki/templates/wiki/document.html, kuma/wiki/templates/wiki/includes/document_macros.html, kuma/wiki/tests/test_jobs.py, kuma/wiki/tests/test_models.py
This should reduce the amount spent in Python a bunch.
=> Bug 1177798 - Only cache a dictionary of user data instead of full ORM objects.

kuma/users/templates/users/profile.html, kuma/wiki/templates/wiki/includes/document_macros.html, media/js/components.js, media/js/main.js, templates/base.html, templates/includes/login.html
Added js-submenu class to all submenus, tweaked javascript to look for this class.
Testing:
- main nav menus
- language & advanced
- in-page search results navigation
- profile page manage menu
=> Bug 815693: Change submenu config to rely on js-submenu class.

settings.py
This reverts commit b2ec1b4595764bd5a6d6523b80f99a46e59b08c6.
=> Revert "Bug 1177264 - Use memcache for django-product-details."

media/js/auth.js, media/stylus/components/structure.styl, templates/includes/login.html
Decoupling the log in picker from the .submenu class since I have other plans for that class.
=> Bug 815693: Log in picker not rely on submenu class

kuma/users/models.py, kuma/users/tests/test_models.py
Supersedes https://github.com/mozilla/kuma/pull/3237 with test.
=> bug 1120821 - Accept more Linkedin profile url variations

templates/base.html
Follow-up to improve the UX to correctly jump to the section anchor.
=> bug 1173122 - en-US license link for better ux

media/js/wiki-samples.js
No need to hold onto these forms when we've posted to the other site, so we can do some cleanup.
=> Bug 1148743 - Do cleanup on generated forms

kuma/search/jobs.py
That should reduce the db queries a notch.
=> Bug 1177264 - Cache the available search filters much longer.

media/stylus/components/mdn10/chapter.styl, media/stylus/mdn10.styl, settings.py
Styles for the timeline (on the history page, on staging) & minification for the css.
=> Bug 1185627: MDN 10th - timeline styles

media/js/wiki-samples.js
This:
-  More reliably gets sample contents 
-  Prevents duplicated "Open in..." buttons for tables.
Can copy this content to test:  https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Drawing_DOM_objects_into_a_canvas
=> Bug 1187363 - "Open in CodePen" option issues

docs/tests-ui.rst, tests/ui/_base.js, tests/ui/_tests.js, tests/ui/tests/auth.js, tests/ui/tests/footer.js, tests/ui/tests/header.js, tests/ui/tests/homepage.js, tests/ui/tests/lib/POM.js, tests/ui/tests/lib/assert.js, tests/ui/tests/lib/config.js, tests/ui/tests/lib/login.js, tests/ui/tests/lib/poll.js, tests/ui/tests/wiki.js
-  A few auth tests fail because we've updated CSS classnames - fixed
-  Updated spelling error :/
-  Using `findByCssSelector`for consistency
=> bug 1184662 - Update profile-related selectors to match current site, make Persona login more reliable

media/js/wiki-samples.js
=> bug 1148743 - Enable JSFiddle

docs/tests-ui.rst
Since intern just upgraded, we should tell people to use the version we've been developing on
=> Bug 1184662 - Update Intern docs to include intern version

tests/ui/tests/auth.js, tests/ui/tests/env.js, tests/ui/tests/footer.js, tests/ui/tests/header.js, tests/ui/tests/homepage.js, tests/ui/tests/wiki.js
- `assert.isTrue(true, ` is kinda lame, switching to `ok`
- removing some `goBack` calls we don't need.
=> bug 1184662 - Some test cleanup

media/stylus/components/home/home-demos.styl
https://bugzilla.mozilla.org/show_bug.cgi?id=1193315
=> Fix bug 1193315 - Prevent 404 on grabbing image

media/js/wiki-compat-tables.js
Increasing animation speed so tables look better.
=> bug 1170235 - Increase animation speed of compat tables

kuma/wiki/constants.py, kuma/wiki/forms.py, kuma/wiki/templates/wiki/move_document.html, kuma/wiki/tests/test_views.py, kuma/wiki/urls.py, kuma/wiki/views.py
That includes adding the percentage sign to it.
=> Bug 1187645 - Refactored check for invalid slug characters.

kuma/demos/templates/demos/base.html, kuma/demos/templates/demos/base_popup.html, kuma/landing/templates/landing/fellowship.html, kuma/search/templates/search/base.html, kuma/users/templates/socialaccount/signup.html, kuma/users/templates/users/user_detail.html, kuma/users/templates/users/user_edit.html, kuma/wiki/templates/wiki/base.html, kuma/wiki/templates/wiki/document.html, media/js/components.js, media/js/users.js, media/js/wiki.js, settings.py
A few more resources which are standalone and can be async.
=> Make newsletter and users resources async

provisioning/roles/kuma/tasks/django.yml
Fixes [assets issue that @a2sheppy mentioned on dev-mdn](https://groups.google.com/d/msg/mozilla.dev.mdn/7rlsYEYuTBk/UgonlwmmAwAJ).
=> bug 957802 - add compilejsi18n to provisioning

kuma/landing/templates/landing/homepage.html, kuma/search/templates/search/results.html, media/stylus/components/home/home-masthead.styl, media/stylus/includes/mixins.styl, media/stylus/search-suggestions.styl, media/stylus/search.styl
Please let me know if I have missed something; this is my first time contributing. 
Thanks!
=> Bug 1182341: Search UI, Identify search field with a magnifying icon at start of field

kuma/users/templates/users/user_edit.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1195366
=> fix bug 1195366 - Launch person from edit interface

media/stylus/base/elements/forms.styl
https://bugzilla.mozilla.org/show_bug.cgi?id=1194308
=> fix bug 1194308 - Prevent Wrapping of code buttons

media/js/auth.js, media/js/fellowship.js
Just some cleanup I thought I could do.
=> bug 1055078 - Fellowship and auth cleanup

kuma/users/migrations/0004_auto_20150722_1243.py
Commit 874db113 changed profile.misc to a nullable TextField, so JSONField could be removed. This changes the follow-on commit to manually load the JSON string.
=> bug 1180208 - Manually load JSON in migration 0004

media/js/wiki.js, media/stylus/components/wiki/contributor-avatars.styl
https://bugzilla.mozilla.org/show_bug.cgi?id=1201594
=> fix bug 1201594 - Hide contributor bar on mobile

kuma/wiki/tasks.py
Not my favorite way to brush this under the rug, but we're getting too many of these errors and emails.
=> bug 1174209 - catch, log, and retry DNE exceptions

media/stylus/components/structure/main-nav.styl
https://bugzilla.mozilla.org/show_bug.cgi?id=1201251
=> fix bug 1201251 - Ensure nav stays on screen on small devices

media/stylus/base/elements/sectioning.styl
https://bugzilla.mozilla.org/show_bug.cgi?id=1201584
=> fix bug 1201584 - Make footer links larger tap targets

media/js/wiki-samples.js, media/stylus/base/elements/forms.styl, media/stylus/components/wiki/open-in-host.styl, media/stylus/wiki.styl
https://bugzilla.mozilla.org/show_bug.cgi?id=1201604
=> fix bug 1201604 - Hide CodePen and Stylus buttons upon print

media/js/syntax-prism.js
Sample doc html;  https://gist.github.com/darkwing/c395a73fbfcb1cc650c8
=> fix bug 1203230 - Don't re-prism the prisms

kuma/dashboards/templates/dashboards/includes/revision_dashboard_body.html, kuma/dashboards/views.py
=> Bug 1203403 - Revert commit aad6fce

media/stylus/base/elements/sectioning.styl, media/stylus/components/structure.styl, media/stylus/components/structure/contentinfo.styl, templates/base.html
Line height for vertical spacing. Grammatical corrections to footer text.
Border to separate footer from content starting at tablet size when width no longer does it.
=> Fix Bug 1201584 - footer links

README.rst
Emphasize the contribution guide as the starting point for new contribs
=> [no bug] - enhance readme

.gitignore, provisioning/roles/kuma/files/apache2/vhosts.conf, static/.htaccess
=> Bug 1197444 expiry

docs/tests-ui.rst, tests/ui/_base.js, tests/ui/intern-browserstack.js, tests/ui/intern-local.js, tests/ui/intern-sauce-labs.js, tests/ui/tests/homepage.js, tests/ui/tests/lib/config.js, tests/ui/tests/lib/login.js, tests/ui/tests/lib/poll.js, tests/ui/tests/wiki.js
Upgrades Intern to 3.0.3, removes old demo/homepage test
=> bug 1197858 - Upgrade intern to 3.0.3

media/stylus/includes/mixins.styl
https://bugzilla.mozilla.org/show_bug.cgi?id=1174320
=> fix bug 1174320 - Prevent duplicate colors within stylus

media/stylus/includes/mixins.styl
=> fix bug 1205750 - Limit precision of REM units

tests/ui/tests/auth.js, tests/ui/tests/dashboards.js, tests/ui/tests/homepage.js, tests/ui/tests/lib/login.js, tests/ui/tests/wiki.js
Now that we have the tests working everywhere, we can now clean them up a bit
=> bug 1184662 - Intern test cleanup

docs/development.rst, provisioning/roles/kuma/files/apache2/vhosts.conf
Testing this pull request:
1. `rm -rf static/img`
2. Verify that images *do not* appear
3. `vagrant provison`
4. Verify that images *do* appear
=> Bug 1197444: Fix display of images locally

contribute.json
Noticed this file needed some updating.
=> fix bug 1209045 - Update contributors.json to reflect current team

kuma/static/stylus/components/wiki/properties.styl, kuma/static/stylus/wiki.styl
Added new general class for the writers to transition all other instances too.
=> Fix Bug 1207335 - Standardize summary-box code

kuma/static/js/helpfulness.js
2 new options for "What would make it better?".
Do not ask more than once per day.
Should address all concerns from #3515.
=> Bug 1032455: Tweaks to helpfulness

kuma/static/stylus/components/wiki/properties.styl
=> Bug 1212752: Remove .audionodebox class

kuma/static/js/wiki-compat-tables.js, kuma/static/js/wiki.js
Border-bottom should be added to appropriate cells at appropriate times again.
=> Big 1206309 - Fix cell opening.

tests/ui/_cli.js, tests/ui/tests/dashboards.js, tests/ui/tests/lib/config.js
Got more complicated than I wanted but got there in the end.
=> bug 1184670 - Don't allow admin tests on prod

kuma/static/js/wiki-compat-tables.js, kuma/static/stylus/components/compat-tables/bc-history.styl, kuma/static/stylus/components/compat-tables/bc-table.styl
Remove CSS transitions from elements, set speed of javascript transition to something less stressful.
=> Bug 1206309: Remove CSS transitions

.gitmodules, kuma/core/middleware.py, kuma/core/tests/__init__.py, kuma/demos/tests/test_models.py, kuma/landing/test_templates.py, kuma/users/migrations/0004_auto_20150722_1243.py, kuma/wiki/content.py, kuma/wiki/feeds.py, kuma/wiki/forms.py, kuma/wiki/kumascript.py, kuma/wiki/migrations/0002_auto_20150430_0805.py, kuma/wiki/migrations/0004_remove_document_team.py, kuma/wiki/migrations/0005_delete_teamwork_contenttypes.py, kuma/wiki/migrations/0007_update_locale_fields.py, kuma/wiki/models.py, kuma/wiki/search.py, kuma/wiki/tests/test_forms.py, kuma/wiki/tests/test_models.py, kuma/wiki/tests/test_templates.py, kuma/wiki/tests/test_views.py, kuma/wiki/views/utils.py, requirements/source.txt
This contains the first original cleanup commits from #3482
=> Some cleanup commits from #3482.

tests/ui/tests/fixtures/in-content.html
Per @Elchi3 's request:  https://bugzilla.mozilla.org/show_bug.cgi?id=1212767
=> bug 1212767 - Update test fixture CSS class

scripts/chief_deploy.py
The stylus and cleancss node commands are symlinked to /usr/local/bin on admin.  This allows ./manage.py collectstatic to compile stylesheets on deploys.
=> Add /usr/local/bin to PATH on admin

kuma/static/js/wiki-compat-tables.js, kuma/static/styles/components/compat-tables/bc-history-link.styl, kuma/static/styles/components/compat-tables/bc-history.styl
{{embedCompatTable('web-css-display')}} will give you a table with history drop downs.
Corresponding change to kumascript macro: https://gist.github.com/stephaniehobson/0d0955e02533e040ba7c
=> Bug 1206309: Display tweaks for history drop downs.

kuma/static/styles/components/content.styl
Test pages: https://developer.mozilla.org/en-US/search?locale=en-US&css_classnames=callout-box
=> Bug 1217513: Made .callout-box more RTL and mobile friendly

provisioning/roles/kuma/files/vagrant/settings_local.py, settings.py
=> Bug 1139490: Use sourcemaps in DEBUG mode

kuma/static/js/wiki-compat-tables.js, kuma/static/styles/components/compat-tables/bc-beta.styl, kuma/static/styles/wiki-compat-tables.styl
Add a menu with options: more about beta, take survey, see old tables, report an error.
=> Bug 1206309: Add a feedback mechanism for compat tables

locale/bn_BD/LC_MESSAGES/django.po, locale/de/LC_MESSAGES/django.po, locale/fy/LC_MESSAGES/django.po, locale/it/LC_MESSAGES/django.po, locale/sl/LC_MESSAGES/django.po, locale/sq/LC_MESSAGES/django.po, locale/zh_CN/LC_MESSAGES/django.po, locale/zh_TW/LC_MESSAGES/django.po
This fixes some broken .po files found using dennis linting. There is one that is still broke that revealed a bug in dennis that is already fixed on master.
=> Fix broken .po files

kuma/static/js/analytics.js, kuma/static/js/wiki.js
Separating the data to allow more sort options.
=> Fix Bug 1218466: Update javascript, ajax, and youtube trackError calls.

kuma/static/js/helpfulness.js
Extend waiting period to ask again to 7 days. Move setting localStorage variables earlier in the file so asking again is not contingent on their answer. Track waiting period for helpfulness and articles using same technique.
=> Bug 1032455: Helpfulness - extend wait

kuma/static/js/wiki-edit.js
The checking now is prone to race conditions so we need to just simplify it.
=> fix bug 1221750 - Simplify dirtiness checking

scripts/chief_deploy.py
Opening PR for new kumascript branch that includes New Relic monitoring.
We should push this branch to staging before merging so we can verify the New Relic monitoring.
=> fix bug 1005013 - update kumascript submodule

kuma/demos/__init__.py
Need to check all other urls also.
=> bug 654320 - updated html5 video and audio 404 w3 urls

kuma/static/js/wiki-compat-tables.js
compatability -> compatibility
Notified by our nl translator, tonnes.
=> Bug 1206309 - Fix typo in an en-US compatibility string

kuma/static/js/components.js, kuma/static/js/wiki.js, kuma/wiki/templates/wiki/includes/buttons.html, templates/includes/google_analytics.html
Please also test watch/subscription notifications, and verify I didn't break helpfulness notifications with my change.
=> bug 842340 - remove watch_menu waffle flag

kuma/static/styles/components/content.styl
Removed extra spacing from bottom of calloutboxes.
=> Fix Bug 1217513: Calloutbox extra spacing

kuma/static/styles/components/share-link.styl, kuma/static/styles/components/share.styl, kuma/wiki/templates/wiki/document.html, kuma/wiki/templates/wiki/includes/document_macros.html
=> Bug 875062: Move share links to end of article

kuma/wiki/templates/wiki/includes/kumascript_errors.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1230380
=> Fix bug 1230380 - Correct edit template link

kuma/static/js/helpfulness.js
Added a check to make sure we didn't ask in another tabs since they opened the article.
=> Fix Bug 1229425: Helpfulness only ask once

kuma/wiki/tests/test_models.py
I'm not sure if there is a bug for this?
=> Fix heisen test

kuma/static/styles/components/content.styl
Add modifier class to make standard tables full width.
Headsup: update documentation when live.
=> Fix Bug 1228682: Full width standard tables

kuma/static/js/wiki-edit.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1064209
=> Fix bug 1064209: Add date/time info for saved drafts

docs/development.rst
r? @jezdez (please merge if r+)
=> Minor peep doc fixes

kuma/static/styles/components/wiki/communitybox.styl
Fixes this issue:
https://jzdz.me/050t1g3E2h3d
=> Bug 1070001: Correct set-font-size usage

kuma/wsgi.py, tox.ini
We chose to ignore: E731 do not assign a lambda expression, use a def
=> Fixed flake8 errors

kuma/static/js/wiki.js, kuma/static/styles/components/wiki/quick-links.styl, kuma/static/styles/components/wiki/structure.styl, kuma/wiki/jinja2/wiki/document.html
=> Fix Bug 1235075: Remove show/hide toggle

CONTRIBUTING.md, README.rst, docs/development.rst, docs/installation.rst, docs/localization.rst, docs/tests.rst, docs/troubleshooting.rst
Handful of minor docs updates based on my experiences down the mine.
I tried to do minor tweaks rather than rewriting. I think the docs could use some more intensive brushing up, but I didn't want to deal with that right now.
r?
=> Docs updates

docs/installation.rst, kuma/core/management/commands/ihavepower.py, kuma/core/tests/test_commands.py
This adds an ihavepower Django management command for elevating user
accounts to superstaff status to ease development work.
I HAVE POWER!
r?
=> fix bug 1239430: Add ihavepower command

CONTRIBUTING.md, docs/localization.rst
We can't accept translation changes in pull requests. All translation
changes should happen through Pontoon.
These changes make that clearer.
Quick r?
=> Fix bug 1240148: Fix docs regarding translation prs

kuma/wiki/constants.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1239021
=> Fix bug 1239021: Correct ALLOWED_ATTRIBUTES for MathML <mn> element

templates/pipeline/js.jinja
Updates pipeline template to add crossorigin property as recommended by:
https://raygun.io/blog/2015/05/fix-script-error-and-get-the-most-data-possible-from-cross-domain-js-errors/
=> Fix Bug 1228442 - Report errors from CDN served JS files.

kuma/wiki/models.py, kuma/wiki/tests/test_jobs.py, kuma/wiki/tests/test_models.py, kuma/wiki/tests/test_tasks.py, kuma/wiki/tests/test_templates.py, kuma/wiki/tests/test_views.py, kuma/wiki/views/delete.py
Also does:
- add some code comments for easier understanding
- handle database transaction inside model method, not view
- refresh model instance before making revision the current one by resetting ORM object with related info
Seems like a regression from #3483
=> Bug 1209025 - Fix some regressions in the revert view.

bower.json, kuma/static/js/libs/jquery/jquery.js, settings.py
Updated version of jQuery. Re-ordered the users.js package to fix an error I was seeing on the user profile edit page.
=> Fix Bug 1238616: Update to jQuery 2.2

kuma/settings/common.py
If you just built a dev environment and it was pristine and didn't
have any of the product-details files, then you were in a bit of a
pickle because in order to get product-details files, it'd run through
the settings code which required the product-details files which you
didn't have because that's the very thing you were trying to get. Ugh.
This fixes that by moving some code around such that LOCALES and
LANGUAGES get built together (LANGUAGES requires LOCALES anyhow) and
if the product-details files aren't there, it prints a warning and
rolls its eyes, but then returns empty structures. This is ok because
it only happens if there are no product-details files and that should
only be the case if you haven't gotten the product-details, yet.
r?
=> Fix bug 1247447: Fix bootstrapping problem with product-details

scripts/check_anonymize.sql
Add a script check_anonymize.sql that verifies that the data doesn't contain PII. This script needs to be started after anonymize.sql has been applied to the database.
=> Bug 1238933 - Check database sanitization

kuma/settings/common.py, kuma/users/jinja2/socialaccount/signup.html, kuma/users/signup.py, kuma/users/tests/test_views.py, requirements/default.txt
This adds a CAPTCHA to the user registration flow below the "Choose a username" section:
=> Fix bug 1252697 - Add CAPTCHA to user registration flow

kuma/core/templatetags/jinja_helpers.py, kuma/core/tests/test_helpers.py
This basically works around an issue with Babel's locale data that misses formatting
strings sometimes and raises a KeyError. We fall back to English that such cases.
https://bugzilla.mozilla.org/show_bug.cgi?id=1247086
=> Bug 1247086 - Wrap exception when formatting date/time with missing format string.

kuma/dashboards/jinja2/dashboards/includes/revision_dashboard_body.html
=> Bug 1265151 - Missing translation of some strings

jinja2/403.html, jinja2/404.html, kuma/wiki/jinja2/403-create-page.html
Log when a user runs up against the page creation permission denied page.
=> Fix Bug 1269452: Track page create 403

docs/installation.rst, docs/troubleshooting.rst
Same as PR #3856, but with an additional commit for some styling fixes.
=> Linux statd doc update 957802

kuma/static/styles/components/users/user-head.styl, kuma/users/admin.py, kuma/users/forms.py, kuma/users/jinja2/users/user_detail.html, kuma/users/jinja2/users/user_edit.html, kuma/users/tests/test_forms.py, kuma/users/tests/test_views.py
For https://bugzilla.mozilla.org/show_bug.cgi?id=1271499
* Remove About Me (bio) from Profile display/edit pages
* Remove Website URL from Profile display/edit pages
* Adjust tests for these 2 fields being removed from pages
=> New issue 1271499 remove about me

kuma/wiki/jinja2/wiki/list/needs_review.html
For https://bugzilla.mozilla.org/show_bug.cgi?id=882719
Add directions with links specific to editorial/technical review instructions to the review list page.
=> bug 882719 - Technical/Editorial Review Instructions

kuma/core/templatetags/jinja_helpers.py, kuma/core/utils.py, kuma/dashboards/jinja2/dashboards/includes/revision_dashboard_body.html, kuma/dashboards/jinja2/dashboards/revisions.html, kuma/dashboards/tests/test_views.py, kuma/dashboards/urls.py, kuma/dashboards/views.py, kuma/wiki/tests/test_views.py, kuma/wiki/urls.py, kuma/wiki/views/__init__.py, kuma/wiki/views/akismet_revision.py
This will make the spam submission through ajax request. It also fixes the Resubmit Button.
I will fix the test failors and add more tests. till then anyone can test it and let me know if more improvement is needed.
=> [Bug 1268642] Mark spam/ham with one click with ajax

kuma/static/js/wiki-samples.js
=> Fix bug 1265151

kuma/wiki/jinja2/wiki/document.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1279688 
https://www.youtube.com/watch?v=2ZBtPf7FOoM
=> Fix bug 1279688 – search in all topics for macro usage

docs/feature-toggles.rst, kuma/settings/common.py, kuma/wiki/jinja2/wiki/base.html, kuma/wiki/jinja2/wiki/ckeditor_config.js, kuma/wiki/tests/test_templates.py, kuma/wiki/views/document.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1279797
https://www.youtube.com/watch?v=af59U2BRRAU
=> Fix bug 1279797 - Remove CustomCSS

requirements/README.rst, requirements/constraints.txt, requirements/default.txt, requirements/local.txt
Add a comment summarizing how each requirement is used in Kuma. For requirements that are unused, or have a more commonly used variant, add a note to remove it. Move requirements of requirements to ``constraints.txt``. Add a ``README.rst`` for future devs.
The versions have not been updated. That will be done slowly, in separate PRs.
=> bug 1277577 - Rearrange and document requirements

kuma/users/tests/test_templates.py, kuma/users/tests/test_views.py, kuma/users/views.py, kuma/wiki/jinja2/wiki/email/spam_ban.ltxt
Phase 4 of https://bugzilla.mozilla.org/show_bug.cgi?id=1259776
=> Email the spam watch list upon banning a user and cleaning up their mess

kuma/authkeys/decorators.py, kuma/authkeys/tests/test_decorators.py
=> [Bug 1260477] Invalid authorization header raise 500 error

kuma/users/jinja2/users/ban_user_and_cleanup_summary.html, kuma/users/tests/test_views.py, kuma/wiki/jinja2/wiki/email/spam_ban.ltxt
To the ban user and cleanup summary page, and to the email sent to the MDN spam list.
=> Add akismet revision links

kuma/wiki/jinja2/wiki/includes/buttons.html
A very small fix. @jwhitlock r?
=> [Bug 859499] Show locale code with locale name in language button

jinja2/includes/google_analytics.html, kuma/wiki/jinja2/wiki/document.html
Adds survey behind a waffle flag and segments user in GA.
Removes helpfulness, partially so they don't clash and partially because we're adding iPerceptions because helpfulness isn't collecting what we need.
😐
=> Fix Bug 1286541: Add iPerceptions Survey

kuma/static/js/libs/ckeditor/source/build.sh
=> [Bug 1291969] CKEditor build script should use release versions of plugins

CONTRIBUTING.md, Dockerfile, README.rst, contribute.json, docs/ckeditor.rst, docs/feature-toggles.rst, kuma/static/img/embed/README, tests/performance/README.md, tests/ui/README.md
* Update CKEditor documentation with current process
* Switch to readthedocs.io
* Document the iperceptions waffle flag
r? @stephaniehobson
=> bug 957802, 1286541: Documentation updates

kuma/wiki/jinja2/wiki/document.html
Move block of JavaScript into the document head.
=> Fix Bug 1297484

jinja2/base.html, kuma/landing/jinja2/landing/homepage.html
Also fix bug 1295863: remove marketplace from nav
Also fix bug 1219354: add URL to "report content problem"
=> Fix Bug 1260487: Remove obsolete menu items

kuma/wiki/jinja2/wiki/document.html
Copy the improvements from #3926
As it is front end thing, @stephaniehobson r?
=> [Bug 1294908] Improvement in article pages language picker

kuma/static/js/analytics.js
Watch for _blank on links when tracking, open in new tab.
=> Bug 1254630: _blank in nav menus

Dockerfile-base, requirements/README.rst, requirements/dev.txt, requirements/local.txt
=> Refactor dev requirements out of local

kuma/dashboards/jinja2/dashboards/spam.html, kuma/dashboards/utils.py, kuma/static/styles/dashboards.styl
Small changes to improve display of spam dashboard.
Added 'text-content' parent class so inherits wiki table format.
Styled configuration error and processing messages.
=> Bug 1260264: Formating Change For Spam Dashboard

docs/localization.rst
Update the Localization docs for docker
r?
=> [bug 1218563] Update localization doc for docker

docs/elasticsearch.rst
Not many changes needed for Docker, but refreshed the docs anyway:
* Development uses Elasticsearch 1.7, not 1.3
* Remove justification for moving from Google / MySQL search
* Remove value judgements from Admin vs shell methods
=> bug 1218563: Update ElasticSearch docs

.env-dist, Jenkinsfile, Makefile, docker-compose.test.yml, k8s/elasticsearch-rc.yaml, k8s/elasticsearch-svc.yaml, k8s/kumascript-deployment.yaml, k8s/kumascript-svc.yaml, k8s/memcached-rc.yaml, k8s/memcached-svc.yaml, k8s/mysql-deployment.yaml, k8s/mysql-svc.yaml, k8s/redis-rc.yaml, k8s/redis-svc.yaml, kuma/wiki/tests/test_templates.py
WIP. I have this branch running on https://ci.us-west.moz.works/view/MDN/job/mdn_pipeline/ and as of https://ci.us-west.moz.works/view/MDN/job/mdn_pipeline/23/console all existing tests but one are passing, and that one is because I've added the --nomigrations flag to py.test by default when running tests with docker-compose. I have xfailed that test for now, but given that this feature is currently broken in production I'm questioning the value of keeping that test at all.
=> Jenkins pipeline

kuma/wiki/jinja2/wiki/includes/document_macros.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1308300
=> Bug 1308300 - Add a "comment" field above the diff when updating a page 

docs/installation.rst, kuma/core/management/commands/ihavepower.py
It now takes a optional password with the management command. @jwhitlock r?
=> [Bug 1218563] Update ihavepower command to take optional password

kuma/static/styles/components/structure.styl
It's a hack but it's a very targeted hack.
=> Fix Bug 1305178: Hide empty paragraphs

jinja2/base.html
=> Bug 1273028: Escalating Persona shutdown warning.

requirements/default.txt
Django 1.8.15 -> 1.8.16 - Security release
https://www.djangoproject.com/weblog/2016/nov/01/security-releases/
=> bug 1314290: Update to Django 1.8.16

kuma/users/jinja2/account/signup.html
Fix unclosed ``{% if %}`` block in signup template.
=> bug 1273028: Fix template logic

kuma/static/styles/components/newsletter.styl
=> Bug 1310322: Fix thank you message overlapping close button

tests/conftest.py, tests/functional/test_article.py, tests/functional/test_feedback.py, tests/functional/test_home.py, tests/functional/test_language_selector.py, tests/functional/test_notfound.py, tests/functional/test_report.py, tests/functional/test_search.py, tests/pages/article.py, tests/pages/base.py
- Change approach to opening article pages not matching URL_TEMPLATE 
- Add viewport sizes fixture to tests.
- Mark tests that don't require database to run.
- Mark flaky tests 
- Update comments for clarity
=> Bug 1314708: Mark tests requiring database.

kuma/static/js/newsletter.js, kuma/static/styles/components/newsletter.styl, kuma/wiki/jinja2/wiki/document.html
Should be easier to move around the page for A/B tests now.
=> Bug 1310322: Make newsletter code more robust

Dockerfile, Jenkinsfile
=> bug 1218563: Make build-base in Jenkinsfile and chown kuma

kuma/static/styles/components/newsletter.styl
Had some problems with z-index in the A/B tests, this fixes it.
=> Bug 131022: Increase newsletter button z-index.

kuma/wiki/jinja2/wiki/includes/spam_error.html
Here's a draft alternative text. I wasn't sure how to test this, do you have any pointers?
=> Bug 1322788: Reword the spam fiter error to be less discouraging

.travis.yml, Jenkinsfile, docker-compose.test.yml, docker-compose.yml, scripts/docker-compose.travis.yml
Map user to $UID in docker-compose
Update Jenkinsfile syntax to eliminate deprecation warnings
https://ci.us-west.moz.works/view/MDN/job/mdn_multibranch_pipeline/job/fix-compose-test/
=> bug 1218563: fix make compose-test

tests/conftest.py, tests/functional/test_article.py, tests/functional/test_home.py, tests/functional/test_language_selector.py, tests/functional/test_notfound.py, tests/functional/test_report.py, tests/functional/test_search.py, tests/pages/base.py, tests/pages/notfound.py, tests/utils/urls.py
- Check module imports
- Fix spacing
- Add destructive test definition
- Change test names
- Combine tests
=> Bug 1314708: Clean up Tests

CONTRIBUTING.md, README.rst, docs/celery.rst, docs/ckeditor.rst, docs/development.rst, docs/documentation.rst, docs/elasticsearch.rst, docs/feature-toggles.rst, docs/installation-vagrant.rst, docs/installation.rst, docs/localization.rst, docs/tests-performance.rst, docs/tests-ui.rst, docs/tests.rst, docs/troubleshooting.rst, requirements/README.rst
Rebase of #4066, with some small changes. 
Big overhaul of most lists, correcting inconsistencies with the formatting as well as old style titles and headers converting to sentence-style capatalization.
=> bug 957802: Doc - titles and lists standardized

docs/localization.rst
=> bug 1321352: Fix typo

.travis.yml, tox.ini
This fixes the docker build in TravisCI (hopefully).
=> bug 1218563: Pass UID to tox docker build

tests/functional/test_article_edit.py, tests/pages/article.py, tests/pages/article_edit.py, tests/pages/base.py, tests/pages/regions/ckeditor.py
=> Bug 1314708: Add functional tests for edit pages.

tests/functional/test_language_selector.py, tests/pages/article_edit.py, tests/pages/base.py
bug 1330782: fix race condition in functional tests
* fix BasePage.wait_for_page_to_load method
* fix EditPage.wait_for_page_to_load method
* fix BasePage.Header.open_feedback method
=> bug 1330782: fix race condition in functional tests

Dockerfile-base
=> bug 1218563: Update base image to v3.6

docs/development.rst, docs/installation.rst, docs/troubleshooting.rst, gulpfile.js
=> Update docs and remove eslint directive from gulpfile

kuma/settings/testing.py
Complete the report on the effect of pipeline settings on test execution speed from PR #4109.
=> bug 1330838: Complete report on pipeline settings

.env-dist, Dockerfile, Jenkinsfile, Jenkinsfiles/demo-example.yml, Jenkinsfiles/demo.groovy, Makefile
WIP working example: https://mdn-demo.virginia.moz.works/en-US/ deployed by https://ci.us-west.moz.works/view/MDN/job/mdn_multibranch_pipeline/job/demo/16/console
=> Demo deploys to k8s via Jenkinsfile + Deis workflow

kuma/settings/common.py, kuma/static/js/wiki-helpful-survey.js, kuma/static/styles/components/wiki/wiki-helpful-survey.scss, kuma/static/styles/wiki.scss, kuma/wiki/jinja2/wiki/document.html
Adds a survey widget to the bottom of all article pages.
=> bug 1330106: Add "was this helpful?" survey to all articles.

jinja2/base.html, kuma/landing/jinja2/landing/homepage.html
OK, trying this again.
This time, I made sure to only add the template files I modified, with 
git add jinja2/base.html
git add kuma/landing/jinja2/landing/homepage.html
Before committing with git commit -m 'my message'
Does this now work?
=> Learn 1338488

kuma/wiki/jinja2/wiki/document.html
=> Add MM + not-yet-rendered message to wiki pages.

kuma/static/styles/includes/_mixins.scss
=> Fix 'Sign Out' color on zone pages.

kuma/landing/jinja2/landing/homepage.html, kuma/static/styles/components/wiki/promos.scss
Adds `utm_` params to the URL and changes just a *wee* bit of CSS.
Accompanies [kumascript/#137](https://github.com/mozilla/kumascript/pull/137)
=> Update Sauce Labs promo URL.

docs/development.rst, gulpfile.js, kuma/core/pipeline/sass.py, kuma/settings/common.py, kuma/settings/testing.py, npm-shrinkwrap.json, package.json
For local testing, `docker-compose stop`, then `npm install`, then `docker-compose up`. Start `gulp` in a new terminal (in your `kuma` root dir) and that should be that.
Also, ensure `DEBUG=True` in your `.env` file.
=> Use gulp to process .scss files for local dev.

kuma/core/apps.py
I was finding another way to handle candidate language and failed time by time.
So for this time, I think its good enough to fix the broken thing.
@jwhitlock @escattone r?
=> [Bug 1340003] Internal Server Error when translating into a candidate language

requirements/default.txt
Django 1.8.16 -> 1.8.18: Security updates, Oracle DB fix
=> bug 1353410: Upgrade Django

Dockerfile-base
Adding this ahead of the other changes so the environment has it available when the PR that uses it comes.
=> Add stylelint to dockerfile

kuma/static/styles/components/wiki/reviews.scss, kuma/wiki/jinja2/wiki/document.html, kuma/wiki/jinja2/wiki/includes/approvals.html, kuma/wiki/tests/test_views.py
-  Remove banner from top of articles. 
- Enhance sidebar message with links that were previously in the banner.
- Small cosmetic change to sidebar message layout.
- Updated tests
=> Fix Bug 1354620: Remove 'review needed' banners

jinja2/403.html, jinja2/404.html, kuma/users/tests/test_views.py, kuma/users/views.py
This patch will make banned user profile return 404
=> [Bug 1353138] Banned user profiles should 404

requirements/default.txt, requirements/test.txt
=> add deps for django-redirect-urls + tests

kuma/static/styles/zone-addons.scss, kuma/static/styles/zone-apps.scss, kuma/static/styles/zone-ten.scss, kuma/static/styles/zones/base.scss, kuma/static/styles/zones/components/dev-program.scss, kuma/static/styles/zones/components/image.scss
- add base styles to addons
- add mobile breakpoint for .dev-program-callouts
- fix apps logo being too big on landing page
- fix Firefox and Marketplace logos being cut off on landing pages with no subnav
=> Bug  944186: Tweaks to individual zone styles

kuma/static/styles/components/wiki/indicators.scss
In support of https://github.com/mozilla/kumascript/pull/179
=> Adds secureContexts class to indicators

jinja2/base.html, kuma/wiki/jinja2/wiki/ckeditor_config.js, kuma/wiki/jinja2/wiki/sphinx.html
Finish removing traces of last redesign before going onto the next one.
=> Bug 1370594: Redesign cleanup

kuma/wiki/jinja2/wiki/translate.html
Don't need homepage styles on translation edit page.
=> Remove home.css from edit translation page

kuma/static/styles/components/newsletter.scss, kuma/static/styles/components/structure/global-notice.scss, kuma/static/styles/components/wiki/wiki-helpful-survey.scss
Fix bug 1371803.
Fix bug 1294512.
=> Remove soapbox, newsletter, and helpfulness from print

jinja2/base.html, jinja2/includes/redesign_notice.html, kuma/settings/common.py, kuma/static/js/redesign.js, kuma/static/styles/components/redesign.scss, kuma/static/styles/includes/_vars.scss, kuma/static/styles/main.scss
- add beta and launch notices, hidden by default
- add js to show notices on first visit to new design
- depends on a variable added in the header/footer/type PR
=> Bug 1370594: Beta and launch notices

jinja2/base.html, kuma/static/styles/components/structure/login.scss
- update the UTM parameter for the donate link
- remove duplicate code declaration
=> Bug 1370594: UTM link & remove dup

kuma/static/styles/components/newsletter.scss, kuma/static/styles/components/redesign.scss, kuma/static/styles/components/wiki/structure.scss
Added a background colour and adjusted the spacing to not rely on margins.
=> Bug 1370594: Fix newsletter display on zone pages

kuma/static/styles/base/elements/forms.scss
=> Bug 1370594: Textareas get normal font weight.

jinja2/includes/config.html, kuma/settings/common.py
Use the design style in CKEditor, if the user is in the beta program.
=> bug 1271509: Beta style in CKEditor

kuma/static/styles/includes/_vars.scss
Getting lots of feedback on this one.
=> Bug 1370594: Decrease contrast of text color

Jenkinsfiles/demo.groovy, Jenkinsfiles/instance_cleanup.sh, docs/development.rst
for https://github.com/mozmeao/infra/issues/335
=> Move deployments from virginia to portland

kuma/scrape/tests/test_source_links.py, kuma/users/tests/test_templates.py
Fix tests that no longer pass due to the redesign.
=> bug 1370594: Update tests for redesign

kuma/settings/common.py
Update to latest kumascript. Update to latest locales, which included fixing a translation and shipping new strings from removing the blue design.
=> KumaScript, Locale updates

kuma/static/styles/components/wiki/wiki-helpful-survey.scss
=> Bug 1370594: Hide helpfulness when hidden

jinja2/base.html
=> Fix Bug 1384287: Update copyright info

kuma/static/styles/components/wiki/interactive.scss
@stephaniehobson This is not the final solution but, if we can get this onto staging, it will make user testing a lot better all around. Let me know if that is possible. Thanks!
=> Updates sizing of iframes for interactive editor

scripts/chief_deploy.py
Update ping_newrelic to use the v2 API:
https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/recording-deployments
I've manually tested the ``curl`` command, and I'd like to push to staging to confirm it work.
=> bug 1376606: Update to New Relic v2 API

jinja2/base.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1390381
🤷‍♂️
=> bug 1390381: Change default page title to "MDN Web Docs"

docs/deploy-scl3.rst, docs/index.rst
We're adding a pre-push tasks of updating the locales submodule, which gives a good opportunity to document our push proceedures.
=> bug 1385405: Add doc for deploying to SCL3

docs/deploy-scl3.rst
Noticed by @MatonAnthony in IRC #mdndev.
=> bug 1385405: Correct URL for production

kuma/settings/common.py, kuma/urls.py
=> bug 1391092: Add ability to serve legacy files from Django

kuma/static/styles/components/wiki/interactive.scss
Adds a bit of styling for the survey link added in https://github.com/mdn/kumascript/pull/291
=> Fix issue #229, styling rules for interactive editor survey link

docs/feature-toggles.rst, kuma/settings/common.py, kuma/settings/content_experiments.json, kuma/static/js/experiment-interactive-editor.js
@jwhitlock I believe I have all the ingredients here but, not sure how to test this locally. Perhaps there is still something missing?
=> Fix issue #213, implement traffic cop for interactive examples testing

.coveragerc, kuma/core/tests/__init__.py, kuma/core/tests/logging_urls.py, kuma/core/tests/taggit_extras/models.py, kuma/core/tests/test_jobs.py, kuma/core/tests/test_misc.py, kuma/core/tests/test_taggit_extras.py, kuma/dashboards/tests/test_views.py, kuma/dashboards/views.py, kuma/humans/tests.py, kuma/scrape/tests/__init__.py, kuma/scrape/tests/test_scraper.py, kuma/scrape/tests/test_storage.py, kuma/search/tests/__init__.py, kuma/search/tests/test_indexes.py, kuma/spam/tests/test_akismet.py, kuma/users/tests/__init__.py, kuma/users/tests/test_models.py, kuma/users/tests/test_views.py, kuma/wiki/tests/__init__.py, kuma/wiki/tests/test_admin.py, kuma/wiki/tests/test_content.py, kuma/wiki/tests/test_helpers.py, kuma/wiki/tests/test_models.py, kuma/wiki/tests/test_views.py
Refactor and remove test code to eliminate unused code and branches.
=> bug 957802: Remove unused test code and branches

kuma/settings/content_experiments.json
=> Updates reduce to Reduce in content_experiments.json

kuma/wiki/models.py
Remove untested and unused code from ``kuma/wiki/models.py``.
=> bug 957802: Remove dead code from kuma/wiki/models.py

kuma/static/styles/components-skinny/syntax/example.scss, kuma/static/styles/components-skinny/syntax/syntaxbox.scss, kuma/static/styles/components/syntax/example.scss, kuma/static/styles/components/syntax/syntaxbox.scss, kuma/static/styles/includes-skinny/_mixins.scss, kuma/static/styles/includes/_mixins.scss
As recommended by the Brigade as part of the redesign.
=> Bug 1370594: Remove blueprint background from code samples

kuma/settings/common.py, kuma/settings/local.py, kuma/settings/prod.py, kuma/settings/stage.py, kuma/settings/testing.py
This PR implements the env var overrides requested in https://github.com/mozmeao/infra/issues/477.
=> bug 1308630: add env overrides for aws

kuma/static/js/task-completion.js
And make task-completion.js file conform to coding style guide.
=> Fix bug 1401135: Wrap task completion CTA in gettext

kuma/settings/common.py
More research is needed to determine what this should be set to.
=> bug 1110799: Don't set repos in RAVEN_CONFIG

kuma/settings/common.py
Update KumaScript, and update strings for the transition from mailing lists to Discourse.
=> Pre-push 2017-10-16

kuma/static/styles/base/elements/typography.scss
- reduce padding [as discussed](https://developer.mozilla.org/en-US/docs/Web/API)
- make background colour transparent rgba
- remove text color declaration since new rgba blends well with other backgrounds
-  remove background from code on [api landing page](https://developer.mozilla.org/en-US/docs/Web/API)
=> Reduce padding and change bgcolor on inline code

kuma/attachments/forms.py, kuma/attachments/tests/test_views.py
See https://bugzilla.mozilla.org/show_bug.cgi?id=1410559
=> bug 1410559: prevent ISE when no file in cleaned data

kuma/settings/common.py
* String updates for de, es, es_MX, ff, fr, hu, id, it, ja, ms, nl, pl, pt_BR, ru, sv_SE, sw, ta, zh_CN, and zh_TW.
* mdn/kumascript#325 - Compat: Add tests
* mdn/kumascript#347 - LearnSidebar: Add Client-side Web APIs
* mdn/kumascript#356 - SpecName: Fix Visual Viewport link
* mdn/kumascript#357 - Compat: Android → Android webview
* mdn/kumascript#359 - L10n-Common: French for MissingPage
To do:
=> Update locales, KumaScript

kuma/static/js/components.js
Editing to conform to ESLint in preparation for other changes.
=> Bug 1414107: Conform to ESLint

kuma/static/styles/components/compat-tables/bc-history.scss, kuma/static/styles/components/compat-tables/bc-table.scss
Mismatch between the classes I need and the classes on the tables. Easier to fix the code than republish all the pages with the macro.
=> Tweak table type classes

kuma/static/styles/submission.scss, kuma/users/adapters.py, kuma/users/forms.py, kuma/users/jinja2/socialaccount/signup.html, kuma/users/jinja2/users/includes/user_title_info.html, kuma/users/jinja2/users/user_edit.html, kuma/users/migrations/0007_user_is_github_url_public.py, kuma/users/models.py, kuma/users/signup.py, kuma/users/tests/test_templates.py, kuma/users/tests/test_views.py, kuma/users/views.py
The change is working except for the Signup view, I don't understand how to link the Form to the model on this one.
And there might be some CSS issue with the design, as I'm far for at ease with CSS.
=> Bug 1360294 - Add ability for users to hide github link from their public profile

docs/installation.rst
Added a few details about what to change in the .env  file for easy understanding
=> added details about the changes in the .env

Jenkinsfile, Jenkinsfiles/stage-push.groovy, Jenkinsfiles/utils.groovy
This PR refactors [utils.groovy](https://github.com/mozilla/kuma/blob/master/Jenkinsfiles/utils.groovy) to handle kumascript as well.
=> bug 1406546: refactor groovy code to handle kumascript as well as kuma

docs/installation.rst
Added some helpful details and about not using docker with sudo.
=> Help details

kuma/dashboards/jinja2/dashboards/includes/revision_dashboard_body.html, kuma/dashboards/views.py
WIP for https://github.com/mozmeao/infra/issues/598
=> Optimize prefetch_related usage in revisions dashboard

.gitignore, docs/feature-toggles.rst, etc/sample_db.json, jinja2/base.html, jinja2/includes/common_macros.html, jinja2/includes/config.html, kuma/landing/jinja2/landing/homepage.html, kuma/settings/common.py, kuma/static/js/auth.js, kuma/static/js/wiki-edit.js, kuma/wiki/jinja2/wiki/includes/buttons.html, kuma/wiki/jinja2/wiki/includes/page_buttons.html
This removes the Optimizely flag as well as related code and config.
=> Remove Optimizely flag, feature, and related code

kuma/wiki/jinja2/wiki/includes/document_macros.html
Change required after https://github.com/mdn/interactive-examples/issues/330
=> Updates filenames for non-iframe interactive editor

requirements/default.txt
https://github.com/mozmeao/infra/issues/640
I'm unsure if there's anything else that needs to be updated to use the latest New Relic dep.
=> update to latest newrelic dep

kuma/wiki/jinja2/wiki/document.html
Adding l10n-template marks for this new label
=> Fix bug 1419338

.eslintrc.js, kuma/static/js/badges.js, kuma/static/js/components.js
Fixes eslint warnings in badges.js and component.js
=> Fix Bug 1401291, fixes badges.js and component.js

kuma/static/js/wiki-move.js
Ensure `wiki-move.js` passes linting
=> Fix Bug 1401291, ensure wiki-move.js pass linting

.eslintrc.js, kuma/static/js/promote.js, kuma/static/js/users.js
Ensure `promote.js` and `users.js` pass linting
=> Fix Bug 1401291, ensure promote.js and users.js pass linting

docs/feature-toggles.rst, etc/sample_db.json, kuma/users/adapters.py, kuma/users/jinja2/account/login.html, kuma/users/tests/test_templates.py
Changes the `registration_disabled` waffle flag to a switch.
=> Fix Bug 1136741, changes registration_disabled to a switch

docs/feature-toggles.rst, etc/sample_db.json, kuma/wiki/constants.py, kuma/wiki/forms.py, kuma/wiki/migrations/0011_create_spam_data.py, kuma/wiki/tests/test_forms.py
Removed `wiki_spam_exempted` waffle flag
=> Fix Bug 1136741, remove wiki_spam_exempted flag

docs/feature-toggles.rst, etc/sample_db.json, kuma/landing/jinja2/landing/homepage.html, kuma/settings/common.py, kuma/wiki/migrations/0011_create_spam_data.py
Changes `foundation_callout` to a Django setting
=> Fix Bug 1136741, change foundation_callout to setting

docs/feature-toggles.rst, etc/sample_db.json, kuma/wiki/constants.py, kuma/wiki/forms.py, kuma/wiki/tests/test_forms.py
Changes the `wiki_spam_training` flag to a switch
=> Fix Bug 1136741, change wiki_spam_training flag to switch

docs/feature-toggles.rst, etc/sample_db.json, kuma/landing/jinja2/landing/homepage.html, kuma/settings/common.py, kuma/users/jinja2/users/user_edit.html, kuma/wiki/jinja2/wiki/document.html
Changes `newsletter` and `newsletter_article` switches to Django settings.
=> Fix Bug 1136741, change newsletter and newsletter_article switches to settings

.eslintignore, kuma/static/js/main.js, kuma/static/js/moz-jquery-plugins.js
Ensures `main` and `moz-jquery-plugins` pass linting. Also ignores all files in `libs` folder.
=> Fix Bug 1401291, ensures main and moz-jquery-plugins pass linting

kuma/settings/common.py
=> Update kumascript, locale submodules

docs/feature-toggles.rst, etc/sample_db.json, kuma/wiki/models.py, kuma/wiki/tests/test_models.py
Removed `wiki_error_on_delete` switch
=> Fix Bug 863692, remove wiki_error_on_delete switch

docs/feature-toggles.rst, jinja2/403.html, kuma/wiki/decorators.py, kuma/wiki/tests/test_views.py
=> Fix Bug 1136741, removes kumabanned flag

docs/feature-toggles.rst, etc/sample_db.json, kuma/wiki/models.py, kuma/wiki/tests/test_models.py
Removes the `wiki_force_immediate_rendering` switch
=> Fix Bug 1136741, remove wiki_force_immediate_rendering switch

kuma/static/js/highlight.js
This is the last one! We can block on JS linting now!!
=> Fix bug 1401291: pass linting

.eslintrc.js
Now attempting a commit will fail with exit code 1, if there are linting errors o/\o
=> Fix Bug 1401291, change warnings to error - eslint

jinja2/base.html, jinja2/includes/google_analytics.html, kuma/settings/common.py, kuma/static/js/analytics.js, kuma/static/js/task-completion.js
We now only load GA if DNT is disabled. Also, I moved the analytics block to before any of the CSS or JS as suggested here: https://developers.google.com/analytics/devguides/collection/analyticsjs/#the_javascript_tracking_snippet
=> Fix Bug 1420288, only load GA if DNT disabled

kuma/settings/common.py
- Add translations for ff and te
=> Update locales, kumascript submodules

Jenkinsfiles/standby-push.yml, Jenkinsfiles/utils.groovy
Add a case so that pushing "standby-push" will update the standby maintenance mode deployment in Frankfurt.
=> bug 1406546: Add standby-push branch handling

kuma/static/styles/components/wiki/interactive.scss
@jwhitlock Turns out we need even moar height ;p
=> Fix issue #408, adds an additional 200px for class .taller

kuma/settings/common.py
Update submodules, including the ``2018.02`` string update.
=> Pre-push submodule update

Jenkinsfiles/upgrade_pytest_1308322.yml
=> bug 1402950: Remove PR-specific Jenkinsfile

kuma/landing/jinja2/landing/homepage.html
Updates to text suggested in [bug 1431845](https://bugzilla.mozilla.org/show_bug.cgi?id=1431845). I missed this when reviewing PR #4639 😢
=> bug 1431845: Update SEO in homepage metadata

kuma/static/styles/fellowship.scss
Found this one still hanging around.
=> Removes the fellowship.scss straggler

kuma/settings/common.py
Updates Mozilla Developer Network to MDN Web Docs
Removes strings related to fellowship
=> Pre push date 2018 01 31

jinja2/base.html, kuma/settings/common.py, kuma/settings/local.py
It seems like the most efficiant fix with current configuration.
@jwhitlock small PR, r?
=> [Bug 1434690] Use different favicon on staging and development

tests/functional/test_search.py, tests/pages/base.py
Test the new interactions for the search area (hides the user toolbox instead of the navigation menus, includes an animation). Also, alphabetize the element selectors for the header region.
=> bug 1434558: Update functional tests for search

kuma/search/fields.py, kuma/search/renderers.py, requirements/default.txt
It passes all the tests! But need some more investigation.
I will investigate more later this week.
@jwhitlock Can you take a look if I have taken proper approach?
=> [Bug 1399639] Updating Django Rest Framework

kuma/settings/common.py
* String update 2018.05, which moved around a lot of strings, but only added one.
* Added some ignores to ``PUENTE`` to speed up locale update by a couple of seconds.
* So many 💀 deleted macros 💀 .
=> Pre-push 2018-02-20

CONTRIBUTING.md, README.rst, contribute.json, kuma/users/adapters.py
Update links (some moz.la short links) in other documentation, and for the "delete my account" link.
=> bug 1439608: Update more Bugzilla links

kuma/static/styles/components/wiki/interactive.scss
Adds a custom class required for the HTML interactive editor.
=> Adds custom class for tabbed editor

kuma/settings/common.py
Locale strings updated for removal of ``dbgettext``, and refreshed from database.
=> Update kumascript submodule, update locale strings

kuma/users/jinja2/socialaccount/signup.html
[bug 1442681](https://bugzilla.mozilla.org/show_bug.cgi?id=1442681) - missed one 😞
=> bug 1442681: Update product in Bugzilla link

kuma/attachments/tests/test_views.py, kuma/attachments/views.py
This is another in a series of PR's that add the appropriate caching headers and related tests to all Kuma endpoints as part of the effort of placing a CDN in front of MDN. This PR adds/modifies caching headers and tests for the endpoints for the `kuma.attachments.views`.
=> bug 1431259: caching headers/tests for attachments views

kuma/settings/common.py
Only locale updates this time: new translations, and some new strings for translations.
=> Pre-push 2018-03-28

kuma/urls.py
Fix for the cache-control header for the `miel` endpoint.
=> bug 1431259: fix caching for miel endpoint

jinja2/includes/footer/moz-footer.html
Removes donate link from footer.
=> Closes Bug 1461250, remove donate link from footer

kuma/users/tests/test_forms.py
Django 1.9 updates ``assertRaisesMessage`` so that the test becomes:
```
<message> in str(<exception>)
```
where our ``<message>`` is a lazy-evaluated translated string, and results in a ``TypeError``:
```
'in <string>' requires string as left operand, not __proxy__
```
This PR fixes the ``TypeError`` by converting it to a regular string, such as
``str(USERNAME_EMAIL)``, and also converts the tests to pytest style,
entirely avoiding ``assertRaisesMessage`` magic.
=> bug 1401246: Convert adapter.clean_username tests

kuma/dashboards/tests/test_views.py, kuma/users/tests/test_templates.py
In spam dashboard tests, adjust how ``RevisionAkismentSubmissions`` are created, to be compatible with Django 1.9 and later.
=> bug 1401246: Update aksimet submission creation

requirements/constraints.txt, requirements/default_and_test.txt, requirements/docs.txt, tests/functional/test_notfound.py
Sync the six version in the docs requirement file, and move six to default_and_test, shared with tests.
=> bug 1401246: Sync six, add to test environment

.prettierrc, kuma/static/js/analytics.js, kuma/static/js/interactive.js
@jwhitlock before I change these to the `ga` calls I want to give @tkadlec a chance to review and try it out locally.
=> bug 1468271: Add custom performance metrics for interactive examples iframe

kuma/static/js/interactive.js
=> bug 1468271: Change to hit events (not timing), and unique labels (timestamp+rand)

kuma/static/js/analytics.js, kuma/static/js/interactive.js
=> Issue sprints/143, send additional timing events

kuma/settings/common.py, kuma/static/js/analytics.js, kuma/static/js/interactive.js, kuma/static/js/utils/perf.js, kuma/static/js/utils/post-message-handler.js, kuma/static/js/utils/utils.js, kuma/static/js/wiki-skinny.js
@tkadlec r? This is the other side of https://github.com/mdn/interactive-examples/pull/977 - I also did some refactoring to make the code more modular and easier to understand/read.
@jwhitlock Opening this for code review by Tim, I first need to have https://github.com/mdn/interactive-examples/pull/977 reviewed and merged so that I can test this properly. So, will mark as WIP for now.
=> Add handler for additional post messages from interactive examples, and a refactor

kuma/static/js/interactive.js, kuma/static/js/utils/post-message-handler.js
=> Fix Bug 1477263, change event label for RUM data

jinja2/base.html, jinja2/includes/config.html, kuma/static/js/lang-switcher.js
I believe this fixes the [bug 1471829](https://bugzilla.mozilla.org/show_bug.cgi?id=1471829). @schalkneethling r?
=> [Bug 1471829] Don't prompt remember language notification if already exist

kuma/static/js/utils/perf.js
@jwhitlock @schalkneethling r?
=> Fix typo of user-agent in console.error() calls

kuma/wiki/signal_handlers.py, kuma/wiki/tests/test_views.py, kuma/wiki/tests/test_views_document.py, kuma/wiki/views/document.py, tests/pages/article.py, tests/performance/smoke.py
Remove additional references to zoned documents from the code and documentation.
=> bug 1462475: Remove some more references to zones

kuma/settings/common.py
One new PR on the KumaScript side. For locales, new translations, and update translatable strings:
* Drop content creator survey on homepage
* Add FF Dev Edition banner on homepage
* Drop locale / contributor banner on homepage
* Drop content zone UI
* Add "Link to section" tooltip for section links
=> Pre-push 2018-08-21 - Update submodules, strings

kuma/landing/jinja2/landing/homepage.html
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1486852
=> Fix bug 1486852: Add compat data contribution link to homepage

jinja2/includes/header-main-nav.html
@jwhitlock small, but important change.
=> Fix Bug 1485302, use rel=noopener when using target=_blank

kuma/settings/common.py
Update kumascript and locales submodules to latest versions. 
Add 2018.11 string update for:
* PR #4930 - Add discourse to profile
* PR #4934 - Improve document purging 
* PR #4959, PR #4955 - BCD call to action on homepage
=> Update kumascript, translations, 2018.11 string update

jinja2/base.html, jinja2/includes/icons/arrows/chevron-down.svg, jinja2/includes/icons/arrows/chevron-up.svg, jinja2/includes/icons/emojis/thumbs-down.svg, jinja2/includes/icons/emojis/thumbs-up.svg, kuma/contributions/forms.py, kuma/contributions/jinja2/contributions/contribute.html, kuma/contributions/jinja2/contributions/includes/contribution-form.html, kuma/contributions/jinja2/contributions/thank_you.html
Further updates for the addition of a pop-up contribution form.
=> bug 1490727: Updates for user testing branch

kuma/contributions/jinja2/contributions/contribute.html, kuma/landing/jinja2/landing/homepage.html, kuma/static/js/contribution-handler.js, kuma/wiki/jinja2/wiki/document.html
@jwhitlock This now defers and loads stripejs async on all pages where it is used in popover mode. On the contribute page, it is still loaded as before. r?
=> Bug 1490727, defer stripejsand load async

kuma/contributions/jinja2/contributions/contribute.html, kuma/contributions/jinja2/contributions/includes/contribution-form.html, kuma/static/styles/components/contribution/page.scss
Tested and it seemd good! Just check I'm using the correct translation syntax pls
=> update copy, fix FAQ feedback link, stop textarea from being resized

kuma/contributions/jinja2/contributions/contribute.html, kuma/contributions/jinja2/contributions/includes/contribution-form.html, kuma/static/js/contribution-handler.js, kuma/static/styles/components/contribution/banner.scss, kuma/static/styles/components/contribution/page.scss
- Removes 'remember me' from stripe checkout
- Fixes ie11 text alignment on popover button
- FAQ copy updates
- Update legal copy
- Hide banner after payment submission
=> Bug 1490727 Update copy and minor bugs.

kuma/contributions/jinja2/contributions/contribute.html, kuma/contributions/jinja2/contributions/email/thank_you/email.html, kuma/contributions/jinja2/contributions/thank_you.html, kuma/contributions/tasks.py, kuma/static/js/contribution-faq.js, kuma/static/js/contribution-handler.js
This PR updates the analytics structure for the contributions flow and cleans up some legacy issues.
PR is awaiting:
=> bug 1490727: Analytic structure update and code cleanup.

Jenkinsfiles/utils.groovy
This PR configures full-scale maintenance-mode deployments to MozIT's prod instance.
=> bug 1483072: deploy mozit prod at full-scale

kuma/settings/common.py
Update to latest locale and kumascript, and then extract strings for:
* The new [dashboards index](https://developer.mozilla.org/en-US/dashboards)
* Payments string updates
=> Update locale and kumascript submodules, 2018.13 string update

kuma/settings/common.py
If the ``CSP_REPORT_URI`` looks like a Sentry URI, add the commit hash as sentry_release. Builds on https://github.com/mdn/infra/pull/139, but there aren't any hard dependencies on each other.
=> bug 948151: Add release to Sentry CSP reports

kuma/static/layout-tests/no-inline-js.html, kuma/static/layout-tests/no-js.html, kuma/static/layout-tests/normal.html, kuma/static/layout-tests/raw-html.html, kuma/static/layout-tests/unused-css.html
This adds some static pages so that we can get a really clear picture of where our heavy layout performance issues are coming from.
=> Static pages for testing layout perf

kuma/payments/forms.py, kuma/payments/jinja2/payments/includes/payments-form.html, kuma/payments/tests/test_views.py, kuma/static/js/payments-handler.js, kuma/static/styles/components/payments/form.scss
This PR adds a checkbox to confirm recurring payment submission.
**In this PR**
- https://trello.com/c/dIsVyv2F/44-as-a-user-i-can-agree-to-the-payment-terms-so-that-i-can-confirm-my-recurring-payment
**Notes for QA**
**screenshots**
=> bug 1490727: Include confirmation checkbox for recurring payments.

kuma/settings/common.py
Update kumascript and locale submodules, and send the new strings for recurring payments to Pontoon for translation.
=> Submodule updates, send new strings to Pontoon

kuma/payments/jinja2/payments/thank_you.html
This is PR for:
https://trello.com/c/dPtdqsPZ/56-bug-error-on-recurring-payment-page-returns-to-one-time-payment-page
Added link to support recurring payment.
=> bug 1490727: Fixed redirect bug in payments error page

kuma/payments/jinja2/payments/email/thank_you/email.html, kuma/payments/jinja2/payments/thank_you.html
This is PR for:
https://trello.com/c/WSmbJuRf/24-as-a-user-i-need-consistent-information-about-subscription-cancellation-and-management-so-that-im-not-confused
Consistent information about subscription cancellation and management in thank you page and email
=> bug 1490727: Update information about subscription cancellation

kuma/payments/jinja2/payments/payments.html
this is PR for:
https://trello.com/c/Ek6n2n2C/19-as-a-user-i-can-see-information-about-recurring-payments-so-that-i-can-understand-how-recurring-payment-works
Added four new FAQ for monthly payments.
QA:
=> bug 1490727: add four new FAQ for monthly payments

kuma/payments/jinja2/payments/includes/payments-banner.html, kuma/payments/jinja2/payments/includes/payments-form.html, kuma/static/js/payments-confirmation.js, kuma/static/js/payments-handler.js
This PR introduces the analytic events in recurring payments for authenticated/anonymous users.
**In this PR** 
- https://trello.com/c/MepXwFak/18-as-a-mdn-developer-i-want-a-list-of-key-metrics-so-that-i-can-implement-them
**implementation**
- Recurring payment banner shown for logged in users: 
eventCategory: "Recurring payments", eventAction: "banner shown", eventLabel: "authenticated", eventValue: 0
- Recurring payment banner shown for anonymous users:
eventCategory: "Recurring payments", eventAction: "banner shown", eventLabel: "anonymous", eventValue: 0
- Recurring payment banner opened for logged in users:
eventCategory: "Recurring payments", eventAction: "banner expanded", eventLabel: "authenticated", eventValue: 0 
- Recurring payment banner opened for anonymous in users: …
=> bug 1490727: Recurring payment analytics implementation

kuma/payments/forms.py
this is PR for:
https://trello.com/c/EaB3auiq/83-bug-feature-as-a-user-if-an-error-with-my-payment-occurs-as-the-result-of-a-problem-with-my-card-i-want-to-be-made-aware-of-this
=> bug 1490727: Fix for multiple subscriptions issue

kuma/payments/jinja2/payments/includes/payments-banner.html
Change text to "Help grow MDN", to avoid donation phrasing.
=> bug 1490727: Change text on banner

kuma/static/layout-tests/iex-unused-css.html
@atopal I think this is the combination we want to test for maximum impact. I can also add inlined example versions of the other static layout tests
=> Add static test of inlined example plus unused css

kuma/settings/common.py
Update the locale and kumascript submodules, and push string update 2018.16, changing the payment banner text to 'Help grow MDN'.
=> Update locales, kumascript, and push new string

kuma/payments/jinja2/payments/management.html, kuma/payments/tests/test_views.py
@davidflanagan and I noticed some issues in the strings that I'd like to fix before we send them to the translators: 
* Change title to "MDN subscription management"
* Fix spelling
* Use [American spelling](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Writing_style_guide#Spelling) of canceled
=> bug 1490727: Adjust payment management UI strings

kuma/static/js/components/payments/payments-handler.js, kuma/static/styles/components/payments/_vars.scss, kuma/static/styles/components/payments/banner.scss
Issue details are available in https://github.com/mdn/sprints/issues/706
@davidflanagan 	r?
=> Bug 1490727, sprints/706, payment button obscured when fields are invalid

kuma/static/styles/components/payments/form.scss, kuma/static/styles/components/payments/page.scss
To clarify the first item in the list on https://github.com/mdn/sprints/issues/710, below is the desired design layout:
=> Bug 1490727, sprints/710, cosmetic updates to payments FAQ page

kuma/payments/jinja2/payments/includes/payments-form.html, kuma/static/js/components/payments/payments-handler.js, kuma/static/styles/components/payments/form.scss
Details of the problem detailed here:
https://github.com/mdn/sprints/issues/704
@davidflanagan 	r?
=> Bug 1490727, sprints/704, cannot check terms checkbox with field label

tests/functional/test_report.py, tests/pages/base.py
This PR fixes the integration test broke by https://github.com/mozilla/kuma/pull/5183 (which I missed in my review).
=> bug 1518844: fix test_report_content

kuma/static/styles/components/payments/banner.scss, kuma/static/styles/components/payments/page.scss
Details can be found in:
https://github.com/mdn/sprints/issues/708
Pages to test are:
* en-US/payments/recurring/success
* en-US/payments/success
=> Bug 1518844, UI updates to thank you pages

kuma/static/styles/components/payments/banner.scss, kuma/static/styles/components/payments/form.scss
Details of required changes can be seen here:
https://github.com/mdn/sprints/issues/709
My comments on some of the changes here:
https://github.com/mdn/sprints/issues/709#issuecomment-454416389
=> Bug 1518844, UI updates to payments banner

tests/functional/test_dashboard.py
Remove an unused import to make flake8 happy.
=> bug 1520616: Remove unused import

kuma/settings/common.py
This is now included in the base template for all wiki pages as of PR #5202.
=> bug 1521135: Add codepen to CSP allowed script-src

kuma/settings/common.py
Add "Try it live!" for new embedded Codepen examples. First strings of 2019!
=> Update strings 2019.01

kuma/wiki/tasks.py
Kuma's render_stale_documents task splits the list of stale
documents into groups of 5, then re-renders each group in
parallel. This typically causes about 12 requests to the KumaScript
server at the same time, causing load spikes that only occur
once an hour when this task runs.
This patch changes the task so that the subtasks for each group
of documents are chained and run in series instead of in parallel.
This should reduce the load on KumaScript and enable us to drop
down to a single KumaScript server.
=> Bug 1522718: render stale documents in series, not in parallel

kuma/dashboards/forms.py, kuma/dashboards/jobs.py, kuma/dashboards/tests/test_views.py, kuma/dashboards/urls.py, kuma/dashboards/utils.py, kuma/dashboards/views.py
Minor changes to update `kuma.dashboards` to better support Python 3.
=> bug 1467518: update kuma.dashboards to support Python3

kuma/health/tests/test_views.py, kuma/health/urls.py, kuma/health/views.py
This PR updates the `kuma.health` app to better support Python3. The only changes here provide a string experience that is more consistent between Python2 and Python3.
=> bug 1467518: update kuma.health to better support Python3

kuma/humans/management/commands/make_humans.py, kuma/humans/tasks.py
This PR updates the `kuma.humans` app to better support Python3. The only changes here provide a string experience that is more consistent between Python2 and Python3.
=> bug 1467518: update kuma.humans to better support Python3

docs/development.rst
The Deis code was removed in PR #4541.
=> fix bug 1465829: Remove Deis demo docs

kuma/users/jinja2/account/login.html, kuma/wiki/jinja2/wiki/document.html, kuma/wiki/jinja2/wiki/includes/buttons.html
I feel little capacity to judge the worth of SEO modifications given the murkiness of that world to me, but this is my understanding of [this understanding](https://github.com/mdn/sprints/issues/939) of [bug 1524846](https://bugzilla.mozilla.org/show_bug.cgi?id=1524846).
=> bug 1524846: reduce crawling of edit and login pages

kuma/wiki/tasks.py, kuma/wiki/tests/test_tasks.py
This PR replaces #5245. It adds the home page to each enabled locale's sitemap (e.g., https://developer.mozilla.org/en-US/ is added to https://developer.mozilla.org/sitemaps/en-US/sitemap.xml), and refactors/improves the sitemap tests.
=> bug 1527010: add home page to each locale sitemap

docker/images/kumascript/Dockerfile
* Set ownership when files are copied rather than as a second step
* Combine the npm install into a single Docker layer
* Fix spelling and re-word some comments
=> bug 957802: Combine commands in KumaScript image

kuma/static/styles/components/wiki/content/collapsible.scss, kuma/static/styles/includes/_vars.scss
=> Bug 1523643, fixes anchor widget dropping to new line on small mobile viewports

kuma/static/js/components/payments/focus-visible.js
=> Bug 1534298, code improvement based on suggestion by @davidflanagan

kuma/landing/views.py, kuma/urls.py, kuma/wiki/api/v1/urls.py, kuma/wiki/api/v1/views.py, kuma/wiki/tests/test_api.py
This PR implements a simple read-only API for querying document
content and metadata as JSON. The intent is to use this API to
enable client-side navigation for MDN documents.
=> Bug 1525719: Add a document API at /api/v1/doc/<locale>/<slug>.

kuma/wiki/models.py, kuma/wiki/tests/test_models.py
This PR adjusts the `Document.clean_current_revision` method to avoid two things:
- errors during the `Revision.make_current` call when the slug of the revision doesn't match the slug of the document (see https://github.com/mdn/sprints/issues/936#issuecomment-475694728)
- duplicate calls to `Revision.make_current` when the current revision is approved (most cases)
The tests for the `Document.clean_current_revision` method have also been updated to detect these changes.
=> bug 1519582: ensure same slug & title when cleaning

tests/js/banners/banners-state-util.test.js
=> Fix failing jest test

requirements/default.txt
=> fixes bug 1542759 - Jinja2 2.10.1

etc/nginx/ssl/generate_dev_cert.sh
Fixes the shebang. Found this while working on something else.
=> bug 1218563: fix shebang in generate_dev_cert.sh

kuma/core/tests/__init__.py
Followup to fix the code comment nit that fell out from https://github.com/mozilla/kuma/pull/5348
=> bug 1544084 - correction on code comment

kuma/static/styles/base/elements/typography.scss
See https://github.com/mdn/kumascript/pull/1104
=> mdn/kumascript#1104: Use `<code class=templateLink>` for {{TemplateLink}}

README.rst
review?(@davidflanagan, @Elchi3)
=> docs(readme): Add “WhatsDeployed.io” badge

kuma/wiki/content.py
See https://bugzilla.mozilla.org/show_bug.cgi?id=1548130#c7 and https://bugzilla.mozilla.org/show_bug.cgi?id=1548130#c8
=> fixes bug 1548130 - make reindexing faster

kuma/banners/jinja2/banners/includes/developer-needs.html
=> Sprints issue 1393, update developer needs banner copy

.travis.yml, scripts/ci-jest
Add a matrix to Travis to run Jest tests in Travis CI.
=> bug 1548914: Run jest tests in Travis CI

requirements/default.txt
I need to tie this to a bug ID.
=> bug 1551701 - upgrade redis and django-redis

requirements/README.rst, requirements/constraints.txt, requirements/dev.txt
=> fixes bug 1551710 - remove hashin from dev requirements

kuma/javascript/src/document-provider.jsx
This PR adds functionality to the `DocumentProvider` React component that allows client-side navigation even when no document JSON exists for a slug within a non-English locale. Currently, when document JSON is requested for a non-English document and nothing exists for that locale (the response is a 404), client-side navigation is abandoned. We instead request a full page load, and the `react_document` view that serves the full-page load will fall back to the English version of the document if the non-English version doesn't exist. This PR does that same thing but on the client-side.
For local testing, I used the following `.env`:
```
DEBUG=True
DOMAIN=mdn.localhost
ENABLE_RESTRICTIONS_BY_HOST=True
BETA_HOST=beta.mdn.localhost:8000
WIKI_HOST=wiki.mdn.localhost:8000 …
```
=> bug 1525719: handle 404 in client-side nav

kuma/javascript/src/task-completion-survey.jsx, kuma/javascript/src/task-completion-survey.test.js
My PR that changed gettext() landed after the PR that added the task
completion survey. But the task completion survey used the old gettext
API, so I ended up creating a master branch that does not pass tests.
This PR fixes it.
=> Fix lint errors

package-lock.json, package.json, requirements/default.txt
Update newrelic agent for python from 3.2.1.93 -> 4.18.0.118
Update newrelic agent for nodejs from 4.13.1 -> 5.9.0
=> bug 1518653: Update newrelic agents

kuma/javascript/src/__snapshots__/page.test.js.snap, kuma/javascript/src/header/__snapshots__/dropdown.test.js.snap, kuma/javascript/src/header/__snapshots__/header.test.js.snap, kuma/javascript/src/header/__snapshots__/language-menu.test.js.snap, kuma/javascript/src/header/__snapshots__/login.test.js.snap, kuma/javascript/src/header/__snapshots__/search.test.js.snap, kuma/javascript/src/header/dropdown.jsx, kuma/javascript/src/header/header.jsx, kuma/javascript/src/header/language-menu.jsx, kuma/javascript/src/header/login.jsx, kuma/javascript/src/header/login.test.js, kuma/javascript/src/header/search.jsx, kuma/javascript/src/page.jsx
This PR is mostly CSS changes to the React code on the beta domain.
The design changes include:
- a new blue bar on top with a color gradient
- changed margins and font sizes in the header
- new design for the search box
- language menu moved out of the header
=> UX polish for the beta domain

kuma/javascript/src/__snapshots__/page.test.js.snap, kuma/javascript/src/page.jsx
See https://github.com/mdn/sprints/issues/1588
=> Make the maximum width of React-based page layouts 1400px

kuma/static/js/interactive.js, kuma/static/js/utils/post-message-handler.js, kuma/static/js/utils/utils.js
PR #5445 causes a JS error in the developer console because a JS file
was is missing its the utils.js dependency. The problem is the
randomString() utility. Rather than include the entire utils.js file
this PR just removes the randomString() function and replaces the two
places it was called with a more efficient alternative.
=> Remove mdn.utils.randomString()

kuma/banners/jinja2/banners/includes/developer-needs.html
=> Bug 1552481, add survey link

package.json
See also https://github.com/mdn/kumascript/pull/1173
=> bug 1555418 - Remove or update  the engines property from package.json

requirements/default.txt
I think the security risk is extremely low in our context but upgrading just feels right since it's so easy.
=> Django 1.11.21

package-lock.json
I don't know else to test this. I started the local web server and used both mdn.localhost:8000 and beta.mdn.localhost:8000 and clicked around on things.
=> npm audit fix June 5

kuma/attachments/models.py, kuma/authkeys/models.py, kuma/search/models.py, kuma/users/models.py, kuma/wiki/content.py, kuma/wiki/models.py
This will need to be rebased once https://github.com/mozilla/kuma/pull/5487 lands in master.
=> bug 1558219 - Get rid of all MyModel.__unicode__

kuma/wiki/content.py, kuma/wiki/jinja2/wiki/ckeditor_config.js, kuma/wiki/tests/test_content.py
=> Bug 1553512, fix insertion of blank paragraphs

kuma/static/styles/components/home/callouts/_grid-tools.scss, kuma/static/styles/components/newsletter.scss, kuma/static/styles/includes/_mixins.scss
@davidflanagan r? I used `fa` for testing RTL
=> Bug 1539793, fix landing page for RTL locales

kuma/wiki/management/commands/correct_current_revision_documents.py
@escattone Perhaps a quick review on this. It's so harmless if it's not perfect. 
Now I can do:
```
docker-compose exec web ./manage.py correct_current_revision_documents --start-date=2019-04-16 --end-date=2019-04-23
```
It's a small step forward but it should make the next report much smaller (and faster).
=> bug 1551999 - make correct_current_revision_documents find less

kuma/javascript/src/header/__snapshots__/header.test.js.snap, kuma/javascript/src/header/header.jsx
This PR adds a prominent request for feedback to all beta pages
and links to https://bugzilla.mozilla.org/show_bug.cgi?id=1561020
as a central location for collecting bugs and suggestions about
the beta site.
=> Bug 1525719: add a "Give Feedback" link to beta pages

.eslintrc.js, kuma/javascript/src/header/search.jsx, kuma/javascript/src/task-completion-survey.jsx, kuma/javascript/src/user-provider.jsx, package-lock.json, package.json
Adds [rules of hooks](https://reactjs.org/docs/hooks-rules.html) linting and fixes three linting errors that was highlighted post install.
=> Add rules-of-hooks linting

Makefile, kuma/javascript/src/header/language-menu.jsx, package.json
This should break the first time. I'll fix that in a second commit just to prove that it works.
=> bug 1562262 - run prettier check in ci

kuma/landing/jinja2/landing/homepage.html, kuma/wiki/jinja2/wiki/document.html
=> Bug 1564302, show dev needs survey on all pages

kuma/javascript/src/header/__snapshots__/header.test.js.snap, kuma/javascript/src/header/__snapshots__/search.test.js.snap, kuma/javascript/src/header/search.jsx, kuma/static/styles/base/elements/forms.scss
=> Bug 1563464, missing label for search input field

kuma/javascript/src/document.jsx, kuma/javascript/src/interactive-examples.js, kuma/static/styles/components/wiki/spec.scss
~~Our mobile views are rather broken now. This adds a temporary band-aid while I work on a larger "rewrite" to fix mobile. I am also hiding the interactive examples on mobile(phone) as it has no user benefit being shown at these viewport sizes.~~
@peterbe r?
=> Bug 1563256, horizontal scrolling on mobile view

kuma/javascript/src/titlebar.jsx
Fixes scrollbar under title bar on Windows - @SphinxKnight r?
=> Bug 1562853, scrollbar under title on windows

kuma/javascript/src/last-modified-by.jsx
=> Bug 1568040, last updated by link includes comma and space

kuma/users/jinja2/socialaccount/authentication_error.html
A whole lot better than nothing!
=> make it easier to debug auth problems

jinja2/react_base.html, kuma/javascript/src/index.jsx, kuma/wiki/jinja2/wiki/react_document.html
Removes the lang switcher from the footer of beta pages. @callahad r?
=> Bug 1568254, remove footer lang switcher from beta

kuma/settings/common.py
* Fixes authenticated API calls in beta.
=> Add BETA_HOST in CSRF trusted origins.

jinja2/react_base.html, kuma/javascript/src/index.jsx
Adds footer lang switcher back to homepage.
@peterbe r?
=> Bug 1569794, add footer lang switcher back to homepage

requirements/default.txt
https://www.djangoproject.com/weblog/2019/aug/01/security-releases/
=> django 1.11.23

kuma/static/styles/components/structure-shared.scss, kuma/static/styles/components/structure/page-header/_vars_nav.scss, kuma/static/styles/components/structure/page-header/nav-main.scss, kuma/static/styles/components/structure/page-header/static/_main-nav.scss, kuma/static/styles/components/structure/page-header/static/_vars-nav.scss, kuma/static/styles/main-shared.scss
This stops us from serving the main menu code for both the current and new menu to both front-ends. @peterbe r?
=> Bug 1569958, separate menu CSS for static site from wiki

kuma/wiki/jinja2/wiki/react_document.html
Fix bad comment from #5614 in `react_document.html`.
=> bug 1525719: fix comment in react_document template

kuma/landing/views.py
=> Unnecessary SQL select for react home landing page

kuma/javascript/src/header/__snapshots__/header.test.js.snap, kuma/javascript/src/header/__snapshots__/login.test.js.snap, kuma/javascript/src/header/login.jsx, kuma/static/styles/minimalist/structure/_header.scss
=> Bug 1570022, set min width on whoami widget

kuma/wiki/tests/test_views_translate.py, kuma/wiki/views/translate.py
=> wiki.views.translate with `tolocale` invalid causes ISE

kuma/users/jinja2/socialaccount/signup.html, kuma/users/tests/test_templates.py
This is the copy updates only. This does not change the design/layout at all.
=> Fix issue #5645, update copy for new user registration

docker/images/kuma_base/Dockerfile
After:
```
kuma@9eac8d1c6da9:/app$ node --version
v10.16.3
kuma@9eac8d1c6da9:/app$ npm --version
6.9.0
```
=> bug 1568242 - Upgrade Node 10 and npm 6

kuma/javascript/src/header/__snapshots__/dropdown.test.js.snap, kuma/javascript/src/header/__snapshots__/language-menu.test.js.snap, kuma/javascript/src/header/__snapshots__/login.test.js.snap, kuma/javascript/src/header/dropdown.jsx, kuma/static/styles/minimalist/components/_dropdown.scss, kuma/static/styles/minimalist/components/_main-nav.scss, kuma/static/styles/minimalist/document.scss, kuma/static/styles/minimalist/vars/_vars-nav.scss
=> Issue #5685, remove Emotion and move CSS to Sass - Dropdown

kuma/javascript/src/header/__snapshots__/header.test.js.snap, kuma/javascript/src/header/header.jsx
Remove beta notice @peterbe r?
=> Fixes #5722, remove beta notice

kuma/static/js/components/local-anchor.js
This instruments the section links for both left and right-click events. @peterbe r?
=> Fixes #5726, instrument events on section links

kuma/javascript/src/document.jsx, kuma/static/styles/minimalist/document.scss, kuma/static/styles/minimalist/structure/_containers.scss, kuma/static/styles/minimalist/structure/_sidebar.scss
=> Issue #5685, remove Emotion and move CSS to Sass - Document and Sidebar

kuma/javascript/src/router.jsx, kuma/static/styles/minimalist/components/_loading-bar.scss, kuma/static/styles/minimalist/main.scss
=> Issue #5685, remove Emotion and move CSS to Sass - loading bar

kuma/javascript/src/search-results-page.jsx, kuma/static/styles/minimalist/structure/_search-results.scss
@peterbe r?
Also as mentioned in the original PR:
> Peter, also note, I did not link up search-results.scss because I will leave 
> that to you to determine the best place to hook that into the work you are 
> currently doing on search. Thanks!
=> Issue #5685, remove Emotion and move CSS to Sass - search results page

kuma/javascript/src/titlebar.jsx, kuma/static/styles/minimalist/components/_titlebar.scss, kuma/static/styles/minimalist/document.scss, kuma/static/styles/minimalist/vars/_vars-color-palette.scss
=> Issue #5685, remove Emotion and move CSS to Sass - titlebar

kuma/javascript/src/header/__snapshots__/header.test.js.snap, kuma/javascript/src/header/__snapshots__/login.test.js.snap, kuma/javascript/src/header/login.jsx, kuma/static/styles/minimalist/components/_login.scss, kuma/static/styles/minimalist/main.scss
=> Issue #5685, remove Emotion and move CSS to Sass - Login

kuma/javascript/src/task-completion-survey.jsx, kuma/static/styles/minimalist/components/_task-completion.scss, kuma/static/styles/minimalist/document.scss
=> Issue #5685, remove Emotion and move CSS to Sass - task completion survey

kuma/javascript/src/header/__snapshots__/header.test.js.snap, kuma/javascript/src/header/__snapshots__/search.test.js.snap, kuma/javascript/src/header/search.jsx, kuma/static/styles/minimalist/components/_search-widget.scss, kuma/static/styles/minimalist/main.scss
=> Issue #5685, remove Emotion and move CSS to Sass - search widget

kuma/dashboards/tests/test_views.py, kuma/dashboards/views.py, tests/headless/test_cdn.py
What we chatted about in Slack #mdn-dev-internal
=> Password protect user lookup and topic lookup

docs/development.rst
=> Document new package.json scripts

kuma/static/styles/minimalist/components/_main-nav.scss, kuma/static/styles/minimalist/document.scss
=> Fixes #5697, use correct structure partial for new frontend

kuma/search/jinja2/search/react.html, kuma/settings/common.py, kuma/static/styles/minimalist/search-page.scss
=> Site-search CSS busted

kuma/wiki/jinja2/wiki/react_document.html
=> Removes merge conflict comments that was left in HTML file

kuma/javascript/src/newsletter.jsx
Some of this might be opinionated, as in: I like...
- ...early returns
- ...destructuring
Happy to revert if that seems less readable to anyone.
There were some checks in there for whether `newsletterForm` exists, I dropped those because `submit` could only be called after the component was rendered at least once. And since the form isn't rendered conditionally `newsletterForm` should always exist. Unless I'm missing something... 🙃 
Fixes #5782
=> React newsletter fixes & refactor

kuma/javascript/src/newsletter.jsx, kuma/javascript/src/user-provider.jsx
=> blocked localStorage breaks site

jinja2/includes/preload.html
Fixes #5687
Preloading `ZillaSlab-Regular`
=> preload ZillaSlab-Regular

.travis.yml, kuma/wiki/jinja2/wiki/react_document.html
=> diff never again

kuma/scrape/management/commands/__init__.py
=> scrape_document with trailing slash fails

kuma/javascript/src/header/__snapshots__/header.test.js.snap, kuma/javascript/src/header/__snapshots__/search.test.js.snap, kuma/javascript/src/header/search.jsx, kuma/static/styles/minimalist/components/_search-widget.scss
=> Prevent search from submitting when query is empty

docs/development.rst, kuma/api/v1/views.py, kuma/settings/common.py, requirements/dev.txt
Fixes #5857
I know this isn't urgent or important but I installed it locally and found it pretty useful so instead of just throwing it all away I wrapped it up as a little contribution.
=> add django-querycount as a dev requirement

kuma/settings/common.py
I couldn't find any reference to these in our code, or our dependencies.
Might as well remove them, right? :)
=> Remove unused settings constants

kuma/search/jinja2/search/results.html
Fixes #5809
Changes document URLs in search to a wiki document URl when searching through wiki
=> Change document URL to wiki when searching on it

kuma/javascript/src/document.jsx, kuma/javascript/src/error-boundaries.jsx, kuma/javascript/src/error-boundaries.test.js, kuma/javascript/src/index.jsx
Fixes #5720 
Fixes #5913
When the whole app fails:
When the `Content` component fails:
=> React error boundaries

kuma/api/v1/views.py, kuma/javascript/src/search-results-page.jsx, kuma/search/jinja2/search/react.html, kuma/search/search.py, kuma/search/views.py
Fixes #5824 
When the search results page is rendered with react, the results are pre-loaded using SSR.
=> Server-side generate site-search

kuma/attachments/management/commands/configure_github_social.py
Fixes #5969 
I got the conditional wrong before 🙈
=> Fix configure github script conditional

kuma/javascript/src/__snapshots__/newsletter.test.jsx.snap, kuma/javascript/src/newsletter.jsx
Fixes #5961 (maybe)
@schalkneethling I personally don't think we should merge this until we know about the magnitude and details of what causes this problem. This only fixes one of the possible (imagined) scenarios. I'd like to have a repro first.
=> Stop sending users to mozilla's newsletter page in submit handler

kuma/javascript/src/error-boundaries.jsx
=> send a bit of the error to GA

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.rst, contribute.json, docs/assets.rst, docs/ckeditor.rst, docs/conf.py, docs/deploy.rst, docs/development.rst, docs/feature-toggles.rst, docs/installation.rst, docs/localization.rst, docs/rendering.rst, docs/tests-functional.rst, jinja2/500.html, jinja2/includes/header-main-nav.html, kuma/humans/models.py, kuma/javascript/src/bcd-signal.jsx, kuma/javascript/src/header/__snapshots__/header.test.js.snap, kuma/javascript/src/header/main-menu.jsx, kuma/javascript/src/index.jsx, kuma/javascript/src/live-examples.js, kuma/landing/jinja2/landing/homepage.html, kuma/landing/jinja2/landing/react_homepage.html, kuma/static/styles/components/wiki/_indicators.scss, kuma/wiki/management/commands/correct_current_revision_documents.py, package.json, scripts/record_deployments.py
=> Edit all reference to github mozilla/kuma to mdn/kuma 

kuma/wiki/admin.py
=> 504 errors in Admin console

kuma/wiki/jinja2/wiki/react_document.html, kuma/wiki/views/document.py
=> Legacy namespace documents not indexed/followed

kuma/search/tests/test_views.py, kuma/search/urls.py, kuma/search/views.py
Fixes #5957
Might be a better way to do this, but this provides the expected results as commented [here](https://github.com/mdn/kuma/issues/5957#issuecomment-545433404)
=> Search json endpoint redirect

jinja2/includes/react_google_analytics.html, jinja2/react_base.html, kuma/wiki/jinja2/wiki/react_document.html
=> avoid request.user usage in react_base.html

kuma/javascript/src/user-provider.jsx
Fixes #6052 
This has been tested locally.
=> fix GA send pageview callback for React

.gitignore, docs/development.rst
=> simplify section on customizing Docker env

package-lock.json, package.json
Fixes #6049
Perhaps a bigger and better solution is to switch to [`lint-staged`](https://github.com/okonet/lint-staged) to run `eslint`, `stylelint`, and `prettier`. One thing at a time I guess.
=> use pretty-quick

kuma/javascript/src/error-boundaries.jsx, package-lock.json, package.json
Fixes #5930 
I've also updated flow, which was outdated by a couple of months. Newer versions tend to run more stable and every now and then add some clever inference. Nothing was broken during the update.
=> Flow types for error boundaries

.prettierignore, kuma/settings/common.py, kuma/static/js/components/user-signup/signup.js, kuma/static/styles/minimalist/atoms/_mixins-buttons.scss, kuma/static/styles/minimalist/atoms/_mixins-forms.scss, kuma/static/styles/minimalist/components/_auth-service-header.scss, kuma/static/styles/minimalist/components/_auth-signup-form.scss, kuma/static/styles/minimalist/structure/signup-flow.scss, kuma/static/styles/minimalist/vars/_vars-color-palette.scss, kuma/users/jinja2/socialaccount/base_signup.html, kuma/users/jinja2/socialaccount/includes/change_email_address.html, kuma/users/jinja2/socialaccount/includes/change_username.html, kuma/users/jinja2/socialaccount/includes/email_choices.html, kuma/users/jinja2/socialaccount/signup.html, kuma/users/signup.py, kuma/users/templatetags/jinja_helpers.py, kuma/users/tests/test_templates.py, kuma/users/tests/test_views.py, kuma/users/views.py, requirements/default.txt
There is quite a bit that changes here. To confirm that signup works as expected, follow the user flows detailed below.
Before you start, ensure you are in a new private window or user profile where you are not logged into either your local instance of Kuma or Github
1. Load up the landing page of MDN Web Docs
2. Click on the `Sign in` link at the top right of the page
3. You will be directed to Github and asked to sign in to authorize
4. For this, you can use the mdnwebdocs-tester account (Ask me if you do not have the details. Not sure if we have a way of sharing this info securely. Perhaps with keybase.io?)
5. After authorizing with Github and the needed verification via GMail you will be sent back to MDN, and should see the following:
6. Click the "Create profile" button without …
=> Fixes #5909 provide sensible defaults new user signup

kuma/settings/common.py
=> Newsletter JS should load deferred

kuma/redirects/redirects.py, tests/headless/map_301.py
=> add more ext-workshop redirects

kuma/api/v1/tests/test_views.py, kuma/api/v1/urls.py, kuma/api/v1/views.py, kuma/users/templatetags/jinja_helpers.py, kuma/users/tests/test_helpers.py
=> add endpoint and Jinja helper for username check

kuma/core/i18n.py, kuma/wiki/templatetags/jinja_helpers.py, kuma/wiki/templatetags/ssr.py
=> use functools.lru_cache instead

kuma/attachments/feeds.py, kuma/attachments/utils.py, kuma/authkeys/admin.py, kuma/authkeys/models.py, kuma/authkeys/tests/test_decorators.py, kuma/authkeys/tests/test_views.py, kuma/core/decorators.py, kuma/core/jobs.py, kuma/core/managers.py, kuma/core/middleware.py, kuma/core/models.py, kuma/core/tests/test_locale_middleware.py, kuma/core/utils.py, kuma/feeder/management/commands/update_feeds.py, kuma/feeder/models.py
Part of #6129
Turns out there's a LOT more of these. 
I could go on or just take a break with what I've got. Large PRs suck. This breaks it up a little.
=> f-strings as much as possible

requirements/default.txt
I can't even remember why I started doing this upgrade! Sorry. Either way, it seems to work. 
`docker-compose exec web ./manage.py shell_plus` tests the `shell_plus` feature.
=> django-extensions 2.2.5

kuma/settings/common.py, kuma/static/styles/minimalist/components/_auth-signup-form.scss, kuma/users/jinja2/socialaccount/signup.html
@escattone r?
Add the following to your `.env`
```
ENABLE_NEWSLETTER_SIGNUP=True
```
@Gregoor just an FYI for when you do the backend
=> Fixes #6040, add newsletter signup checkbox to signup

README.rst
Changed P1/ P2 bug links from Bugzilla to Github.
=> Fixes #6114

kuma/api/v1/tests/test_views.py, kuma/search/serializers.py, kuma/search/tests/test_serializers.py, kuma/search/views.py, kuma/settings/common.py
=> Render 400 page when search query too large

kuma/javascript/src/live-examples.js
Fixes #6161
Jump straight to [this comment](https://github.com/mdn/kuma/issues/6161#issuecomment-561805170) to see what the problem is. The [next comment](https://github.com/mdn/kuma/issues/6161#issuecomment-561805517) demonstrates the solution.
=> scoop up the right pre elements' text content

docs/assets.rst, kuma/core/middleware.py, kuma/core/tests/test_middleware.py, kuma/settings/common.py
=> serving static files on attachment domain

docker/images/kuma_base/Dockerfile
=> Node 12 in Kuma

kuma/attachments/forms.py, kuma/attachments/tests/test_views.py, kuma/attachments/views.py
=> allow image/svg uploads for staff

kuma/users/templatetags/jinja_helpers.py, kuma/users/tests/test_helpers.py
Fixes #6235 
This is blocking pushes.
=> exclude Persona social accounts when getting avatar URL

kuma/redirects/redirects.py, tests/headless/map_301.py
=> add redirect for AMO Features Extensions policies

kuma/landing/jinja2/landing/react_homepage.html
=> landing styles in site_css block

kuma/static/styles/base/_icons.scss, kuma/static/styles/includes/_mixins_indicators.scss
=> fix(styles): Remove now unnecessary `display: none;` declaration

kuma/settings/common.py, kuma/static/js/components/modal.js
@peterbe Switched to `defer` and updates comment.
Fixes #6275
=> Load modal js as defer

kuma/javascript/src/header/login.jsx
=> multi-auth link should contain current locale

docs/data.rst, docs/troubleshooting.rst
Added instructions to fix two issues I ran into while setting up my local environment:
1. KumaScript macros not evaluating
2. Scraping missing documents
=> Update Troubleshooting section in Kuma Docs 

kuma/static/js/components/modal.js, kuma/static/js/components/user-signup/auth-modal.js
=> esc key should close auth modal

docs/elasticsearch.rst
Update instructions per our Slack convo: https://mozilla.slack.com/archives/CLTBV3W9X/p1578358816108100
=> Update search index instructions

.env-dist.dev
- Update `DOMAIN` to match what @escattone provided for my .env file 
- Add other values that Ryan provided that I think might be relevant 
Closes #6187
=> Update env-dist file

kuma/users/jinja2/users/user_edit.html
Fixes #6026 - This now removes the copy as decided here https://github.com/mdn/kuma/issues/6026#issuecomment-572075144 ~ @Gregoor r?
=> Remove copy below user avatar, edit profile

kuma/wiki/content.py, kuma/wiki/tests/test_content.py
=> avoid TypeError in get_seo_description

kuma/javascript/src/article.jsx
Fixes #6251 
Fixes #6308
Looks like I was erroneously showing the message for non-existent content before!
=> Use correct message for outdated content

kuma/users/tests/test_templates.py, kuma/users/tests/test_views.py
@peterbe This adds some basic tests for the new signin landing page r?
fix #6024
=> Add tests for signin landing page

jinja2/includes/auth-modal-content.html, kuma/users/jinja2/socialaccount/base_signup.html
=> remove 'MDN Profile' wording

docs/installation.rst
- Change `localhost:8000` to `localhost.org:8000`
- Update command to add social auth 
- Add Docker instructions
=> Update Installation instructions

kuma/static/styles/minimalist/components/_auth-providers.scss, package-lock.json, package.json
=> Remove focus outline on modal

kuma/static/styles/minimalist/components/_search-widget.scss
=> Remove blue outline from search input on focus

kuma/wiki/management/commands/render_document.py
So many times I've had to rerender a bunch of documents and when I do that I often inject a little `docs=docs.filter(slug__startswith='Web/CSS')` or something. Then I have to remember to remove that line. 
Just thought I'd finally throw it into master.
=> render_document with --slugsearch

kuma/api/v1/tests/test_views.py, kuma/conftest.py, kuma/settings/common.py, kuma/settings/testing.py, kuma/wiki/tests/test_jobs.py, kuma/wiki/tests/test_views_edit.py
=> always clear cache between pytests

kuma/users/jinja2/socialaccount/signup.html, kuma/users/tests/test_templates.py
=> Update MDN Profile to MDN Account

kuma/users/tests/__init__.py, kuma/users/tests/test_views.py, kuma/users/views.py
Fixes #6396
What used to become a problematic empty string now becomes this:
=> suggest an incremented username on clashes

docker/images/kuma_base/Dockerfile
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md
=> Update to the latest Node LTS (12.13.1 -> 12.16.0)

kuma/users/admin.py
Fixes #6485
To reproduce, before checking out this branch go to:
http://localhost.org:8000/admin/users/user/?q=anything 
That'll break, and this PR fixes it.
=> don't search on user tags

kuma/static/js/components/user-signup/signup.js, kuma/static/styles/minimalist/components/_auth-service-header.scss, kuma/users/jinja2/socialaccount/signup.html
Fixes #6483 
Tested with and without multi auth enabled.
=> Do not show avatar transition on signup

poetry.lock
- Updating boto3 (1.11.14 -> 1.11.17)
https://github.com/boto/boto3/blob/1.11.17/CHANGELOG.rst
- Updating botocore (1.14.14 -> 1.14.17)
https://github.com/boto/botocore/blob/1.14.17/CHANGELOG.rst
- Updating google-auth (1.11.0 -> 1.11.1)
https://github.com/googleapis/google-auth-library-python/blob/v1.11.1/CHANGELOG.md
=> Routine dependency updates

kuma/wiki/constants.py
=> noindex of MDN/Jobs

kuma/users/jinja2/users/includes/delete-user-content.html, kuma/users/views.py
Part of #6479
Combined with https://github.com/mdn/kuma/pull/6482 these two PRs should resolve #6479. We'll have to close it manually when PRs are merged. 
Here's what it looks like:
=> ask about attachment revisions before deleting self

kuma/core/ga_tracking.py, kuma/users/tests/test_views.py, kuma/users/views.py
=> send GA events on errors when editing new profile

scripts/revise/revise.py
Discovered that I had the wrong order of the files in the underlying `git diff` when running the `revise diff ...` command. Simple fix.
=> simple fix of "revise diff ..." command

kuma/users/utils.py
Fixes #6527 
I didn't realize that the [`default_source`](https://stripe.com/docs/api/invoices/create#create_invoice-default_source) field was polymorphic and could also be of a Source type. It _could_ also have other types than the two handled here, but let's not get paranoid 🙊
=> Retrieve stripe card from source if it's not already a card

.editorconfig
Indentation not ~Indentiation~
=> Typo repair only

kuma/javascript/src/header/main-menu.jsx
=> Correct small typo in event name within comment

kuma/wiki/views/translate.py
=> submit translation on soft-deleted parent

kuma/wiki/tests/test_views_akismet.py
=> make test_spam_no_permission less fragile

kuma/javascript/src/index.jsx
=> Correct small typo in property name in comment

kuma/wiki/views/delete.py
=> Possibly to prefill Reason textarea on $delete

tests/headless/__init__.py
Simple adjustment to the integration tests that I missed when reviewing #6502.
=> fix robots headless test for wiki domain

docker-compose.yml, docker/images/kuma_base/Dockerfile, docs/development.rst, pytest.ini
=> Improve handling of Python warnings

jinja2/includes/google_analytics.html, jinja2/includes/react_google_analytics.html
The async tag did not impact performance, so adding it back in per the original ticket, #6253. 
Reverts https://github.com/mdn/kuma/pull/6601
=> Re-introduce async GA tag

kuma/javascript/src/router.jsx
I contend that this is a better approach than https://github.com/mdn/kuma/pull/6628 
This PR kills two birds with one stone:
1. If the `<Router />` is called with a truthy `initialData` (which happens to all our current routes) the `loading` state is set to `false` on inception. 
2. Today we have only [exactly 2 routes](https://github.com/mdn/kuma/blob/bcbc20828c16de808e4417771dc6bbd88f0e006c/kuma/javascript/src/single-page-app.jsx#L20) and they are similar in that they always get mounted with initial data. We will soon add another route (e.g. `SubscriptionLandingRoute`) and it won't have initial data or even need to get data from the server. But it'll still need to satisfy the `Route` class interface and have a `fetch` method but it can be `return Promise.resolve(null)`. 
When I was …
=> not tying loading to data

kuma/users/jinja2/users/includes/stripe_subscription.html
=> Update subscription copy on edit profile

kuma/static/styles/minimalist/main.scss
=> Adds missing newsletter styling to minimalist

kuma/api/v1/tests/test_views.py, kuma/api/v1/views.py
Fixes #6728 
This is backend only. Btw Tobin is there a separate task for me also wiring up the new stripe modal with this data? Or is it part of #6728?
=> Add user email to the whoami endpoint

jinja2/includes/config.html, jinja2/includes/style.html, kuma/javascript/src/payments/index.jsx, kuma/javascript/src/payments/subscription-form.jsx, kuma/payments/jinja2/payments/index.html, kuma/settings/common.py, kuma/static/styles/components/payments/_page.scss, kuma/static/styles/minimalist/components/subscriptions/_subscription-form.scss, kuma/static/styles/minimalist/components/subscriptions/_subscriptions-base.scss, kuma/static/styles/minimalist/components/subscriptions/subscriptions.scss, kuma/static/styles/minimalist/molecules/_buttons.scss, kuma/static/styles/minimalist/vars/_vars-color-palette.scss
This concludes the UI portion of #6578 
NOTE: We will not show the component for mobile and tablet
@Gregoor let's take this thing over the finish line :)
I _think_ that might be the only missing pieces.
=> Add embedded subscription form to subscription landing page

tests/headless/test_endpoints.py
=> fix test of contribute redirect

kuma/users/providers/github/views.py, kuma/users/providers/google/views.py, kuma/users/tests/__init__.py, kuma/users/tests/test_views.py
Part of #6759
I hope the code comment is sufficient to explain the rationale of this PR. 
Note that this doesn't close the issue.
=> comment out auth-started GA event for now

kuma/payments/tests/test_views.py, scripts/ci-python
Fixes https://github.com/mdn/kuma/issues/6797
=> start ssr servie after 'make build-static' for CI

kuma/javascript/src/active-banner.jsx, kuma/static/styles/components/banners/mdn-subscriptions.scss
Updates copy for the subscription banner. Also updates the link to point to the subscription landing page.
@Gregoor r?
fixes #6772
=> Update subscription banner copy and link

kuma/javascript/src/active-banner.jsx, kuma/javascript/src/active-banner.test.js
=> subscription banner divorced from auth state

kuma/javascript/src/payments/subheaders/signup.jsx, kuma/payments/tests/test_views.py
=> Removed colon before MDN member number subscriptions flow

kuma/settings/common.py, kuma/users/views.py, kuma/wiki/events.py, kuma/wiki/tests/test_templates.py
=> remove EMAIL_LIST_SPAM_WATCH from constance

kuma/settings/common.py, kuma/users/models.py, kuma/users/views.py
Part of #6848
I checked in prod, about the default:
```
>>> from constance import config
>>> config.BETA_GROUP_NAME
'Beta Testers'
>>>
```
=> replace constance BETA_GROUP_NAME to settings

kuma/javascript/src/payments/subheaders/thank-you.jsx, kuma/javascript/src/payments/subscription-form.jsx, kuma/static/styles/minimalist/components/subscriptions/_subscription-form.scss
Also removed colon from subtitle that was missed in pr 6868. Worked on this with @mindy.
=> Revised /mo formatting

.gitattributes
=> Revert "Add .gitattributes for keeping LF EOL for all text"

kuma/settings/common.py, kuma/users/tasks.py
Part of #6848
Here's how I checked the default value from prod:
```
>>> from constance import config
>>> config.WELCOME_EMAIL_FROM
'Janet Swisher <no-reply@mozilla.org>'
```
=> move WELCOME_EMAIL_FROM to settings

scripts/ci-flow, scripts/ci-jest
=> use yarn test instead of npm test

jinja2/includes/header-main-nav.html
=> link to github issues /new/choose

kuma/api/v1/tests/test_views.py, kuma/api/v1/urls.py, kuma/api/v1/views.py
=> Clean away api.v1.views.get_user

kuma/payments/tests/test_views.py, kuma/payments/urls.py, kuma/payments/views.py
=> redirect to new subscription management page

kuma/wiki/tests/test_views_translate.py, kuma/wiki/views/translate.py
Fixes #6970
Steps to test. 
1. Make sure you're on the `master` branch
2. Go to http://wiki.localhost.org:8000/en-US/docs/Learn/Getting_started_with_the_web
3. Click to add translation 
4. Make the translation and **edit the slug** to a non-English one http://wiki.localhost.org:8000/en-US/docs/Learn/Getting_started_with_the_web$translate?tolocale=sv-SE **For example, set the slug to `Borja_med_webben`**
5. View it http://wiki.localhost.org:8000/sv-SE/docs/Learn/Borja_med_webben
6. Delete it http://wiki.localhost.org:8000/sv-SE/docs/Learn/Borja_med_webben$delete
7. Start over, **but** this time when you make that initial translation **don't** override the slug. Leave it in English. 
8. Expect an internal server error. 
9. Switch over to the branch in this PR. 
10. Works (!|?)
=> unable to translate with deleted tomb stone document with different slug

kuma/wiki/views/misc.py
Fixes #6754
See email from me about this.
=> limit response in $local/docs/get-documents

contribute.json, kuma/javascript/src/header/__snapshots__/header.test.js.snap, kuma/javascript/src/header/main-menu.jsx
=> github new issue link

docker/images/kuma_base/Dockerfile
Release notes can be seen here: https://github.com/mdn/kumascript/pull/1366
r? anybody?
=> Node 12.16.3

kuma/authkeys/tests/test_views.py, kuma/search/views.py, kuma/users/models.py, kuma/wiki/tests/test_ssr.py, poetry.lock, pyproject.toml
=> flake8 3.8.1

contribute.json
=> Our contribute.json is all sorts of wrong

Jenkinsfiles/default.groovy, kuma/authkeys/tests/test_views.py, kuma/search/views.py, kuma/users/models.py, kuma/wiki/tests/test_ssr.py, poetry.lock, pyproject.toml
This resolves #7048 and removes the test ran by docker-compose for a PR, since we already run the test on travisci this step is sort of redundant
=> Remove test for default pipeline

Jenkinsfiles/utils.groovy
Rename `target` to `target_file` this is a follow on fix for #7049
=> Rename target to target_file

Jenkinsfiles/standby-push.groovy, Jenkinsfiles/utils.groovy
Also sneaked in some changes to notify slack that its pushing to EKS and also removed the record deployment job for EKS
=> Set default argument for make when there are only 3 arguments

kuma/javascript/src/payments/components/incentives.jsx
=> Change wording for discounts on MDN Merch Store

kuma/static/styles/minimalist/components/_newsletter.scss
This resolves the problem with the BIG X :smile: 
@mindy r?
fix #7086
=> Set size for newsletter-hide

kuma/settings/pytest.py, kuma/users/newsletter/apps.py
Fix #7100 
The title says it all really
=> don't run sendinblue signal handlers and checks without config

kuma/settings/common.py
=> change default email email from

kuma/users/jinja2/users/email/welcome/html.ltxt, kuma/users/jinja2/users/email/welcome/plain.ltxt
=> welcome email deep links

jinja2/includes/footer/moz-footer.html, jinja2/react_base.html, kuma/javascript/src/footer.jsx
Fixes #7047
I tested it by opening:
* http://wiki.localhost.org:8000/en-US/docs/Web/HTML
* http://localhost.org:8000/en-US/
* http://localhost.org:8000/en-US/docs/Web/HTML
* http://localhost.org:8000/en-US/payments/
=> link to MDN swag store

kuma/javascript/src/payments/components/incentives.jsx
=> Change discount code text

kuma/api/v1/tests/test_views.py, kuma/users/jinja2/users/email/payment_received/plain.ltxt
=> about subscription management page in email

kuma/landing/views.py
=> allow robots to /*users/

kuma/settings/common.py
Fixes https://github.com/mdn/kuma/issues/7121
=> fix welcome email sender address

tests/headless/test_redirects.py
Remove debug statements inadvertently left-in from https://github.com/mdn/kuma/pull/7142. 🤦
=> remove debug statements

kuma/wiki/jinja2/wiki/react_document.html
=> Moving the preconnect directive up in wiki template

kuma/javascript/src/payments/pages/terms.jsx, kuma/javascript/src/payments/pages/terms.test.jsx, kuma/javascript/src/payments/routes.jsx, kuma/payments/jinja2/payments/terms.html
=> updating payment terms to reflect current functionality

kuma/users/admin.py
=> user admin and IsStripeCustomer

poetry.lock
Update Django to version `2.2.13`. I used the following to create this PR:
```sh
poetry update django
```
=> update django to 2.2.13

kuma/api/v1/tests/test_views.py, kuma/api/v1/views.py, kuma/javascript/src/user-provider.jsx
Fixes #7194
If you don't like what I called it in `user-provider.jsx` you can perhaps till go ahead and merge this (or make a counter PR) and fix it when you start using it.
=> wiki_contributions in whoami

poetry.lock, pyproject.toml
Adding `gunicorn[gevent]` and updating the newrelic python agent. I ran the following commands:
```
poetry add gunicorn[gevent]
poetry update newrelic
```
=> Install gevent and update newrelic package

docker/images/kuma_base/Dockerfile
Matches https://github.com/mdn/kumascript/pull/1386
=> Node 12.18.0

poetry.lock
Before trying to dig more into https://github.com/mdn/kuma/issues/6238 and https://github.com/mdn/kuma/issues/7247, let's update to the latest version of Celery. I used `poetry update celery` to generate this PR.
=> update celery to 4.4.5

kuma/settings/common.py
=> add application/x-python-serialize content-type

kuma/javascript/src/accountsettings/components/cancel-subscription-form.jsx, kuma/javascript/src/accountsettings/components/close-account-form.jsx, kuma/javascript/src/accountsettings/components/close-account-form.test.jsx, kuma/javascript/src/accountsettings/components/close-account.jsx, kuma/javascript/src/accountsettings/components/close-account.test.jsx, kuma/javascript/src/accountsettings/components/invitation.jsx, kuma/javascript/src/accountsettings/components/subscription-detail.jsx, kuma/javascript/src/accountsettings/components/subscription.test.jsx, kuma/javascript/src/accountsettings/pages/index.jsx, kuma/javascript/src/accountsettings/pages/index.test.jsx, kuma/static/styles/components/payments/_page.scss, kuma/static/styles/minimalist/atoms/_notifications.scss, kuma/static/styles/minimalist/components/accountsettings/_confirmation-form.scss, kuma/static/styles/minimalist/components/accountsettings/subscription.scss, kuma/static/styles/minimalist/pages/accountsettings.scss
This adds the UI for the close account component of account settings
fix #7174
=> Add UI for close account

docker/images/kuma_base/Dockerfile
Wanna be [as cool as kumascript](https://github.com/mdn/kumascript/pull/1402)
=> Node 12.18.2

docs/feature-toggles.rst, jinja2/includes/newsletter.html, kuma/core/migrations/0006_create_l10n_survey_banner_flag.py, kuma/javascript/src/active-banner.jsx, kuma/settings/common.py, kuma/static/styles/components/banners/l10n-survey.scss, kuma/wiki/jinja2/wiki/includes/banner-styles.html
Add new l10n survey banner behind the l10n_survey waffle flag
@Gregoor r? This should ideally go out today.
fix #7315
=> Add new l10n survey banner

kuma/redirects/redirects.py, tests/headless/map_301.py, tests/headless/test_redirects.py
=> redirect firefox accounts per mdn/kuma#7345

kuma/core/utils.py, kuma/users/adapters.py
=> retry on SMTPConnectError

kuma/javascript/src/active-banner.jsx
=> Order for which banner to show is unpredictable

kuma/javascript/src/header/main-menu.jsx
=> Fix JS errors in main menu

kuma/settings/common.py
=> update default WELCOME_EMAIL_FROM

kuma/users/jinja2/users/email/welcome/html.ltxt, kuma/users/jinja2/users/email/welcome/plain.ltxt
=> Reword the welcome email

.github/workflows/python-lints.yml
=> run python lint in GHA

kuma/static/js/wiki.js
https://eslint.org/docs/rules/no-prototype-builtins
=> fix eslint error

kuma/static/styles/minimalist/components/_main-nav.scss
Set main-menu z-index to 100
fix #7455
=> main menu z-index

docker/images/kuma_base/Dockerfile
Based on https://github.com/mdn/kumascript/pull/1416/files
=> node:12.18.3@sha256:1a97a0b0

README.rst
Fixes #7490
By replacing the Javscript Lints link with Javascript and SASS Lints link.
=> Update README.rst svg issue.

docker/images/kuma_base/Dockerfile, kuma/redirects/redirects.py, tests/headless/map_301.py, tests/headless/test_redirects.py
* add firefox source docs redirects
=> Add firefox source docs redirects (#7412)

docker/images/kuma_base/Dockerfile
Inspired by https://github.com/mdn/kumascript/pull/1429
=> node 12.19.0

kuma/static/styles/components/banners/developer-needs.scss, kuma/static/styles/minimalist/vars/_vars-color-palette.scss
Update to DNA banner UI to distinguish better from the previous banner.
fix #7581
=> update dna banner ui

kuma/landing/jinja2/landing/homepage.html, kuma/landing/jinja2/landing/react_homepage.html
=> remove link to MDN/Promote on home page

kuma/static/styles/minimalist/components/_search-widget.scss
Change the UI of the search input in the header to match Yari
fix #7648
=> fix: header search ui change

kuma/users/jinja2/users/user_detail.html
=> Remove "Recent Docs Activity" from View profile

jinja2/includes/header-toolbox.html
=> remove "Site Tools" menu from profile

kuma/users/views.py
Fixes #7672
That was easy! And it totally works.
=> change preferredlocale in the edit profile view

kuma/javascript/src/header/__snapshots__/header.test.js.snap, kuma/javascript/src/header/search.jsx
=> move icon in header search to the right

kuma/wiki/tests/test_views.py, kuma/wiki/views/legacy.py
=> Wrong redirect on localized home page

kuma/javascript/src/search-results-page.jsx
Fixes #7688
To understand this fix, read: https://github.com/mdn/kuma/issues/7688#issuecomment-747663872
=> use the search results' locale, not the current page

kuma/api/v1/decorators.py, kuma/api/v1/tests/test_views.py, kuma/api/v1/views.py
=> Add support for Cross-Origin search requests

kuma/static/styles/components/users/_user-head.scss
=> Fix mis-aligned .user-buttons items on MDN profile page

kuma/settings/common.py, kuma/wiki/models.py, kuma/wiki/signal_handlers.py, kuma/wiki/tasks.py, kuma/wiki/tests/test_templates.py, kuma/wiki/tests/test_views_revision.py
=> get rid of tidy_revision_content task

kuma/api/v1/tests/test_views.py, kuma/api/v1/views.py
Part of #7734
This, reduces the `cache.get(...)` calls from 16 down to 2.
=> optimize listing of waffle flags

jinja2/includes/header-main-nav.html, kuma/javascript/src/header/__snapshots__/header.test.js.snap, kuma/javascript/src/header/main-menu.jsx
Part of https://github.com/mdn/yari/issues/2525
=> Change the "Join the MDN Community" link in the global nav

docker/images/kuma_base/Dockerfile
=> use poetry 1.1.4 in docker

kuma/api/v1/search/__init__.py
some leftover comment from when I was experimenting with `multi_match`.
=> remove an outdated comment

kuma/api/v1/search/__init__.py, kuma/search/views.py
=> non-en-US searches

kuma/settings/common.py
Update the `locale` sub-module.
=> update locale sub-module

kuma/search/views.py
=> Search results presents the locale in the wrong case

scripts/ci-python
Hopefully, self-explanatory from the PR title and the git diff :)
=> remove TravisCI optimization hack

kuma/core/migrations/0012_create_common_survey_banner_switch.py, kuma/javascript/src/active-banner.jsx, kuma/javascript/src/active-banner.test.js, kuma/settings/common.py, kuma/static/styles/components/banners/base.scss, kuma/wiki/jinja2/wiki/includes/banner-styles.html
Adds the new learning web dev banner to the homepage.
Tablet and desktop only
fix #7787
=> fix: add new learning web dev banner

kuma/api/v1/search/__init__.py
Fixes #7789
Look at http://localhost.org:8000/api/v1/search?q=finding&locale=en-US before and after this branch. Collapse the `documents` key and look at the `suggestions` key.
=> return total for suggestions correctly

kuma/api/v1/forms.py, kuma/api/v1/tests/test_views.py, kuma/api/v1/urls.py, kuma/api/v1/views.py
Part of https://github.com/mdn/yari/issues/2505
=> Support account settings

kuma/api/v1/search/__init__.py, kuma/api/v1/tests/test_search.py
=> Let's CDN cache most site-search queries

kuma/users/views.py
it used to work *sometimes* before if you had a cookie already. 
Now, I tested it with a fresh new private window and used an email that would need to sign-up.
=> correctly generate csrftoken for sign-up

kuma/users/views.py
=> make sign-up work for private email GH accounts

poetry.lock
Update Django to 2.2.21 (security release).
=> update django to 2.2.21 (security release)

docker-compose.yml
Forgot to update the version of the compose file (see https://docs.docker.com/compose/compose-file/compose-versioning/#version-24).
=> must specify version 2.4 of compose files

kuma/users/jinja2/users/email/welcome/html.ltxt, kuma/users/jinja2/users/email/welcome/plain.ltxt
As promised, I've had a go at updating the MDN signup welcome mail, to better match today's MDN.
I have also tried to update the corresponding plain.ltxt file, although I'm not 100% sure if I've got that right.
LMK what you think. Thanks!
=> updating welcome email

kuma/api/v1/tests/test_views.py, kuma/api/v1/views.py
Fixes #7882
This is the before:
Let's remember to check back on [those graphs](https://one.newrelic.com/launcher/nr1-core.explorer?platform[accountId]=1807330&platform[timeRange][duration]=1800000&pane=eyJ0cmFuc2FjdGlvbklkIjoiNWIyMjU3NjU2MjU0NzI2MTZlNzM2MTYzNzQ2OTZmNmUyZjQ2NzU2ZTYzNzQ2OTZmNmUyZjZiNzU2ZDYxMmU2MTcwNjkyZTc2MzEyZTc2Njk2NTc3NzMzYTc3Njg2ZjYxNmQ2OTIyMmMyMjIyNWQiLCJuZXJkbGV0SWQiOiJhcG0tbmVyZGxldHMudHJhbnNhY3Rpb25zIiwiZW50aXR5SWQiOiJNVGd3TnpNek1IeEJVRTE4UVZCUVRFbERRVlJKVDA1OE56STVOamcwTmpnIn0&sidebars[0]=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5hY3Rpb25zIiwiZW50aXR5SWQiOiJNVGd3TnpNek1IeEJVRTE4UVZCUVRFbERRVlJKVDA1OE56STVOamcwTmpnIiwic2VsZWN0ZWROZXJkbGV0Ijp7Im5lcmRsZXRJZCI6ImFwbS1uZXJkbGV0cy50cmFuc2FjdGlvbnMifX0) after this change makes it into prod.
=> Let's stop sending waffle flags in whoami

.github/workflows/python-lints.yml, Makefile, kuma/settings/common.py
Forgot to remove these two unused SSR settings in https://github.com/mdn/kuma/pull/7825.
=> remove SSR settings

docker-compose.ssl.yml
Missed this when I opened #7916.
=> replace meinheld with gevent in docker-compose.ssl.yml

kuma/settings/common.py, kuma/settings/pytest.py
I noticed some of these unused settings yesterday, and wanted to clean them up before I leave.
=> remove settings that are no longer used

kuma/users/tasks.py, kuma/users/tests/test_tasks.py
"mdn_plus" is not part of the capabilites and therefore this was broken.
=> fix subscription state change
