mdn/kuma

CONTRIBUTING.md, Jenkinsfiles/stage-integration-tests.yml, Makefile, README.rst, contribute.json, docs/conf.py, docs/data.rst, docs/deploy.rst, docs/localization.rst, docs/tests-ui.rst, kuma/settings/common.py, scripts/run_functional_tests.sh, tests/conftest.py, tests/performance/smoke.py
This PR updates kuma to reflect the new domain name (actually a return to the old domain name!) for stage: `developer.allizom.org`.
=> bug 1431259: change stage domain to developer.allizom.org

jinja2/includes/preload.html
I currently have a few pages of MDN listed on the [performance dashboard](https://mozmeao-perf-dashboard.netlify.com/) I'm building for our team. Because I'm spending a fair bit of time looking at this, I was intrigued to see a noticable up-tick in both load times and bytes in, as you can see here:
After a bit of digging in the [web page test result](https://www.webpagetest.org/results.php?test=180403_16_4c356dcf4f3d6eb2c89cbb53d94a3cbf), I noticed that both `.woff` and `.woff2` files are being loaded, which seemed like a bug:
I think this PR should fix the issue because:
- Any browser that supports `.woff2` should no longer need `.woff` files.
- Any browser that supports `rel="preload"` should also support `.woff2`.
=> Only preload .woff2 font files

docs/deploy.rst, docs/localization.rst, kuma/settings/common.py
This updates the locale and kumascript submodules, and includes string update 2018.08, localizing the "View All" link in document history.
I haven't been following the documentation for updating localizable strings, because they've been slightly different when done as part of the deployment process. To get the docs in line with current reality, I've move the string update instructions into the deployment instructions, and used these to create this PR.
=> Pre-push 2018-04-05

kuma/core/templatetags/jinja_helpers.py, kuma/core/utils.py
[django-statici18n](https://github.com/zyegfryed/django-statici18n) is now using the locale name, such as ``en_US``, rather than the standardized language code, like ``en-US``. Replace that dash with an underscore, and update some utility functions to be clear about [locale names versus language codes](https://docs.djangoproject.com/en/1.11/topics/i18n/#definitions) (which may be important as we retire the custom locale middleware).
=> bug 1399639: Use locale name for statici18n path

kuma/core/decorators.py, kuma/core/tests/test_decorators.py, kuma/wiki/tests/test_views.py, kuma/wiki/views/document.py
Use a "no-cache" cache control header when redirecting to create a page, to avoid a loop where you have to wait for the cache to expire to see the new page. This also updates the ``shared_cache_control`` decorator to take no action if it detects the cache control header is set to no-cache.
=> bug 1431259: Don't cache the "create page" redirect

kuma/core/decorators.py, kuma/core/middleware.py, kuma/core/tests/test_locale_middleware.py, kuma/core/utils.py
This PR does the following:
- adds the shared cache control header to the locale redirects performed by `LocaleURLMiddleware`
- in the spirit of DRY, factors out the `add_shared_cache_control` function to use independently of the `shared_cache_control` decorator
- changes the `nocache` check to be an `or` of the no-cache and no-store cases (sorry, that was my mistake to suggest `and` when originally proposing the addition of no-store to the check)
=> bug 1431259: add cache control header to locale redirects

kuma/wiki/tests/test_views.py, kuma/wiki/views/document.py
This PR adjusts the `Cache-Control` header for documents. We will no longer cache if the user is logged-in or there are Kumascript errors. This should help with issues due to caching when a user deletes, restores, or re-renders a document.
=> bug 1431259: do not cache docs if logged-in user or ks errors

kuma/attachments/tests/test_views.py, kuma/authkeys/tests/test_views.py, kuma/core/tests/__init__.py, kuma/core/tests/test_decorators.py, kuma/core/tests/test_locale_middleware.py, kuma/core/tests/test_views.py, kuma/dashboards/tests/test_views.py, kuma/health/tests/test_views.py, kuma/landing/tests/test_views.py, kuma/search/tests/test_views.py, kuma/users/tests/test_tasks.py, kuma/users/tests/test_templates.py, kuma/users/tests/test_views.py, kuma/version/tests/test_views.py, kuma/wiki/tests/test_feeds.py, kuma/wiki/tests/test_templates.py, kuma/wiki/tests/test_views.py, kuma/wiki/tests/test_views_admin.py, kuma/wiki/tests/test_views_akismet.py, kuma/wiki/tests/test_views_create.py, kuma/wiki/tests/test_views_delete.py, kuma/wiki/tests/test_views_document.py, kuma/wiki/tests/test_views_edit.py, kuma/wiki/tests/test_views_list.py, kuma/wiki/tests/test_views_misc.py, kuma/wiki/tests/test_views_revision.py, kuma/wiki/tests/test_views_translate.py
This PR arose from @jwhitlock's [comment](https://github.com/mozilla/kuma/pull/4734#discussion_r180241870) in #4734 as well as @safwanrahman's earlier [comment](https://github.com/mozilla/kuma/pull/4719#discussion_r177575655). It creates two new test utility functions `assert_no_cache_header` and `assert_shared_cache_header`, and then replaces all groups of assertions that each encapsulates.
=> create/use test functions to encapsulate cache-control header assertions

kuma/attachments/tests/test_templates.py, kuma/attachments/tests/test_views.py, kuma/core/utils.py, kuma/dashboards/tests/test_views.py, kuma/users/tests/test_views.py, kuma/wiki/content.py, kuma/wiki/tests/test_content.py, kuma/wiki/tests/test_views.py, kuma/wiki/tests/test_views_document.py, kuma/wiki/views/document.py
This PR fixes [Bugzilla #1453796](https://bugzilla.mozilla.org/show_bug.cgi?id=1453796). The bug occurs when the `include` parameter is used during document requests, for example when using the `page` macro. The `include` parameter triggers a removal of all elements with `class="noinclude"`, which is done using `pyquery`, after which it re-generates the filtered HTML. During the re-generation of the HTML, any empty HTML elements (e.g., `<iframe ...></iframe>`) are output as self-closing elements (e.g., `<iframe ... />`), which in the case of `iframe`, is illegal. When loaded, the self-closing `iframe` seems to be interpreted as simply an opening tag, and so swallows all subsequent HTML.
For example, https://developer.mozilla.org/en-US/docs/Web/CSS/perspective?raw=1&macros=1&section=Setting …
=> bug 1453796: fix generation of HTML when filtering noincludes

requirements/constraints.txt, requirements/default.txt
Update celery and dependencies to prepare (again) for Celery 4.x update.
* celery 3.1.20 → 3.1.25: Support Task protocol 2 from 4.x
* billiard 3.3.0.22 → 3.3.0.23: Fix traceback wrapper
* kombu 3.0.33 → 3.0.37: Serialization, Redis fixes
* django-celery 3.1.17 → 3.2.2: Celery 4 compatibility
=> bug 1399639: Update to celery 3.1.25, deps

kuma/settings/common.py
After the change to AppConfig, search tasks are no longer auto-registering. Force the issue by using ``CELERY_IMPORTS``.
Other tasks (wiki, user, etc) are being auto-registered.
=> bug 1455652: Register async search tasks

jinja2/includes/preload.html
Saw this article[1] by Zach Leatherman, shard by Alex Gibson, and it was a real doh! moment. After reading the spec, it makes no sense to preload the Bold font variant. The recommended block time defined in the spec[2] is ~100ms with no swap time.
As the Bold variant take over 400ms to download(see below), preloading this on the first hit is a wasted HTTP request.
[1] https://www.zachleat.com/web/preload-font-display-optional/
[2] https://drafts.csswg.org/css-fonts-4/#valdef-font-face-font-display-optional
=> Do not preload fonts set as optional

kuma/wiki/jinja2/wiki/document.html
Google is ignoring the hreflang if the current page is not referenced
too.
This commit add the hreflang for the current page you are in top
of the already existing hreflang for the translations.
=> bug 1449210: Add hreflang for the current document

.travis.yml, kuma/core/tests/test_helpers.py, kuma/settings/common.py, requirements/constraints.txt, requirements/default.txt, tox.ini
According to the Jinja2 v2.9 changelog:
The with and autoescape tags are now built-in.
Thus I have removed them from the settings file.
Link: http://jinja.pocoo.org/docs/2.10/changelog/#version-2-9
=> [BUG: 1401246] Update jinja and django-jinja

kuma/static/js/dashboard.js
The process that extracts translations doesn't know JS. Change to call ``gettext`` with the string directly, rather than by variable.  Without this change, these strings ('Revert', 'View Page', etc) would be removed from Pontoon and https://github.com/mozilla-l10n/mdn-l10n/ the next time strings are extracted.
The code could be further simplified to eliminate ``actionsArray`` and the ``for`` loop, but I'm not sure if this was the first step in a longer refactor, such as passing the ``actionsArrays`` to the function.
=> bug 1451261: Translate action button text

jinja2/includes/login.html, kuma/users/tests/test_templates.py, kuma/users/urls.py, kuma/wiki/jinja2/wiki/includes/approvals.html, kuma/wiki/jinja2/wiki/includes/document_macros.html, kuma/wiki/tests/test_templates.py, kuma/wiki/views/document.py, kuma/wiki/views/revision.py
This PR removes `csrfmiddlewaretoken` from the responses of all endpoints that require caching in the CloudFront CDN, which ends up being just the `wiki.document` endpoint. This provides a possible solution to bug 1456165, since it avoids setting a new `csrftoken` cookie on `wiki.document` page loads due to the fact that the CDN behavior can't forward the existing one (it can't forward the existing `csrftoken` cookie without negating caching altogether for that behavior, since CloudFront does not provide separate configuration for caching and forwarding).
=> bug 1456165: remove csrfmiddlewaretoken from wiki.document view responses

kuma/settings/common.py, requirements/default.txt
Update to django-debreach 1.4.2, which adds support for Django 2.0. Then parse the Django version in settings, to avoid installing debreach, using the context processor, or the middleware in Django 1.10 or later, where Django has built-in mitigation of [BREACH](https://en.wikipedia.org/wiki/BREACH) and the debreach middleware raises an ``ImproperlyConfigured`` exception.
=> bug 1401246: Don't use django-debreach in Django 1.10 and later

kuma/settings/common.py
Session verification, which includes invalidating sessions after password changes, is enabled by default in Django 1.10. We don't use passwords, but session verification can still used, and enabling the
middleware will let us detect issues before 1.11 is used.
=> bug 1429933: Enable session verification

requirements/default.txt
* newrelic 2.96.0.80→3.2.0.91: Manadatory SSL, security issues with SQL analysis and tracing APIs, fix memory leaks.
=> bug 1399639: Update to newrelic 3.2.0.91

kuma/dashboards/tests/test_views.py, kuma/dashboards/views.py
Refactor the revision dashboard tests to remove some invalid test paths and get them to the new pytest standard. Then add a new test and a 1-line change that allows deleted documents to be shown on the revision dashboard, without the server error of [bug 1419419](https://bugzilla.mozilla.org/show_bug.cgi?id=1419419).
=> bug 1419419: Handle deleted documents on the revision dashboard

jinja2/includes/footer/moz-footer.html
The GitHub icon was accidentally used when converting to inline SVG.
=> bug 1451261: Use twitter icon for Mozilla twitter

docker-compose.yml, kuma/settings/common.py
Removed `CELERYD_LOG_LEVEL` from `kuma/settings/common.py `
Used `--loglevel` flag in `docker-compose.yml` command instead.
This does not completely remove the `RemovedInDjangoXXXWarnings`, since I haven't added the SessionAuthenticationMiddleware. [It is no longer required in Django 1.10 and Session verification is enabled regardless.](https://docs.djangoproject.com/en/2.0/releases/1.10/)
> Session verification is enabled regardless of whether or not 'django.contrib.auth.middleware.SessionAuthenticationMiddleware' is in MIDDLEWARE_CLASSES. SessionAuthenticationMiddleware no longer has any purpose and can be removed from MIDDLEWARE_CLASSES. It’s kept as a stub until Django 2.0 as a courtesy for users who don’t read this note.
=> [bug 1429933] remove depreciated CELERYD_LOG_LEVEL

kuma/users/views.py, requirements/default.txt
Update django-allauth to the current version, before updating our customization of the ``SignupView``.
In Django 1.8, ``django.views.generic.edit.FormMixin``'s method
[get_form()](https://docs.djangoproject.com/en/1.8/ref/class-based-views/mixins-editing/#django.views.generic.edit.FormMixin.get_form) changed so that ``form_class`` was no longer a required argument, but instead calls ``get_form_class()`` if it has the default value of ``None``.
In Django 1.8, this removes a deprecation warning. In Django 1.10, this fixes a runtime error.
=> bug 1429933: Update get_form to match upstream class

kuma/settings/common.py
Context processors moved from ``django.core.context_processors`` to ``django.template.context_processors`` in Django 1.8. This removes a deprecation warning in 1.8, and a run-time error in Django 1.10.
It also fixes a stray trailing comma in the ``!_NEED_DEBREACH`` path.
=> bug 1429933: Update context processor paths

kuma/core/tests/test_commands.py, kuma/dashboards/utils.py, kuma/scrape/tests/test_source.py
[PEP 352](https://www.python.org/dev/peps/pep-0352/) makes changes to exceptions, including:
* Python 2.5 added the ``BaseException`` class.
* Python 2.6 deprecated the ``message`` attribute.
* Python 3.0 removes the ``message`` attribute.
Instead of testing ``exception.message``, test ``str(exception)``. Also, convert some tests to pytest style.
=> bug 1429933: Avoid BaseException.message

kuma/wiki/tests/test_feeds.py
MySQL backend warns ``Warning: Column 'email' cannot be null``.
=> bug 1429933: Set email to empty string in test

kuma/core/tests/test_views.py
``SimpleTestCase.urls`` is deprecated in Django 1.8 and will be removed in Django 1.10.
=> bug 1429933: Use ROOT_URLCONF, not .urls

kuma/feeder/utils.py
Django 1.8 formalized the Model _meta API, and deprecated methods that were private but in common use. Following the [migration guide](https://docs.djangoproject.com/en/1.8/ref/models/meta/#migrating-from-the-old-api), switch from ``_meta.get_field_by_name`` to ``_meta.get_field``.
=> bug 1429933: Switch to _meta.get_field

requirements/constraints.txt, tests/conftest.py, tests/headless/test_cdn.py
This is the state of the browserless CDN tests after about 3 days. The tests cover every behavior in the CDN except for `static/*`, and cover a significant portion of the endpoints. There are certainly more tests that could be developed to check specific endpoints for cache variation based on specific headers or cookies or query parameters, but these are a decent start I think.
During the course of writing these tests, I found another bug with the current configuration of the CDN, namely that when editing based on a revision (e.g., https://developer.allizom.org/en-US/docs/Web/HTML$edit/1299417) the publish will be met with a permission-denied error. This is due to the fact that this endpoint bypasses the `*$edit` behavior, a pass-through behavior which forwards the `csrftoken` cookie, and …
=> bug 1431259: add headless tests for cdn

etc/newrelic.ini
The ``DisallowedHost`` exception is raised when a client's requested hostname does not match one of the accepted hostnames in [ALLOWED_HOSTS](https://docs.djangoproject.com/en/2.0/ref/settings/#allowed-hosts). This is common in AWS from security scanners searching AWS IP blocks, or when AWS allocates an IP address or EC2 instance that was owned by a previous website. There is no security risk or positive action that can be taken, so it should not result in New Relic alerts.
See [bug 1461209](https://bugzilla.mozilla.org/show_bug.cgi?id=1461209).
=> bug 1461209: Ignore DisallowedHost exception

kuma/core/tests/test_locale_middleware.py, kuma/core/tests/test_middleware.py, kuma/core/tests/test_urlresolvers.py
In preparation to update the locale infrastructure, expand tests for middleware and other components, and convert to pytest style:
* ``LocaleURLMiddleware``
- Convert tests to pytest.
- Test ``Accept-Language`` header variations from ``get_best_language``
- Add more ``?lang`` scenarios
- Add legacy locale redirect tests
- Add non-locale 404 tests
* ``RemoveSlashMiddleware`` - Convert tests to pytest. The test cases actually exercise the ``mindtouch_to_kuma_redirect`` view, and the middleware code never runs. The next PR will update the test cases and fix the functionality.
* ``SetRemoteAddrFromForwardedFor`` - Convert tests to pytest.
This was originally part of PR #4766, but has been split out to confirm that tests pass with ``LocaleURLMiddleware`` before replacing it.
=> bug 1461350: Update Middleware tests

tests/conftest.py, tests/headless/test_cdn.py
This PR fixes the headless tests such that they now successfully run against the local development instance loaded with a stock sample database.
- Add `is_local_url` and `is_searchable` fixtures.
- Use pytest's ability to [mark a test with `xfail` from within the test function](https://docs.pytest.org/en/latest/skipping.html#xfail-mark-test-functions-as-expected-to-fail). This was simpler than trying to create a dynamic fixture.
- Modify some URL's to work on both a local instance loaded with the stock sample database as well as the stage and production instances (e.g., `/en-US/docs/Web/HTML$revision/1252409` rather than `/en-US/docs/Web/HTML$revision/1293895`)
I also removed the `sensitive_url` fixture since it was unused.
=> bug 1431259: fix headless tests with localhost

kuma/core/middleware.py, kuma/core/tests/test_middleware.py, kuma/wiki/views/legacy.py
``is_valid_path`` always returns ``True``, because ``mindtouch_to_kuma_redirect`` is setup as a catch-all view that matches everything that didn't already match a pattern. In turn, ``mindtouch_to_kuma_redirect`` returns either 404s or permanent redirects.
The PR updates ``is_valid_path`` to detect that ``mindtouch_to_kuma_redirect`` was the resolved view, and then calls the refactored ``mindtouch_to_kuma_url`` to see if it would be a 404 or redirect. Since ``is_valid_path`` can now return ``False``, ``RemoveSlashMiddleware`` can actually remove slashes on URLs like ``/contribute.json/``.
There is a similar Django function ``is_valid_path`` that has the same issue detecting 404 URLs. We'll need this improved ``is_valid_path`` to use Django's locale redirect code.
=> bug 1461350: Improve is_valid_path

kuma/settings/testing.py
Avoid interacting with the runtime cache in tests by using the local memory cache for django cacheback, and by changing the cache key prefix in tests.
On current master, the tests update cached values, such as the zone remaps list:
```
www-data@d02dc8105233:/app$ ./manage.py shell_plus
>>> from kuma.wiki.jobs import DocumentZoneURLRemapsJob
>>> print DocumentZoneURLRemapsJob().get('en-US')
[(u'/docs/Web/Apps', u'/Apps'), (u'/docs/Mozilla/Firefox', u'/Firefox'), (u'/docs/Mozilla/Add-ons', u'/Add-ons')]
>>> exit()
www-data@d02dc8105233:/app$ pytest kuma/wiki/tests/test_views_list.py
www-data@d02dc8105233:/app$ ./manage.py shell_plus
>>> from kuma.wiki.jobs import DocumentZoneURLRemapsJob
>>> print DocumentZoneURLRemapsJob().get('en-US')
[(u'/docs/top', u'/fleetwood-mac'), …
```
=> bug 1461350: Avoid runtime cache in tests

kuma/wiki/middleware.py, kuma/wiki/tests/test_middleware.py
As a first step to retiring zoned URLs, use a ``302 Found`` redirect rather than a ``301 Permanently Moved`` redirect, so that we can prepare browsers and search engines for the change.
=> bug 1462479: Use non-permanent redirects for zones

kuma/core/urlresolvers.py, kuma/users/models.py, kuma/users/tests/__init__.py, kuma/users/tests/test_templates.py, kuma/wiki/tests/test_views.py
Remove extra parameters from Kuma's reverse call:
* ``prefix`` - No one used this
* ``force_locale`` - Forced locale prefix in URL, now default
* ``unprefixed`` - Forced no locale prefix in URL, now default for non-prefixed URLs.
Some now-dead code in ``test_edit_spam_ajax`` that were using these parameters is also removed.
=> bug 1461350: Remove extra reverse parameters

docs/tests.rst, kuma/core/tests/__init__.py, kuma/search/tests/__init__.py, kuma/users/tests/test_adapters.py, kuma/users/tests/test_templates.py, kuma/users/tests/test_views.py, kuma/wiki/tests/test_templates.py, kuma/wiki/tests/test_views.py
With the ``LocaleMiddleware``, the default is to include the locale prefix in URLs, so the ``LocalizingMixin`` and ``LocalizingClient`` are no longer needed.
The ``SessionAwareClient`` included code from Django 1.7, and was probably added when MDN was on Django 1.4 or earlier, and is included in the default 1.8 test client:
https://github.com/django/django/blob/6a0dc2176f4ebf907e124d433411e52bba39a28e/django/test/client.py#L411-L426
=> bug 1461350: Simplify test client

tests/headless/map_301.py
This PR fixes the `test_legacy_urls` test for the URL `/cn/docs/Talk:Kakurady`.
=> bug 1461350: fix headless redirect test

kuma/attachments/tests/test_templates.py, kuma/attachments/tests/test_views.py, kuma/authkeys/tests/test_views.py, kuma/conftest.py, kuma/core/tests/test_views.py, kuma/dashboards/tests/test_views.py, kuma/landing/tests/test_views.py, kuma/search/store.py, kuma/search/tests/test_views.py, kuma/users/adapters.py, kuma/users/providers/github/views.py, kuma/users/tests/__init__.py, kuma/users/tests/test_adapters.py, kuma/users/tests/test_tasks.py, kuma/users/tests/test_templates.py, kuma/users/tests/test_views.py, kuma/wiki/tests/conftest.py, kuma/wiki/tests/test_feeds.py, kuma/wiki/tests/test_templates.py, kuma/wiki/tests/test_views.py, kuma/wiki/tests/test_views_akismet.py, kuma/wiki/tests/test_views_code.py, kuma/wiki/tests/test_views_create.py, kuma/wiki/tests/test_views_delete.py, kuma/wiki/tests/test_views_document.py, kuma/wiki/tests/test_views_edit.py, kuma/wiki/tests/test_views_list.py, kuma/wiki/tests/test_views_misc.py, kuma/wiki/tests/test_views_revision.py, kuma/wiki/tests/test_views_translate.py
When using Kuma's ``reverse``, don't pass ``locale="en-US"`` (common in tests to avoid a redirect) or ``locale=request.LANGUAGE_CODE`` (used in app code to avoid a redirect), but instead rely on the default behavior of including the active language.
Continue passing the locale parameter for non-default locales, or if the test makes a request that sets the active language (usually by making a request to a non-default locale).
The active language is reset to en-US at the start of each test with an always-run fixture ``set_default_language``.
=> bug 1461350: Default to locale=en-US in tests

Makefile, docker/images/kuma_base/Dockerfile, docker/images/kuma_base/Dockerfile-1.10, docker/images/kuma_base/Dockerfile-1.11, docker/images/kuma_base/Dockerfile-1.9
[bug 1301116](https://bugzilla.mozilla.org/show_bug.cgi?id=1301116) was about an issue running ``./manage.py extract`` with the Ubuntu image. Now that we're on a Python image and two years have passed, it appears it is no longer needed.
There's a gross warning about ``/usr/local/lib/python2.7/site-packages/backports/__init__.py`` that is caused by configparser 3.5.0 (see https://bitbucket.org/ambv/configparser/issues/20/importwarning-missing-__init__py and https://bitbucket.org/brandon/backports/issues/5/missing-__init__py). Until it is fixed, it is easy enough to avoid it by touching that file.
I'm often creating a Docker image with Django 1.9 and 1.11 in it, by changing the Django version in ``requirements/default.txt``, and running ``VERSION=django-1.9 make build-base``. I'm adding a …
=> bug 1301116, 1401246: Dockerfile updates for Django update

kuma/core/middleware.py, kuma/core/tests/test_middleware.py, kuma/settings/common.py
Convert ``RemoveSlashMiddleware`` to look at cases where adding a slash would also make a valid URL, such as ``/en-US`` or ``/admin``.
The ``CommonMiddleware`` would do this work, except that ``is_valid_url`` always returns ``True`` due to the catch-all view ``mindtouch_to_kuma_redirect``. It is easier to customize ``CommonMiddleware`` in Django 1.9 and later, and eliminating ``mindtouch_to_kuma_redirect`` is also an option for future work.
=> bug 1461350: Add slashes in SlashMiddleware

requirements/default.txt, requirements/dev.txt
Upgrade `puente` and `django-babel` to the latest versions (0.5.0 and 0.6.2, respectively). This has been tested locally such that `docker-compose exec web ./manage.py extract` works all of the way to Django 1.11 (ensure the `django.pot` and `javascript.pot` files remain unchanged).
=> bug 1401246: upgrade django-babel and puente

kuma/wiki/feeds.py
This prepares the `DocumentJSONFeedGenerator` class for the post-Django-1.8 world, while still working as things stand today.
=> bug 1401246: get DocumentJSONFeedGenerator ready for Django 1.9

kuma/spam/tests/conftest.py, kuma/spam/tests/test_akismet.py, kuma/spam/tests/test_forms.py
This PR prepares the tests under ~~`kuma/spam/tests/test_akismet.py::AkismetClientTests`~~ `kuma/spam/tests` for Django 1.9. It seems Django 1.9, with its new `allow_database_queries` class-level `SimpleTestCase` attribute, is better at detecting the DB writes from `constance.test.override_config`. The tests within `kuma/spam/tests/test_akismet.py::AkismetClientTests` should have sub-classed `django.test.TestCase` rather than `django.test.SimpleTestCase` all along.
=> bug 1401246: prepare spam tests for Django 1.9+

kuma/wiki/views/document.py, kuma/wiki/views/list.py
Fixing all the `select_related` queryset to get compataibility with django 1.9+.
It seems to be a bug in django code that let selecting non related fields by `select_related` as it was fetching the whole object instead of the fields only.
The actual use case would be using `only` for limiting fetch fields instead of full object. In all of our use case, it seems that we are covered with `only`.
@jwhitlock @escattone r?
=> [Bug 1401246] Fixing select_related to select only foreignkey fields

kuma/urls_untrusted.py, kuma/wiki/tests/test_views_code.py, kuma/wiki/urls_untrusted.py
Update the URLs for the attachment host to ensure that code samples and file attachments are processed with locale prefixes.
This adds a test ``test_code_sample_host_restricted_host`` that confirms that a code sample can be viewed with ``ENABLED_RESTRICTIONS_BY_HOST``. This test fails before this change. Other tests are split up so they test a single configuration.
The urls cache is set when the ``RestrictedEndpointsMiddleware`` overrides the urlconf. Django's [SimpleTestCase](https://github.com/django/django/blob/6a0dc2176f4ebf907e124d433411e52bba39a28e/django/test/testcases.py#L217-L228) has code to reset this cache, but pytest doesn't [unless mark.urls is used](https://github.com/pytest-dev/pytest-django/blob/a67ab3bd0eda8a2b76b4c5954b04482b4f27e20a/pytest_django/plugin.py#L447-L473). …
=> bug 1461350: Update URLs for attachment host

kuma/core/middleware.py, kuma/core/tests/__init__.py, kuma/core/tests/test_locale_middleware.py, kuma/settings/common.py, kuma/urls.py, kuma/wiki/feeds.py, kuma/wiki/tests/test_middleware.py, kuma/wiki/tests/test_templates.py, kuma/wiki/tests/test_views.py, kuma/wiki/tests/test_views_code.py
This PR centralizes Django version detection in settings, because I was getting tired of duplicating the same two imports across the code. If desired, this can be pulled into a new PR, or removed.
In Django 1.9, [HTTP redirects are no longer converted to absolute URIs](https://docs.djangoproject.com/en/2.0/releases/1.9/#http-redirects-no-longer-forced-to-absolute-uris). Absolute URIs, such as ``https://developer.mozilla.org/en-US/docs/Web/JavaScript``, were a requirement with [RFC 2616](https://tools.ietf.org/html/rfc2616.html). Relative URIs, such as ``/en-US/docs/Web/JavaScript``, are allowed in the ``Location`` header with [RFC 7231](https://docs.djangoproject.com/en/2.0/releases/1.9/#http-redirects-no-longer-forced-to-absolute-uris). Django 1.8 still forces absolute URIs.
This PR …
=> bug 1401246: Use relative URIs for redirects in Django 1.9 and later

kuma/core/middleware.py, kuma/core/tests/test_locale_middleware.py
The ``LangSelectorMiddleware`` preserves query string parameters other than ``lang=<locale>``. PR #4807 (use relative references in redirect) introduced a bug, where extra querystring parameters would raise an ``AttributeError`` and return a 500 error. Add a test to exercise this branch, and fix the
bug.
=> bug 1401246: Fix query params in lang selector

.travis.yml
Use ``PYTHONHASHSEED=0`` in the Django 1.9, 1.10, and 1.11 jobs, to mirror the standard 1.8 build. This avoids test failures due to random behavior, such as key order in dictionaries, which are covered by a different optional TravisCI build.
Related to PR #4806.
=> bug 1401246: Use random seed in Django 1.9+ jobs

kuma/core/views.py
This simple PR eliminates about 176 of the following warnings from the Django 1.9 test run:
```
RemovedInDjango20Warning: Error handlers should accept an exception parameter. Update your code as this parameter will be required in Django 2.0
```
I considered, and actually implemented, the option of simply removing all of the custom error handlers, since Django will automatically use our custom `403.html`, `404.html`, and `500.html` templates. I decided against that approach, at least for now, because we lost our custom `Cache-Control` header (set with the `never_cache` decorator) for those error responses. It is true that our CloudFront CDN is configured to never cache `403`s, `404`s, and `500`s, but it seems important to make that explicit in the `Cache-Control` header as well. We could …
=> bug 1401246: avoid error-handler exception-argument warnings

kuma/settings/common.py, kuma/wiki/tests/test_views_document.py, kuma/wiki/views/document.py
This PR gets the `kuma/wiki/tests/test_views_document.py` tests running (or skipped) through to Django 1.11.
- PUT requests with an `If-Match` header (done via the `wiki.document.api` endpoint) are broken in 1.9 and 1.10, but work in 1.11 (with some minor additional changes). In Django 1.9 and 1.10, both the `ConditionalGetMiddleware` and the `CommonMiddleware` will incorrectly meddle with the response for conditional requests made with **any** HTTP method (they should only meddle with the response for conditional `GET`s, as is done starting in Django 1.11). So the `test_api_put_existing` tests using conditional `PUT`s are skipped in Django 1.9 and 1.10.
- Since conditional headers are only considered for `GET` requests starting in Django 1.11 (as long as `settings.USE_ETAGS` is False), I …
=> bug 1401246: fix test_views_document.py for Django 1.9+

kuma/conftest.py, kuma/dashboards/tests/test_views.py, kuma/spam/tests/conftest.py, kuma/users/tests/test_tasks.py, kuma/users/tests/test_templates.py, kuma/users/tests/test_views.py, kuma/wiki/tests/__init__.py, kuma/wiki/tests/test_admin.py, kuma/wiki/tests/test_forms.py, kuma/wiki/tests/test_views.py, kuma/wiki/tests/test_views_admin.py, kuma/wiki/tests/test_views_akismet.py, kuma/wiki/tests/test_views_code.py, kuma/wiki/tests/test_views_document.py, kuma/wiki/tests/test_views_misc.py, requirements/default.txt
* django-waffle 0.11 → 0.14.0: Significant caching improvements, fixes for management commands, update Django and Python support.
[Bug 1189160](https://bugzilla.mozilla.org/show_bug.cgi?id=1189160) was listed as a blocker (by me) for the Django 1.11 update, when I was hoping to get all the requirements up to date. I was expecting some breakage with this update, but tests pass, and browsing in the development environment appears to work. There doesn't appear to be any downside to this update.
=> bug 1189160: Update to django-waffle 0.14.0

kuma/core/middleware.py, kuma/core/tests/test_forms.py, kuma/core/tests/test_middleware.py, kuma/settings/common.py, kuma/wiki/middleware.py, kuma/wiki/tests/test_middleware.py
Now that #4821 has been merged, this PR updates the Kuma middleware in `kuma.core.middleware` and `kuma.wiki.middleware` to handle both the [new style](https://docs.djangoproject.com/en/2.0/releases/1.10/#new-style-middleware) and original style. All of the third-party middleware we currently use is already compatible with both styles, except for [the middleware of `django-redirect-urls`](https://github.com/pmac/django-redirect-urls/blob/master/redirect_urls/middleware.py). I've created a temporary shim (`kuma.core.middleware.RedirectsMiddleware`) to handle that until a new version is available with middleware compatible with both the new and original style.
This has been tested locally with Django 1.8, 1.9, 1.10, and 1.11.
Once we're on Django 1.11, we may want to consider re-writing our …
=> bug 1401246: make middleware work with MIDDLEWARE setting

kuma/wiki/tests/test_views_delete.py, kuma/wiki/tests/test_views_document.py
These lines stood out when I looked at the report from ``make coveragetesthtml``. It should be rare to have uncovered lines in test code.
=> bug 1401246: Remove non-covered code branches

kuma/authkeys/urls.py, kuma/users/urls.py
This eliminates a warning when running management commands under Django 1.11.
I missed this during PR #4764, because wow I wasn't expecting the user app to include URLs from the apices app.
=> bug 1401246: Move leading slashes for authkey URLs

kuma/wiki/migrations/0001_squashed_0036_update_locales.py
Django 1.9 adds a migration for the sites app, which means that there is a new latest migration, and attempting to run migrations raises an error:
```
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration wiki.0001_squashed_0036_update_locales is applied before its dependency sites.0002_alter_domain_unique on database 'default'.
```
Instead of using ``__latest__``, use the actual migration names from Django 1.8, so that migrations will run without errors.
=> bug 1401246: Pin Django app migrations

docs/development.rst, docs/docker.rst, docs/installation.rst
I skimmed the development documentation, running most of the commands against images with Django 1.11, by loading the django-1.11 branch, running ``VERSION=latest make build-base``, and [reseting my containers](https://kuma.readthedocs.io/en/latest/troubleshooting.html#reset-a-corrupt-database), including starting from a fresh MySQL. There were a few documentation issues I found while reviewing the docs, and I took the opportunity to fix them.
It appears that all of our development processes work with Django 1.11, after fixing an issue running migrations with Django 1.11 on a fresh database (PR #4827).  I also found some non-critical problems. There are non-covered lines in tests (PR #4825), and warnings about the URL patterns in the ``authkeys`` app (PR #4826).
We have some documentation …
=> bug 1401246: Update development docs

kuma/core/templatetags/jinja_helpers.py
[django-statici18n v1.3.0](https://github.com/zyegfryed/django-statici18n/blob/master/docs/changelog.rst#v130-2017-jan-19) uses the language code (``en-US``) in the path for the translation catalog in Django 1.10 and later. For 1.9 and earlier, it uses the locale code (``en_us``).
=> bug 1401246: Use language code in statici18n

kuma/settings/common.py
The default for Django errors (the "django" log) is to send them to the console and to mail admin. Set the handler for Django errors to just send them to the console.
=> bug 1401246: Don't email Django errors to admins

kuma/core/middleware.py, kuma/settings/common.py, requirements/default.txt
Upgrade `django-redirect-urls` to version 1.0, which supports Django 1.11+. Thanks @pmclanahan!
Tested locally with:
```sh
VERSION=latest make build-base
docker-compose up -d
docker-compose exec web make lint test
pytest --base-url http://localhost:8000 tests/headless
```
=> bug 1401246: upgrade to django-redirect-urls 1.0

kuma/core/management/commands/anonymize.py, kuma/core/management/commands/delete_old_ip_bans.py, kuma/feeder/management/commands/update_feeds.py, kuma/scrape/management/commands/sample_mdn.py, kuma/search/management/commands/reindex.py, kuma/wiki/management/commands/delete_old_revision_ips.py, kuma/wiki/management/commands/delete_old_spam_attempt_data.py, kuma/wiki/management/commands/refresh_wiki_caches.py, kuma/wiki/management/commands/render_document.py, requirements/default.txt
Several management commands are broken in Django 1.11, because the compatibility layer for the ``optparse`` to ``argparse`` transition was removed in Django 1.10.  Other commands were broken for a very long time. One command, ``./manage.py pop``, never worked. Finally, ``./manage.py pipchecker`` requires a third-party update.
Safe verification:
```
./manage.py anonymize --help
./manage.py delete_old_ip_bans --help
./manage.py delete_old_revision_ips --help
./manage.py delete_old_spam_attempt_data --help
./manage.py pipchecker --help
./manage.py refresh_wiki_caches --help
./manage.py reindex --help
./manage.py render_document --help
./manage.py update_feeds --help
```
Sort of safe:
```
./manage.py delete_old_ip_bans
./manage.py delete_old_revision_ips
./manage.py …
```
=> bug 1401246: Fix management commands for Django 1.11

Jenkinsfiles/push.groovy, docs/deploy.rst
Switches the active repo for MDN infrastructure from https://github.com/mozmeao/infra to https://github.com/mdn/infra.
=> bug 1466976: use mdn/infra instead of mozmeao/infra

jinja2/base.html, jinja2/includes/config.html, jinja2/includes/google_analytics.html, kuma/core/tests/test_views.py, requirements/default.txt
Make a few changes to try to handle the weird error in https://sentry.prod.mozaws.net/share/issue/37332e34333737383038/:
* Test that the server error page will render with a minimal ``request`` object.
* Test that ``request.user`` exists before calling ``request.user.is_authenticated()`` in templates included by ``500.html``.
* Update ``newrelic``, even though [the changes don't look relevant](https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes).
=> bug 1467513: Render server error page with minimal request

kuma/settings/common.py
**This PR should not be merged until we're ready to run [the experiment to extend the CDN caching TTL](https://github.com/mdn/sprints/issues/175).**
Changes the `s_maxage` setting of the `Cache-Control` header from 5 minutes to 24 hours for all of the endpoints with responses modified by `kuma.core.utils.add_shared_cache_control`. This setting is used in turn by MDN's CloudFront CDN to set the TTL period for its caching. This is an experiment, and will be reverted a short time (2-5 days) after it's merged and deployed.
=> bug 1431259: change cache TTL from 5min to 24hr (experiment)

kuma/core/i18n.py, kuma/core/middleware.py, kuma/core/tests/test_middleware.py, kuma/search/tests/__init__.py, kuma/wiki/middleware.py
I did some work on our Kuma middleware a short while ago, but when I realized it needed Django 1.11 in place, I shelved it. I thought it was useful, as it mostly embraced the new, ~~functional~~class-style of writing middleware (except `ReadOnlyMiddleware`), but it's real goal was to remove the dependency on `django.utils.deprecation.MiddlewareMixin` and go all-in with the new-style. I didn't want to lose the work, which wasn't totally finished, so I added what was missing and decided it was now or never.
=> bug 1401246: convert to new-style middleware

kuma/static/styles/components/wiki/interactive.scss
Fixes a bug with specificity of the tabbed editor styles.
=> bug 1468540: Prepend .interactive to tabbed editor classes to fix specificity bug

kuma/settings/common.py
**This PR ends [the experiment to extend the CDN caching TTL](https://github.com/mdn/sprints/issues/175).**
Reverts the `s_maxage` setting of the `Cache-Control` header from 24 hours back to 5 minutes (see #4845).
=> bug 1431259: change cache TTL from 24hr back to 5min

tests/headless/test_cdn.py
When submitting https://github.com/mdn/infra/pull/5 and https://github.com/mdn/infra/pull/6, I failed to update the headless CDN tests to reflect the addition of the `users*` behavior. This change affected the 4 locale-selection tests for the `/users/signin` slug. This PR updates the tests to reflect the CloudFront CDN changes on stage and production.
=> bug 1468414: update cdn tests to reflect new cdn config

.travis.yml, kuma/core/templatetags/jinja_helpers.py, kuma/core/tests/test_utils.py, kuma/core/utils.py, kuma/search/tests/test_utils.py, kuma/users/tests/test_adapters.py, kuma/wiki/content.py, kuma/wiki/templatetags/jinja_helpers.py, kuma/wiki/tests/test_content.py, kuma/wiki/tests/test_events.py, kuma/wiki/tests/test_feeds.py, kuma/wiki/tests/test_templates.py, kuma/wiki/tests/test_views.py
The kuma suite currently depends on dict order.
This is an attempt to remove this dependency, which would allow us to remove a considerable chunk of configuration and a better mirror of the real usage of the code.
=> Bug 1127798: Kuma test suite depends on dict order

scripts/record_deployments.py
``scripts/record_deployments.py`` takes the starting and ending commit hashes, as well as other parameters, and calls the APIs for New Relic and SpeedCurve to record a deployment.
It gets the API keys from the environment, to avoid printing them on the command line when calling the scripts. It assumes the New Relic application IDs and the SpeedCurve site ID are not sensitive information, and can be passed on the command line. 
I've tried this manually with the latest deployment. It took a couple of tries to call it correctly, and I used a bash script (I can share privately) to store the variables needed to call the script. I wasn't able to get a clean run this time, and I'd like another deployment to work out bugs before automating it.  My thought is that it would be called by Jenkins …
=> bug 1445641, bug 1464892: Add deployment recorder

.travis.yml, requirements/constraints.txt, requirements/default.txt, tox.ini
Add a optional TravisCI build that runs the tests under Python 3.6. This requires changing the way the builds are configured so that most will continue to run under Python 2.7.
Clean up the tox.ini configuration to call this build "pytest" rather than "py27", and fix the locales target.
Update requirements so that they install without errors:
* ``importlib`` isn't needed in Python 2.7, and fails to install in 3.6 - remove it
* ``django-allauth`` requires ``python3-openid``, which requires ``defusexml``, under Python 3.x
Tests don't even run, due to non-compat code in a library, but this is a starting point so @MatonAnthony and others can start iterating on Python 3 changes.
=> bug 1467518: Add Python 3.6 build target

docker/images/kuma_base/Dockerfile
Update the Python base image from Debian 8 (jessie) to 9 (stretch), which is the current LTS release, along with some additional cleanup:
Move the `ENV` declarations to the top, to reduce the number of intermediate images.
Move all the package installation to the same section, to avoid refreshing the `apt-get` cache twice. Include the `gpg` package and dependencies, which is no longer in the default image. Update the names of the MySQL packages.
Update the `node.js` installation code to bump the minor version and use the current code for importing GPG signing keys. Drop the unused `yarn` install. The 8.x node.js update will come later.
=> bug 1468490: Update to Debian 9 (stretch) base image

.travis.yml
Code that depends on a fixed dictionary hash was removed in PR #4851. This removes it from the optional Python build, and removes the seed/no seed branch from the test script.
=> bug 1467518: Use random hashes in Python 3.6 build

CONTRIBUTING.md, kuma/core/tests/__init__.py, kuma/core/tests/test_helpers.py, kuma/core/tests/test_templates.py, kuma/core/tests/test_views.py, kuma/dashboards/tests/test_views.py, kuma/landing/tests/test_templates.py, kuma/search/tests/test_filters.py, kuma/search/tests/test_indexes.py, kuma/search/tests/test_serializers.py, kuma/search/tests/test_types.py, kuma/users/tests/test_forms.py, kuma/users/tests/test_helpers.py, kuma/users/tests/test_models.py, kuma/wiki/tests/test_content.py, kuma/wiki/tests/test_models.py, kuma/wiki/tests/test_tasks.py, kuma/wiki/tests/test_templates.py, kuma/wiki/tests/test_views.py
This PR remove the `ok_()` method that is no longer necessary.
- Open a bug (or find an existing bug) to link this.
- Reword the commit to include details in the commit title and message.
=> Remove ok_() from tests

Makefile
Clear out the development emails with ``make clean``, which saves a small bit of disk space (for me, 20 MB over 6+ months) and makes it easier to find the latest email when debugging.
=> bug 1419532: Delete dev emails with make clean

kuma/static/js/interactive.js, kuma/static/js/utils/post-message-handler.js
@jwhitlock @tkadlec Here is the Kuma side of the final metric we want to track for now.
=> add handler for interactive examples load end event, bug 1468271

CONTRIBUTING.md, kuma/core/tests/__init__.py, kuma/core/tests/test_decorators.py, kuma/core/tests/test_form_fields.py, kuma/core/tests/test_helpers.py, kuma/core/tests/test_misc.py, kuma/core/tests/test_models.py, kuma/core/tests/test_pagination.py, kuma/core/tests/test_templates.py, kuma/core/tests/test_utils.py, kuma/core/tests/test_views.py, kuma/dashboards/tests/test_views.py, kuma/landing/tests/test_templates.py, kuma/search/tests/test_filters.py, kuma/search/tests/test_indexes.py, kuma/search/tests/test_serializers.py, kuma/search/tests/test_tasks.py, kuma/search/tests/test_types.py, kuma/search/tests/test_utils.py, kuma/users/tests/test_adapters.py, kuma/users/tests/test_forms.py, kuma/users/tests/test_helpers.py, kuma/users/tests/test_models.py, kuma/wiki/tests/test_content.py, kuma/wiki/tests/test_helpers.py, kuma/wiki/tests/test_kumascript.py, kuma/wiki/tests/test_middleware.py, kuma/wiki/tests/test_models.py, kuma/wiki/tests/test_templates.py, kuma/wiki/tests/test_views.py
The `eq_()` function is a reliquat of the transition from nose to
pytest.
It does not provide anything except clutter for the current codebase.
This commit removes all references to `eq_()` and replace it with
`assert`
=> bug 1240083: Remove eq_() from tests

kuma/settings/common.py
Changes the s_maxage setting of the Cache-Control header from 5 minutes to 48 hours for all of the endpoints with responses modified by kuma.core.utils.add_shared_cache_control. This setting is used in turn by MDN's CloudFront CDN to set the TTL period for its caching. This is an experiment, and will be reverted a short time (2-5 days) after it's merged and deployed.
=> bug 1431259: change cache TTL from 5min to 48hr (experiment)

jinja2/includes/footer/mdn-footer.html, jinja2/includes/footer/moz-footer.html, kuma/users/jinja2/socialaccount/snippets/login_service_icon.html, kuma/wiki/templatetags/jinja_helpers.py, kuma/wiki/tests/test_helpers.py
This adds the Jinja helper for SVG. Also applies the new helper to currently identified use cases. Open question is whether we should make `include_svg` the standard way to include SVG files in HTML or only use it when we want to pass a custom title.
=> Add jinja helper for SVG. Fix issue 23 on sprints repo

kuma/settings/common.py
This reverts the experiment started with the deployment of #4876.
=> bug 1431259: reset cdn cache ttl to 5min

kuma/wiki/models.py, kuma/wiki/tests/test_models.py, kuma/wiki/tests/test_utils.py, kuma/wiki/utils.py
I have fixed the issue in `utils.py` as well as `get_redirect_url`. In `get_redirect_url`, it was returning full url sometimes, sometimes relative path. It has been fixed.
@jwhitlock @escattone r?
=> bug 1465085: Handle a child of a redirect with a full URL without raising an error

Makefile, docker/images/kuma_base/Dockerfile-1.10, docker/images/kuma_base/Dockerfile-1.11, docker/images/kuma_base/Dockerfile-1.9, docker/images/kuma_base/Dockerfile-py3
Remove the kuma_base variants from the Django update process, and add a new one for the Python 3 update effort.  To use it:
1. Run ``make build-base-py3``
2. Create ``docker-compose.override.yml`` that recreates the ``worker`` container, but with the py3 variant image, and running pytest:
```yaml
version: '2.1'
services:
py3:
image: quay.io/mozmar/kuma_base:py3
command: pytest --reuse-db kuma
user: ${UID:-33}
volumes:
- ./:/app:z
depends_on:
- memcached
- mysql
- elasticsearch
- redis
- kumascript
environment:
- ACCOUNT_DEFAULT_HTTP_PROTOCOL=http
- ALLOWED_HOSTS=*
- ATTACHMENT_HOST=${ATTACHMENT_HOST:-localhost:8000}
- BROKER_URL=redis://redis:6379/0
- CELERY_ALWAYS_EAGER=False
- CELERY_RESULT_BACKEND=redis://redis:6379/1
- CSRF_COOKIE_SECURE=False
- …
```
=> bug 1467518: Cleanup Django update images, add Python 3 image

kuma/settings/local.py
Update the code that enables Django Debug Toolbar (DDT) for the change from ``MIDDLEWARE_CLASSES`` to ``MIDDLEWARE`` in Django 1.10. This should have been done in PR #4830 (oops).
I want to get rid of the alternate settings files entirely ([bug 1308630](https://bugzilla.mozilla.org/show_bug.cgi?id=1308630)), but I also want my debug toolbar working again, so I'm going with the minimal change.
=> bug 1401246: Update Django Debug Toolbar injection for MIDDLEWARE

jinja2/base.html, kuma/core/tests/test_views.py, kuma/core/views.py
Update the test to trigger the production bug, where ``request.user`` was being read to determine if a flag ``section_edit`` was applicable.
In the error view, detect if the request object is missing attributes ``.user`` or ``.LANGUAGE_CODE``, and add good defaults, before rendering.
=> bug 1467513: Add request attributes in error view

kuma/wiki/jinja2/wiki/document.html
@jwhitlock This is with regards to mdn-fiori issue https://github.com/mdn/mdn-fiori/issues/32
=> bug 1418301: Remove preload hints for iframe assets

requirements/default.txt
* django-soapbox 1.3 → 1.5: Django 1.11, Python 3.6 support, and working database migrations.
This was discovered because the sample database no longer has soapbox tables in Django 1.11. This is fixed in 1.5. I tested by building the base image (``VERSION=latest make build-base``), removing almost all the sources from ``/etc/sample_db.json``, building the sample DB (``scripts/create_sample_db.sh``), and looking for the soapbox table in the SQL (``grep soapbox mdn_sample_db.sql ``).
It appears Django migrations were never applied for the existing tables.  We'll need a one-time different migrate command in production, such as:
```
./manage.py migrate --fake-initial
```
or
```
./manage.py migrate soapbox 0001 --fake
./manage.py migrate
```
This is run during deployments, as …
=> bug 1467532: Update to django-soapbox 1.5

kuma/wiki/tests/test_views.py, kuma/wiki/views/document.py
If [/en-US/docs/Main_Page](https://developer.mozilla.org/en-US/docs/Main_page) is a redirect to a non-Document MDN URL, then return a 404 to [/en-US/docs/MainPage/SubPage](https://developer.mozilla.org/en-US/docs/Main_page/SubPage) when logged in, rather than raise an Internal Server Error (500 ISE).
I didn't refactor the tests, which can be refactored after PR #4853 simplifies the logic.
=> bug 1465085: Return 404 for the child of a 301 to a non-document URL

kuma/static/styles/base/utilities.scss, kuma/static/styles/components/wiki/customcss.scss
This is a companion PR to #4853. If/when that PR is merged/deployed, this PR should be merged/deployed as well.
The "death of zones" PR (#4853) removes all zone-related CSS. However, we'd actually like to keep two classes (see [bugzilla 1469029](https://bugzilla.mozilla.org/show_bug.cgi?id=1469029)). This PR adds those two classes into the mainstream CSS.
I wasn't sure of the best place for these two classes to live, so please suggest a different home if you don't like my choice.
=> bug 1469029: keep two zone-related css classes

tests/headless/test_cdn.py
This PR addresses a gap in the original modifications made to some of the tests within `tests/headless/test_cdn.py` by #4853. Those modifications were made without realizing that some of the tests related to the caching of the 302's for former-zone vanity URL's had to be asserted one way when behind a CDN and another when not. This was simply due to the fact that although the `Cache-Control` header enables caching for those cases, they fell into CDN behaviors that prevented caching when accessed via the CDN.
=> bug 1462475: fix tests/headless/test_cdn.py

requirements/default.txt, requirements/dev.txt
I've install MySQL 8 locally, and now ``mysqlclient`` won't install. This fixes it, but more importantly our MySQL libraries are very stale.
* ``hashin`` 0.13.0 → 0.13.2: Allow pre-release only packages, more Python version matching. Not needed, but I update this whenever I use it for version updates.
* ``django-mysql`` 1.0.4 → 2.3.1: Fix JSONField serialization, add Django 1.11+ and mysqlclient compatibility, MariaDB 10.3 support.
* ``mysqlclient`` 1.3.7 → 1.3.13: Support MariaDB 10.2, MySQL 8, other fixes.
Here's our MySQL versions:
* Development: MySQL 5.6, in [docker-compose.yml](https://github.com/mozilla/kuma/blob/705339d6b92d1b788896b1727f7394567a4cd0be/docker-compose.yml#L66)
* TravisCI: MySQL 5.6, the [default](https://docs.travis-ci.com/user/database-setup/#MySQL)
* Production: …
=> bug 1467532: Update MySQL libraries

kuma/static/styles/base/elements/forms.scss
The publish and keep editing button in the editing section looks taller than Publish button hence adding a min height to Publish button fixes this issue.
=> bug 1474435: "Publish & keep editing" button taller than the others

requirements/default.txt
* Django 1.11.13 → 1.11.15: Mitigate open redirect risk with CommonMiddleware
=> bug 1467532: Update to Django 1.11.15

Jenkinsfiles/push.groovy, Jenkinsfiles/utils.groovy
This PR depends on the infrastructure pieces added by mdn/infra#16, using them to create two new `utils` functions (`get_revision_hash` and `record_rollout`) for use by the `Kuma` and `Kumascript` push pipelines, and also updates the `push.groovy` file to use those `utils` functions to record deployments for the `Kuma` push pipeline.
=> bug 1445641, bug 1464892: enable deployment recording

.travis.yml, docker-compose.test.yml, docker-compose.yml, docker/images/kuma_base/Dockerfile, kuma/core/cache.py, kuma/core/tasks.py, kuma/core/tests/__init__.py, kuma/core/utils.py, kuma/feeder/management/commands/update_feeds.py, kuma/health/views.py, kuma/landing/tests/test_views.py, kuma/landing/views.py, kuma/settings/common.py, kuma/settings/prod.py, kuma/wiki/kumascript.py, kuma/wiki/tasks.py, kuma/wiki/tests/test_tasks.py, requirements/constraints.txt, requirements/default.txt
Redis is a better suited cache than memcache for our usage.
We have hit the memcache technical limitations such as:
- 1MB values
- Simple string storage
- Lack of key introspections
All those features are provided by Redis while also providing the same
feature set as memcache.
Redis is already used by Kuma and removing memcache also means reducing
our infrastructure costs.
To be able to entirely remove `memcache` from MDN infrastructure, we need to switch mdn/kumascript to `redis` too.
This PR is not done at this stage and I'm currently not specifically working on it.
Removing `memcache` is having the expected side-effects of remove `memcache_hashring` non-compatibility with Python 3.
=> bug 1431497: Migrate from memcache to redis

docker-compose.test.yml
The spam tests use waffle flags and switches, which are now stored inthe Redis cache, and fail in the noext tests. Instead, check kuma/health.
Test process:
```
VERSION=latest make build-base  # Get a base image with the new libraries
docker-compose -f docker-compose.yml -f docker-compose.test.yml run noext
```
=> bug 1431497: Swap spam for health in noext tests

kuma/search/filters.py, kuma/search/paginator.py, kuma/search/tasks.py, kuma/search/tests/test_filters.py, kuma/wiki/kumascript.py, kuma/wiki/tests/test_kumascript.py, requirements/constraints.txt, requirements/default.txt
*Note: this builds on PR #4905, which I suggest deploying first*
Update to ES 2 libraries:
* elasticsearch 1.9.0 → 2.4.1: Last release in ES 2.x cycle
* elasticsearch-dsl 0.0.9 → 2.2.0: Sync interface with ES 2.x features, such as dropping F objects (filters are now merged with queries), merging "and", "or", etc. into 'bool' queries.
* python-dateutil 2.4.2 → 2.7.3: Zone updates and format change, expanded ambiguous date support, ISO 8601 parsing, drop Python 2.6 and 3.2, many more.
Make changes required by the 2.x libraries:
* Replace ``F()`` with ``Q()`` queries
* Replace ``and``, `or``, and ``filtered / filter`` queries with ``bool`` equivalents
Make changes that work with both 2.x and 5.x libraries:
* Update document counts in paginator for Django 1.10 / ES 5
* Switch from …
=> bug 1464093: Update to Elasticsearch 2 libraries

.travis.yml, kuma/core/templatetags/jinja_helpers.py, kuma/core/utils.py, kuma/feeder/tests/test_utils.py, kuma/feeder/utils.py, kuma/health/tests/test_views.py, kuma/scrape/tests/test_scraper.py, kuma/search/tests/test_serializers.py, kuma/search/tests/test_views.py, kuma/spam/akismet.py, kuma/version/tests/test_views.py, kuma/wiki/constants.py, kuma/wiki/content.py, kuma/wiki/kumascript.py, kuma/wiki/templatetags/jinja_helpers.py, kuma/wiki/tests/__init__.py, kuma/wiki/tests/test_content.py, kuma/wiki/tests/test_kumascript.py, kuma/wiki/tests/test_templates.py, kuma/wiki/tests/test_utils.py, kuma/wiki/tests/test_views.py, kuma/wiki/tests/test_views_create.py, kuma/wiki/tests/test_views_document.py, kuma/wiki/tests/test_views_misc.py, kuma/wiki/views/document.py, kuma/wiki/views/edit.py, kuma/wiki/views/translate.py, tox.ini
Move a step closer to run the tests on Python 3.
This PR rewrite the minimal necessary code to allow `pytest` to properly collect all the tests before running them.
<strike>- There is one error left that I don't manage to fix at this stage.</strike>
- Merge PR #4870 or cherry-pick those changes to a branch based on master.
- This PR is based on #4870 (which removes a blocker for the migration to Python 3).
- `make lint` returns errors due to code no longer compatible with Python 3.
- `django.utils.six` is used for the compatibility layer as suggested by @jwhitlock on IRC.
=> bug 1467518: Enable pytest to collect all test on the Python 3 image.

jinja2/base.html, jinja2/includes/google_analytics.html
Merge the minimized Mozilla DNT Helper and the Google Analytics setup into a single inline ``<head>`` script.
=> bug 1458197: Merge DNT and GA inline scripts

CONTRIBUTING.md
Fix typo in Markdown reference to the MDN GitHub organization.
=> bug 957802: Fix link to MDN GitHub org

.travis.yml, docker-compose.yml, kuma/search/filters.py, kuma/search/tests/test_filters.py, kuma/search/views.py, kuma/wiki/search.py, requirements/constraints.txt, requirements/default.txt
* Update the development environment to ElasticSearch 5.6.10, using [elastic.co's docker image](https://www.docker.elastic.co). They are deprecating [the images on dockerhub](https://hub.docker.com/_/elasticsearch/).
* Update the client libraries to the latest compatible with ES 5.6.10. Unlike the 0.x to 2.x transition, the client libraries have to be in sync with the server version, and there are several breaking changes that require simultaneous code changes. This makes me less impressed with the ElasticSearch libraries.
* ES 5 splits ``String`` into ``Text`` (tokenization and full text search) and ``Keyword`` (optimized for exact matches). I took the opportunity to move case-insensitive keyword queries into Python.
* Fix [bug 1180144](https://bugzilla.mozilla.org/show_bug.cgi?id=1180144 …
=> bug 1464093: Upgrade to ElasticSearch 5.6

kuma/wiki/models.py
This PR is part of the cleanup after the death of zones #4853, and paves the way for the DB migration to remove the `wiki_documentzone` table and the `zone_subnav_local_html` field from the `wiki_document` table.
- Removes the `DocumentZone` model
- Removes the `zone_subnav_local_html` field from `Document` model
=> bug 1462475: remove models/fields related to zones

docs/elasticsearch.rst
Kuma is using 5.6.10 in development and production. The previous production version was 2.4, but the docs were not updated.
Add some more details about the ElasticSearch support policy, and which version Kuma is targeting. The version history was removed from Wikipedia, and there doesn't seem to be a good release history on the ES website, so link to the end-of-life support page.
=> bug 1464093: Update ElasticSearch docs for 5.6.10

scripts/anonymize.sql, scripts/clone_db.py
Don't clone the table when anonymizing, and drop it if present.
A test run is fast with the sample database in the development environment:
```
(host) $ make bash
(web) $ scripts/clone_db.py developer_mozilla_org -H mysql -p kuma
```
=> bug 1462475: Drop zone table in anon script

README.rst
Sync the P1 hint with the process documents (like [the wiki](https://wiki.mozilla.org/Engagement/MDN_Durable_Team/Processes#Triaging_Requests) and [the triage process doc](https://docs.google.com/document/d/1h3R5v60ZXaRG4pFI5Ia2Woov-39Swda6Z5Jxp0F4GDI/edit#heading=h.bfalthrbzqwk)). 
Drop [kuma-lib](https://github.com/mozilla/kuma-lib) and [mozhacks](https://github.com/mozilla/mozhacks) from the [PR queue list](http://prs.mozilla.io/mozilla:kuma%3Bmdn:kumascript,infra,mdn-fiori), and add [infra](https://github.com/mdn/infra) and [mdn-fiori](https://github.com/mdn/mdn-fiori).
=> bug 957802: Update P1 hint, PR queues

Jenkinsfiles/utils.groovy
This PR allows us to handle both the current and new Jenkins pipelines during this period of transition.
On the new Jenkins service owned by IT, it will use the new configuration scripts [within the `oregon` region](https://github.com/mdn/infra/tree/master/apps/mdn/mdn-aws/k8s/regions/oregon) rather than the current ones [within the `portland` region](https://github.com/mdn/infra/tree/master/apps/mdn/mdn-aws/k8s/regions/portland).
=> bug 1483072: handle the new Jenkins pipelines

Jenkinsfile
The ``jenkins`` user's ID is different in the MozMEAO and IT Jenkins server, so don't hard-code it.
=> bug 1483072: Get jenkins user ID via shell

kuma/settings/common.py, kuma/static/js/interactive.js
This addresses some issues when reviewing PR #4935 and getting my Kuma dev environment to talk to a local checkout of https://github.com/mdn/interactive-examples/
* I gave @schalkneethling the wrong command in https://github.com/mozilla/kuma/pull/4404#discussion_r137103509 to override ``INTERACTIVE_EXAMPLES_BASE`` from the environment, this corrects it.
* The code that looks for the interactive example iframe events was always looking for the production domain, this changes it to look for ``INTERACTIVE_EXAMPLES_BASE`` via ``mdn.interactiveEditor.editorUrl``.
=> bug 1308630, bug 1468271: Fixes for custom Interactive Examples URLs

requirements/default.txt
* bleach 2.1.3 → 2.1.4: Handle ambiguous ampersands, like &xx;
=> bug 1467532: Update to bleach 2.1.4

Jenkinsfiles/integration-tests.groovy
This PR fixes the `stage-integration-tests` branch within the multi-branch `kuma` pipeline on the new IT-managed Jenkins service. On the new IT-managed Jenkins service, the `jenkins` user does not have a user ID of `1000`, so the Docker-based test runs don't have permission to write to the test results directory, so pass the actual `jenkins` user ID instead.
This change has been tested on both the new IT-managed as well as the current MozMEAO-managed Jenkins service.
=> bug 1483072: pass jenkins user id to docker runs

Jenkinsfiles/utils.groovy
This PR makes Jenkins less chatty when running the Kuma and Kumascript push branches (`stage-push`, `prod-push`, and `standby-push`).
=> bug 1483072: make jenkins less chatty

kuma/redirects/redirects.py, tests/headless/map_301.py
Previously, the sub-path was added to the destination URL by appending it in a callable. If the ``sub_path`` included a Python format string, like ``/foo/bar/{var}``, then django-redirect-urls would run ``.format`` on it, and raise a ``KeyError`` for ``{var}``.
Instead of a callable, use a format string like ``/en-US/docs/Learn/{sub_path}``. This way, django-redirect-urls will format the string with the ``sub_path`` captured in the regex.
=> bug 1481078: Fix zone redirects with format chars

.env-dist.dev, kuma/settings/common.py, kuma/settings/local.py, kuma/wiki/content.py, kuma/wiki/managers.py, kuma/wiki/tests/test_content.py, kuma/wiki/tests/test_views_code.py, kuma/wiki/views/code.py
The constance setting ``KUMA_WIKI_IFRAME_ALLOWED_HOSTS`` was a regex used to validate code sample request hosts and what ``src`` URLs were allowed for ``<iframe src="">``. It was also easy to get wrong, and needed to change in predictable ways for each deployment environment.
Code sample domain checking is updated to use ``ATTACHMENT_HOST`` and ``ATTACHMENT_ORIGIN`` for domain validation. This may require setting these correctly in stage and production.
A new setting ``ALLOWED_IFRAME_PATTERNS`` allows for more precise protocol and domain matching, optional path matching (by prefix or regex match), and can be automatically adjusted for ``ATTACHMENT_HOST`` and ``INTERACTIVE_EXAMPLE_BASE`` settings.
There are patterns that are no longer allowed by default:
* …
=> bug 1308630: Replace KUMA_WIKI_IFRAME_ALLOWED_HOSTS with ALLOWED_IFRAME_PATTERNS

kuma/conftest.py, kuma/core/templatetags/jinja_helpers.py, kuma/core/tests/test_helpers.py, kuma/static/styles/components/wiki/indicators.scss, kuma/wiki/jinja2/wiki/confirm_purge.html, kuma/wiki/jinja2/wiki/deletion_log.html, kuma/wiki/tasks.py, kuma/wiki/tests/__init__.py, kuma/wiki/tests/conftest.py, kuma/wiki/tests/test_tasks.py, kuma/wiki/tests/test_templates.py, kuma/wiki/tests/test_views.py, kuma/wiki/tests/test_views_delete.py, kuma/wiki/tests/test_views_document.py, kuma/wiki/views/delete.py, kuma/wiki/views/document.py
This fixes a few bugs and issues with document purging:
* On the deleted document page, show who deleted a document if the viewer has revert permissions.
* On the deleted document page, add a "Purge document" button if the viewer is allowed to purge the document.
* Add a purge confirmation page, so GET will work for ``$purge`` pages (fixes [bug 1197390](https://bugzilla.mozilla.org/show_bug.cgi?id=1197390)).
* If a document has been purged, treat it as a missing document (fixes [bug 1380388](https://bugzilla.mozilla.org/show_bug.cgi?id=1380388)).
* Add an async task to remove deletion logs for purged documents.
=> bug 1380388: Improve document purging

kuma/landing/jinja2/landing/homepage.html
"compat" is a useful abbreviation for compatibility in English, but could be challenging to translate.  Fix before sending to translators.
=> bug 1486852: Don't abbrev. compatibility

kuma/static/styles/components/wiki/indicators.scss
Multiple indicator sections are separated by whitespace unless hacks and CSS classes are applied. Use the ``:matches`` selector to add some more automatic "snugging", with auto-expanded rules for browsers (like Firefox) that don't support :matches, since PostCSS will require additional work to integrate into the asset pipeline ([bug 1366868](https://bugzilla.mozilla.org/show_bug.cgi?id=1366868)).
This was cherry-picked from PR #4884, without the changes that add PostCSS and ``postcss-selector-matches``
=> bug 1486527: Improve indicator snugging

kuma/wiki/content.py, kuma/wiki/kumascript.py, kuma/wiki/managers.py, kuma/wiki/models.py, kuma/wiki/templatetags/jinja_helpers.py, kuma/wiki/tests/test_content.py
The method ``Document.objects.clean_content`` provides the default bleaching and ``iframe`` ``src`` filtering for rendered wiki content. However, it doesn't act like a manager method, and this makes it awkward to call as a Jinja2 filter or on KumaScript preview content. It also made it awkward to optionally turn off ``iframe`` ``src`` filtering via a setting.
This moves ``clean_content`` to ``kuma.wiki.content`` as a plain function, and refactors to ``AllowedHTMLTests`` tests to be standard ``pytest`` tests, and to use ``clean_content`` rather than a ``bleach.clean`` call that is almost the same.  It also reduces the test cases, since many of the existing tests were little more than ``bleach.clean`` configuration tests.
=> bug 1308630: Refactor clean_content

kuma/scrape/sources/base.py, kuma/scrape/sources/document.py, kuma/scrape/sources/links.py, kuma/scrape/tests/test_source_document.py
To review https://github.com/mdn/kumascript/pull/789 (in progress), I needed a bunch of documents from the sidebar. Two issues made this hard:
``{{CompatGeckoDesktop(version)}}`` still [outputs URLs for the Firefox zone](https://github.com/mdn/kumascript/blob/b566c863c733b7ee3757f65bb5c6e32967ad80e1/macros/CompatGeckoDesktop.ejs#L137), and the scraper now halts on an exception when it tries to process it. The zone URL handler was removed in PR #4920 for [bug 1462475](https://bugzilla.mozilla.org/show_bug.cgi?id=1462475), which wasn't so long ago, so I'm adding another commit to the bug.  This doesn't resurrect the whole ``normalized_path`` code (5b527e703ef90dfe35f3a20991203b90fb706145), just handles paths that don't look like documents.  I hope to fix ``{{CompatGeckoDesktop}}``, but the …
=> bug 1462475: Improve ./manage.py scrape_links

kuma/wiki/constants.py
Due to an issue with initialization order, ``<details>`` allowed the standard attributes ``style``, ``class``, ``id``, ``lang``, ``dir``, and ``title``, but not ``open``.  
Required for the changes in PR #4957 and https://github.com/mdn/kumascript/pull/789.
=> bug 1488884: Allow attribute <details open>

docker-compose.yml
Use the ``ATTACHMENT_HOST`` environment variable to customize the domain for the live samples base URL for KumaScript. This KumaScript setting is added in https://github.com/mdn/kumascript/pull/777.
=> bug 1482159: Set live samples URL for Kumascript

kuma/scrape/scraper.py, kuma/scrape/sources/base.py, kuma/scrape/tests/test_source.py
Fix a couple of issues with the scraper:
When running ``./manage.py scrape_links https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio``, there was a link to https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Perceivable#Guideline_1.2_\u2014_Providing_text_alternatives_for_time-based_media, which has a unicode character in the anchor tag. Make the ``decode_href`` function a little more flexible, so it handles unicode strings that aren't ``ascii``.
When running ``./manage.py scrape_links https://developer.mozilla.org/en-US/docs/MDN/Doc_status/Guide``, I got some ``504 Gateway Timeout`` responses. The scraper handles these, but the log format message was malformed. The format string is fixed.
=> bug 1490356: Fix scraper bugs for Unicode URLs and 504 responses

tests/functional/test_maintenance_mode_redirects.py
While testing the new prod PoC instance in maintenance mode, I discovered that I failed to remove two maintenance-mode tests when I submitted https://github.com/mozilla/kuma/pull/4769 about 4 months ago. This PR does that.
=> bug 773921: remove mm tests of invalid endpoints

kuma/static/styles/components/wiki/indicators.scss
Fixes [bug 1487656](https://bugzil.la/1487656):
> Inspecting the minified stylesheet, it turns out that the minifier actually merged the :matches(…) and non‑:matches(…) blocks together, which breaks on browsers which don’t support :matches(…).
> 
> A temporary solution would be to comment out the :matches(…) block, but a long term one will require a way to tell the CSS minifier to not merge the :matches(…) and non‑:matches(…) blocks together.
> 
> ```css
> .note+.note, .note+.notice, .note+.overheadIndicator, .note+.warning,
> .note+p:empty+.note, .note+p:empty+.notice,
> .note+p:empty+.overheadIndicator, .note+p:empty+.warning, .note+p:empty+pre,
> .note+pre, .notice+.note, .notice+.notice, .notice+.overheadIndicator,
> .notice+.warning, .notice+p:empty+.note, .notice+p:empty+.notice,
> …
```
=> Bug 1487656 ‑ Comment out the indicator `:matches(…)` block for now

requirements/default.txt
stripe 2.8.0 is the Python library for the [Stripe Payments API](https://stripe.com/docs/api). The commits are cherry-picked from https://github.com/mozilla/kuma/tree/potato-1490727, and have two authors.
=> bug 1490727: Add stripe dependency

kuma/static/styles/includes/_vars.scss
The current contrast is 4.01, which is below the minimum 4.5 ratio needed to meet the WCAG AA guidelines. The proposed change increases the contrast to 4.52.
See also [bug 924583](https://bugzilla.mozilla.org/show_bug.cgi?id=924583)
=> Bug 1306286: increase contrast for $blue and link-color

kuma/static/styles/search.scss
MDN's search result pages have had for years a problem
where the icon in the left column is substantially
above the title of the page to its right. This PR
fixes that problem.
=> Fix alignment of icons and titles in search results

Jenkinsfiles/push.groovy
Set `TO_REVISION_HASH` to the latest commit hash of the `kuma` repo.
=> bug 1483072: set TO_REVISION_HASH from repo

Jenkinsfiles/utils.groovy
Temporarily use the [`prod.mm.test.sh` configuration file](https://github.com/mdn/infra/blob/master/apps/mdn/mdn-aws/k8s/regions/oregon/prod.mm.test.sh) for production deployments to the `oregon` Kubernetes cluster (new MozIT cluster). This temporarily prevents full-scale deployments until we are ready to move to the new cluster.
=> bug 1483072: temporarily use prod.mm.test for oregon

scripts/record_deployments.py
SpeedCurve won't run a deploy if one is in progress. Detect as a non-quite-success, not-quite-failure. Also, make the code more Python-3 compatible by using response.text, which should be decoded to unicode automatically.
=> bug 1445641: Ignore SpeedCurve in-progress 403

kuma/contributions/utils.py, kuma/contributions/views.py, kuma/core/email_utils.py
* Pass request to ``enabled()``, fixing the contribute views.
* Handle ``request`` objects without a ``user`` attribute
* Make the ``request`` object in the backend email renderer a fake ``Request`` object, not a ``RequestFactory``.
=> bug 1490727: Fix contrib_beta waffle check

kuma/static/js/components.js
To enable tabbing through the menu without being forced to tab through each item.
See also [bug #1056933](https://bugzilla.mozilla.org/show_bug.cgi?id=1056933). Marco said this was a useful hack, though, as we already know there are better long term improvements that could be made.
=> Move close button to start of menu

kuma/contributions/jinja2/contributions/includes/contribution-form.html, kuma/contributions/views.py, kuma/landing/tests/test_templates.py, kuma/wiki/tests/test_templates.py
Similar to PR #4757, remove the CSRF protection from the stripe callback, since it adds a ``csrf_token`` cookie to requests on the homepage and wiki document pages, and interacts poorly with the CDN. 
Stripe's Checkout example code (like [rails](https://stripe.com/docs/checkout/rails)), does not include CSRF checking, and they show how to [exclude CSRF checks on Django](https://stripe.com/docs/webhooks#receiving-webhooks-with-csrf-protection). I believe our code is safe, because the Stripe-generated token, ``POST``ed to the callback, is used to identify a legitimate transaction. Opening this up will allow someone to make a contribution form for MDN that posts to us, but not to substitute their own Stripe account.
=> bug 1490727: Exclude CSRF checking from Stripe contribute webhook

kuma/contributions/jinja2/contributions/includes/contribution-form.html, kuma/contributions/jinja2/contributions/thank_you.html, kuma/settings/common.py
More copy tweaks from @atopal:
* Banner button changes from "Contribute" to "Support MDN"
* Banner copy update
* Update the support email to mdn-support@mozilla.com (use credit card ``4100000000000019`` to see support message)
=> bug 1490727: Update copy

kuma/contributions/jinja2/contributions/email/thank_you/plain.ltxt, kuma/contributions/jinja2/contributions/thank_you.html
Changes to the "thank-you" copy both on the page as well as the email.
=> bug 1490727: tweak thank-you copy for contributions

kuma/contributions/jinja2/contributions/email/thank_you/email.html
I didn't realize that the "thank-you" copy in the HTML for emails had its own copy rather than using the plain text copy within it.
=> bug 1490727: update thank-you html email copy

kuma/contributions/jinja2/contributions/email/thank_you/email.html
We missed that staging and prod have proper STATIC_URL
We currently have
`{{ site }}{{ static('img/image.png') }}`
seems like all we need is `{{ static('img/image.png') }`
This PR should solve this!
=> Bug 1490727 Use correct static URL in thank you email.

docker-compose.yml, jinja2/includes/config.html, kuma/contributions/context_processors.py, kuma/contributions/forms.py, kuma/contributions/tests/test_forms.py, kuma/contributions/utils.py, kuma/landing/jinja2/landing/homepage.html, kuma/landing/tests/test_utils.py, kuma/landing/tests/test_views.py, kuma/wiki/jinja2/wiki/document.html
More nits and blockers for beta launch:
* Update ``STATIC_URL`` in development environment, to reduce confusion between development, staging, and production.
* Change the charge description from 'Contribute to MDN Web Docs' to 'Support MDN Web Docs'
* Enable the Contribution standalone pages always, because of social sharing, but the popup for waffle-selected users.
=> bug 1490727: More contributions updates

kuma/static/styles/base/elements/typography.scss, kuma/static/styles/components/tags.scss
When against a grey background, the blue color used for links is below the minimum 4.5 ratio needed to meet the WCAG AA guidelines, even after #4983.
=> Bug 924583: Use $blue-dark for link color against grey background

jinja2/includes/google_analytics.html, requirements/default.txt, requirements/dev.txt
Update and add libraries:
* django-debug-toolbar 1.8 → 1.10.1: Update Django support matrix, remove jQuery dependency. The jQuery dependency was loaded with a protocol-relative URL, which made for a more complex policy.
* raven 6.2.1 → 6.9.0: Better remote user support, Django support matrix update, sanitization support, other updates. This is the Python Sentry client, and I'm borrowing the pattern from other Mozilla projects, which forward CSP violation reports to Sentry.
* [django_csp](https://github.com/mozilla/django-csp) 3.4: Mozilla's Django project for adding the  Content Security Policy header. Unused in this PR, but it would be good to get it in the base image for future reviews.
This also updates the Google Analytics snippet to force SSL, used in the [current …
=> bug 948151: Library, other updates for CSP effort

kuma/wiki/tasks.py
Do not attempt to email admins when a ``DocumentRenderingInProgress`` exception is raised by the render function.
Also, pass the string version of the exception to mail_admins.
=> bug 1475610: Handle DocumentRenderingInProgress

kuma/contributions/jinja2/contributions/contribute.html
This fixes a typo (per @alispivak) in the copy for FAQ 1 within the contribution workflow.
=> bug 1490727: fix typo in answer to FAQ #1

Jenkinsfiles/utils.groovy
This should enable the MozIT Jenkins service to start pushing both Kuma and Kumascript images to the MozIT standby cluster on updates to `standby-push` branch within the Kuma and Kumascript repos. @limed has already configured the MozIT Jenkins service with the required K8s credentials (`${HOME}/.kube/germany.config`).
=> bug 1483072: enable deployments to MozIT standby

kuma/health/urls.py, kuma/health/views.py, kuma/settings/common.py, kuma/wiki/views/edit.py, kuma/wiki/views/translate.py
Builds on PR #5001, which can be merged first to get the libraries into the base image.
Add a CSP configuration, based on testing several pages on development. Enabling CSP and other options are configured from the environment, and off by default. The policy is configured in the Django settings, and not configured by the environment. The policy allows inline CSS and JavaScript, so that the site works without modification, but doesn't add as much security as it could.
CKEditor 4.5.10 still requires ``unsafe-eval``, but [4.7](https://ckeditor.com/blog/CKEditor-4.7-released/) claims to remove this requirement. A decorator adds ``unsafe-eval`` only on the editing pages that use CKEditor.
The reporting view is copied from [mozilla/bedrock](https://github.com/mozilla/bedrock/blob/333d3df02ad697f …
=> bug 948151: Add permissive CSP

kuma/dashboards/jinja2/dashboards/index.html, kuma/dashboards/jinja2/dashboards/spam.html, kuma/dashboards/tests/test_views.py, kuma/dashboards/views.py, kuma/urls.py
Add index of dashboards, lists of documents, and special wiki pages for moderators.
It sorts by translated titles, so that is makes some sense in French as well.  "Spam Dashboard" wasn't translated before, so this marks it for translation.  There are some wiki documents included that add new strings as well.
I omit the link to the "inprogress" translations tag in English, since it is always empty. I also omit the Spam Dashboard link if the user doesn't have permission to see it.
=> bug 1495765: Add index of dashboards

kuma/settings/common.py
Add the production attachment URL to the list of CSP allowed domains for images (``img-src``). Include the local attachment URL if it isn't production or the same as the web domain (covered by 'self').
=> bug 948151: Add attachment URLs to CSP img-src

kuma/settings/common.py, kuma/static/js/components/local-anchor.js, kuma/static/js/components/page-load-actions.js, kuma/static/js/utils/utils.js, kuma/static/js/wiki-toc.js, kuma/static/styles/base/elements/document.scss, kuma/static/styles/components/wiki/elements.scss
This resolves the problem described in bug 1479817 on Bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1479817
I also extracted the `scrollToHeading` function into utils and removed the jQuery dependency it had. Also, added `scroll-behaviour: smooth;` to the `html` element so, now in supported browsers, the scroll behaviour will be silky smooth. (Try Fx)
@jwhitlock @hobinjk r?
=> Fix Bug 1479817, anchor link headings are obscured by toc

kuma/core/i18n.py, kuma/core/middleware.py, kuma/core/urlresolvers.py, kuma/users/tests/test_models.py, requirements/default.txt, requirements/dev.txt
[bug 1477016](https://bugzilla.mozilla.org/show_bug.cgi?id=1477016) is a bug introduced with the locale updates for Django 1.11. When generating URLs from a management command, no translation is active, and this appears as ``None`` in Django 1.11. When helping users recover their account, I often use management commands to generate and send profile recovery emails, and these emails contained invalid URLs with the locale set to '/None/'.
The change (maybe) is that Django's ``get_language()`` returns ``None`` when languages are deactivated. This is done by setting the active language to a class that returns ``None`` for the language code, avoiding falling back to the default language.
https://github.com/django/django/blob/bd197d3f927f6d17fc4738366126e06c6a95f366/django/utils/translation/tran …
=> bug 1477016: Resync locale logic with Django 1.11, use en-US when no translation is active

kuma/static/styles/base/elements/document.scss
As mentioned in https://bugzilla.mozilla.org/show_bug.cgi?id=1498685, smooth scrolling in Chrome can trigger motion sickness in some users. This removes the scrolling behaviour and switching back to normal.
=> Bug 1498685, remove smooth scrolling

kuma/static/styles/base/elements/document.scss, kuma/static/styles/base/elements/forms.scss, kuma/static/styles/base/elements/typography.scss, kuma/static/styles/components/contribution/form.scss, kuma/static/styles/components/home/column-callout.scss, kuma/static/styles/components/home/home-hacks.scss, kuma/static/styles/components/home/home-masthead.scss, kuma/static/styles/components/structure/nav-footer.scss, kuma/static/styles/components/structure/socialaccount-providers.scss, kuma/static/styles/components/users/user-links.scss, kuma/static/styles/components/users/user-tags.scss, kuma/static/styles/components/wiki/communitybox.scss, kuma/static/styles/components/wiki/content/card-grid.scss, kuma/static/styles/components/wiki/content/originaldocinfo.scss, kuma/static/styles/components/wiki/crumbs.scss, kuma/static/styles/components/wiki/indicators.scss, kuma/static/styles/components/wiki/quick-links.scss, kuma/static/styles/components/wiki/toc.scss, kuma/static/styles/includes/_mixins.scss, kuma/static/styles/includes/_mixins_indicators.scss, kuma/static/styles/includes/_vars.scss, media/maintenance/css/maintenance.css
This switches to Arial from Verdana. As a result I had to also make some tweaks to the typography. It is not a 1:1 match, but then it is not intended to be. Let me know your thoughts. Thanks!
=> Fix Bug 1491154, switch from Verdana to Arial

Jenkinsfiles/utils.groovy
This PR configures the deployments to the MozIT prod instance in the same manner as they're configured for MozMEAO prod. This can be merged at any time.
=> bug 1483072: deploy to MozIT prod with usual settings

kuma/static/styles/components/wiki/indicators.scss
This removes the `.banner` and `.badge` style classes, which are no longer in use on MDN:
- https://developer.mozilla.org/search?locale=*&css_classnames=banner&topic=none
- https://developer.mozilla.org/search?locale=*&css_classnames=badge&topic=none
Part&nbsp;of [bug&nbsp;1492018](https://bugzil.la/1492018).
Follow‑up to #4979 and mdn/kumascript#830.
---
=> Bug 1492018: Remove `.banner` and `.badge` style classes

kuma/dashboards/forms.py, kuma/settings/common.py, kuma/urls.py, requirements/constraints.txt, requirements/dev.txt, tests/functional/test_feedback.py, tests/pages/base.py, tests/utils/urls.py, tox.ini
Our TravisCI flake8 test installs the latest, and flake8 3.6.0 was released, so flake8 builds are busted for a while. This updates the libraries and makes the code work with the latest linters.
* flake8 3.5.0 → 3.6.0: Update dependencies, small fixes
* flake8-import-order 0.17.1 → 0.18: Python 3.7 support
* pycodestyle 2.3.1 → 2.4.0: Checks break after binary operator (``W504``), invalid escape sequences in string literals (``W605``).
* pyflakes 1.6.0 → 2.0.0: Checks unused exception binding, etc.
Update the code to mark regex with ``r''``, to avoid escape sequence checks. Add ``W504`` to the ignore list, since it conflicts with ``W503`` (break before binary operator).
=> bug 1467532: Update to flake8 3.6.0, dependencies

kuma/static/js/libs/prism/prism-line-numbers.js
for https://bugzilla.mozilla.org/show_bug.cgi?id=1499455
the span element with line-numbers-rows class is added by prism, and this looks like the code.
added `aria-hidden=true`
this at least skips the line number on Safari + VoiceOver
=> Bug 1499455 - Hide code line numbers from screen reader.

kuma/payments/jinja2/payments/payments.html
Update payments FAQ #5 to clarify that Foundation donations are tax-deductible in the US, and not generally in other places. Link to the FAQ entry for more details.
=> bug 1490727: Clairify tax status of Foundation

Jenkinsfiles/default.groovy, Jenkinsfiles/master.groovy
Correction for #5044. Since we're no longer pushing images to both quay.io (from the MozMEAO Jenkins service) and DockerHub (from the MozIT Jenkins service), but to DockerHub only, stop pushing images altogether when we are running on the MozMEAO Jenkins service.
This approach has already been tested in a replay on the MozMEAO Jenkins service.
Hide whitespace changes when reviewing.
=> bug 1483072: stop pushing images from MozMEAO Jenkins

kuma/settings/common.py
Use ``SITE_URL``, like ``https://developer.allizom.org``, instead of ``'site'``, in CSP rules, so that loading the origin domain doesn't generate CSP reports for assets.
The default image is loaded from https://i2.wp.com/developer.mozilla.org/static/img/avatar.png?ssl=1, so this needs to be in the ``img-src`` rule. 
Also, the avatar URL needs to be publicly accessible, so use the production URL in development, fixing [bug 1485073](https://bugzilla.mozilla.org/show_bug.cgi?id=1485073).
=> bug 948151: Adjust CSP for CDNs, Gravatar default image

kuma/redirects/redirects.py, tests/headless/map_301.py, tests/headless/test_redirects.py
This PR addresses [bug 1477468](https://bugzilla.mozilla.org/show_bug.cgi?id=1477468). One of the assumptions I've made is that the ultimate goal is to remove all of the Marionette documents from MDN, so I've not depended upon the existence of Marionette documents when constructing the external redirects. For example, there are existing documents, like https://developer.mozilla.org/en-US/docs/Marionette and https://developer.mozilla.org/en-US/docs/Marionette/Builds, that are in-content redirects to their respective documents https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette and https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/Builds, but I've created explicit external redirects for them as well as their targets.
As part of the work towards this PR, I've deleted …
=> bug 1477468: add redirects for marionette

kuma/static/js/utils/utils.js
[Bugzilla 1503101](https://bugzilla.mozilla.org/show_bug.cgi?id=1503101)
This PR changes TOC existence check from `toc !== undefined` to truthy check, as [`document.getElementById()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById) returns `null`.
[Example of a page without TOC](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/panel)
=> bug 1503101: Fix hash link on pages without TOC

Jenkinsfiles/default.groovy, Jenkinsfiles/master.groovy, Jenkinsfiles/utils.groovy
This PR is part of the post cut-over cleanup of the Kuma repo. It removes the Groovy code related to the MozMEAO Jenkins service, which, as of this morning, had its MDN-related pipelines (for Kuma, Kumascript, and the interactive examples) deleted.
=> bug 1483072: remove Jenkins code related to MozMEAO

kuma/settings/common.py
In the CSP reporting URI and the Django sentry integration, set the environment from env variable ``SENTRY_ENVIRONMENT`` (default ``None``). This will be set by https://github.com/mdn/infra/pull/139.
=> bug 9489151: Set Sentry environment

package-lock.json, package.json
* node-sass 4.9.2 → 4.9.4: Update dependencies ``node-gyp``, ``request`` to avoid security issues. Removes ``cryptiles`` and ``hoek``. Upgrades ``minimatch``, but vulnerable versions may remain in other packages.
Issues on snyk:
* ``cryptiles`` < 4.1.2: https://app.snyk.io/vuln/npm:cryptiles:20180710
* ``hoek`` < 5.0.3: https://app.snyk.io/vuln/npm:hoek:20180212
* ``minimatch`` < 3.0.2: https://app.snyk.io/vuln/npm:minimatch:20160620
=> bug 1467532: Update to node-sass 4.9.4

kuma/payments/jinja2/payments/payment_terms.html, kuma/payments/tests/test_views.py, kuma/payments/urls.py, kuma/payments/views.py
This is only plain template which will be filled out with proper legal information.
Next step is to add this page as a link to checkbox form.
=> bug 1490727: Add new page for payment terms, for now just empty template

kuma/static/styles/components/compat-tables/_vars.scss, kuma/static/styles/components/compat-tables/bc-browser.scss, kuma/static/styles/components/compat-tables/bc-supports.scss, kuma/static/styles/components/compat-tables/bc-table.scss
See [bug&nbsp;1480106](https://bugzil.la/1480106) for details.
Follow‑up to #4948, which didn’t correctly update the **No&nbsp;support** and **Partial&nbsp;support** backgrounds.
Also fixes the <q>Samsung&nbsp;Internet&nbsp;Android</q> text overflow bug.
review?(@jwhitlock, @escattone)
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
=> Bug 1480106: Fix mobile BCD table support background and name overflow

kuma/payments/jinja2/payments/email/thank_you/email.html, kuma/payments/jinja2/payments/thank_you.html, kuma/payments/tests/test_views.py
* 🇺🇸 Americanize "programme" before sending strings to translators.
* Update test docstrings, which had been duplicated.
* Use the one-line mock for enabling or disabling payments (thanks @michal-macioszczyk!)
=> bug 1490727: Fix payments nits

kuma/wiki/jinja2/wiki/ckeditor_config.js
I didn’t know how to do this in https://github.com/mozilla/kuma/pull/4979 until @schalkneethling opened https://github.com/mozilla/kuma/pull/5069.
review?(@chrisdavidmills, @jwhitlock)
=> Bug 1492018: Prefer `.blockIndicator` for styling Note and Warning boxes

docker/images/kuma_base/Dockerfile
An unknown change (`gpg` did not update) is causing an error when trying to create `trustdb.gpg`:
```
gpg: cannot open '/dev/tty': No such device or address
```
Adding `--no-tty` allows the key download to continue successfully.
This began in 377ab2d5a72bb2e3e43eeb6d9a5c589693d5d790 from PR #5089.
=> bug 1506521: Add --no-tty to GPG commands

kuma/settings/common.py
An integer value is the lifetime of a database connection, in seconds, not the number of requests before closing:
https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-CONN_MAX_AGE
=> bug 957802: Fix comment for CONN_MAX_AGE

kuma/payments/jinja2/payments/includes/payments-banner.html, kuma/payments/jinja2/payments/includes/payments-form.html, kuma/static/js/payments-handler.js, kuma/static/styles/components/payments/banner.scss
**In this PR**
https://trello.com/c/SQgMeAXd/11-as-an-anonymous-user-i-want-to-learn-why-i-have-to-log-in-to-github-so-that-i-dont-leave-the-process
** notes for QA **
**Screenshot**
=> bug 1490727: Recurrent payment force GitHub redirect

kuma/static/styles/components/wiki/crumbs.scss, kuma/static/styles/components/wiki/quick-links.scss
@hobinjk This reduces the font size for the sidebar entries and breadcrumbs, which resolves bug 1506591. r?
=> Fix Bug 1506591, reduce font size of sidebar entries and crumbs

kuma/static/styles/components/wiki/indicators.scss
This reduces the top margin and overall sizing of the secure context icon when used inline.
Page to test: https://developer.mozilla.org/en-US/docs/Web/API/PaymentResponse
Before:
After:
@hobinjk r?
=> Fix Bug 1505486, reduce top margin for inline secureContext icon

kuma/wiki/jinja2/wiki/ckeditor_config.js
To test this, edit a page on MDN. In CKEditor, choose the "Note" component from the `Styles` dropdown. Switch to the source output, confirm that the following is output:
```
<div class="note" role="complementary">
<p>&nbsp;</p>
</div>
```
Switch back to the WYSIWYG and add a "Warning" component. Switch to source and confirm that the output is as follows:
```
<div aria-label="Important note" class="warning" role="region">
<p>&nbsp;</p>
</div>
```
r?
=> Bug 1493499, add aria roles to notes/warning boxes inside ckeditor

kuma/static/styles/includes/_vars.scss
This resolves the problem as described in Sprints issue 608, and diagnosed here:
https://app.zenhub.com/workspaces/mdn-sprint-board-5ab3d23fd0f4ea53b0022a61/issues/mdn/sprints/608#issuecomment-437789094
@jwhitlock @hobinjk r?
=> (fix) - Bug 1504238, interactive examples and content area has gotten narrower

requirements/constraints.txt, requirements/default_and_test.txt
* requests: 2.18.4 → [2.20.1](https://github.com/requests/requests/blob/master/HISTORY.md): security fix for authorization header on https to http redirects, content-type parsing is case insensitive, other fixes.
Update the requirements for requests as well:
* certifi 2018.1.18 → [2018.10.15](https://github.com/certifi/python-certifi): Update to latest release
* idna 2.6 → [2.7](https://github.com/kjd/idna/blob/master/HISTORY.rst): Unicode 10.0, reject dot-prefixed domains
* urllib3 1.22 → [1.24.1](https://github.com/urllib3/urllib3/blob/master/CHANGES.rst): Support for dropping headers on redirect, drop Python 2.6 and 3.3 support, other fixes
=> bug 1467532: Update to requests 2.20.1, requirements

kuma/payments/views.py
This is PR for:
https://trello.com/c/Ek6n2n2C/19-as-a-user-i-can-see-information-about-recurring-payments-so-that-i-can-understand-how-recurring-payment-works
Quick change, right now payment Name field is pre-filled only from User fullname field.
=> bug 1490727: Changed to pre-fill payment name only from MDN user fullname field

kuma/core/utils.py
Revert 25041d4bb5d406e362ddc08df6fa3b0a4ba72569, which processed the queryset with list before paginating it, for Python 3 compatibility.
I suspect the Py3 change is instead the unit tests for pagination.
=> bug 1508268: Do not load queryset before paginate

kuma/static/styles/components/wiki/toc.scss
Safari only supports the prefixed version at the moment.
=> Support sticky ToC on Safari

kuma/static/styles/components/home/home-masthead.scss
This prevents the hero area's background SVG from causing horizontal scrolling at small mobile viewports. @hobinjk r?
=> Bug 1496482, fix horizontal scrolling on mobile viewwports, landing page

docker/images/kuma_base/Dockerfile, jinja2/404.html, jinja2/base.html, jinja2/includes/google_analytics.html, jinja2/includes/header-toolbox.html, jinja2/includes/login.html, kuma/authkeys/tests/test_decorators.py, kuma/core/decorators.py, kuma/core/utils.py, kuma/dashboards/jinja2/dashboards/includes/watch_approved.html, kuma/dashboards/jinja2/dashboards/includes/watch_locale.html, kuma/dashboards/views.py, kuma/users/adapters.py, kuma/users/jinja2/account/password_reset.html, kuma/users/jinja2/account/password_reset_done.html, kuma/users/templatetags/jinja_helpers.py, kuma/wiki/jinja2/wiki/base.html, kuma/wiki/jinja2/wiki/document.html, kuma/wiki/jinja2/wiki/includes/approvals.html, kuma/wiki/jinja2/wiki/includes/buttons.html, kuma/wiki/jinja2/wiki/includes/kumascript_errors.html, kuma/wiki/jinja2/wiki/list/revisions.html, kuma/wiki/views/document.py, kuma/wiki/views/list.py, requirements/default.txt
To upgrade Kuma to Django 2.0, we need to address multiple warnings.
- 15971ffd7a8915cec67b3138a1424930472dc27b fix the issues within our code.
- f5b781577b56119c434264d0415783c24e7d263f updates django-allauth to a version which is Django 2.0 ready.
- 377ab2d5a72bb2e3e43eeb6d9a5c589693d5d790 address an issue with the Docker build and introduce `PYTHONWARNINGS=all` for documentation purposes.
After the `django-ratelimit` update, the remaining warnings are coming from `django-tidings` but will disappear automatically when we update to Django 2.0 (see: https://github.com/mozilla/django-tidings/blob/master/tidings/compat.py)
I am not sure it is worth waiting for a `django-ratelimit` release to merge this, but I believe we should take contact with the module maintainer to see if a release can …
=> bug 1467520: bug 1467532: Resolve RemovedInDjango20Warnings

kuma/static/js/payments-handler.js
This PR simply ensures we represent pennies to the correct place, ie 1.2 to  $1.20
**in this PR**
- https://trello.com/c/Kw80DkXl/58-bug-fractional-custom-amounts-should-be-displayed-as-000
**Notes for QA**
=> bug 1490727: Round floating point amounts to 2 decimal places

kuma/static/js/payments-confirmation.js
Analytics bug:
In GA we have 2 'payment success' events without labels, this may be because these 2 users have browser storage disabled, so the users original authentication level was not being pulled into the event label. 
This PR Prevents events from being fired if the users browser storage is disabled, and sends a default event label of 'lost' if we can't get the users authentication level.
**In this pr**
- https://trello.com/c/gGrrocTl/101-ga-success-event-doesnt-have-a-label
**QA notes**
=> Dont send analytics if localstorage is disabled, send a default label if there is no user.

jinja2/includes/config.html, kuma/settings/common.py, kuma/static/js/compat-table/components/compat-table-survey.js, kuma/static/js/wiki-compat-trigger.js, kuma/static/styles/compat-table/components/_compat-table-survey.scss, kuma/static/styles/wiki-compat-tables.scss
This adds the new survey to the BCD table. This is ready for code review. Still need to confirm the following:
1. Copy for the survey link
2. Whether we want to open the survey in a new tab, or the current tab
@Elchi3 r?
=> Bug 1501282, add BCD survey

Jenkinsfiles/integration-tests.groovy, Jenkinsfiles/prod-integration-tests.yml, Jenkinsfiles/stage-integration-tests.yml, docker-compose.selenium.yml, requirements/constraints.txt, requirements/dev.txt, requirements/test.txt, scripts/run_functional_tests.sh, tests/functional/test_dashboard.py, tests/functional/test_report.py, tests/pages/article_edit.py, tests/pages/base.py, tests/pages/notfound.py
This PR is a step forward for the functional tests, but issues remain. For me, it felt the most natural to to bundle these five commits into one PR, but I can split them out into separate PR's if preferred.
Here are the highlights:
- I've updated to these versions:
- Python `selenium` package to version `3.141.0` (latest)
- Python `pytest-selenium` package to version `1.14.0` (latest)
- Docker image `selenium/standalone-chrome:3.141.5` (latest)
- Docker image `selenium/standalone-firefox:3.141.5` (latest)
- Python `PyPOM` package to version `2.2.0` (latest)
- I moved away from using the selenium hub and selenium node Docker images to using the stand-alone selenium Docker images for `chrome` and `firefox` (resolved `WebDriverException: Message: Error forwarding the new session cannot find …
=> bug 1462400: Improve functional tests

.travis.yml, docker/images/kuma_base/Dockerfile, docker/images/kuma_base/Dockerfile-py3, docs/development.rst, kuma/core/pipeline/cleancss.py, package-lock.json, package.json
This patch updates package.json to upgrade from clean-css 3.x
to clean-css-cli 4.x. It makes other modifications to add and
correctly process the command-line arguments that are required
for the new version of cleancss.
Test plan:
- spot check the files in static/build/styles to make sure they
have not changed too dramatically. In particular, pay attention
to relative paths for images and fonts.
- run locally to verify that there is no obvious CSS breakage.
=> bug 1487403: upgrade cleancss to version 4.x

kuma/users/tests/test_views.py, kuma/wiki/models.py, kuma/wiki/templatetags/jinja_helpers.py, kuma/wiki/tests/test_content.py, kuma/wiki/tests/test_events.py, kuma/wiki/tests/test_helpers.py, kuma/wiki/tests/test_models.py, kuma/wiki/tests/test_tasks.py, kuma/wiki/tests/test_templates.py, kuma/wiki/tests/test_utils.py, kuma/wiki/tests/test_views.py, kuma/wiki/utils.py
``absolutify`` is a Jinja2 filter and utility function that turns paths into absolute URLs. It currently uses ``Site.objects.get_current()`` to get the domain name, and assumes ``https`` is the protocol. This means tests assume the site prefix is ``https://example.com``, and require a database or to mock the ``get_current`` method. Also, when used locally, the link is ``https://localhost:8000``, and broken due to the ``https``. It also has some unneeded flexibility, to allow using a different ``Site`` object which is unused outside of tests.
Maybe for these reasons, lots of code now has custom methods for creating absolute URLs. I'd like to get back to One Way of doing this common operation.
This PR updates ``absolutify`` to use ``settings.SITE_URL``, which is ``https://localhost:8000`` …
=> bug 1510020: In absolutify, use settings.SITE_URL instead of Site.get_current()

kuma/wiki/jinja2/wiki/document.html, kuma/wiki/tests/test_views.py, kuma/wiki/views/document.py
We currently constuct the <title> of a document like this:
`<title> - <SEO root document title> | MDN`
So for https://developer.mozilla.org/en-US/docs/Learn/CSS we have:
>  Learn to style HTML using CSS - Learn web development | MDN
This patch shortens the title by removing the SEO root title, leaving:
> Learn to style HTML using CSS | MDN
=> Bug 1423716: stop adding the SEO root title to all document titles

kuma/static/styles/components/payments/form.scss
IE puts an `X` to the right of inputs in order to clear them.
This overlaps the `?` help text action on the email field, so we should disable the IE marker for this input.
**in this PR**
- https://trello.com/c/Vh52EyJj/96-internet-explorer-x-button-displayed-in-email-field-overlaps-the-button
**Screenshot of the bug:**
=> bug 1490727: Remove clear field `x` from email input on IE on payments form.

kuma/static/js/payments-confirmation.js, kuma/static/js/payments-handler.js
We're having issues with analytics for recurring payments. The `Recurring payments > success` event has no label. The label is required for conversion rates as it contains the users authentication level.
The solution proposed is to create a new event that has the users authentication in the event action - as this seems more reliable.
We want to preserve the current setup so have added _Recurring payment v2_ event category that has the user's status in the event action.
Also to keep consistency I have added *all* _recurring payment v2_ events (inc banner shown/expanded) to include the users authentication level in the action.
With _recurring payment v2_ I have also kept the authenticated/anonymous label for filtering (if it ever decides to work again!)
All new events will look something …
=> bug 1490727:  Added a new set of analytics for recurring payments.

kuma/static/js/payments-handler.js
On the popover we should not persist the custom amount input.
**in this pr**
- https://trello.com/c/66tR9Dje/80-ui-banner-only-remembers-custom-amount-vs-faq-pages-dont-remember-either-predefined-or-custom-amounts
**notes for QA**
=> bug 1490727: Force form to remove custom amount on change.

kuma/payments/jinja2/payments/thank_you.html
Simply re-align the text to the centre.
**in this pr**
- https://trello.com/c/SMnw7COU/95-error-page-looks-off
Fixes this bug
=> bug 1490727: Align payment error page content to the centre.

kuma/payments/jinja2/payments/payments.html, kuma/payments/jinja2/payments/thank_you.html, kuma/static/js/payments-faq.js, kuma/static/styles/components/payments/page.scss
No confirmation or validation is attached to the feedback form on the FAQ/confirmation/error pages
**in this pr**
- https://trello.com/c/zFm1s07N/70-bug-no-confirmation-received-for-feedback-message-sent
**notes for QA**
=> Add some validation and success info on feedback form.

kuma/core/middleware.py, kuma/core/tests/test_locale_middleware.py
Kuma's locale middleware correctly detects the desired language when
non-standard capitalization is used. "En" is detected as "en-US",
"PT" is detected as "pt-PT", and "FR-FR" is detected as "fr". But even
though the language is corrected detected from the path, the
LocaleStandardizerMiddleware does a case-insensitive prefix match
between the path and the detected language and responds with a 404
in this case becasue "En" is not a prefix of "en-US" and because
"fr" is not a prefix of "FR-FR".
This patch modifies LocaleStandardizerMiddleware to do case-insensitive
comparisons so that locales like "En", "EN", "PT" and "FR-FR" that
previously gave unnecessary 404s now redirect to a canonical locale.
Note that the middleware has all along allowed locales like "en-U" to
redirect to "en-US". It …
=> Bug 1509357: redirect En/ and EN/ to en-US/

docker/images/kuma_base/Dockerfile, docker/images/kuma_base/Dockerfile-py3
Test Plan:
- compare the static/build directory before and after this change
to ensure that none of the built assets change with the upgrade.
=> bug 1505084: update the kuma_base Docker image to use Node 10.14

tests/functional/test_article.py, tests/functional/test_article_edit.py, tests/functional/test_home.py, tests/pages/base.py
Both of these tests:
- `tests/functional/test_article.py::test_header_signin`
- `tests/functional/test_article_edit.py::test_edit_sign_in`
would sometimes fail due to their buttons being obscured by the task-completion survey, so I disabled the survey prior to clicking. I also removed the `trigger_signin` method from the `Header` class, replacing it with `.signin_link.click()`, as I thought it was more direct and readable (i.e., the method led me to think it was doing something more than just clicking on the sign-in link).
=> bug 1462400: fix test_header_signin and test_edit_sign_in

kuma/settings/common.py, tests/headless/__init__.py
Thanks to @jwhitlock, who pointed out that we're not serving the correct `robots.txt` file for the attachments domain. We should be serving an empty string for `robots.txt` for `mdn.mozillademos.org` (and its origin `demos-origin.mdn.mozit.cloud`), but instead we've been serving `ROBOTS_GO_AWAY_TXT` since we cut-over to the MozIT-based infrastructure. That was my fault for overlooking the need for this update during the cut-over. This PR corrects that oversight.
=> bug 1483072: update prod attachment origin

kuma/static/styles/components/compat-tables/bc-icons.scss, kuma/static/styles/components/compat-tables/bc-table.scss, kuma/static/styles/includes/_vars.scss
Problem is described here[https://github.com/mdn/sprints/issues/680] and in the screenshots below:
Tested in Firefox, Chrome, Safari, Edge and IE11
@davidflanagan 	r?
=> Fix Bug 1509833, ensure browser text labels are consistent across all pages for BCD tables

kuma/wiki/jinja2/wiki/ckeditor_config.js
This patch removes the "Summary" style we've decided not to
use anymore and renames the existing SEO summary
option to simply "Summary", per discussion held on Discourse:
https://is.gd/ss9I6r
=> Bug 879839 - Remove Summary style, rename SEO Summary option

docker/images/kumascript/Dockerfile
https://github.com/mdn/kumascript/pull/1008 updates KumaScript to
use Node 10 instead of Node 8. This patch updates the KumaScript
Dockerfile in the Kuma repo to install Node 10 in the KumaScript image.
=> Bug 1505084: update the KumaScript Dockerfile to install Node 10.13.0

docs/development.rst, docs/installation.rst, requirements/docs.txt
docker-compose 1.23.0 changed the way containers are named to add a
random string of hexadecimal digits to each name, so the instructions
in docs/installation.rst that use the `docker exec -i <container_name>`
form no longer work since the container name is not predictable.
This patch updates those commands to use `docker-compose exec <service>`
instead.
The patch also updates requirements/docs.txt to keep the version of
Jinja2 in sync with what is in requires/default.txt
Test Plan:
- `cd docs; make html` and verify that the generated file looks right.
- install a new copy of Kuma, following these revised instructions
=> bug 957802: Update docs to use docker-compose exec

requirements/default.txt, requirements/dev.txt
* hashin 0.13.4 → [0.14.1](https://github.com/peterbe/hashin#version-history): Adds ``--update-all`` and ``--interactive`` (which look interesting), support  extras syntax, and threaded PyPI requests. I use ``hashin`` to generate these PRs, so I keep it up to date.
* Django 1.11.16 → 1.11.18: Addresses [GeoDjango bug](https://docs.djangoproject.com/en/2.1/releases/1.11.17/), Python 3.7 compat, and a [security issue in the default 404 handler](https://www.djangoproject.com/weblog/2019/jan/04/security-releases/) (which Kuma replaces). This should have no effect, but tools may complain we're missing a security update.
=> bug 1518653: Update to Django 1.11.18, hashin 0.14.1

kuma/static/styles/wiki-wysiwyg.scss
In PR #5154, the name of the seoSummary class was changed
in the CKEditor menu to just "Summary". This patch makes
the same change to the CSS that is used to display the
style when in the editor, so that the label drawn above
the styled content says that instead of "SEO Summary".
=> Fix the label of the seoSummary style to be just "Summary"

docker-compose.yml, kuma/wiki/tests/test_views.py, kuma/wiki/tests/test_views_document.py, tests/headless/test_endpoints.py
See [bug 1404669](https://bugzilla.mozilla.org/show_bug.cgi?id=1404669) for more context.
This PR:
- fixes `?redirect=no` handling for content-based redirects within the development environment (it does not fix the bug for the stage and production environments, for that and for a fuller explanation of this bug and its resolution, see https://github.com/mdn/infra/pull/168)
- since no current unit or functional tests are able to detect this bug, adds two headless functional tests, one of which specifically checks for this bug, that can be run against the sample, stage, and production databases
- refactors the existing content-based redirection tests into the `pytest` style
This PR is a companion to https://github.com/mdn/infra/pull/168, and if approved, should be merged along with that PR …
=> Fix "?redirect=no" for document-based redirects (bug 1404669)

kuma/settings/common.py, kuma/static/js/components/payments/focus-visible.js, kuma/static/styles/components/payments/banner.scss, kuma/static/styles/components/payments/form.scss
Problem described in https://github.com/mdn/sprints/issues/705
We can eventually get rid of the JS once `:focus-visible` has wide enough browser support. You can read more on `:focus-visible` here:
https://drafts.csswg.org/selectors-4/#the-focus-visible-pseudo
=> Bug 1518844, remove focus rings from focusable elements, except for keyboard users

kuma/wiki/kumascript.py
With [node 10.14.0](
https://nodejs.org/en/blog/vulnerability/november-2018-security-releases/#denial-of-service-with-large-http-headers-cve-2018-1212), there is an 8K limit to HTTP headers. When file data is base64-encoded as a header, it can grow beyond 8K for some pages with 10 or more attachments. This results in a 400 error when rendering.
Reduce the attachment metadata to the filename and URL, which are the two attributes used by [Embed_text](https://github.com/mdn/kumascript/blob/master/macros/Embed_text.ejs) and [EmbedSVG](
https://github.com/mdn/kumascript/blob/master/macros/EmbedSVG.ejs), the only macros that use this data. Also, drop the "attachments" header, which encodes the same data but is unused.
This is a first step to removing these macros and no longer passing …
=> bug 1520574: Reduce file data passed to kumascript

kuma/static/styles/components/wiki/content/summary.scss, kuma/static/styles/wiki.scss
This changes sections marked with the class `summary` from
to 
As discussed in https://bugzilla.mozilla.org/show_bug.cgi?id=1510719 and https://discourse.mozilla.org/t/css-and-class-confusion-summary-vs-seosummary/30588/14
@wbamberg @davidflanagan r?
=> Bug 1510719, remove special styling for summary class

kuma/dashboards/tests/test_views.py, kuma/dashboards/views.py, tests/functional/test_dashboard.py, tests/headless/test_cdn.py
We believe that scrapers/crawlers hitting the revision dashboard
(while ignoring our robots.txt file) are causing significant
database load that is reducing performance of the site.
This patch changes the dashboards/revisions endpoint to require
login and to not be cached. The changes to kuma/dashboards/views.py
are trivial; most of the changes are adjustments to tests.
=> Bug 1520616: require login for the revision dashboard

__tests__/sass/mdn/_a11y-helpers-mixins-test.scss, __tests__/sass/test.scss, kuma/static/js/components/payments/focus-visible.js, kuma/static/styles/components/payments/form.scss, kuma/static/styles/includes/_mixins.scss
Problem is described here(although not very clearly ;p)
https://github.com/mdn/sprints/issues/713
In essence, the problem is that even though the radio buttons do receive focus, and is navigable using the arrow keys, it is not clear when they have focus.
Here is the current behaviour on production. As can be seen, when focus is moved from the email field to the radio buttons, nothing actually indicates that the focus has moved to the `checked` radio button. It feels like focus moves from the email field, to someplace on the form, and then to the custom amount field.
Adding the `focus-visible` class with the clear focus ring solves the problem
=> Bug 1518844, ensure focus is clearly indicated on amount radio buttons

docker-compose.ssl.yml, docker-compose.yml, kuma/wiki/kumascript.py, kuma/wiki/models.py, kuma/wiki/tests/test_models.py, kuma/wiki/tests/test_views.py, kuma/wiki/tests/test_views_document.py
https://github.com/mdn/kumascript/pull/1035 is a big patch that
rewrites and modernizes the KumaScript server. This is a smaller PR
that updates the Kuma repo for those changes.
The primary change is that the KumaScript server no longer supports
a GET endpoint for rendering documents, so Kuma now needs to send
document content to KumaScript for rendering with a POST request. This
change is primarily in wiki/kumascript.py, but it causes small
follow-on changes in a nubmer of other files as well.
The patch also includes some new useful scripts I wrote while testing.
And it changes docker-compose.yml to remove memcached which is no
longer required.
=> Bug 1509430: Kuma changes for the new version of KumaScript

docker-compose.test.yml
* ``sqlite_memcached`` - Not used because of MySQL-specific behavior, and now broken due to dropped ``memcached`` dependency.
* ``nosearch`` - We continue to test with a containerized ElasticSearch server.
=> bug 1509430: Drop unused test configurations

kuma/wiki/kumascript.py
Loading ``config.KUMASCRIPT_TIMEOUT`` as a function default requires database and cache access, which isn't available for all configurations, such as collecting localization data when building the production Docker images. Instead, use ``None`` and read the config in the function body.
Update ``cache_control`` to also use the None pattern, for consistency.
=> bug 1509430: Move to just-in-time KS timeout

kuma/wiki/kumascript.py
Remove file attachment data from the KumaScript API. This avoids creating a header that exceeds 8K bytes when a page has several attachments.
This API was used by two macros, [EmbedSVG](https://github.com/mdn/kumascript/blob/811f0f19b8acb6990ca94ee4f8e5334a65b975ba/macros/EmbedSVG.ejs#L6) and [Embed_text](https://github.com/mdn/kumascript/blob/811f0f19b8acb6990ca94ee4f8e5334a65b975ba/macros/Embed_text.ejs#L30-L35). @wbamberg has removed this macro from all pages on MDN Web Docs.
*Update*: Macros removed in https://github.com/mdn/kumascript/pull/1047
=> bug 1520574: Remove file data from the KumaScript API

requirements/default.txt
* django-ratelimit 1.1.0 → 2.0.0: Fail open on missing cache, drop support for Django 1.10 and earlier, add support for Django 2.0 and 2.1. This will remove the deprecation warnings about using ``is_authenticated`` as a function rather than a property.
=> bug 1518653: Update to django-ratelimit 2.0.0

__tests__/sass/mdn/_button-states-mixins-test.scss, __tests__/sass/test.scss, kuma/settings/common.py, kuma/static/js/components/codepen-iex/codepen-iex.js, kuma/static/styles/components/codepen-iex/codepen-iex.scss, kuma/static/styles/includes/_mixins.scss, kuma/wiki/constants.py, kuma/wiki/jinja2/wiki/base.html
A description of this can be found here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1521135
There is also another doc from @wbamberg that details the various stages. The PR addresses Stage A:
https://gist.github.com/wbamberg/ca85831ec166a0bfed4bbcc031d3bf73#stage-a-enable-mdn-codepen-integration
Here are a couple of screenshots showing the interaction:
On load:
When hovering over the button:
After clicking the button
I used `/en-US/docs/Web/API/Document/querySelector` for the example. To test, you need to add the following code to the document via CKEditor(This is also how the writers will add the examples for Stage A):
```
<div class="codepen-iex" data-default-tab="js,result" data-editable="true" data-height="400" data-prefill="">
<pre class="hidden" data-lang="html">
&lt;button …
```
=> Bug 1521135, Stage A of codepen-iex implementation

kuma/wiki/managers.py
This PR represents a small part of the work related to [bug 1518482](https://bugzilla.mozilla.org/show_bug.cgi?id=1518482), but I wanted to have something to show after a frustrating day of trying to make sense of SEO and Google's new and old search consoles (e.g., the new search console doesn't seem to show the 38K+ errors that the old one does).
This PR removes 101 Google Bot indexing errors of the category `Submitted URL blocked by robots.txt`, which means the URL is included within the `sitemap` but excluded by `robots.txt`. The main lot here are the document URL's with a slug that starts with `Experiment:` (100 of them). The mysterious one is the single URL https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver/status (a redirect to a bugzilla page), which is not …
=> bug 1518482: remove some docs from sitemap

jinja2/includes/config.html, kuma/settings/common.py, kuma/static/js/wiki-compat-trigger.js, kuma/static/styles/wiki-compat-tables.scss
I decided the keep the JS and SCSS files in the codebase. Seeing that it is very generic, and we are bound to run another survey for BCD at some point, this will make it much faster to get it up and running.
Also, the code is not loaded anywhere, so there is no negative performance impact to keeping it.
=> Bug 1522441, switch back to Github link from survey for BCD

kuma/static/styles/locales/ja.scss, kuma/static/styles/locales/ko.scss, kuma/static/styles/locales/zh-CN.scss, kuma/static/styles/locales/zh-TW.scss
[Bugzilla 1522385](https://bugzilla.mozilla.org/show_bug.cgi?id=1522385)
This PR overrides global `font-style: normal !important` of following locales, for `.syntaxbox > var` and `.syntaxbox > em`.
```
ja
ko
zh-CN
zh-TW
```
Why: To mark that certain keywords are programmer-specified contents, and can be changed.
Related issue: [973171: Don't use italic text in CJKT pages](https://bugzilla.mozilla.org/show_bug.cgi?id=973171)
=> bug 1522385: Enable italic text within syntaxbox for CJKT

kuma/attachments/jinja2/attachments/includes/attachment_list.html, kuma/dashboards/jinja2/dashboards/includes/revision_dashboard_body.html, kuma/wiki/jinja2/wiki/confirm_document_delete.html, kuma/wiki/jinja2/wiki/confirm_revision_revert.html, kuma/wiki/jinja2/wiki/document.html, kuma/wiki/jinja2/wiki/edit.html, kuma/wiki/jinja2/wiki/includes/document_macros.html, kuma/wiki/jinja2/wiki/list/revisions.html
This PR is another contribution towards the work of https://github.com/mdn/sprints/issues/751 ([bug 1518482](https://bugzilla.mozilla.org/show_bug.cgi?id=1518482)). It addresses some of the 502/504 errors, specifically the ones related to the `users.user_detail` endpoint (e.g., https://developer.mozilla.org/en-US/profiles/myf). That endpoint is not without cost, as it makes a query for the user's most recent revisions, has little to no worth in terms of SEO, and yet is crawled on every document page (the contributor links at the bottom). This PR adds `rel="nofollow"` to all links to user profiles on MDN. The main benefit will be from the document pages (since they're loaded with `index, follow` for the robots `meta` tag). Most, if not all, of the other changes were done for consistency, …
=> bug 1518482: nofollow links to user profiles

kuma/static/styles/components/content.scss, kuma/static/styles/includes/_mixins.scss
Part of [bug 1510719](https://bugzilla.mozilla.org/show_bug.cgi?id=1510719)
This removes all remaining instances of&nbsp;`.summary` that were missed in&nbsp;https://github.com/mozilla/kuma/pull/5193.
=> Bug 1510719: Remove remaining `.summary` special styling

kuma/landing/views.py
This PR disallows the search endpoint in `robots.txt` per recommendation of our SEO expert. It is the rebirth of #5221, but with a new approach to disallowing the search endpoint in the `robots.txt` file such that valid document pages whose slug includes `/search` will not be included.
It has been tested using the [Google Search console's robots.txt Tester](https://www.google.com/webmasters/tools/robots-testing-tool?siteUrl=https://developer.mozilla.org/).
To test locally:
- Add `ALLOW_ROBOTS_WEB_DOMAINS=localhost:8000` to your `.env` file prior to `docker-compose up -d`
- Navigate to http://localhost:8000/robots.txt
=> bug 1518482: disallow search in robots.txt

kuma/search/jinja2/search/results.html
This work stems from the recommendation from our SEO expert to disallow the search results page. Since it doesn't seem possible to disallow the search results page via `robots.txt` (see #5221), the next best thing is to disallow it via the `robots` `meta` tag. We're already blocking indexing on the search results page via the `robots` `meta` tag, but let's add `nofollow` to make it complete.
=> bug 1518482: nofollow search results

kuma/wiki/jinja2/wiki/document.html, kuma/wiki/tests/test_views.py, kuma/wiki/views/document.py, tests/functional/test_feedback.py
This reverts commits ff5f81e65c22ddb530a3a2355caee138a4a3f569
and 5fdf95cae312cbddaceb89be32370c7fe4ec27e2.
=> Revert "Bug 1423716: stop adding the SEO root title to all document titles"

kuma/payments/context_processors.py, kuma/payments/utils.py, kuma/payments/views.py, kuma/users/templatetags/jinja_helpers.py, kuma/wiki/content.py, kuma/wiki/tests/test_models.py, requirements/constraints.txt, requirements/dev.txt, tests/functional/test_dashboard.py, tests/headless/test_cdn.py, tests/pages/dashboard.py, tox.ini
Package updates:
* hashin 0.14.1 → 0.14.4: Comment parsing fix for ``--update-all``, add ``--index-url`` to use different PyPI server.
* flake8 3.6.0 → 3.7.3: Add support for per-file ignores
* configparser 3.5.0 → 3.7.1: Sync with Python 3.7.2
* pycodestyle 2.4.0 → 2.5.0: Check for over-indented blocks (``E117``)
* pyflakes 2.0.0 → 2.1.0: Check for "``is``" with string and integer literals, other Python 3.x support
Add a new dependency for flake8:
* entrypoints 0.3: Advertise objects with a common interface
The flake8 update raised several new warnings, and I've made small changes to the code to fix them. I've also fixed issues with import order that weren't detected by TravisCI.
I've updated ``tox.ini`` so that we won't get automatic flake8 updates anymore 😿 but we will get import order …
=> bug 1332666: Update hashin, flake8, and dependencies

kuma/feeder/admin.py, kuma/feeder/management/commands/update_feeds.py, kuma/feeder/models.py, kuma/feeder/sections.py, kuma/feeder/tasks.py, kuma/feeder/tests/test_models.py, kuma/feeder/tests/test_tasks.py, kuma/feeder/tests/test_utils.py, kuma/feeder/utils.py
This PR updates the `kuma.feeder` app to better support Python3. The only changes here provide a string experience that is more consistent between Python2 and Python3.
=> bug 1467518: update kuma.feeder to better support Python3

kuma/landing/tests/test_utils.py, kuma/landing/urls.py, kuma/landing/views.py
This PR updates the `kuma.landing` app to better support Python3. The only changes here provide a string experience that is more consistent between Python2 and Python3.
=> bug 1467518: update kuma.landing to better support Python3

kuma/redirects/redirects.py
This PR updates the `kuma.redirects` app to better support Python3. The only changes here provide a string experience that is more consistent between Python2 and Python3.
=> bug 1467518: update kuma.redirects to better support Python3

kuma/core/utils.py, kuma/feeder/management/commands/update_feeds.py, kuma/wiki/exceptions.py, kuma/wiki/tasks.py
Simplify batch processing by removing the cache lock code. Code coverage also increases since there are no tests for this code.
The cache lock code was added in PR #2423, when rendering stale documents was expensive, and was being groomed to be the mechanism for mass document regeneration. With the changes of the past 5 years, this is no longer the case, and the risk of parallel re-render threads is less.
The cache was also used for feed processing, which could also be expensive. We currently only display the Hacks Blog feed, and do not intend to republish more feeds. Again, the risk of parallel feed fetching is much less for MDN and Hacks then it was 5 years ago.
=> bug 1522718: Remove cache lock code

kuma/payments/constants.py, kuma/payments/context_processors.py, kuma/payments/jinja2/payments/includes/payments-form.html, kuma/payments/tasks.py, kuma/payments/tests/test_forms.py, kuma/payments/tests/test_utils.py, kuma/payments/tests/test_views.py, kuma/payments/urls.py, kuma/payments/utils.py, kuma/payments/views.py, kuma/users/signal_handlers.py, kuma/users/tests/test_signal_handlers.py
*This is an update of PR #5139 after rebasing on current master.*
When a User is deleted all subscriptions will be canceled. This uses the utility function ``cancel_stripe_customer_subscription``, which is also used when a User cancels their subscription subscription.
I changed a few other things as well, which could be broken up into more PRs if this one is too big:
* The utility functions ``get_stripe_customer_data`` and ``cancel_stripe_customer_subscription`` took a username and email, for the sole purpose of logging them if Stripe returned an error. I've removed the error handling from these functions and moved it to the ``recurring_payment_management`` view, which is the only function that uses these utilities.
* I've adjusted the error handling as well, to gracefully handle all …
=> Bug 1490727: Cancel subscriptions when a user is deleted

requirements/default.txt, requirements/dev.txt
* [hashin 0.14.4 → 0.14.5](https://github.com/peterbe/hashin#version-history): Sort hashes for reliable ordering (used to update requirements)
* [Django 1.11.18 → 1.11.20](https://docs.djangoproject.com/en/dev/releases/1.11.19/): Address memory exhaustion issue with very long or large Decimal value (CVE-2019-6975)
* [Werkzeug 1.11.4 → 1.14.1](https://github.com/pallets/werkzeug/blob/master/CHANGES.rst): Many fixes and changes. Add some XSS protection to the in-browser debugger.
Note: Werzeug is used with ``./manage.py runserver_plus``, which allows interactive debugging of a single threaded server (see [Customizing the Docker environment](https://kuma.readthedocs.io/en/latest/development.html#customizing-the-docker-environment)). It is not used in production. …
=> bug 1332666: Security updates for Python packages Django, Werkzeug

kuma/static/styles/components/wiki/content/collapsible.scss
=> Bug 1523643, heading link widget breaks to new line on mobile

jinja2/react_base.html, kuma/urls.py, kuma/wiki/jinja2/wiki/react_base.html, kuma/wiki/jinja2/wiki/react_document.html, kuma/wiki/urls.py, kuma/wiki/views/document.py
This patch adds a new /ducks/ url just like our existing /docs/ url
for wiki documents, except it has a duck in the header. The URL route
is not installed if we're in production so this should be safe. We
are going to use this new url for our experimentation with React.
=> Bug 1525719: create a non-production /ducks/ endpoint for the React spike

docker/images/kuma_base/Dockerfile, docker/images/kuma_base/Dockerfile-py3, package-lock.json, package.json, scripts/travis-install
npm 6.4.1, included with node 10.14.2, uses loose version identifiers in the requires list. The exact versions installed are still specified, so nothing changes. However, since it would confuse the output of real package changes, I'm adding as an independent PR.
For example, ``@babel/highlight`` used to look like this:
```json
"@babel/highlight": {
"version": "7.0.0",
"resolved": "https://registry.npmjs.org/@babel/highlight/-/highlight-7.0.0.tgz",
"integrity": "sha512-UFMC4ZeFC48Tpvj7C8UgLvtkaUuovQX+5xNWrsIoMG8o2z+XFKjKaN9iVmS84dPwVN00W4wPmqvYoZF3EGAsfw==",
"dev": true,
"requires": {
"chalk": "2.4.1",
"esutils": "2.0.2",
"js-tokens": "4.0.0"
},
```
but now it looks like this:
```json
"@babel/highlight": {
"version": "7.0.0",
"resolved": …
```
=> bug 1468491: Update package-lock "requires" for npm 6, merge to devDependencies

kuma/static/js/wiki-edit.js
The CKEditor save buttons are enabled and disabled depending
on whether any of the content has changed. The JavaScript to do this
uses a jQuery find() function to locate a ".editor-container" element
within a form, and then dispatches dirty or clean events on that
container element.
This is fine in the normal case, but if the editor is maximized
then the DOM hierarchy changes and there is no .editor-container.
The find() call returns an empty array and the events are dispatched
on the zero elements in that array.
This patch adds a special case: when no container element is found,
we dispatch the required events directly on the form (which is where
the handlers for those events are installed.)
=> Bug 1522998: fix the CKEditor save buttons in maximized mode

.travis.yml
This may require clearing the caches in TravisCI, otherwise packages compiled for node 8 may mess up the build.
=> bug 1505084: Use node 10 in TravisCI

kuma/settings/common.py, kuma/static/js/utils/bug1522937-iex-test.js
The testing scenarios are described here:
https://github.com/mdn/sprints/issues/921#issuecomment-460967275
Pages for testing can be copied from production. These are:
* https://developer.mozilla.org/en-US/docs/User:schalkneethling/mobile/box-shadow-no-iex
* https://developer.mozilla.org/en-US/docs/User:schalkneethling/mobile/box-shadow-display-none
* https://developer.mozilla.org/en-US/docs/User:schalkneethling/mobile/box-shadow-display-none-empty-src
This is temporary while we gather some performance metrics. Once @atopal has sufficient data, we will back-out the script.
=> Bug 1522937, test three scenarios for hiding IEx

docker/images/kumascript/Dockerfile
This PR adds the default Java JRE to the KumaScript Docker image. The Java JRE is required to run the Nu HTML validator (https://github.com/validator/validator) which we're going to use to create a KumaScript test utility function that does HTML validation (PR coming soon) for use within tests for KumaScript macros.
The base image has been changed from the `slim` version (`10.14.2-slim`) to the `stretch` version (`10.14.2`) because the `default-jre` install fails with the `slim` version. It is possible to keep using the `slim` version, but it would require the "manual" creation of a man-page directory within the Dockerfile to accommodate the `default-jre` install, and in the interest of avoiding "manual", special-case tweaks, I decided to go with the `stretch` version to keep it simple …
=> bug 924958: add JRE to KumaScript Docker image

bower.json, kuma/settings/common.py, kuma/static/js/libs/prism/prism-clike.js, kuma/static/js/libs/prism/prism-core.js, kuma/static/js/libs/prism/prism-css-extras.js, kuma/static/js/libs/prism/prism-css.js, kuma/static/js/libs/prism/prism-javascript.js, kuma/static/js/libs/prism/prism-json.js, kuma/static/js/libs/prism/prism-line-highlight.js, kuma/static/js/libs/prism/prism-line-numbers.js, kuma/static/js/libs/prism/prism-markup.js, kuma/static/js/libs/prism/prism-rust.js, kuma/static/js/prism-mdn/components/prism-json.css, kuma/static/js/prism-mdn/components/prism-json.js, kuma/static/styles/libs/prism/prism-line-highlight.css, kuma/static/styles/libs/prism/prism-line-numbers.css, kuma/static/styles/libs/prism/prism.css
Resolves [bug&nbsp;1520004](https://bugzilla.mozilla.org/show_bug.cgi?id=1520004).
Extracted from #5157.
---
review?(@escattone, @jwhitlock)
=> Bug 1520004: Update Prism to version 1.15

kuma/static/styles/locales/ja.scss
The reason for introducing font-style: normal !important is now obsolete, as wrote in line 49.
Now I hope I'm doing this right, after #5219
=> Update ja.sccs to enable italic font style back

kuma/core/middleware.py, kuma/core/tests/test_locale_middleware.py
This PR changes locale-based redirects for the homepage from 302's to 301's for SEO reasons (see https://github.com/mdn/sprints/issues/932). All other endpoints are still redirected via 302 by `LocaleMiddleware`.
For reference, especially see:
- https://github.com/mdn/sprints/issues/932#issuecomment-466117128
- https://github.com/mdn/sprints/issues/932#issuecomment-466123774.
For the record, this was the description at the time this PR was originally submitted:
> This PR changes the redirects that `LocaleMiddleware` performs from 302's to 301's, per https://github.com/mdn/sprints/issues/932#issuecomment-462832669. My understanding is that this should be done for all paths without a locale, not just the homepage (so for example, https://developer.mozilla.org/docs/Web/Apps redirects with a …
=> bug 1441672: make locale redirects for the homepage permanent

kuma/static/js/libs/ckeditor/source/plugins/mdn-syntaxhighlighter/plugin.js, kuma/static/js/syntax-prism.js, kuma/static/styles/components/syntax/base.scss
Fixes [bug 1529886](https://bugzilla.mozilla.org/show_bug.cgi?id=1529886)
See&nbsp;also https://github.com/mozilla/kuma/pull/5189
=> Fix bug 1529886: Make `no‑line‑numbers` always hide the line numbers

Jenkinsfiles/utils.groovy, jinja2/base.html, jinja2/react_base.html, kuma/settings/common.py, kuma/wiki/jinja2/wiki/document.html, kuma/wiki/jinja2/wiki/react_document.html, kuma/wiki/models.py, kuma/wiki/tests/__init__.py, kuma/wiki/tests/test_models_document.py, kuma/wiki/tests/test_views_document.py, kuma/wiki/views/document.py, tests/headless/test_endpoints.py, tox.ini
This PR updates the way `hreflang` values are set for documents. For reference, see [bug 1523273](https://bugzilla.mozilla.org/show_bug.cgi?id=1523273). There's one special case that made this more challenging. The special case is that the `hreflang` value for any given document sometimes depends on the other translations that are available for that document. For example, if the document is available in both the `pt-BR` and `pt-PT` locales, the `hreflang` value for the `pt-BR` document would be `pt-BR`, like this:
```
<link rel="canonical" href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array">
<link rel="alternate" hreflang="en" href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array" title="Array">
<link …
```
=> bug 1523273: use proper hreflang values

kuma/health/views.py, kuma/wiki/constants.py, kuma/wiki/kumascript.py, kuma/wiki/tests/test_kumascript.py
This PR arose out of the work to solve the 504 timeout errors described in [bug 1529010](https://bugzilla.mozilla.org/show_bug.cgi?id=1529010). It tightens the exceptions that are caught when performing `kumascript.get` and `kumascript.post` calls to only `requests.exceptions.ConnectionError` and `requests.exceptions.ReadTimeout` errors -- basically connection and timeout errors -- which currently are not caught at all when making `kumascript.post` calls for previews, while for `kumascript.get` calls, every `Exception` was caught. It also adds `requests.exceptions.ReadTimeout` errors to the errors that are handled when making calls to the `health.status` endpoint. It also adds new tests for the `kumascript.get` and `kumascript.post` functions.
This PR should eliminate Sentry errors like …
=> bug 1529010: update kumascript module error handling

kuma/static/styles/components/wiki/edit/translate/translate-document.scss
[Bugzilla 1532147](https://bugzilla.mozilla.org/show_bug.cgi?id=1532147)
This PR removes `white-space: normal` from `<pre>` blocks of localization source document.
Currently all line breaks and multiple blanks are gone from source doc.
The issue itself had been gone for sometime by some reason I do not know. Now it's happening again.
The code has been there for a long time too; I wonder what was the reason for `white-space: normal`, and would removing it cause any side effects? (I don't think so...)
=> bug 1532147: Respect white spaces of localization source's code blocks

kuma/javascript/src/client-side-nav.js, kuma/javascript/src/index.jsx
This PR builds on previous /ducks/ PRs and adds simple pushState/popstate
client side navigation for MDN wiki pages. The intent isn't to get
everything working perfectly but to get an idea for what kind of
speedup we can expect from this technique
=> Bug 1525719: React spike: try simple client-side navigation

kuma/settings/common.py
When I rewrote the header in React I removed the animated search box
but left the nav-main-search.js component in the bundle. In development
this caused a benign JavaScript error, but in production the error prevents
the execution of other JS in the same bundle and the header does not appear
at all. This patch just modifies bundle definition to remove that
now-unnecessary JavaScript file.
=> Bug 1525719: fix a JavaScript error for the /ducks/ URLs

kuma/urls.py, kuma/users/api/v1/urls.py, kuma/users/api/v1/views.py, kuma/users/tests/conftest.py, kuma/users/tests/test_api.py, kuma/users/tests/test_views.py
This is the first cut of the `whoami` user API, which simply populates and returns a JSON object based on the presence/absence of the `sessionid` cookie.
=> bug 1525719: first cut of the whoami api

.env-dist.dev, .gitignore, docs/ckeditor.rst, jinja2/includes/config.html, kuma/settings/common.py, kuma/static/js/libs/ckeditor/source/build.sh, kuma/wiki/jinja2/wiki/includes/ckeditor_scripts.html
There was some code to support CKEditor in development mode, however this code was broken. This gets it working, and fixes some leftovers from SCL3, such as using ``MEDIA_URL``.
Add a environment variable ``CKEDITOR_DEV`` that enables development mode for CKEditor. The developer must also download the CKEditor source code, using ``build.sh --download``. This runs the CKEditor source, and loads the plugins at runtime. The developer must still build the production assets to commit the changes.
This also drops the Django pipeline bundles for CKEditor, and instead always loads the two scripts when editing.
**However**, I'm not sure this is the right approach. If instead we only support a full build of CKEditor, then we could drop most of this change, only keeping a couple of ``<script>`` tags …
=> bug 1497646: Add CKEditor development mode

kuma/wiki/tests/test_models_document.py, kuma/wiki/tests/test_views_document.py
``pytest`` tries to index the IDs parameter, and ``dict.keys()`` returns an iterator that doesn't support indexing in Python3. Wrap ``keys()`` in a ``tuple`` so it works in Python 2 and 3.
=> bug 1523273: Wrap test IDs in tuple for Py3 compat

kuma/static/js/components/payments/focus-visible.js
This solves the initial problem but, I ran into another problem. Once I confirmed that I want to cancel my subscription, I am sent to this URL https://developer.mozilla.org/en-US/payments/recurring/management but, here I get a permission denied error.
Going back to https://developer.mozilla.org/en-US/payments/recurring/management via Edit profile > Manage monthly subscription still shows the subscription.
That might simply be because it is still active, but maybe not? If it is because it is still active, we probably want to look at adding a note that indicates that it is in fact cancelled, and perhaps the date on which the subscription will end.
That is out of scope for this bug though, but thought I would mention it.
@jwhitlock @atopal Thoughts?
=> Bug 1534298, ensure contributeForm exist before adding event listener

.eslintignore, .flowconfig, kuma/javascript/src/current-user.jsx, kuma/javascript/src/current-user.test.js, kuma/javascript/src/flow-typed/npm/jest_v24.x.x.js, kuma/javascript/src/header/__snapshots__/dropdown.test.js.snap, kuma/javascript/src/header/__snapshots__/header.test.js.snap, kuma/javascript/src/header/__snapshots__/login.test.js.snap, kuma/javascript/src/header/dropdown.jsx, kuma/javascript/src/header/dropdown.test.js, kuma/javascript/src/header/header.test.js, kuma/javascript/src/header/login.jsx, kuma/javascript/src/header/login.test.js, kuma/javascript/src/header/logo.test.js, kuma/javascript/src/header/search.test.js, kuma/javascript/src/index.jsx, package-lock.json, package.json
This PR introduces a new CurrentUser.Provider React component
that uses fetch() to get user data from the whoami API and then
uses the React Context API to share that user data with any components
that need it. The patch also includes changes to the existing Login
component to display the avatar of logged in users.
The patch also modifies the Login component to display a dropdown menu for
logged in users to allow view profile, edit profile and sign out commands.
This also includes modifications to the Dropdown component to make
it work with non-textual menu labels and to attach the menu to the
right side of the label instead of the left side.
Finally, the patch also bumps the minor version of React and makes
some changes to ensure that we can use Flow on our Jest tests.
=> Bug 1525719: Query user data on the client side with new whoami API

kuma/settings/common.py
This will eliminate warning w001 from [django-mysql](http://django-mysql.readthedocs.org/en/latest/checks.html#django-mysql-w001-strict-mode), and the default in MySQL 5.7.
=> bug 1401272: Enable MySQL Strict Mode

kuma/static/js/components/local-anchor.js
On the edit page, there is no element with ID ``document-main``, so an error is raised when adding the click event listener. When the lookup fails, skip the work to add anchors for linking.
=> bug 1534804: Avoid prepending anchors on edit page

kuma/wiki/constants.py, kuma/wiki/jinja2/wiki/document.html, kuma/wiki/models.py, kuma/wiki/tests/test_models.py, kuma/wiki/views/legacy.py, tests/headless/test_endpoints.py
We've got various pages with slugs that begin with User:, Talk:,
User_talk:, and Template_talk: in our wiki that we really don't
want to support any more. We're not quite ready to delete them
but we at least don't want them to be turn up in search results.
This PR gives these pages a <meta name="robots" content="noindex,nofollow">
tag to prevent crawlers from indexing or crawling them.
Note that (per bug 1443179) we, in general, do not want to use
nofollow on pages. But in this case, since we're almost ready to
delete these pages, I don't think we want to rely on any links
they contain.
=> Bug 970278: Add noindex, nofollow tag to deprecated MindTouch pages

kuma/landing/views.py, kuma/wiki/views/document.py
Adjust rate limits added in response to a Dec 3, 2017 downtime event (PR #4591, [bug 1423738](https://bugzilla.mozilla.org/show_bug.cgi?id=1423738)).
Drop the rate limit on the homepage, which should get cached quickly by CloudFront.
Double the rate limit on documents, to begin probing what limit still allows the system to respond without downtime.
Approving. merging, and deploying should be coordinated with @limed, who will be most directly impacted by downtime alerts.
=> bug 1532736: Change rate limit on homepage, docs

kuma/scrape/tests/test_source_revision.py, kuma/settings/common.py, kuma/wiki/content.py, kuma/wiki/forms.py, kuma/wiki/management/commands/clean_document.py, kuma/wiki/management/commands/render_document.py, kuma/wiki/models.py, kuma/wiki/tasks.py, kuma/wiki/tests/__init__.py, kuma/wiki/tests/test_content.py, kuma/wiki/tests/test_forms.py, kuma/wiki/tests/test_models.py, kuma/wiki/tests/test_views.py, kuma/wiki/tests/test_views_document.py, kuma/wiki/views/document.py, kuma/wiki/views/translate.py
The intent of this PR is to bring more unity to the rendering of documents among the various endpoints of Kuma (see https://kuma.readthedocs.io/en/latest/rendering.html#future-changes). It takes the step of cleaning the content that's saved with a revision of any document, where the cleaning does the following:
- bleaches the content
- adds section ID's
- filters the sources of `iframe` elements
- alphabetically orders the attributes of elements
That change is small. Most of the other changes in this PR are related to updating the tests as well as adding a few new tests in light of the change to the revision content.
I've also added `TODO` comments within the code to note areas that could be simplified after/if this code is deployed and all existing documents have been updated with a …
=> bug 1519582: bleach revision content on save

Makefile, docker/images/kuma/Dockerfile, jinja2/react_base.html, kuma/core/templatetags/jinja_helpers.py, kuma/settings/common.py
This builds on PR #5279, creating a new translations domain ``react`` that includes all of the ``javascript`` strings, as well as the React strings that are very likely to appear in ``django``. 
This requires the changes in https://github.com/mozilla-l10n/mdn-l10n/commit/bfc4155109fcb1a264454d51d3f01ef3a7d29279, which include an updated ``.gitignore``. This was merged to master with the latest push to production.
``make localerefresh`` now calls the new target ``make locale-populate-react``, which collects existing translations into [compendium](https://www.gnu.org/software/gettext/manual/html_node/Compendium.html#Compendium) files, which are used to populate ``react.po`` from existing translations, without sending them to Pontoon.
``make build-static`` now calls the new target ``make …
=> bug 1525719: Extract strings from React, use existing translations

bower.json, kuma/settings/common.py, kuma/static/js/libs/prism/prism-clike.js, kuma/static/js/libs/prism/prism-core.js, kuma/static/js/libs/prism/prism-css-extras.js, kuma/static/js/libs/prism/prism-css.js, kuma/static/js/libs/prism/prism-javascript.js, kuma/static/js/libs/prism/prism-json.js, kuma/static/js/libs/prism/prism-jsonp.js, kuma/static/js/libs/prism/prism-line-numbers.js, kuma/static/js/libs/prism/prism-markup.js, kuma/static/js/libs/prism/prism-rust.js, kuma/static/styles/libs/prism/prism.css
Resolves [bug 1538693](https://bugzilla.mozilla.org/show_bug.cgi?id=1538693).
<details><summary>
<h2>Kuma affecting changes:</h2>
<table><td>
📝 <strong>Note:</strong> See <a href="https://github.com/PrismJS/prism/releases/tag/v1.16.0">PrismJS/prism@v1.16.0</a> for a full list of changes.
</td></table></summary>
* __C__
* Improve C language (https://github.com/PrismJS/prism/issues/1697) https://github.com/PrismJS/prism/commit/7eccea5c
* __C-like__
* Simplify function pattern of C-like language (https://github.com/PrismJS/prism/issues/1552) https://github.com/PrismJS/prism/commit/b520e1b6
* __C/C++/Java__
* Operator fixes (https://github.com/PrismJS/prism/issues/1528) https://github.com/PrismJS/prism/commit/7af8f8be
* __CSS__
* Fix tokenizing !important …
=> Fix bug 1538693: Update Prism to version 1.16

kuma/landing/views.py
This PR is a simple first step in reducing the number of indexed-but-blocked warnings in our Google search console (see https://github.com/mdn/sprints/issues/1220). The main problem is that we have many endpoints on MDN that are not intended to be indexed/searched, so we block them in our `robots.txt` file. Google search, however, doesn't yet know that they should not be indexed, and so when they're found as links in our pages (or other pages), tries to crawl and index them.
This PR allows the `$edit`, `$translate`, and `$json` endpoints to be crawled (by removing them from among the disallowed in `robots.txt`) so that Google sees that they should not be indexed (all of these endpoints already either return a robots meta tag of `<meta name="robots" content="noindex, nofollow">`, or in the …
=> bug 1518482: reduce indexed-but-blocked search warnings

kuma/payments/jinja2/payments/email/thank_you/email.html, kuma/payments/jinja2/payments/email/thank_you/plain.ltxt, kuma/payments/jinja2/payments/payments.html, kuma/payments/jinja2/payments/thank_you.html, kuma/payments/tasks.py
Tested locally and the links work as expected. Not sure how to test the emails though, but it looks like this should be good to go.
@jwhitlock r?
=> Bug 1533828, add credit card maintenance info

.travis.yml, requirements/dev.txt, requirements/travis.txt, tox.ini
* Move the ``tox`` install to ``travis.txt``, and load from ``dev.txt``
* Install ``codecov`` inside the TravisCI job, and use their [suggested integration](https://github.com/codecov/codecov-python#using-tox)
=> bug 957802: Restore coverage uploads

CODE_OF_CONDUCT.md
Update the text of the Code of Conduct to match the new Mozilla
template, with changes:
* Make [markdownlint](https://github.com/DavidAnson/markdownlint) happy (validated on https://dlaa.me/markdownlint/) (https://github.com/mozilla/repo-templates/issues/6)
* Remove redundant quotes around a link (https://github.com/mozilla/repo-templates/issues/5)
* Add links to Bugzilla Etiquette and Contributing docs
=> bug 1540177: Sync CoC with Mozilla template

Makefile, docker/images/kuma/Dockerfile, kuma/wiki/jinja2/wiki/react_document.html
This addresses the comments on PR #5302:
* Add a comment documenting the why and how of ``make locale-populate-react``, and how to remove it when it is no longer needed.
* Delete the temporary folder ``/locale/compendia`` in ``make locale-populate-react``, so it doesn't need to be deleted when building the kuma docker image.
It also switches ``wiki/react_document.html`` to use ``react_i18n`` instead of ``statici18n``, so that it will load the variant ``static/jsi18n/{locale}/react.js``.
=> bug 1525719: React l10n deux 1525719

Jenkinsfiles/integration-tests.groovy
Starting about 11 days ago, we've started seeing that the integration tests often fail, and it seems to be due to the headless tests often taking more than 6 minutes to complete (after which they're killed by the `timeout` command). This PR increases the timeout from 6 minutes to 7 minutes for the browser-based integration tests as well as the headless integration tests.
=> bug 1462440: increase timeout for functional tests

kuma/core/tests/test_utils.py, kuma/core/utils.py, kuma/payments/jinja2/payments/includes/payments-banner.html, kuma/users/templatetags/jinja_helpers.py
This is a potential fix for the ISE (e.g., see the error in Sentry for stage: `Reverse for 'github_login' not found. 'github_login' is not a valid view function or pattern name.`) for both the `beta` homepage as well as any `beta` doc page on stage (e.g., `https://beta.developer.allizom.org/en-US` and `https://beta.developer.allizom.org/en-US/docs/Web/CSS`).
I was unable to get the contribution banner to display for `beta.mdn.localhost:8000` for local testing (it did display for `mdn.localhost:8000`), so I'm unable to confirm if this will fix the issue, but I wanted to submit the PR for review as early as possible.
For testing, I'd recommend doing the following:
* update your `/etc/hosts` file to look something like this:
```
##
#
##
127.0.0.1	localhost demos mdn.localhost …
```
=> bug 1525719: fix provider_login_url for beta

kuma/static/js/wiki.js, kuma/static/styles/components/structure/document-head.scss, kuma/static/styles/components/wiki/crumbs.scss
Having read over the report in https://bugzilla.mozilla.org/show_bug.cgi?id=1523662 it seems the problem is that `JavaScript` is split into two words by the RegExp i.e. `Java<wbr />Script`
When Google then for some pages uses the text of the breadcrumbs as the text for the linking URL the raw HTML is displayed, including the `<wbr />` tag. As per @atopal's suggestion, and tweaking the RegExp, this no longer happens.
=> Bug 1523662, Google results container wbr in displayed URL

kuma/javascript/src/document-provider.jsx
This patch fixes a bug in client-side navigation on the beta site.
We weren't calling history.pushState() on the first page load, so
after navigating away, the back button would not correctly return
to that initial page.
As part of the fix, the localeAndSlug property of the state is
modified to include an initial slash character.
=> Bug 1525719: call history.pushState() on initial page

docker-compose.ssl.yml, kuma/settings/common.py
This fixes the permission-denied errors that MDN editors were getting when https://github.com/mozilla/kuma/pull/5325 (along with other updates) was pushed to production earlier today (it was rolled back). These errors are still happening on the stage instance.
This was a subtle error to track down. It turns out that because https://github.com/mozilla/kuma/pull/5325 introduces a non-default value for the `CSRF_COOKIE_DOMAIN`, Django's `CsrfViewMiddleware` will in our case start rejecting all unsafe (e.g., POST) requests because the domain check of the `Referer` header starts to fail. When the default value (`None`) of `CSRF_COOKIE_DOMAIN` is used, the domain check of the `Referer` header consists in comparing its domain against the value of the `HOST` header. However, when a non-default …
=> bug 1525719: add CSRF_TRUSTED_ORIGINS

Jenkinsfiles/integration-tests.groovy
This PR increases the timeout for the headless tests from 7 min to 8 min, since we've noticed that the headless tests seem to take at least 6.5 minutes to run and this gives them a little more breathing room.
=> bug 1462440: increase timeout for headless tests

kuma/javascript/src/__snapshots__/page.test.js.snap, kuma/javascript/src/page.jsx, kuma/wiki/jinja2/wiki/react_document.html
This patch modifies the page.jsx component to use CSS Grid layout
and display itself differently on narrow screens than it does on
larger screens. The main difference is that on narrow screens the
sidebar is moved to the bottom of the page, and the TOC bar is
hidden. There are also some font and margin size changes for
narrow screens as well.
The patch also includes a change to the react_document.html template
to make the MDN newsletter banner display with the correct margins.
=> Bug 1525719: make the React Page component responsive.

kuma/users/jinja2/socialaccount/signup.html, kuma/users/tests/test_templates.py, kuma/users/tests/test_views.py
The signup page is displayed after a new user logs in with GitHub for the first time. It includes an email selector that is highly custom, like it came from 2012:
* The email includes **Verified** or Unverified, to show GitHub's verification status. We trust emails that GitHub say are verified, and send a verification email otherwise
* The last selection is "Other", and includes an ``email`` ``<input>`` that is displayed on the same line
* If an existing user has a matching email, then we display with a strikeout, to indicate that while GitHub returned it, picking that email will cause the form to fail
These special features have been broken for a while. My suspicion is that it broke during the Django 1.11 update, since we're using undocumented APIs to build the custom form. I'm not sure …
=> bug 1475871: Fix the "Other" email field in signup, add tests

kuma/wiki/forms.py, kuma/wiki/tests/test_forms.py
This replaces PR #5342, which used NFC. After further research, NFKC appeared to be a better choice, and if we're making the change anyway let's use the better normalization for slugs.
This adds a NFKC normalization step to the ``RevisionForm`` and ``DocumentForm``, used when editing, translating, and moving pages, so that slugs are automatically normalized before saving.
Some unicode text is displayed the same, but is composed of a different sequence of unicode codepoints. For example, the Greek small case epsilon with a tonos (έ) can be represented by a single codepoint, or by an epsilon (ε) followed by a combining acute accent. This can mean that two unicode strings appear the same but are different because of the code points. Further, some codepoints appear to be formatted versions …
=> bug 1357416: Normalize slugs to NFKC

requirements/docs.txt
No-risk since the docs environment isn't executed on our servers. 
But I just wanted to get rid of this warning: https://github.com/mozilla/kuma/network/alert/requirements/docs.txt/Jinja2/open
=> bug 1542759 - upgrade Jinja2 used for docs

kuma/conftest.py, kuma/core/tests/__init__.py, kuma/wiki/forms.py, kuma/wiki/tasks.py, kuma/wiki/tests/test_templates.py, kuma/wiki/tests/test_views.py, kuma/wiki/views/edit.py
The way I tested manually was messy but insightful. 
The code that calls `send_first_edit_email` used to look like this:
```python
if is_first_edit:
send_first_edit_email.delay(new_rev.pk)
```
What I did was temporarily edit it to look like this:
```python
if 1:
print("Trigger to send email...")
send_first_edit_email.delay(new_rev.pk)
import time, time
time.sleep(10)
if random.random() > 0.5:
raise Exception("oh no!")
else:
print("i'm done sleeping")
```
Then, after editing a wiki page I watched the console (by the way, I changed my email to console printing rather than files inside the docker container). The was the out:
```
<timestamp1>: Trigger to send email...
<timestamp2>: **the whole email string output**
<timestamp3>: i'm done sleeping
```
...or...
```
<timestamp1>: Trigger to send …
```
=> fixes bug 1544084 - Sending first edit email potentially premature

assets/ckeditor4/source/plugins/mdn-syntaxhighlighter/plugin.js, bower.json, kuma/settings/common.py, kuma/static/js/libs/prism/prism-bash.js, kuma/static/js/libs/prism/prism-wasm.js, kuma/static/styles/wiki-wysiwyg.scss
Resolves [bug 1527533](https://bugzilla.mozilla.org/show_bug.cgi?id=1527533).
I’ve also added the Prism syntax definition for bash, because it’s exposed in the interface and used on the WebAssembly documentation pages, eg. https://developer.mozilla.org/docs/WebAssembly/Text_format_to_wasm
I’ve also exposed the Rust syntax in the interface because it’s also used on the WebAssembly documentation pages, eg. https://developer.mozilla.org/docs/WebAssembly/Rust_to_wasm
=> Fix bug 1527533: Add Prism syntax definition for WebAssembly

kuma/core/middleware.py, kuma/core/tests/test_locale_middleware.py, kuma/health/tests/test_views.py, kuma/urls.py, kuma/wiki/tests/test_events.py, kuma/wiki/utils.py
The way I tested it was with:
```
$ PYTHONWARNINGS=all pytest kuma --capture=no -vv | tee warnings.log
```
The warnings output is so large but it's easy to search through that `warnings.log` file. 
The only warnings about django.core.urlresolvers, now, comes from [`django-decorator-include`](https://bugzilla.mozilla.org/show_bug.cgi?id=1467529#c8) which'll be for another day.
=> bug 1467529 - django.urls import of django.core.urlresolvers

docker-compose.yml, docs/development.rst
I was tempted to add it to [`.env-dist.dev`](https://github.com/mozilla/kuma/blob/master/.env-dist.dev) but there are so many other juicy tips and tricks that is not already in there.
=> fixes bug 1546114 - control PYTHONWARNINGS in docker-compose

kuma/users/models.py, kuma/users/tests/test_models.py, kuma/users/tests/test_tasks.py, kuma/users/views.py
The account recovery code, used to allow legacy Persona users to link existing MDN profiles to GitHub, often sets a password for the user.
When generating a recovery URL, a random password was set on the user. This may be because Django's ``PasswordResetForm`` checks that the user has a usable password, and maybe there was other code that required that. I checked with Django 1.11 and current code, and it is OK to send a recovery email to a user with a blank or unusable password, so I'm removing that code and adding test code that the URL can be generated. Django made a similar choice, and [allows password reset when the existing password is unusable in Django 2.1](https://docs.djangoproject.com/en/2.1/topics/auth/passwords/#django.contrib.auth.hashers.is_password_usable).
When logging a …
=> bug 1340194: Stop setting random passwords for account recovery

kuma/wiki/views/edit.py
It appears that https://github.com/mozilla/kuma/pull/5348 has broken editing (see https://github.com/mdn/sprints/issues/1366). I'm not sure why, since I can't reproduce it locally or even on stage, so this PR reverts the change that wrapped the edit view in an atomic transaction, in order to restore functionality for the writers while this is investigated further.
=> bug 1544084: revert atomic edits

docker-compose.yml, kuma/javascript/src/__snapshots__/page.test.js.snap, kuma/javascript/src/document-provider.jsx, kuma/javascript/src/header/__snapshots__/header.test.js.snap, kuma/javascript/src/header/__snapshots__/login.test.js.snap, kuma/javascript/src/header/header.jsx, kuma/javascript/src/header/login.jsx, kuma/javascript/src/header/search.jsx, kuma/javascript/src/index.jsx, kuma/javascript/src/ssr.jsx, kuma/javascript/ssr-server.js, kuma/javascript/ssr-server.test.js, kuma/settings/common.py, kuma/wiki/jinja2/wiki/react_document.html, kuma/wiki/templatetags/ssr.py, kuma/wiki/tests/test_ssr.py, kuma/wiki/views/document.py, package-lock.json, package.json, webpack.config.js
This PR enables server-side rendering of the React UI for pages
on the beta domain with these changes:
- In kuma/wiki/jinja2/wiki/react_document.html we use a new
template tag {{render_react_app()}} to insert the rendered HTML
- We define that tag in kuma/wiki/templatetags/ssr.py
- The ssr.py file JSON serializes the document data and POSTs it
to a new ssr server which returns a string of rendered HTML.
If the HTTP connection fails or times out, ssr.py falls back
on client side rendering.
- This new ssr server is defined in kuma/javascript/ssr-server.js
It uses the Express package as its framework and calls
kuma/javascript/dist/ssr.js to actually do the server-side
rendering.
- The ssr.js file is a webpack bundle created from
kuma/javascript/src/ssr.jsx. There are changes to the webpack …
=> Bug 1525719: enable server-side rendering of the React UI

kuma/javascript/ssr-server.js
In order for New Relic to correctly log all transactions for
an Express server, we need to require('newrelic') before any
other requires. This PR makes that change.
=> Bug 1525719: fix New Relic logging for the SSR server

.travis.yml, docker-compose.yml, docs/development.rst, kuma/api/apps.py, kuma/api/conftest.py, kuma/api/management/commands/publish.py, kuma/api/management/commands/unpublish.py, kuma/api/signal_handlers.py, kuma/api/tasks.py, kuma/api/tests/test_signal_handlers.py, kuma/api/tests/test_tasks.py, kuma/api/v1/tests/test_views.py, kuma/api/v1/views.py, kuma/conftest.py, kuma/javascript/src/document-provider.jsx, kuma/settings/common.py, kuma/wiki/models.py, kuma/wiki/signals.py, kuma/wiki/tests/conftest.py, kuma/wiki/utils.py, requirements/constraints.txt, requirements/default.txt, requirements/docs.txt
This PR provides the foundation for connecting, via the document API, the Wiki side of MDN (creating, editing, deleting, restoring, reverting, and moving documents) with the new read-only, `beta` domain side of MDN. All operations on the Wiki side (listed above) will be automatically reflected to the document API via handlers connected to Django signals (i.e., `post_delete`, `render_done`, and `restore_done`). Those three signals, according to my testing, cover all of the operations listed above, triggering handlers that in turn either `publish` or `unpublish` to the S3 bucket that serves the document API. So for example, when a document is deleted, the `post_delete` handler will launch an `unpublish` task into Celery, which when run within a Celery worker, will delete the pre-rendered …
=> bug 1525719: publish/unpublish to/from the doc API

.travis.yml, docker-compose.yml, docs/elasticsearch.rst, docs/rendering.rst, kuma/search/management/commands/reindex.py, kuma/search/tests/test_filters.py, kuma/wiki/search.py, kuma/wiki/tests/test_kumascript.py, requirements/constraints.txt, requirements/default.txt
I can search and I can reindex. 
There might be some stuff in `kuma/wiki/search.py` that is obsolete not with the upgrade of `elasticsearch_dsl`. For example, in other projects where I use ES 6.x and `elasticsearch_dsl` I don't specify a mapping in the sub-class `Meta` but instead you specify settings and an index name. However, kuma is odd in that you created and define indexes using the Django Admin. I didn't want to rock the boat too much at this point. In particular, I'm not fully grasped up on why we bother doing indexes through the Django Admin. I've never done it like that before and it all feels, to me, right now, like overkill.
=> fixes 1544482 - elasticsearch 6.x

kuma/wiki/content.py, kuma/wiki/search.py, kuma/wiki/tasks.py
The sad truth is that when doing this change locally, it doesn't actually make a huge difference. 
Instead of incurring 1-2 SQL queries per document, it's now 0 SQL queries (warmed up by the prefetch_related). 
The real heavy cost lies in the lines `obj.get_summary_text()` and `obj.extract.macro_names()`.
=> bug 1548130 - index faster

kuma/search/management/commands/reindex.py, kuma/search/models.py
This PR reduces the default chunk size used when indexing for search, as well as makes it consistent whether indexing via the Django Admin console or via the `./manage.py reindex` management command. The default was 500 when using the Django Admin console, and 1000 when using the `./manage.py reindex` management command. Now, they are both 250.
The reason for this is that using a chunk size of 500 caused out-of-memory issues with the `celery-worker` pods on stage, even when the Kubernetes memory limit of the `celery-worker` pods was increased to match that of the pods on prod (`4Gi`).
A re-index on stage was successfully completed on stage with a chunk-size of 250.
=> bug 1544482: reduce indexing default chunk size

requirements/default.txt
tl;dr; this [won't get rid of the django2 upgrade warnings](https://bugzilla.mozilla.org/show_bug.cgi?id=1467529#c10) but it's never bad to do small upgrades incrementally.
=> bug 1467529 - django-decorator-include 1.4.1

docker-compose.yml, docs/development.rst
Here's how I test this:
```
▶ cat .env | rg _WORKERS
CELERY_WORKERS=2
GUNICORN_WORKERS=3
```
Then I see this output:
```
web_1            | [2019-04-23 20:25:18 +0000] [1] [INFO] Starting gunicorn 19.7.1
web_1            | [2019-04-23 20:25:18 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
web_1            | [2019-04-23 20:25:18 +0000] [1] [INFO] Using worker: meinheld.gmeinheld.MeinheldWorker
web_1            | [2019-04-23 20:25:18 +0000] [9] [INFO] Booting worker with pid: 9
web_1            | [2019-04-23 20:25:18 +0000] [10] [INFO] Booting worker with pid: 10
web_1            | [2019-04-23 20:25:18 +0000] [11] [INFO] Booting worker with pid: 11
```
Note, this means the same number of workers both for `web` and for `api`.
=> fixes bug 1546503 - custom celery and gunicorn workers in docker-compose

kuma/api/v1/tests/test_views.py, kuma/api/v1/views.py
For server-side rendered and cached versions of our pages, we need
to remove any user-specific data from the page. This includes waffle
flags, which can vary by user. This PR enables us to query the waffle
flags after a page has loaded, at the same time that we query the
user's name and profile picture.
=> Bug 1525719: add waffle flags to the /api/v1/whoami endpoint

kuma/api/v1/tests/test_views.py, kuma/api/v1/views.py, kuma/javascript/src/document-provider.jsx, kuma/javascript/src/document-provider.test.js, kuma/javascript/src/header/login.jsx, kuma/javascript/src/header/search.jsx, kuma/wiki/jinja2/wiki/react_document.html, kuma/wiki/views/document.py
This PR re-organizes the document API JSON structure according to https://github.com/mozilla/kuma/pull/5371#discussion_r280120646. @davidflanagan, I think I've updated all of the appropriate places in the React files. I noticed that `docker-compose exec web npm run test` doesn't pass, but it doesn't seem to be related to my changes since the same failures occur when I run it with `master`.
=> bug 1525719: reorganize doc API data

kuma/core/decorators.py, kuma/landing/urls.py, kuma/landing/urls_beta.py, kuma/landing/views.py, kuma/settings/common.py, kuma/urls.py, kuma/urls_beta.py, kuma/views.py, kuma/wiki/views/document.py
This PR addresses the gaps identified with the current implementation of the separation of domains (`beta` and `wiki` domains) listed in https://github.com/mdn/sprints/issues/1205#issuecomment-481456076. In summary, it adds missing endpoints to the `beta` domain and updates some Content Security Policies to account for the `wiki` domain. When adding the missing endpoints to the `beta` domain, some of the changes were made to allow the views that serve those endpoints to be wrapped in different `shared_cache_control` decorators depending on whether they served the `beta` domain or the `wiki` domain.
For testing, I used my usual `.env` file:
```
DEBUG=True
DOMAIN=mdn.localhost
ENABLE_RESTRICTIONS_BY_HOST=True
BETA_HOST=beta.mdn.localhost:8000
WIKI_HOST=wiki.mdn.localhost:8000 …
```
=> bug 1525719: wiki and beta domains (part 2)

kuma/javascript/src/app.jsx, kuma/javascript/src/document-provider.jsx, kuma/javascript/src/document-provider.test.js, kuma/javascript/src/header/header.jsx, kuma/javascript/src/header/login.jsx, kuma/javascript/src/header/search.jsx, kuma/javascript/src/index.jsx, kuma/javascript/src/locale-provider.jsx, kuma/javascript/src/page.jsx, kuma/javascript/src/ssr.jsx, kuma/wiki/jinja2/wiki/react_document.html, kuma/wiki/templatetags/ssr.py, kuma/wiki/tests/test_ssr.py, kuma/wiki/views/document.py
This patch creates a cleaner separation between document data and
request-related data in our code that does server-side rendering
and no longer mixes requestLocale into the document data object.
On the client-side locale is now handled with a LocaleProvider
component and corresponding context object.
=> Bug 1525719: handle request locale more cleanly in beta pages

tests/headless/test_endpoints.py
I broke a headless test (`test_beta_api_basic`) with my https://github.com/mozilla/kuma/pull/5387, so this PR fixes that. It also removes the test that checks that the `/api/v1/doc/*` endpoint is not available on the `wiki` domain. That endpoint is available on the `wiki` domain due to the fact that requests for the `beta` and `wiki` domains go through the same CDN, and the CDN origin for that particular endpoint is not Django but S3.
=> bug 1525719: fix headless tests

requirements/constraints.txt
requires.io is complaining about urllib3 but I'm pretty sure `requests` wouldn't let us use urllib3 1.25.x.
Annoyingly, there's no [CHANGELOG](https://github.com/urllib3/urllib3/blob/master/CHANGES.rst) for 1.24.3 and the [release tag](https://github.com/urllib3/urllib3/compare/1.24.3...master) mentions a lot of changes. 
First, let's see if Travis likes it and then we can wonder how to test this manually.
=> urllib3 1.24.3

package-lock.json, package.json
[Changelog here](https://github.com/boopathi/react-svg-loader/blob/master/CHANGELOG.md#301) which basically points to an upgrade of `babel-plugin-react-svg` to 3.0.0 and `react-svg-core"` to 3.0.0. (along with some irrelevant changes of requiring at least node 8).
=> react-svg-loader 3.0.1

kuma/core/context_processors.py, kuma/search/tests/test_views_admin.py, templates/admin/search/index/change_list.html
Any URL in `settings.ES_URLS`, *with credentials in the URL*, get scrubbed before being displayed like `https://username:password@....` (where the '...' is the same as before).
=> fixes bug 1548082 - hide ES_URLS creds in admin display

jinja2/includes/config.html, kuma/api/v1/views.py, kuma/javascript/src/app.jsx, kuma/javascript/src/document-provider.jsx, kuma/javascript/src/document-provider.test.js, kuma/javascript/src/ga-provider.jsx, kuma/javascript/src/ga-provider.test.js, kuma/javascript/src/locale-provider.test.js, kuma/javascript/src/user-provider.jsx, kuma/javascript/src/user-provider.test.js, kuma/wiki/jinja2/wiki/react_document.html
We currently hardcode a bunch of ga() analytics calls into the
HTML rendered by our Jinja templates, even when the data in question
depends on the current user or the current waffle flags. This means
that the HTML we generate can't be cached for re-use.
This PR modifies the react_document.html template so that our
React-based beta pages are cacheable and do not reference the
current user or current waffle flags. Instead, user and waffle
related ga() calls are now made on the client side in user-provider.jsx
when that data is obtained from the /whoami API.
This PR also adds ga('send', 'pageload') calls for client-side navigation.
=> Bug 1525719: move user and waffle-related ga() calls to client side

kuma/api/v1/tests/test_views.py, kuma/api/v1/views.py, kuma/javascript/src/document-provider.jsx, kuma/javascript/src/document-provider.test.js, kuma/wiki/jinja2/wiki/react_document.html, kuma/wiki/views/document.py
I was double-checking how we handle contributors in the React-based views, and realized that there was some redundancy in the `react_document` view, as well as a number of no-longer-used context variables. This PR simplifies that view based on current usage. There is more here that we'll simplify later as we move more of the Jinja template code to the React side.
=> bug 1525719: cleanup react_document view

kuma/javascript/src/document-provider.jsx, kuma/javascript/src/ga-provider.jsx, kuma/javascript/src/page.jsx, kuma/javascript/src/perf.js
This PR uses performance.mark() and performance.measure() to record
the fetch and the fetch+render times for each client-side navigation
and reports those times to Google Analytics with a 'timing' hitType
and a timingCategory of 'Client side navigation'.
=> Bug 1525719: measure and report client-side navigation timing.

tests/functional/test_feedback.py
Again, this is a minor tweak that came out of the testing for the new beta and wiki domains. In this case, the https://developer.mozilla.org/en-US/docs/MDN/Feedback document's title differed between stage and prod. The stage document was out of date, so I scraped the document from prod into stage to make them the same, and then standardized the test on the prod title.
This is not urgent. I just didn't want to forget about it.
=> bug 1525719: fix functional tests for prod

renovate.json
This PR adjusts the `renovate` configuration to exclude the Dockerfile for kuma (`docker/images/kuma/Dockerfile`). The base image in that file, `mdnwebdocs/kuma_base:latest` should never be pinned, since it is never acquired from the registry but rather always from a local build performed immediately previous (see our Jenkins and Travis flows).
=> bug 1553303: exclude kuma Dockerfile from renovate

tests/headless/__init__.py
These are some minor tweaks that came out of the testing for the new `beta` and `wiki` domains.
- the addition of `demos.mdn.mozit.cloud` to `INDEXED_ATTACHMENT_DOMAINS` (used by the headless tests) fixes a test failure when running the headless tests against https://developer.mozilla.org or https://wiki.developer.mozilla.org
- the removal of `cdn.mdn.mozilla.net` (the domain name that used to point to our former static-asset CDN, now long unused) is simply clean-up (it has no effect on the tests)
This is not urgent. I just didn't want to forget about it.
=> bug 1525719: fix headless test when run against prod

kuma/javascript/src/index.jsx, kuma/javascript/src/l10n.js, kuma/javascript/src/l10n.test.js, kuma/javascript/src/ssr.jsx, kuma/javascript/src/task-completion-survey.test.js, kuma/wiki/templatetags/ssr.py, kuma/wiki/tests/test_ssr.py
In a recent patch I introduced a new l10n.js module for localization
of our React code. It used the Function() constructor to build a
plural function from the plural expression string that Django supplied.
Unfortunately, this violates the CSP policy that we would like to start
using.
So this PR modifies the backend to embed a valid plural function into
the window._react_data object that it includes in each HTML page. And
it also modifies ssr.jsx to use the Function() constructor to create
the plural function (in Node, so it does not violate CSP) when needed.
Because this patch decouples the plural expression from the string
catalog, it also removes the generic localizationData object and
uses the stringCatalog object directly.
=> Bug 1525719: modify localization code to not violate CSP

kuma/javascript/src/index.jsx
The main.js file is not included into our React-based pages, so
the language menu in the footer does not autosubmit like it is
supposed to. This PR adds the required event handler to make it
work again. For now, at least, this code is just tacked on at
the end of index.jsx so it can be transpiled and bundled with
webpack.
=> Make the language menu work for React-based pages

docker-compose.yml
Sometimes, when running `docker-compose -f docker-compose.yml -f docker-compose.test.yml run test` within Jenkins, the host system's bind to port 9200 fails when spinning-up the `elasticsearch` service:
```
+ docker-compose -f docker-compose.yml -f docker-compose.test.yml run test
Creating kuma_master-dag2lj3obypfho7nheyqt4rqhoc6v2dswzq2pndatnegq7lwo6na_elasticsearch_1 ... 
Creating kuma_master-dag2lj3obypfho7nheyqt4rqhoc6v2dswzq2pndatnegq7lwo6na_mysql_1         ... 
Creating kuma_master-dag2lj3obypfho7nheyqt4rqhoc6v2dswzq2pndatnegq7lwo6na_redis_1         ... 
Creating kuma_master-dag2lj3obypfho7nheyqt4rqhoc6v2dswzq2pndatnegq7lwo6na_elasticsearch_1 ... error
ERROR: for kuma_master-dag2lj3obypfho7nheyqt4rqhoc6v2dswzq2pndatnegq7lwo6na_elasticsearch_1  
Cannot start service elasticsearch: …
```
=> bug 1553333: fix ES port-binding failure in Jenkins

kuma/settings/common.py
Interactive examples embedded in our pages post two different sets
of perf metrics to us, and for some reason we handle these messages
in two different places. One handler is in includes/perf.html and
this was already running in React-based pages. The other handler is
in js/utils/post-message-handler.js and it had been removed from
React-based pages. This PR puts it back.
In addition to this PR, we also need to land
https://github.com/mdn/bob/pull/244 in order for the interactive
examples data reporting mechanism to work with our beta site.
=> Include the post-message-handler.js module in React-based pages.

requirements/default.txt
This PR partially reverts https://github.com/mozilla/kuma/pull/5411, moving the Python Redis client package back to version 2. It turns out that the upgrade to Redis version 3 is incompatible with Celery version 3 (see https://github.com/mozilla/kuma/pull/5411#issuecomment-495771668), and breaks our Celery workers.
=> bug 1551701: revert back to Redis 2.x

kuma/javascript/src/__snapshots__/page.test.js.snap, kuma/javascript/src/article.jsx, kuma/javascript/src/page.jsx, kuma/static/js/components/local-anchor.js, kuma/static/js/highlight.js
Kuma runs two JavaScript modules on page load to add styles and
anchors to certain section heading within the main article content.
This PR adds those features to the React version of the site. It
moves the Article component from page.jsx into its own article.jsx
file, and then adds two useEffect() hooks to run code over the
article HTML content each time the article is re-rendered.
=> Use React effect hooks to fix up article section headings.

jinja2/includes/footer/moz-footer.html
The `.svg` file is still used on the user profile page. Can you think of any other references to it?
=> bug 1475383 - Remove Facebook link and icon from footer

kuma/users/providers/github/views.py, kuma/users/tests/__init__.py, kuma/users/tests/test_views.py
With this change, what happens now (if the communication with Github's API fails) is that you get this:
It's not great. For example, it doesn't say that it was "OUR" fault and not the users'. For example, a 500 error from GitHub should first of all [just be reattempted](https://bugzilla.mozilla.org/show_bug.cgi?id=1552277) so the human doesn't have to try again. 
Also, that template doesn't have a good call to action that informs her to try again. 
I suppose we can revisit that later. 
Either way, this is much better than triggering cryptic internal server errors. It gives the user a much better chance to not think "Oh crap! This isn't working. I better do something else."
=> bug 1411271 - be less optimistic about github profile completion

jinja2/react_base.html, kuma/core/templatetags/jinja_helpers.py, kuma/wiki/jinja2/wiki/react_document.html
For reasons I do not understand we've all-of-a-sudden started getting
500 errors from the server because the react.js strings files aren't
properly in the django staticfiles manifest. Rather than figure out
the source cause, this PR just removes the react.js include from the
templates that use it, because with the new React localization system
we don't actually use it anymore, and it should have been removed
a couple of weeks ago.
This is basically a partial revert of commit
bf5fad61ac58f22f5f3b7fcb712cd2f8f0e2dab9 which is what set up
that react.js file in the first place. React localization is now
handled during SSR with the react.json file. So this PR reverts
react.js back to the original javascript.js which provides localization
for any strings used by non-React JavaScript modules. …
=> Bug 1555004: stop including the react.js strings file into beta pages

kuma/javascript/src/__snapshots__/page.test.js.snap, kuma/javascript/src/header/__snapshots__/dropdown.test.js.snap, kuma/javascript/src/header/__snapshots__/header.test.js.snap, kuma/javascript/src/header/__snapshots__/language-menu.test.js.snap, kuma/javascript/src/header/__snapshots__/login.test.js.snap, kuma/javascript/src/header/dropdown.jsx, kuma/javascript/src/header/dropdown.test.js, kuma/javascript/src/header/header.jsx, kuma/javascript/src/header/login.jsx, kuma/javascript/src/header/login.test.js
This PR updates the design of our menus and converts them back to
the original hover behavior, with a smaller target area so that they
don't pop up as easily. And it restores the links that were previously
available when clicking directly on the menu labels.
The hover behavior works with simulated touch events in chrome dev tools
but not in firefox dev tools. I'd like to just deploy this as is and then
we can more easily test with a real touch device.
Because this new menu does not respond to click events, I've had to delete
some test cases that were testing clicks on the menu.
=> Convert the beta page menus back to hover behavior instead of click

kuma/wiki/tasks.py, kuma/wiki/tests/test_tasks.py
Regarding [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1551968#c1) I put in some lines like this:
```python
queries_before = len(connection.queries)
...
queries_after = len(connection.queries)
print("#QUERIES:", queries_after - queries_before)
```
inside the `build_locale_sitemap` function. Now, when I run `docker-compose exec web ./manage.py make_sitemaps` the print output looks something like this:
```
...
('#QUERIES:', 3)
('#QUERIES:', 3)
('#QUERIES:', 3)
('#QUERIES:', 2)
('#QUERIES:', 3)
('#QUERIES:', 3)
('#QUERIES:', 3)
('#QUERIES:', 2)
...
```
(it's one for every `settings.LANGUAGES`)
*Before*, with the `master` branch the same instrumentation looked like this:
```
('#QUERIES:', 26)
('#QUERIES:', 17)
('#QUERIES:', 23)
('#QUERIES:', 17)
('#QUERIES:', 36)
('#QUERIES:', …
```
=> bug 1551968 - Exclude noindex documents from sitemaps

docs/data.rst, kuma/scrape/management/commands/scrape_document.py
I use this tool surprisingly often and it's so annoying to have to start it with one URL at a time. 
Also, in a perfect world, I'd rename the management command to be called `scrape_documents` instead but I didn't want "rock the boat" too much.
=> make scrape_document accept multiple urls

kuma/core/tests/test_utils.py
**Before:**
See https://bugzilla.mozilla.org/show_bug.cgi?id=1552016#c0
**After:**
```
root@e7ae587582f5:/app# pytest kuma/core/tests/test_utils.py --durations=10
================================================================================================ test session starts ================================================================================================
platform linux2 -- Python 2.7.16, pytest-3.1.3, py-1.4.33, pluggy-0.4.0
Django settings: kuma.settings.testing (from ini file)
rootdir: /app, inifile: pytest.ini
plugins: django-3.1.2, cov-2.4.0
collected 13 items
kuma/core/tests/test_utils.py .............
============================================================================================= slowest 10 test durations …
```
=> bug 1552016 - SmartIntTestCase is slow

kuma/javascript/src/header/__snapshots__/login.test.js.snap, kuma/javascript/src/header/login.jsx
In a previous commit I changed the way the avatar is displayed,
and omitted a comma from the srcset attribute. This PR fixes that
bug.
=> Fix the broken avatar image display

kuma/javascript/src/__snapshots__/page.test.js.snap, kuma/javascript/src/page.jsx, kuma/javascript/src/page.test.js, kuma/javascript/src/user-provider.jsx
Clicking these buttons takes the user to the wiki site. Currently
all logged-in users will see the buttons, but this PR includes some
code that makes a distinction between contributors and logged in
users who are not contributors. Once we've made that distinction
on the backend and in the whoami API, the frontend will show the
buttons to contributors onlyi.
=> Add Edit and History buttons to the titlebar for logged-in users.

kuma/javascript/src/__snapshots__/page.test.js.snap, kuma/javascript/src/document-provider.jsx, kuma/javascript/src/header/__snapshots__/header.test.js.snap, kuma/javascript/src/header/header.jsx, kuma/javascript/src/page.jsx
This PR repurposes the blue bar at the top of each MDN page
and animates it while the page is loading. Once the page has
loaded, the blue bar is hidden. This PR removes the old hack
where we faded the document while loading.
=> Add a loading progress indicator at the top of the screen.

kuma/javascript/src/__snapshots__/page.test.js.snap, kuma/javascript/src/page.jsx
This PR moves the table of contents for the page into the sidebar.
These are the links to internal sections that used to be in the
"jump bar". This is based on preliminary designs that Nick has
shown me and he's given approval to land it in this state.
It is still to be decided whether we want to show the TOC on all
pages or only on the Learn/ pages.
=> Move the TOC (the old black "jump bar") into the sidebar

kuma/wiki/views/document.py
This PR simply increases the rate-limiting threshold for both the React and Non-React document views in order to avoid rate-limiting the Google bots. See https://github.com/mdn/sprints/issues/1629 for more context.
=> bug 1532736: increase rate limit on document views

kuma/javascript/src/document-provider.jsx
Our beta pages were calling History.pushState() when first loaded
(via an actual document load) in order to associate state with the
page so that we could go back to it. But this meant that that page
appeared twice in the history. This PR fixes that bug by switching
to History.replaceState().
This PR also fixes a related (unfiled) bug where we were not
updating the document title after client-side navigation so
the Back and Forward menus were showing the wrong document titles.
=> Bug 1556324: Don't add an extra history entry when we load a page.

kuma/javascript/src/__snapshots__/page.test.js.snap, kuma/javascript/src/page.jsx
This PR tweaks the CSS for the "On this Page" TOC box in the sidebar
and changes the JS code so the box is not displayed if there is
no TOC for the page. This fixes bugs 1556024 and 1556469.
=> Bug 1556024 and Bug 1556469: TOC fixes

kuma/static/styles/components/wiki/quick-links.scss
See [bug 1488884](https://bugzilla.mozilla.org/show_bug.cgi?id=1488884) and #4957 for details.
Previously links like `‑ms‑filter` wouldn’t have a bottom margin when it’s the current page, this PR fixes that.
Screenshots:
------------
<details>
<summary><strong>Before</strong></summary>
</details>
<details>
<summary><strong>After</strong></summary>
</details>
=> Bug 1488884: Fix sidebar links without bottom margin

kuma/wiki/management/commands/correct_current_revision_documents.py
@escattone This works in principle. 
The output I get is:
```
▶ docker-compose exec web ./manage.py correct_current_revision_documents --baseurl=http://mdn.localhost:8000 cursor Assignment
Found slugs: [u'Web/JavaScript/Reference/Operators/Assignment_Operators', u'Web/SVG/Attribute/cursor']
DOCUMENT: http://mdn.localhost:8000/en-US/docs/Web/JavaScript/Reference/Operators/Assignment_Operators
History: http://mdn.localhost:8000/en-US/docs/Web/JavaScript/Reference/Operators/Assignment_Operators%24history
Revision: 1543560 of NOT CURRENT: http://mdn.localhost:8000/en-US/docs/Web/JavaScript/Reference/Operators/Assignment_Operators%24revision/1543560 created 2019-04-20 01:51:53.811942
NOT editing at the moment!
Revision: 1470662 of CURRENT    : …
```
=> bug 1551999 - Fix pages with earlier revisions revisions being displayed

requirements/default.txt
This is the last `djangorestframework` release that'll support Python 2 (https://github.com/encode/django-rest-framework/blob/master/docs/community/release-notes.md#39x-series).
=> bug 1518653: upgrade djangorestframework

kuma/static/styles/components/wiki/indicators.scss
bug [1490801](https://bugzilla.mozilla.org/show_bug.cgi?id=1490801): read Only now at Center
=> Fix Bug 1490801: read Only now at Center

kuma/static/styles/components/wiki/indicators.scss, kuma/static/styles/includes/_mixins_indicators.scss
Fixes [bug 1557787](https://bugzilla.mozilla.org/show_bug.cgi?id=1557787)
See also #5477, which introduced the regression.
---
=> Bug 1557787: Fix inline indicator with icon padding regression

kuma/wiki/models.py, kuma/wiki/tests/test_views_code.py
This fixes the bug described in https://bugzilla.mozilla.org/show_bug.cgi?id=1552159. The conditions for the bug are the following:
- `ENABLE_RESTRICTIONS_BY_HOST` is True (this is always true for stage and production, but false by default for local development)
- a request is made for a document's code sample using one of the attachment domains -- for production, these are either `mdn.mozillademos.org` or `demos-origin.mdn.mozit.cloud` 
- the document does not yet have any rendered HTML (its `rendered_html` attribute is falsy)
Under these conditions, an attempt is made to render the document, but fails when `document.get_absolute_url()` is called within `kuma.wiki.kumascript.get`, since the `wiki.document` endpoint is not defined for the attachments domains (for those domains, the root …
=> bug 1552159: fix code sample when no rendered HTML

kuma/dashboards/utils.py
Oops. When I first did a search on the code I didn't see that we're already using xrange from `six`. Turns out, the existing use of `xrange` wasn't blocking Python 3. 
Anyway, I removed it now anyway. I've seen `xrange()` be vastly overused in Python 2. It only makes sense to "upgrade to the iterator version" if you're dealing with VAST lists. Which we don't. Less weird == better.
=> bug 1558255 - xrange is dead

tests/utils/urls.py
This was accidentally [added 3 years ago](https://github.com/mozilla/kuma/commit/6fc1528f39b408074d471d4644bad037e489ffcd#diff-6db1517f37de7d319af9950d4ad2b891R146).
Would cause a `SyntaxError` with Python 3.
=> remove old stray print

kuma/javascript/src/l10n.test.js
kuma/javascript/src/l10n.test.js tests our frontend gettext and
ngettext functions, and the way it was written the test strings
were actually being extracted into the react.pot file, which would
just confuse translators.
This PR changes the l10n.test.js file to invoke those functions
through alias names so that the strings can't be scraped and should
not appear in the react.pot file and react.po files.
=> Don't allow test strings in the l10n test to actually be localized

Makefile, docker/images/kuma/Dockerfile, scripts/ci-localerefresh
This PR removes the `locale-populate-react` Makefile target per @jwhitlock's [instructions](https://github.com/mozilla/kuma/blob/8515a75dbe19613b1480ba88faa725301a71aa24/Makefile#L105). I've already updated https://github.com/mozilla-l10n/mdn-l10n per steps 1 and 2 in @jwhitlock's instructions (see https://github.com/mozilla-l10n/mdn-l10n/commit/4eb53eb84bd21b2582a3c9a79a32187049b90eec).
Thanks to @jwhitlock for not only the original work on this, but the clear instructions on how to take the next step.
=> bug 1557666: remove locale-populate-react Makefile target

kuma/javascript/src/__snapshots__/page.test.js.snap, kuma/javascript/src/page.jsx, kuma/static/js/wiki.js, kuma/static/styles/components/structure/document-head.scss, kuma/static/styles/components/wiki/crumbs.scss, kuma/static/styles/components/wiki/quick-links.scss
Some of our documents have really long one-word titles, like:
CanvasRenderingContext2D.globalCompositeOperation
We want MDN to be able to break long strings like these reasonably.
In the past, we find the lower-to-upper case transitions and
inserted HTML <wbr> tags at those points to tell the browser that
they could break the word there. That was good user-facing UX, but
in bug 1523662 we discovered that for some reason Google was
sometimes showing the literal string "<wbr/>" in its search
results for our site.
So to fix that, we switched from <wbr> to zero width spaces
at the internal word transitions. This resulted in the same word
wrapping behavior, and google has been happy with it, I think.
But it caused this bug: that copy and paste is broken, especially
when trying to paste the …
=> Bug 1557013: don't use zero width spaces for hyphenation

kuma/wiki/templatetags/ssr.py, kuma/wiki/tests/test_ssr.py
Typically when a React page is server-side rendered, the data associated
with that page ends up in the HTML page twice: once as HTML and once
as a JSON object. For MDN document pages I implemented an optimization
where I avoided passing the long strings of HTML content in the JSON
blob.
But then I modified the Sidebar component so that it would render the
TOC only if document.tocHTML was defined and by making the render
dependent on this variable that I had not sent in the JSON blob I
caused Bug 1558308 where hydration failed and the sidebar ended up
missing (it worked for client-side navigation, but the SSR'ed version
of the page would not work correctly.)
I'm reluctant to remove this optimization, but it seems likely to cause
confusing bugs later on, so I'm commenting it out for now. …
=> Bug 1558308: Always pass full HTML strings in document data

kuma/javascript/src/__snapshots__/page.test.js.snap, kuma/javascript/src/header/__snapshots__/header.test.js.snap, kuma/javascript/src/header/__snapshots__/login.test.js.snap, kuma/javascript/src/header/login.jsx, kuma/urls_beta.py, kuma/users/urls_beta.py
Our login and logout endpoints require the ?next= redirect URL to
have the same origin as the endpoint. We were trying to use endpoints
on the wiki domain so that we didn't have to support them on the beta
domain. But that meant that when a user logged in or out, they were
taken away from the beta domain.
This PR fixes that by adding the auth endpoints (and also profile
viewing and editing) endpoints to the beta domain. It makes
corresponding frontend changes in the login.jsx component and
also tweaks the Jinja template for profile view so that we don't
show document editing activity on the beta domain--doing that
requires URLs that are not supported on the beta domain and were
causing 500 server errors due to reverse lookup failures.
=> Bug 1525719: make signin and signout work on the beta domain

kuma/javascript/src/perf.js, kuma/javascript/src/router.test.js
This PR adds LUX.init() and LUX.send() calls to the client-side
navigation analytics code in perf.js, following Speedcurve's
directions.  See:
https://support.speedcurve.com/articles/1708068-using-lux-in-a-single-page-app-spa
=> Bug 1525719: send Speedcurve LUX analytics on client-side navigation

kuma/javascript/src/search-results-page.jsx, kuma/javascript/src/search-results-page.test.js
On the beta site, if an error occured when fetching search results
we used to let it propagate. And then the router would handle it by
punting and doing a regular page reload. But search result pages aren't
rendered on the server, so a full page reload will end up making
the same API fetch call that just failed, and we're likely to end
up with an infinite reload loop.
This PR solves that problem: the SearchRoute fetch() method now
returns either a set of search results or an error, and the
SearchResultsPage component can display the results or the error.
Hopefully users will never see the error display. But if something
goes wrong (like elastic search is down) we'll get an error message
that should be helpful to diagnose the problem.
=> Bug 1525719: improve error handling for search result pages

kuma/javascript/src/perf.js, kuma/javascript/src/router.jsx, kuma/javascript/src/user-provider.jsx
There is code in router.jsx that sends GA events for client-side
navigation. But it was also running on the initial page load as well.
This PR fixes that.
Also, this PR fixes a related bug in perf.js that I discovered while
working on the initial bug. When I added the LUX.init() call in
perf.js, I broke the custom performance measures I was collecting
because apparently LUX.init() clears all existing marks. I've fixed
that bug by calling LUX.init() first before I mark the start time for
the client-side navigation.
=> Bug 1560573: Don't send two pageview events on the first page load

kuma/javascript/src/header/header.jsx
This is the menu in `fr` after this change:
=> Bug 1560191, header menus are not localized on beta site

kuma/javascript/src/search-results-page.jsx, kuma/javascript/src/search-results-page.test.js
The beta search results page does not currently display a
"no matches found" message for searches with no results. This PR
adds that message.
=> Bug 1560958: display a message when there are no search results

kuma/api/v1/views.py, kuma/javascript/src/router.jsx, kuma/javascript/src/search-results-page.jsx, kuma/javascript/src/search-results-page.test.js
Our current search results include highlighted excerpts of
matching documents to provide more context about where the
search terms appear. This PR adds a similar feature to the
beta search results page.
=> Bug 1525719: add highlighted excerpts to search results

kuma/api/management/commands/publish.py, kuma/api/signal_handlers.py, kuma/api/tasks.py, kuma/api/tests/test_signal_handlers.py, kuma/api/tests/test_tasks.py, kuma/api/v1/tests/test_views.py, kuma/api/v1/views.py, kuma/search/tests/test_filters.py, kuma/settings/common.py, kuma/settings/testing.py, kuma/wiki/management/commands/render_document.py, kuma/wiki/models.py, kuma/wiki/signals.py, kuma/wiki/tasks.py, kuma/wiki/tests/test_models.py, kuma/wiki/tests/test_signal_handlers.py
This PR replaces https://github.com/mozilla/kuma/pull/5384 by building on top of it, adding the ability to skip the CDN cache invalidation when doing bulk document renders. Document renders don't have direct access to the `publish` command, only indirect access via the `render_done` signal.  So at its root, this PR changes the `render_done` signal such that it now provides/carries the additional information of whether or not to invalidate the CDN cache. It was important  to find a way to do that because we often run bulk re-renders (for example, all documents that use the `compat` macro).
I think this is complete (including tests), but I do still need to test this with the actual AWS keys, and I need to add the CloudFront distribution ID's for stage/production to the respective Kubernetes …
=> Invalidate cloudfront on publish/render

kuma/javascript/src/document.jsx
Some pages don't have any related topics, and we shouldn't display
the "Related Topics" heading in the sidebar for those pages.
Note that this patch just removes the unnecessary heading from the
sidebar, but does not remove the sidebar itself. There may still be
a few pages htat have not related topics and also have no
sections to link to in an "On this page" section. Those pages have
no need of a sidebar, but they are still going to get one.
=> Bug 1561081: Don't display "Related Topics" heading if there are none

kuma/javascript/src/document.jsx
The CSS for BCD table layout is complicated and depends on the
presence of an element with class wiki-left-present to indicate that
there is a sidbar. That element had been removed on the beta pages,
breaking BCD table layout for widths 1023-1199. This PR adds
the class back to the element that contains the sidebar and
article, fixing BCD table layout.
=> Bug 1561034: fix BCD table layout for small-desktop widths

jinja2/includes/config.html, jinja2/react_base.html, kuma/javascript/src/article.jsx, kuma/javascript/src/bcd.js, kuma/javascript/src/interactive-examples.js, kuma/javascript/src/live-examples.js, kuma/javascript/src/prism.js, kuma/settings/common.py, kuma/static/js/analytics.js, kuma/static/js/newsletter.js, kuma/static/styles/components/content.scss, kuma/wiki/jinja2/wiki/react_document.html
This large PR creates React-compatible versions of a number of
jQuery-based modules, and removes jQuery entirely from our beta pages.
This patch resolves bugs 1559480, 1560161, 1560135 and 1561037.
1) Bug 1559480: make BCD tables appear and behave correctly on beta site.
BCD table formatting and behavior depends on code in
wiki-compat-trigger.js running on page load, so the tables don't work
correctly with client-side navigation. This PR fixes that.
It makes the BCD stylesheet part of the main bundle that is loaded
into every React-based page, so the styles are always there and don't
have to be loaded when we find a page with a BCD table.
It also defines a new bcd.js file that defines an activateBCDTables()
function. We call this function with useEffect() from the Article
component so …
=> Port various JS modules to work with React and to remove jQuery.

kuma/javascript/src/banners.jsx, kuma/javascript/src/banners.test.js, kuma/javascript/src/landing-page.jsx, kuma/landing/jinja2/landing/react_homepage.html, kuma/settings/common.py
Our current system for call-to-action banners relies on the use of
waffle flags in our Jinja templates, which means that the rendered
html cannot be cached on a CDN. This PR introduces a <Banners>
component that can be used in place of the existing banners
javascript bundle and that gets waffle data from the user API
instead of relying on it in the Jinja template. The PR also set
up the react_homepage.html template and the landing_page.jsx
component to display the developer needs survey banner when the
waffle flag is turned on.
=> Bug 1525719: implement a React component for call-to-action banners

kuma/settings/common.py
The LUX script is blocked by CSP on developer.allizom.org. This PR
allows that domain in our CSP configuration.
=> Allow cdn.speedcurve.com in our CSP so the LUX script is not blocked

kuma/javascript/src/banners.jsx, kuma/javascript/src/document.jsx, kuma/javascript/src/landing-page.jsx
Previously the banner was only on the home page, this adds it to
document pages (but not search results pages) for the beta site.
=> Make the DNA banner appear on React-based document pages

kuma/javascript/src/header/__snapshots__/header.test.js.snap, kuma/javascript/src/header/header.jsx
The header component defines menus in a static data structure. Originally
I had gettext() calls directly in that data structure. They were visible
to Puente, but the gettext() ran before string catalogs were available
so translations didn't happen even though they were available in the
catalog.
Then we switched to calling gettext() when rendering. That worked for
translations, but meant that the actual string literals were no longer
visible to Puente and weren't being picked up. So when the react.pot
file went live, we lost those string.
So then we moved the gettext() calls back to the static data structure
and are back to the original problem of calling gettext() before strings
are available.
This PR finally gets it right (I hope). The data structure that defines
the menus is created …
=> Bug 1561975: fix menu localization for beta pages.

kuma/javascript/src/document.jsx, kuma/javascript/src/router.jsx
In a recent PR I landed code that displayed document tags on
each page. In order to do this, I had to extend the doc API to
include a tags property in the JSON blob. It worked fine locally
but I forgot about our S3 cache of JSON blobs used in staging
and in production. The pre-rendered JSON blobs do not have the
new tags property, but the code for displaying the tags assumes
that it will always see tags or at least an empty array.
This was causing an exception during rendering and the router
fell back on doing a hard reload. This PR fixes the problem
by adding backwards compatibility code in the DocumentRoute class:
after fetching a JSON blob, we check for the tags property and
add one (an empty array) if the property does not exist.
With that fix in place, the frontend code can continue …
=> Fix a JS exception that was breaking client-side navigation.

kuma/javascript/src/router.jsx
The router.jsx component for our beta pages scrolls to the top
every time it routes to a new page. But it should only do this for
new pages and not do it when the user navigates with the Back
or Forward buttons in the browser. This PR fixes this.
=> Bug 1562271: don't scroll to top on popstate events

kuma/javascript/src/index.jsx
When our React-based pages are loaded in translate.google.com
various JS errors caused by Google make React unmount the components
that display the (now-translated) content. This patch works around
the problem by simply never calling ReactDOM.hydrate() when we're
loaded into Google Translate
=> Bug 1562293: don't crash in Google Translate

kuma/javascript/src/router.jsx
Currently in our single-page app, we make a point of showing the
loading bar animation on every page transition, and even prolong
the length of the animation so that the user has postitive feedback
that something has happened.
We've gotten feedback that the loading bar makes client-side navigation
feel slower than it actually is, however. So this PR changes the
progress bar animation in two ways.
- first, it no longer artificially prolongs the animation
- second, it changes the animation so that nothing happens
for the first 100ms.
The upshot is that when the page transition takes less than 100ms
the user will not see the progress bar at all. For navigations that
are under 200ms the user will just see a flash of blue, and for
navigations that take longer than that, they'll probably see …
=> Don't show the loading bar for fast client-side navigation.

kuma/javascript/src/article.jsx, kuma/javascript/src/document.jsx
Fixes scrollbars at the bottom of doc pages.
NOTE: This only happens on Windows - @callahad r?
=> Bug 1562853, scrollbars at bottom of article, sidebar on windows

kuma/javascript/src/document.jsx, kuma/javascript/src/router.jsx, kuma/static/styles/components/structure/document-head.scss, kuma/static/styles/components/structure/page-header/main-header.scss
This improves the accessibility of our client-side navigation by setting a `live-region` and also moving focus to the logo. In a follow on PR I am going to reintroduce the skip links for documentation pages. When I do that, I will also move focus to the container for these links as opposed to the logo. For now, this is a noticeable improvement.
https://send.firefox.com/download/56f9e4901abcc514/#rnmfD8S5RpLXmbiPtC7Nwg
https://send.firefox.com/download/2f2b7d36ef9b99cc/#c0M47TqnXzSoQJDt4f3P1Q
@callahad-mozilla-owner r?
=> Bug 1563511, ensure new page content is read on navigation complete

kuma/api/v1/tests/test_views.py, kuma/api/v1/views.py, kuma/javascript/src/document.jsx, kuma/javascript/src/document.test.js, kuma/javascript/src/header/__snapshots__/language-menu.test.js.snap, kuma/javascript/src/header/language-menu.jsx
This PR adds the `Add a translation` link to the language menu on document pages in the `beta` domain. As part of that effort, it adds a new `translateURL` attribute to the JSON structure provided by the document API. That attribute may be either `null` (e.g., when the document is not localizable, which is the case for all non-English documents as well as any documents explicitly marked as such) or an absolute URL to the `wiki` domain. That attribute will be missing from the currently published JSON objects, but since an `undefined` attribute is falsy, that case is handled by the React-based code the same as if the document page was not localizable. In other words, no `Add a translation` link will be seen on stage/prod until all of the stage/prod documents are re-published. So, if and …
=> bug 1562858: 'add a translation' link for beta

kuma/static/js/utils/perf-post-message-handler.js
When I was hacking on https://github.com/mozilla/kuma/pull/5544/files as I was poking around and reloading the page with different console debugging. I got the error every time. Then I applied this fix and it went away. Yay!
=> bug 1542817 - `ReferenceError: ga is not defined` on some pages

kuma/javascript/src/titlebar.jsx, kuma/javascript/src/titlebar.test.js, kuma/static/styles/base/icons.scss
This PR removes the "History" button (clock icon) from the document pages on the beta domain.
Before:
After:
Note: This PR made me think that perhaps, within https://github.com/mozilla/kuma/pull/5548, I should have only added the `Add a translation` link within the language menu dropdown if the user was logged in and a contributor (the same logic used here for deciding whether or not to display the `Edit` button). I suppose so. What do you guys and @atopal and @nickbrandt think?
=> bug 1525719: remove history button on beta doc pages

kuma/settings/common.py
Currently, we're setting the Django `USE_X_FORWARDED_HOST` setting to `True`. This is a relic of the past. This PR changes that Django setting to simply use the default value, which is `False`.
=> bug 1564277: use default USE_X_FORWARDED_HOST setting (False)

kuma/javascript/src/article.jsx, kuma/javascript/src/last-modified-by.jsx
On a `en-US` document: 
On a `sv-SE` document:
=> bug 1565618 - 'last updated by' date localized

kuma/settings/common.py
I suspect there'll be more PRs like that until we can close [the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1566456).
I noticed that `diff.scss` gets included in the `react-mdn` bundle but it's very hard to check that because, you know, globals.
=> bug 1566456 - don't need diff.scss in beta site

kuma/settings/local.py
I made this PR entirely in the GitHub UI whilst waiting for slow docker-compose things in my current messy branch. 
By the way, in that messy branch I needed to make this change and it solved the problem. Now I get tracebacks on stdout.
=> bug 1566971 - set DEBUG_PROPAGATE_EXCEPTIONS free

kuma/javascript/src/search-results-page.jsx
This PR changes our search results page so that it ignores
result excerpts that are too long and so that it forces line
breaks even when excerpts don't have spaces. (There seems to
have been some kind of ElasticSearch change that made it start
sending us long excerpts without spaces.)
I'm sure there is still work to be done on the search results
page, but this fixes the particularly ugly problem.
=> Bug 1564405: don't display long, unwrapped excerpts

kuma/settings/common.py, package-lock.json
Basically, base64 data URIs should be avoided like the plague. They are [hurting us for multiple reasons](https://bugzilla.mozilla.org/show_bug.cgi?id=1566544#c0).
I generated the `static/build/styles/react-mdn.7c70c44b8efa.css` with `collectstatic` (and `DEBUG=False`), then compared that output with [the current prod equivalent](https://developer.mozilla.org/static/build/styles/react-mdn.5b7ff2245ae8.css) and this is the diff you get: https://gist.github.com/peterbe/f65c688aafa9eeb1a934fd65b19c313f
=> bug 1566426 - no base64 in css

kuma/wiki/content.py, kuma/wiki/tests/test_content.py
This PR addresses a loophole in the code that's used to inject section `id`'s as part of the `clean_content` function,  which is run after every render as well as when revisions are saved. Currently, any HTML elements which qualify as "section" tags (see https://github.com/mozilla/kuma/blob/c30762afdebfdf9bfe50077f526188073ffdefd5/kuma/wiki/content.py#L44) are automatically assigned an `id`. For example, this:
```html
<h1>the header text</h1>
```
will become this:
```html
<h1 id="the_header_text">the header text</h1>
```
This automatic selection of an `id` can be manually overridden by providing a `name` attribute, whose value will then be used in place of what would have been automatically assigned. For example, this:
```html
<h1 name="use_me_as_the_id">the header text</h1>
```
will …
=> bug 1566302: sanitize name attr when override for id

kuma/wiki/jobs.py
This PR isn't particularly important. I just didn't want to throw it away. 
What I noticed was the [this `if` statement](https://github.com/mozilla/kuma/blob/bd7581053f3840f5fa22b28e6372c729b0c3468f/kuma/wiki/jobs.py#L42) which would always be true because at that point `recent_creator_ids` isn't a list but a QuerySet object.
It's only later that it gets turned in a python list type. 
Turns out, I can't find any documents in *my* mysql that has no creators and that if statement was never covered with tests anyway. 
Then when I poked I noticed the unnecessary extra SQL query which can be heavy. 
Now in hindsight I realize how RARE this whole block of code is because it's Redis cached for 12 hours. A well. If you just find this annoying and distracting, please close the PR.
=> inefficient queries in DocumentContributorsJob

kuma/settings/common.py
Look how I bravely didn't even wrap this in a `decouple.config()` because I don't think anyone or anything has any business enabling that back on.
=> bug 1567587 - django-cacheback reads the cache for every single set

kuma/wiki/jobs.py
I don't think this will conflict with https://github.com/mozilla/kuma/pull/5546 
Thing is, the `DocumentContributorsJob`cacheback job has a TTL of 12h and the `UserGravatarURLJob` job has a TTL of 24h. But basically, every 12h for every single document, we're calling `UserGravatarURLJob.get()` mostly as a waste of time.
=> bug 1567572 - gravatar_34 is inefficient and never used

kuma/javascript/src/header/__snapshots__/header.test.js.snap, kuma/javascript/src/header/__snapshots__/search.test.js.snap, kuma/javascript/src/header/header.jsx, kuma/javascript/src/header/search.jsx
This fixes the problem of the search input in the header expanding beyond the visible viewport in Safari on iOS 10. Tested on Firefox, Chrome using responsive mode, as well as on iPhone 7 using Safari running iOS 10.
=> Bug 1566429, prevent search input from expanding beyond viewport on iOS 10

kuma/javascript/src/article.jsx, kuma/settings/common.py, kuma/static/styles/components/structure.scss, kuma/static/styles/components/structure/archive.scss, kuma/wiki/jinja2/wiki/document.html
I'm clearly out of my depth here on the scss and stuff...
Basically, the wiki site relies on the fact that the `<head>` is only rendered once per page. That's why it conditionally inserts (or omits) a `<link rel=stylesheet href=archive.css>` into the DOM. That archive.css then overrides `.wiki-main-content`. 
This approach is not going to work with the React site because this kinda of business logic needs to depend not only on the initial server HTML rendering (aka. SSR) but also when you jump between pages. E.g. you might be on a non-archive page and click into an archive page and then click out to another non-archive page. 
So I changed approach. The `<article id="wikiArticle">` tag now becomes `<article id="wikiArticle" class="archive-content">` dynamically. *And*, now the CSS selector …
=> bug 1563210 - visually distinguish between current and obsolete

kuma/api/v1/views.py, kuma/javascript/src/search-results-page.jsx, kuma/javascript/src/search-results-page.test.js
I first edited `search-results-page.jsx` and removed all mention of tags etc. Then I ran the jest tests and everything passed. Kinda sad. Clearly something there is overly mocking or we were just not testing tags in any way.
=> bug 1567482 - no tags in read-only site search results

kuma/javascript/src/document.jsx, kuma/javascript/src/toc.jsx, kuma/static/styles/components/wiki/toc.scss, kuma/static/styles/includes/_vars.scss
This ensures that the TOC component is in a more appropriate place in the DOM source order. As a result some `grid` styles needed updating as well. @callahad r?
=> Bug 1563481, toc component should be higher in source order

kuma/api/v1/views.py
It's a bit cheeky to mutate the versioned API but given the circumstances and situation, I think it's justifiable. 
However, soon this Document API is going to be used fully on developer.m.o so then it's going to be much more disappointing, to integrators, if we change the API. 
With that in mind, *now* is the right time to REMOVE things from the API. I'm not sure how but we should evaluate all the things in that [JSON](https://gist.github.com/peterbe/578e5a291972700f3a9d047693d743af).
=> bug 1568239 - Don't include tags in Document JSON API

kuma/static/js/components/banners/banners.js
Got a little sick and tired of trying to understand how it could even happen that the DOM element is *not* there. Either way, this'll fix the errors in the bug.
=> bug 1565643 - activeBanner isn't always there

kuma/javascript/src/router.jsx
See the comment about how to reproduce: https://bugzilla.mozilla.org/show_bug.cgi?id=1566944#c4
Removing this code solves the problem. And it makes sense. Forcing focus on that title DOM element will force the browser to scroll into view. 
That begs the question: What did that code really do? I.e. what was it for? Why was it necessary?
It was added in this commit: https://github.com/mozilla/kuma/commit/345687b46fb98d782c9256d78eb967acb21fbd4c#diff-17a8d9db184a0bff5b4b3e2054788150R518
I think it's related to a11y but I don't really get it.
=> bug 1566944 - going back scrolls to the top

kuma/javascript/src/perf.js
This is what an error can look like now:
I forced that to happen by putting in a `throw new Error('Peter testing')` inside the `try` block. 
The other changes are just rearranging it a little so that the error handling has one try block per block of relevant code. 
For the record, I didn't change *any code* other than the `catch` blocks.
=> bug 1568265 - better error handling in perf.js

kuma/static/styles/components/structure/page-header/main-header.scss
Ensures the logo shows a focus ring when focused.
@callahad r?
=> Bug 1566726, Web Docs logo lacks focus style

kuma/static/styles/base/fonts/opensans.scss, kuma/static/styles/locales/_zilla.scss, kuma/static/styles/locales/ar.scss, kuma/static/styles/locales/az.scss, kuma/static/styles/locales/fa.scss, kuma/static/styles/locales/ff.scss, kuma/static/styles/locales/ro.scss
@peterbe Finally got around to this one. While `swap` does seem like the property we want, and while it does solve the problem, it introduces a new one. As you can see from the Gif below when on a slow connection there is a period of time when the headings are invisible.
They are then rendered using a fallback, and finally the "correct" font swaps in.
So we are swapping ;p one tradeoff for another in essence. I guess the period where the headings are not shown at all is the short block period, followed by fallback and then finally swap.
Thoughts? r?
=> Bug 1534911, page headings often loads with different font

kuma/javascript/src/search-results-page.jsx
=> bug 1569168 - make urls in search results clickable

kuma/static/styles/components/wiki/elements.scss
@callahad This adds a specific style for the active state of in-content
r?
=> Bug 1568305, add specific styling for active state on in content links

kuma/settings/common.py, kuma/static/styles/base/icons.scss, kuma/static/styles/components/tags.scss, kuma/static/styles/main.scss, kuma/static/styles/wiki-shared.scss
This is the first small step in cleaning up our CSS and separating the CSS we serve to the read-only vs. the wiki versions of MDN Web Docs.
@peterbe r?
=> Bug 1567409, separate metadata tags styling to wiki

jinja2/base.html, kuma/settings/common.py, kuma/static/styles/components/banners/wiki-notice.scss, kuma/wiki/jinja2/wiki/document.html, kuma/wiki/jinja2/wiki/includes/wiki-notice.html
Adds banner to `wiki.` with a link through to `d.m.o`
@peterbe r?
=> Bug 1567218, add banner to wiki to distinguish it from devmo

jinja2/includes/preload.html
We use the Bold for all headings so it's good to preload it.
=> preload ZillaSlab-RBold.subset.woff2

kuma/settings/common.py
Easy change. Less easy in terms of security discussion. 
The way I see it, 2 weeks is far too short and it's annoying to be thrown out. 
Our site doesn't really have anything critical. At best you can edit wiki documents but the money $tuff that we get involved in is shifted onto Stripe anyway. There's no sharing of critical PII. 
In other words, I feel like we can allow for a much longer lasting session cookie. Rogueness can lead to destroying stuff but it can't really lead to revealing sensitive stuff. 
My ideal functionality is a bit like GitHub and Amazon.com. You're more or less always logged in if you've logged in once but if you haven't manually logged in recently, and you click on something "more sensitive" then it triggers a fresh check that I still know my password. 
I'm only …
=> fixes bug 1114650 - stay logged in much longer

.prettierignore, kuma/javascript/src/article.jsx, kuma/javascript/src/search-results-page.jsx, kuma/javascript/src/ssr.jsx, package-lock.json, package.json
Now, you can run `prettier` on the command line or in vscode and the `.prettierignore` file will be the config that decides what files to look at. The means we no longer need to depend on the script in `package.json`.
=> bug 1562270 - Control files to prettier from config file instead

kuma/javascript/src/article.jsx, kuma/settings/common.py, kuma/static/styles/components/highlight.scss, kuma/static/styles/components/home/home-masthead.scss, kuma/static/styles/components/wiki/content/static/_highlighted-headings.scss, kuma/static/styles/includes/_mixins.scss, kuma/static/styles/main-shared.scss
This removes the need for the `highlightSections` JavaScript function that ensures that some of the document headings use the slab style dark backgrounds. It also adds a couple of small updates to the `addAnchors` function to:
1. Not add it to hidden headings
2. To add the link to a different location on the DOM based on whether the heading is an `h2` or `h3`
I tested this on all the top-level pages liked form the main menu, as well as the `Array` page.
@peterbe r?
=> Bug 1569816, switch highlight section to CSS only

jinja2/includes/google_analytics.html, kuma/core/context_processors.py, kuma/core/tests/test_views.py, kuma/landing/tests/test_templates.py, kuma/settings/common.py, kuma/settings/testing.py, kuma/wiki/jinja2/wiki/react_document.html, kuma/wiki/tests/test_templates.py
By landing this, and shipping it to prod, nothing will or should change. If the environment variable isn't even set, it falls back on constance.
=> bug 1570076 - Move GOOGLE_ANALYTICS_ACCOUNT from constance to env vars

jinja2/403.html, jinja2/404.html, jinja2/includes/config.html
With #5614, I broke the logic in the following templates for attachment domain requests. This PR corrects that.
- jinja2/includes/config.html
- jinja2/403.html
- jinja2/404.html
=> bug 1525719: fix templates

kuma/api/v1/views.py
Fixes #5637
That `other_translations` QuerySet is used in two places. When the QuerySet was used in the second place, it noticed it had filtered too much so for every locale it had to go back to the database and fetch more complimentary stuff.
=> avoid excess wiki_document get queries on /docs/Web

jinja2/base.html, jinja2/react_base.html, kuma/javascript/src/document.jsx, kuma/landing/jinja2/landing/react_homepage.html
@callahad This brings us in line with current production. There is more we should do with regards to the structure and semantics of our pages, but this gets us a bit closer.
r?
=> Bug 1571137, ensure documents use appropriate landmarks

kuma/static/styles/components/wiki/content/collapsible.scss
Fixes [bug 1573928](https://bugzilla.mozilla.org/show_bug.cgi?id=1573928) and fixes #5643.
=> Bug 1573928: Fix double top <h2> border on mobile regression

kuma/static/styles/components/content.scss
See https://bugzilla.mozilla.org/show_bug.cgi?id=1553512
If `p:empty { display: none; }` is defined in the CKEditor stylesheet,
then pasting multiple lines of text also inserts an empty `<p></p>`
before the pasted content.
The "Source" button must be clicked twice to re-render the editor and
display the extraneous paragraphs.
I do not entirely understand why this resolves the issue, but it does.
=> Fix Bug 1553512: blank paragraphs when pasting

kuma/settings/common.py
There is no `js/prism-mdn/components/prism-json.css` file anywhere. 
There is a `prism-json.js` though. 
It's sad that django-pipeline doesn't complain louder about that. I should fix that.
=> Remove prism-json.css from PIPELINE_CSS

kuma/javascript/src/breadcrumbs.jsx, kuma/javascript/src/document.jsx, kuma/javascript/src/document.test.js, kuma/javascript/src/titlebar.jsx, kuma/static/styles/minimalist/components/_breadcrumbs.scss, kuma/static/styles/minimalist/document.scss, kuma/static/styles/minimalist/structure/_containers.scss
This segments the CSS for breadcrumbs between the two different front-ends. I also cleaned up the HTML significantly and moved the CSS out of Emotion and into Sass. Visually, nothing should really have changed.
@callahad r?
=> Fixes issue #5668, segment breadcrumb CSS

kuma/landing/jinja2/landing/react_homepage.html, kuma/settings/common.py, kuma/wiki/jinja2/wiki/react_document.html
Conditionally loads the `banners.css` file on the React side as well. If the waffle flag `developer_needs` is enabled, you will notice the banners file being loaded:
if the flag is disabled, the `link rel` will no longer be present:
@peterbe r?
=> Fixes issue #5676, load banners CSS conditionally

kuma/static/styles/includes/_mixins_indicators.scss
Caused by https://github.com/mozilla/kuma/commit/ff8b3efec11748d5d083368b78d905f473dcf03e#diff-60e8b0bdf8dc8d343884f0096dc6c8eeR73 (#5482), as I didn’t quite realise what the difference between `%indicator‑inline‑icon` and `%indicator‑with‑icon` was back then.
---
=> Bug 1557787: Fix inline indicator without icon padding regression

.editorconfig
**Q:** Should I set `indent_style` and `indent_size` for all files? And if so, what should I set it to?
=> chore(editorconfig): Fix `.jsx` indentation configuration

Jenkinsfiles/utils.groovy, scripts/slack-notify.sh
Fixes #5730 
Add notification to Slack `mdn-infra` (for now) on Kuma and Kumascript deployments.
=> Notify Slack as well as IRC from Jenkins

kuma/static/styles/minimalist/document.scss
Removes a couple of pieces of CSS from the `document.scss` file. Saves us a couple of kb ~ @peterbe r?
=> Fixes #5735, remove document editing and management styling from new frontend

Jenkinsfiles/integration-tests.groovy
Fixes #5749 
Add Slack notification on success or failure of the integration tests when run within Jenkins.
=> add Slack notification to integration tests

kuma/javascript/src/ssr.jsx, kuma/javascript/ssr-server.js, kuma/javascript/ssr-server.test.js, kuma/wiki/templatetags/ssr.py, kuma/wiki/tests/test_ssr.py, package-lock.json, package.json
I haven't done any Lighthouse testing locally to see if this makes a big difference. I know it's sane in principle. 
At first, I tried to do ALL of this in Python but after a lot of searching I couldn't find a library that not only JSON serializes but also one that escapes *everything else* that might appear in the string. At first I tried something like this:
```
templ = "<script>window._react_data = JSON.parse('{}');</script>"
return templ.format(
json.dumps(data).replace('</', '<\\/').replace("'", "\\'") etc etc etc
)
```
But everything I tried just failed. There was always something weird. Especially when involving Unicode. It was just one problem after another. I tried searching for some decent Python libs that does what the npm package `jsesc` does but I couldn't find anything. And …
=> 5619 jsonparse  react data

docker/images/kuma_base/Dockerfile, docker/images/kuma_base/Dockerfile-py3, docker/images/kumascript/Dockerfile
Fixes #5762 
Tested as follows:
```
cd  <kuma repo root dir>
VERSION=latest make build-base
KS_VERSION=latest make build-kumascript
docker-compose up -d
docker-compose exec web make build-static
docker-compose restart
docker-compose exec web make test
docker-compose exec web make lint
cd <kumascript repo root dir>
VERSION=latest make test
VERSION=latest make lint
```
=> use npm ci within the docker image builds

kuma/javascript/ssr-server.js, kuma/wiki/templatetags/ssr.py
Fixes #5777
Our ssr-server.js has a max on the body size of 1MB. 
I opened a django shell and looked at the data:
```
>>> doc = Document.objects.get(locale='ja', slug='Web/API/Window')
>>> from kuma.api.v1.views import document_api_data
>>> data = document_api_data(doc)
>>> import json
>>> dumped = json.dumps(data).encode('utf8')
>>> len(dumped)
1202902
>>> len(dumped) / 1024.  / 1024.0
1.147176742553711
```
I.e. **larger than 1MB**. 
I still wasn't able to reproduce it locally.
=> JSONDecodeError in ssr.py

kuma/wiki/jinja2/wiki/react_document.html
Removes `newsletter.js` from the new frontend. @escattone r?
=> Fixes #5774, remove newsletter.js from new frontend

kuma/static/styles/minimalist/document.scss
This removes the `page-buttons` styling from the new frontend.
=> Fixes #5690, remove page-button CSS from new front-end

kuma/javascript/ssr-server.js, package-lock.json, package.json
Fixes #5783 
This PR enables Sentry for the `ssr` service, so uncaught exceptions are now captured by Sentry.
The `package.json` and `package-lock.json` files were auto-generated from doing `npm install @sentry/node`.
=> use sentry for the ssr service

kuma/javascript/src/index.jsx
There are still a *lot* of styling problems, but that is a separate problem I will address in separate pull requests. This prevents the white screen of death and removes the blocker.
Tested in IE10 on Windows 8 and IE11 on Windows 10
=> Fixes #5786, content should be readable in IE

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/change-request.md, .github/ISSUE_TEMPLATE/feature_request.md
Ports an approximation of our Bugzilla templates from https://bugzilla.mozilla.org/form.mdn to GitHub
Unblocks #5683
=> Add GitHub issue templates

kuma/static/styles/minimalist/document.scss
Removes `collapsible.scss` from the new frontend saving us some 🏋
=> Fixes #5692, remove collapsible.scss from new front-end

kuma/javascript/src/document.jsx, kuma/static/styles/minimalist/structure/_containers.scss
This resolves the problem where pages displayed an empty sidebar.
1. Open up http://beta.mdn.localhost:8000/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array and ensure that the layout is as expected.
1. Next open http://beta.mdn.localhost:8000/en-US/docs/Web/Guide
This only has a TOC in the sidebar, but we should still have the two-column layout with the TOC on the left.
1. Next, go to http://wiki.mdn.localhost:8000/en-US/docs/Web/Guide
2. Click on Edit
3. Click on Edit Page Title and Properties and change TOC to `No table of contents`
4. Click publish
5. Go to http://beta.mdn.localhost:8000/en-US/docs/Web/Guide
6. There is nothing to display in the sidebar so, the main content should fill up the entire available space
=> Fixes #5753, beta site shows empty sidebar

kuma/static/styles/minimalist/components/_search-widget.scss
This removes the light grey background from the search form and field.
=> Fixes #5752, search input field always grey

kuma/wiki/jinja2/wiki/document.html, kuma/wiki/jinja2/wiki/react_document.html
Fixes #5680
It's pointless to do `dns-prefetch` *and* `preconnect` because one is a subset of the other. 
What I don't like is that so many pages don't have a iframe whose source is `https://interactive-examples.mdn.mozilla.net/...`. These for example:
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/head
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/body
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array 
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Object …
=> drop preconnect to interactive examples

.env-dist.dev, docs/installation.rst, kuma/attachments/management/commands/configure_github_social.py
Fixes #5822 
In addition to documenting the fields, this also includes a command (and documentation for it) that sets the fields and also creates (or updates) the SocialApp model for GitHub.
To test it run the command as described in the docs (maybe back up your `.env` file). Different scenarios you can test are permutations of pre-existing SocialApp and localhost-Site models, as well as with/without `SITE_ID` and `DOMAIN` fields in your `.env`.
Missing feature: it doesn't ping mdn.localhost to check if hosts are correctly set up. Why? Because our docker instances don't ship with ping 🙈
=> Add command to help with GitHub setup

docs/installation.rst
I lost a day trying to figure out why my containers kept dying on macOS. This note would've saved me.
=> Update Docker docs to cover default memory limits

kuma/static/styles/components/wiki/crumbs.scss, kuma/wiki/jinja2/wiki/includes/document_macros.html, kuma/wiki/templatetags/jinja_helpers.py
Fixes #5853
This one was tricky. I know the issue is a handful but ponder what this PR results in...:
This is what it looks like:
And if I open view-source:http://wiki.mdn.localhost:8000/en-US/docs/Web/CSS/animation-delay and paste in the relevant `<ol>` tag it validates:
=> make breadcrumb schema validate

kuma/javascript/src/l10n.js, kuma/javascript/src/l10n.test.js, kuma/javascript/src/search-results-page.jsx
Fixes #5869 
This removes the indexed params capability of interpolate, since it wasn't used. It also makes the interpolate function a bit simpler.
=> Remove interpolate's named indexed params capabilities

kuma/javascript/src/header/__snapshots__/dropdown.test.js.snap, kuma/javascript/src/header/__snapshots__/language-menu.test.js.snap, kuma/javascript/src/header/__snapshots__/login.test.js.snap, kuma/javascript/src/header/dropdown.jsx, kuma/javascript/src/header/language-menu.jsx, kuma/static/styles/minimalist/components/_dropdown.scss
This does not entirely resolve issue #5859 but, it is now on par with the rest of our menus on the new frontend. The next steps would be to add the additional required JavaScript to ensure that:
1. the menu is navigable via the arrow keys
2. When the menu is opened and closed toggle `aria-hidden` (current `aria-hidden` is not set at all)
3. Ensure focus moves to the first item in the list
4. Pressing the escape key closes the menu
All of this is relevant to this custom menu as well as the main navigation of the site. I will create separate issues for these so that it can be triaged, prioritized, and moved into our sprint work.
In this pull request, I do set a custom label for the `button` element that triggers the menu so that instead of the assistive technology simply reading `English …
=> Fixes #5859, improve accessibility of custom lang dropdown

kuma/javascript/src/article.jsx
Fixes #5806 
This PR adds a simplified `beta` domain version of the translation message that is displayed within the `wiki` domain when falling-back to the English version of a document that has been requested in a non-English locale. The goal here was to show a clear message that was simple to implement in the React world (e.g., no changes would be required to the `document_api_data` function in the back-end). cc @SphinxKnight 
For example, this is the **`wiki`** version of the message (http://wiki.mdn.localhost:8000/ca/docs/Web/HTTP):
This is the `beta` version **before** this PR (http://beta.mdn.localhost:8000/ca/docs/Web/HTTP):
This is the `beta` version **after** this PR (http://beta.mdn.localhost:8000/ca/docs/Web/HTTP):
For local testing, I used these settings in my `.env` file (my …
=> add message when falling-back to English

kuma/javascript/src/breadcrumbs.jsx, kuma/javascript/src/document.test.js, kuma/static/styles/components/wiki/crumbs.scss, kuma/static/styles/minimalist/components/_breadcrumbs.scss
Fixes #5856
I also copied the rendered DOM HTML into here:
(the use of relative URLs is fine. It's just that tool not possible knowing which domain this came from)
=> correct schema on breadcrumb component

kuma/javascript/src/search-results-page.jsx
[As requested](https://github.com/mozilla/kuma/pull/5770#issuecomment-534527385)
This extracts a lot of the SearchResultsPage render code into separate components, making the control fow in it easier to follow.
=> Componentize SearchResultsPage

kuma/attachments/tests/test_models.py, kuma/attachments/tests/test_views.py, kuma/attachments/utils.py, kuma/settings/common.py
This defines a new Constance flag (`WIKI_ATTACHMENTS_DISABLE_UPLOAD`)
which disables adding or editing attachments via the Wiki. Changes may
still be made via the Django Admin.
We need this capability for the EFS-to-S3 migration (#5798).
=> Add Constance flag for disabling attachment upload

kuma/attachments/tests/test_models.py
"Direct assignment to a reverse foreign key or many-to-many relation" [was deprecated](https://docs.djangoproject.com/en/1.11/releases/1.10/#features-deprecated-in-1-10) in Django 1.10.
Switching to `.set(...)` clears up half a dozen test warnings.
=> Fix a few deprecation warnings for Django 2.0

kuma/javascript/src/article.jsx
Fixes #5880
Tested with `docker-compose exec web npm run eslint` and no more warning now.
=> include 'ga' in effect that alerts google analytics

kuma/wiki/constants.py
Fixes #5922
Adding "title" as an allowed attribute for iframes to give context for screen reader users.
=> iframes don't should allow 'title' attribute

kuma/settings/common.py
This is a required companion PR to https://github.com/mdn/kumascript/pull/1245. It adds an `iframe` source used by the Kumascript macro defined in the companion PR to the list of allowed sources.
=> add test262.report to allowed iframe sources

kuma/authkeys/admin.py, kuma/users/admin.py, kuma/wiki/admin.py
The `allow_tags` attribute on `ModelAdmin` methods was removed in Django 2.0
(https://docs.djangoproject.com/en/dev/releases/2.0/#deprecated-features-2-0)
This replaces all instances of `allow_tags` in our codebase, eliminating
the associated RemovedInDjango20Warning. I have manually verified that
every call to an affected method continues to render correctly.
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1467529
=> Remove use of Django 1's `allow_tags` attribute

kuma/javascript/src/error-boundaries.jsx, kuma/javascript/src/index.jsx, kuma/javascript/src/landing-page.jsx, kuma/javascript/src/signup-flow.jsx, kuma/javascript/src/single-page-app.jsx
Fixes #5929
Truth be told, I don't know if this works. I'm not even sure how to test it. If I fake it by manually making sure [these lines](https://github.com/mozilla/kuma/blob/6df857e40c19011fe41b00347d3e7f3de51349cb/kuma/wiki/jinja2/wiki/react_document.html#L41-L46) really do render then `window.ga` *is* defined by when the call to it happens, I see no XHR requests in my browser. 
I don't know if it's because my fake UA is `12345`. Or perhaps there's a race condition. The way we set up GA is that sometime during the `window.onload` it injects a script tag with src `'https://www.google-analytics.com/{{ GA_FILE }}.js'`. What if, milliseconds before that, our React hydration code happens and comes across this `logError` method.
All in all, I'm just nervous about all of this working. Would …
=> GA track errors from error boundaries

kuma/static/styles/minimalist/document.scss
Remove `wiki/article-head.scss` from `kuma/static/styles/minimalist/document.scss`
Fixes #5924
=> Remove wiki/article-head from new frontend (#5924)

kuma/search/views.py
Reproduced error locally by going to search page with no actual search. After this adjustment tests passed and page works regardless if something is actually searched.
=> Fix broken search tests from SSR

kuma/javascript/src/last-modified.jsx, kuma/static/styles/minimalist/structure/_article.scss
=> Better footer article metadata display

kuma/javascript/src/l10n.js, kuma/javascript/src/l10n.test.js
Fixes #5958 
Although this PR fixes #5958 by making the `ngettext` call safer, the root cause of #5958 runs deeper, and its fix seemed to call for more thought and scrutiny (so I'll open a separate PR that partially addresses that). The root cause of #5958 is that we're not sending the `pluralFunction` as part of the `data` that we encode into `window._react_data`, so the default plural function is always used, which causes problems for locales like `zh-CN`, `ko`, and `ja` whose proper plural function is very different (it always returns `0`). The reason this bug only affected the Chinese locales, is that they had translations for the search page while locales like `ko` and `ja` did not yet.
=> make ngettext safer

kuma/javascript/src/last-modified.jsx
=> whitespace after 'Last modified'

kuma/javascript/src/article.jsx
Fixes #5959
Note that there are *no* "Open in Codepen" buttons. At *first*, I did this:
```javascript
// in article.jsx
addLiveExampleButtons(rootElement);
// in live-examples.js
for (let frame of iframes) {
...
try {
let html = rootElement.querySelector(
`#${sectid} ~ pre[class*=html], #${sectid} ~ * pre[class*=html]`
);
} catch(error) {
...
}
```
But then I realized that in that context, we don't have the GAProvider context because `addLiveExampleButtons` isn't a React component. It's just a function. 
So then I changed it to:
```javascript
// in article.jsx
try { 
addLiveExampleButtons(rootElement);
} catch(error) {
console.error(error);
ga('send', ...)
}
// in live-examples.js
for (let frame of iframes) {
...
let html = rootElement.querySelector(
`#${sectid} ~ pre[class*=html], …
```
=> live-examples trusts section IDs too much

kuma/search/tests/test_views.py, kuma/search/utils.py, kuma/settings/common.py
Fixes #5982
In the olden days, I think `rest_framework` was only used for the site-search if someone didn't use the website. E.g. `/en-US/search.json`. 
Then we started using `rest_framework` for BCD signalling and various things in `/api/v1/*`. 
What the old code, that I've deleted, tried to do was to turn the server errors into other things that it was not. If Elasticsearch is having a rough moment (perhaps it's in the middle of shard balancing, or upgrading, or restarting) we should pretend that it worked with a "200 OK". 
If we have unicode errors or Elasticsearch errors I'd rather find out about it properly instead of masking it. For example, if we see elevated Sentry errors related to say `elasticsearch.TransportError` might want to wrap the Elasticsearch call in a retry mechanism. …
=> don't mask all rest framework errors

kuma/api/tasks.py, kuma/api/tests/test_tasks.py, kuma/api/v1/tests/test_views.py, kuma/api/v1/views.py, kuma/wiki/management/commands/render_document.py
@escattone this is NOT urgent. But it's important as the basis of a discussion. Also, I wouldn't mind if we land this in production so I can continue my work with testing this "migration strategy".
This PR is part of a project that spans Kuma, stumptown-content, and stumptown-renderer. 
With this change, I was able to run `render_document --all` and the that populates an S3 bucket. 
Now, because every file gets a unique name (no more `Web` the file and `Web` the "folder" because the file becomes `Web.json`), I can run: `s3cmd sync s3://peterbe-mdn-documents/ kumadocs/ --recursive` and be able to run a Node script that walks this `kumadocs/` directory without problems. 
Part of the [Stumptown Render Kuma AND Stumptown Semi-Dynamically](https://docs.google.com/document/d/1yNJCNJ2iv4H7f8E0OcJ …
=> 5949 expose the raw kuma html in the document json api

.editorconfig
Currently, default indentation for my editor is configured to use tabs, and without this, my editor indents `.scss` files with tabs.
---
This enforces consistent indentation for all files.
I personally prefer tabs though, because they are more space efficient on disk and in memory (4 bytes per pace vs just 1 per tab).
=> chore(editorconfig): Enforce consistent indentation

kuma/javascript/src/ga-provider.jsx, kuma/javascript/src/ga-provider.test.js
=> don't depend on window.ga till it's actually needed

kuma/javascript/src/__snapshots__/l10n.test.jsx.snap, kuma/javascript/src/l10n.js, kuma/javascript/src/l10n.test.jsx, kuma/javascript/src/newsletter.jsx
Fixes #5819 
I added a Component that works similar to `interpolate`, except that it returns an array with `React.Node`s in it. That way you can also use it to interpolate elements into a string (without risking XSS).
Longer term I'd like to investigate using [Fluent](https://github.com/projectfluent/fluent.js/) which we used in Common Voice and will soon be the No 1 localization system inside of FF. The things we do in `l10n.jsx` are similar but less powerful to what Fluent offers (pluralization comes to mind).
=> Issue#5819 add interpolated with elements

webpack.config.js
In cases where `NODE_PATH` has multiple entries (e.g., [with&nbsp;**pnpm**](https://pnpm.js.org); https://github.com/webpack/webpack/issues/5087), the `webpack.config.js` file wasn’t correctly configured to support that.
There’s also no guarantee that Docker won’t start adding more entries to `NODE_PATH`.
=> fix(webpack‑config): Correctly support multi‑entry NODE_PATH

tests/conftest.py, tests/headless/test_endpoints.py, tests/headless/test_robots.py, tests/utils/urls.py
Fixes #6110 
It also goes a bit beyond #6110 and fixes the `is_local_url` pytest fixture as well.
=> fix integration tests for Python 3

jinja2/base.html, jinja2/react_base.html, kuma/static/js/analytics.js, kuma/users/jinja2/socialaccount/base_signup.html, kuma/wiki/jinja2/wiki/react_document.html
Fixes #6132
The problem was that we had this:
```html
<script defer type="text/javascript" src="/static/build/js/react-main.3608eae72453.js" charset="utf-8"></script>
<script>
if (window.mdn && mdn.analytics) mdn.analytics.trackOutboundLinks();
</script>
```
and deep inside `react-main.3608eae72453.js` it *creates* `window.mdn.analytics`. So the `defer` postpones the creation of `mdn.analytics` and the next couple of lines of inline script will always run before that. Easy mistake. 
But then I noticed there is absolutely no use making `trackOutboundLinks` a "public" function inside `mdn.analytics`. Because it gets called every time all the time. So, I just took it out of the object that `mdn.analytics` is and simply pasted it at the bottom of this closure. There's no need for it being a …
=> always track outbound links

kuma/search/paginator.py, kuma/search/tests/test_views.py
Fixes #6092
If you add `?page=20` to the `rest_framework`, which, by default, is for the SQL ORM you get this:
```sql
...  OFFSET 200 LIMIT 10
```
(because the default page size is 10 so the offset is 20 * 10).
But if that `page` number is crazy like, `?page=2000` instead you get:
```sql
...  OFFSET 20000 LIMIT 10
```
which MySQL can handle and won't choke. However, Elasticsearch is quick to judge. It'll crash on an offset that large. 
Normally, the way pagination works in `rest_framework` is that it evaluates and validates the `page` query string parameter pretty late and that might be happening AFTER then SQL/ES query is attempted.
=> don't 500 on overly big ?page in search

kuma/users/signal_handlers.py, kuma/users/tests/test_tasks.py
This removes the messaging around contributions post-sign-up.
@peterbe r?
=> Fixes #6067, remove contributor messaging post signup

requirements/dev.txt
When I use that local `docker-compose.override.yml` and sometimes get errors, the Werkzeug page that tries to display the error sometimes gets its own errors that get printed on the docker-compose foreground but don't seem to effect the HTML display. I'm not sure if this solves it but I did the upgrade so we might as well keep it. 
https://github.com/pallets/werkzeug/blob/master/CHANGES.rst FYI.
=> Werkzeug 0.16.0

kuma/api/v1/views.py, kuma/javascript/src/article.jsx, kuma/javascript/src/document.jsx, kuma/javascript/src/document.test.js
Fix #6046 
The partial localization box was already there, but the condition for it being shown didn't make sense. I changed it to be the same as the wiki logic for showing it and also reuse those styles.
=> Show warning when an outdated translation is being used

bower.json, kuma/static/js/libs/prism/prism-bash.js, kuma/static/js/libs/prism/prism-core.js, kuma/static/js/libs/prism/prism-css-extras.js, kuma/static/js/libs/prism/prism-css.js, kuma/static/js/libs/prism/prism-javascript.js, kuma/static/js/libs/prism/prism-json.js, kuma/static/js/libs/prism/prism-line-highlight.js, kuma/static/js/libs/prism/prism-rust.js
This updates **Prism** to v1.17.1.
<details>
<summary>
<h2>Kuma affecting changes:</h2>
<table><td>
📝 <strong>Note:</strong> See&nbsp;<a href="https://github.com/PrismJS/prism/blob/v1.17.1/CHANGELOG.md#1171-2019-07-21">PrismJS/prism@v1.17.1</a> for&nbsp;a&nbsp;full&nbsp;list of&nbsp;changes.
</td></table>
</summary>
* __Bash__
* Major improvements (https://github.com/PrismJS/prism/issues/1443) https://github.com/PrismJS/prism/commit/363281b3
* __CSS__
* Extended `url` inside (https://github.com/PrismJS/prism/issues/1874) https://github.com/PrismJS/prism/commit/f0a10669
* Removed unnecessary flag and modifier (https://github.com/PrismJS/prism/issues/1875) https://github.com/PrismJS/prism/commit/74050c68
* __CSS Extras__
* Added `even` & `odd` keywords to `n-th` pattern …
=> chore(deps): Update Prism to v1.17

kuma/static/styles/components/wiki/_indicators.scss
Fixes the read-only badges.
@Gregoor r?
=> Fixes #6090, read only badges unreadable

kuma/static/styles/components/compat-tables/_bc-table.scss
Fixes #6138
Turns out this was a quick fix.
=> Allow wrapping for white-space in code elements

kuma/javascript/src/article.jsx
Fixes #6163
CC @chrisdavidmills 
We already had a KS solution for links made via [`jsapixref`](https://github.com/mdn/kumascript/blob/9a44f78ea18a807681d1aeb37b7eb42ec3c8dd3a/macros/jsapixref.ejs#L15) that puts a title into these links. It makes these:
I suppose that's only for JS docs. (Yay KumaScript!)
So my PR is gentle and only adds the tooltip for those that don't already have a tooltip. 
Also, the screenshot won't show it but visually there's no difference but now when you hover over it it doesn't make a `pointer` cursor.
=> disable a.new links in read-only mode

kuma/wiki/content.py, kuma/wiki/tests/test_content.py
Fixes #6217
To test; before you check out my branch, take a perfectly fine slug URL and make somet HTML like this:
```html
<a href="/en-US/docs/Web/Learn/">Learn!</a>
```
After edit and publish you'll notice that the rendered HTML becomes
```html
<a class="new" rel="nofollow" href="/en-US/docs/Web/Learn/">Learn!</a>
```
Now check out my branch and edit again.
=> class="new" is inserted on links that could work

kuma/users/adapters.py, kuma/users/providers/github/provider.py, kuma/users/tests/test_adapters.py
Fixes #6182 
It was a long and winding road to this PR. The `django-allauth` package doesn't make it easy to do this kind of thing, with their poor/sparse documentation and source code that's very difficult to read/understand (the OAuth2-based sign-up flow is spread across multiple classes, sub-classes, adapters, and utility functions). With that said however, I'm really happy with the final results.
This PR handles the automatic detection and reuse of an existing user when performing a social-provider signup, for example via GitHub or Google. The detection of an existing user is made via a match of one of the existing user's **verified** email addresses with one of the **verified** email addresses harvested from the social provider (i.e. GitHub or Google). If a matching existing user is …
=> re-use existing user accounts on signup

kuma/users/jinja2/users/email/welcome/html.ltxt, kuma/users/jinja2/users/email/welcome/plain.ltxt, kuma/users/tasks.py
Fixes https://github.com/mdn/sprints/issues/2425
The `Subject:` line of the email remains `Take the next step to get involved on MDN!`. Is that acceptable?
=> make welcome email more user focused

kuma/settings/common.py
This simple change allows us to use `vhost` S3-bucket addressing on stage/prod, while maintaining `path` addressing for local development using `minio`. Thanks to @callahad for pointing me in the right direction for this change.
=> do not provide a default S3 endpoint URL

kuma/wiki/search.py
Fixes #6261
Tiny change but big effect. Before, [searching for "django"](https://developer.mozilla.org/en-US/search?q=django) would turn up every possible page that has a "Django" link its side bar. Basically crap search results. 
Mind you, on the read-only site the Django pages wouldn't turn up because it's not a topic that's enabled by default. So as of this fix you get:
But on the wiki, if you enable all topics you get:
Also I downloading 1,000 random documents and compared their `doc.rendered_html` vs. `doc.get_body_html()` and the size in bytes is pretty big:
```
rendered MEAN 9197 bytes MEDIAN 6669 bytes
body     MEAN 7516 bytes MEDIAN 4654 bytes
```
So as of this PR, we'll be putting 20% less data into Elasticsearch. 
Also, think about all the references pages that have a list of …
=> exclude sidebar from site-search content

kuma/static/styles/minimalist/components/_auth-service-header.scss, kuma/users/jinja2/socialaccount/signup.html
Fixes #6025 
This updates the signup page, where you are redirected after authorizing with the chosen Auth provider, to show the appropriate provider logo in the header. Did some additional cleanup so we use generic variable names and also ensures the copy reads as expected.
@Gregoor r?
=> Make signup page dynamic based on auth provider

kuma/javascript/ssr-server.js, kuma/settings/testing.py, kuma/wiki/templatetags/ssr.py, kuma/wiki/tests/test_ssr.py
Fixes #5981
This was a lot tricker than I first envision. Sorry. 
Also, all of this will go away with Yari. For now, with this fix, it'll tie us over quite a bit in the many months of Kuma still doing the SSR. 
Ultimately, the problem is that if something went horribly wrong inside `ssr-server.jsx` (the express server) it would fail but never report anything to Sentry. All you'd get is a Sentry error in Python for the possible `HTTPError`. E.g.https://github.com/mdn/kuma/issues/5981#issue-506747552
I don't really understand how or why but it seems that if you don't use...
```
try {
somethignThatCanGoWrong()
} catch (err) {
Sentry.captureException(err);
}
```
...it wouldn't send to Sentry. I don't see why the [SDK Quickstart for Express](https://sentry.io/for/express/) doesn't mention …
=> SSR Sentry error reporting

kuma/static/styles/minimalist/components/_search-widget.scss
Small change that will allow the search input fill the parent container. 
Tested in supported browsers using BrowserStack Live. 
Closes #6089.
=> Remove max-width on search input

kuma/core/tests/test_utils.py, kuma/core/utils.py, kuma/users/providers/github/views.py, kuma/users/tests/__init__.py, kuma/users/tests/test_views.py
(first of all, this PR is not ready because it includes two separate commits. One of which needs to be landed first in [this separate PR](https://github.com/mozilla/kuma/pull/5421). I didn't want to wait for #5421 to land before starting on this because I "had it fresh in my head". Once that other PR lands, I'll clean up this PR)
**This PR is important and not important at the same time.**
It's not important since it's rather harmless little change in something that happens relatively rarely. All it does is protect the completion-view of the signup flow by retrying `request.get` if GitHub was every to respond with a 500, 502 or 504 response. It's the right and a safe thing to do. 
But it's important because this PR introduces an important new utility function. Namely; …
=> 1552277 GitHub complete login network requests should be retrying

kuma/static/styles/minimalist/document.scss
`structure.scss` was being included in two places: `documents.scss` and `main.scss`. Both files are included in `react-mdn.scss`. 
This change removes `structure.scss` from `documents.scss`, so it will only live in `main.scss`. 
Closes #6255
=> Remove structure.scss from documents.scss 

jinja2/includes/style.html, jinja2/react_base.html, kuma/users/views.py, kuma/wiki/jinja2/wiki/react_document.html
Part of #6294
At least, with this change, the modal can't even being to appear. And any browser extension or whatever that might discove the Google auth link, won't be able to find it any more. 
It's a start.
=> disable modal multi-auth if not enabled

kuma/users/jinja2/socialaccount/signup.html
Fixes #6347 
I'm not sure what the `get_provider_account` I replaced, originally solved for as it also didn't do the correct thing for GitHub for me. So if somebody has some historical context, I'd be curious to hear it :)
=> Use form's username for unchanged signup username display

kuma/static/js/wiki.js
Fixes #6355
This should limit unnecessary highlighting applied while localizing a document with code examples.
It will also reduce this left padding below, which is for line numbers.
=> Limit wiki syntax highlighting to #wikiArticle

kuma/static/styles/components/compat-tables/_vars.scss
Last year, BCD had made the decision to remove Edge Mobile from the compatibility data tables, as a) the platform it runs on is deprecated, and b) many users have been confused about whether it referred to the Windows Mobile version (the correct answer), or the iOS/Android versions.  We have already purged Edge Mobile from the entire repository, however a small column-sized gap was left in the table:
This PR aims to fix this styling issue by reducing the column count by one for the "web" and "js" table types (essentially, the two table types that initially displayed Edge Mobile):
=> Fix gap left from Edge Mobile in compat data table

kuma/static/styles/components/syntax/_base.scss
This was working on previous version of [prism](https://github.com/PrismJS/prism/) but not in the last versions:
For instance, check out the background in the operators on the page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Invoked_through_call_or_apply
With the fix:
=> Fix remove background in operators, strings, utls, etc.

kuma/core/admin.py
This PR is a small fix for the Token admin user field. Both stage and prod have so many users (over 400K) that the user field needs to be a raw `id` field rather than a drop-down containing all users.
=> fix token admin user field

poetry.lock, pyproject.toml
- Updating flake8-import-order (0.18 -> 0.18.1)
https://github.com/PyCQA/flake8-import-order/blob/0.18.1/CHANGELOG.rst
Trivial changes to flake8-import-order.
Also unpinned entrypoints, mccabe, pycodestyle, and pyflakes. We do not
use these directly; they're pulled in as dependencies of flake8.
=> Update flake8-import-order (0.18 -> 0.18.1)

poetry.lock, pyproject.toml
- Updating braceexpand (0.1.1 -> 0.1.5)
https://github.com/trendels/braceexpand/blob/v0.1.5/CHANGELOG.md
- Updating pytest-html (1.16.1 -> 1.22.1)
https://github.com/pytest-dev/pytest-html/blob/v1.22.1/CHANGES.rst
- Updating pytest-metadata (1.5.1 -> 1.8.0)
https://github.com/pytest-dev/pytest-metadata/blob/v1.8.0/CHANGES.rst
- Updating pytest-rerunfailures (2.1.0 -> 4.2)
https://github.com/pytest-dev/pytest-rerunfailures/blob/4.2/CHANGES.rst
Unable to go all the way to the current version (8.0) due pytest
version constraints; will address that in a future pull request.
- Updating pytest-variables (1.7.1 -> 1.9.0)
https://github.com/pytest-dev/pytest-variables/blob/v1.9.0/CHANGES.rst
=> Update a few test dependencies

poetry.lock, pyproject.toml
The only functional change from 2.4.0 to 2.4.3 is the addition of a new
`del_query_param_value` method; all of the other releases were tweaks to
tests or package metadata.
https://github.com/zacharyvoase/urlobject/compare/v2.4.0...v2.4.3
=> Update urlobject (2.4.0 -> 2.4.3)

poetry.lock
Fixes failures with Celery ("unhashable type: 'Redis'")
https://github.com/andymccurdy/redis-py/blob/3.4.1/CHANGES
=> Update redis (3.4.0 -> 3.4.1)

kuma/core/jobs.py
Upon startup, I see many instances of the following warning:
/app/kuma/core/jobs.py:56: RemovedInCacheback13Warning: `GenerationKeyJob.get_constructor_kwargs` method should be renamed `get_init_kwargs`.
This fixes that. No behavior changed in cacheback; it was just a rename:
https://github.com/codeinthehole/django-cacheback/commit/3a47e8c8f68e1ea80ae7b346e3148ce86e10d568
=> Fix django-cacheback deprecation warning

kuma/settings/common.py
Four years ago, we subclassed python-decouple's Csv to make TupleCsv:
https://github.com/mdn/kuma/commit/414dd2107ff5588d9f20c28b6b54389eaf0151d2#diff-61a61acfc5dfb7ad94a50fde2865584eR26-R30
Two years ago, we removed our one use of TupleCsv:
https://github.com/mdn/kuma/commit/20c1f72eb216ea6177e677e6b6920bcef05f6999#diff-61a61acfc5dfb7ad94a50fde2865584eL39
We should remove this unused code.
=> Remove dead code related to python-decouple

kuma/users/providers/github/views.py
Fixes #6421 
I tested this locally and it works great.
For additional reference, see https://github.com/pennersr/django-allauth/pull/2458
=> use Authorization header for passing access token for GitHub

kuma/wsgi.py, poetry.lock, pyproject.toml
- Updating whitenoise (3.3.1 -> 5.0.1)
Raw Changelog: https://github.com/evansd/whitenoise/blob/v5.0.1/docs/changelog.rst
Rendered: http://whitenoise.evans.io/en/stable/changelog.html
For us, the only meaningful behavioral change is that whitenoise now
generates ETag headers for static assets, using the same algorithm as
nginx. In practice, this shouldn't change anything as our production
builds serve static content from CloudFront with hashes in the filenames
and immutable cache-control headers.
I've also reverted `kuma/wsgi.py` to match what Django generates out of
the box. Once upon a time we had to customize it to enable Whitenoise,
but those changes were backed out over two years ago:
https://github.com/mdn/kuma/commit/2526865ecb6272baff58da03a36b0e7b3b2db95d#diff-0b07db8a3993b2a29af1 …
=> Update whitenoise (3.3.1 -> 5.0.1)

kuma/wiki/tests/test_content.py, kuma/wiki/tests/test_forms.py, kuma/wiki/tests/test_views.py, poetry.lock, pyproject.toml
- Updating bleach (2.1.4 -> 3.1.0)
https://github.com/mozilla/bleach/blob/v3.1.0/CHANGES
Bleach is now more faithful to the original text, whereas previously it
would ensure that HTML was well-formed before escaping it. Thus, our
some of our tests needed to be updated after this bleach commit:
https://github.com/mozilla/bleach/commit/6b05f3c133e84b0e4ab61e8e117f4c4b333d80d4
Secondly, we were previously testing the escaping of:
<script><iframe src="data:text/plain,foo"></iframe></script>
Bleach 2.1.4's parser escaped the iframe, since iframe elements aren't
allowed instead script elements, and then escaped the script element
because it's not one of our ALLOWED_TAGS. The result:
&lt;style&gt;&lt;iframe src="data:text/plain,foo"&gt;&lt;/iframe&gt;&lt;/style&gt;
Bleach 3, on the other hand, …
=> Updating bleach (2.1.4 -> 3.1.0)

kuma/static/styles/components/compat-tables/_bc-signal.scss
- Apply a thicker border width when hovering over browser icon
**Before:** 
**After:** 
Closes #6064
=> Fix hover styling on BCD signaling section

kuma/javascript/src/bcd-signal.jsx, kuma/static/styles/components/compat-tables/_bc-signal.scss
- Shrink left column
- Center dinosaur logo
- Make numbers round
- Keep "Optional" text from wrapping to a new line
Closes #6063 and #6065
=> Make BCD Signaling section look more like designs 

kuma/javascript/src/header/__snapshots__/language-menu.test.js.snap, kuma/javascript/src/header/__snapshots__/login.test.js.snap, kuma/javascript/src/header/dropdown.jsx, kuma/static/styles/minimalist/components/_dropdown.scss
- Move positioning of dropdown menu to SCSS file, so we can use the `bidi` mixin to handle LTR and RTL languages. 
- Affects both the User Avatar dropdown in the header and the language dropdown
**Sample URL:** 
http://localhost.org:8000/ar/docs/Web/CSS/:focus-visible
**Before:**
**After:** 
Closes #6354
=> Fix dropdown menu position on RTL languages 

kuma/scrape/scraper.py, kuma/scrape/sources/document.py, kuma/scrape/sources/revision.py, kuma/scrape/storage.py, kuma/scrape/tests/test_scraper.py, kuma/wiki/forms.py
The `warn()` method on loggers is deprecated. Use `warning()` instead.
https://docs.python.org/3/library/logging.html#logging.Logger.warning
=> Fix deprecation warnings for logger.warn()

poetry.lock, pyproject.toml
- Updating pytest-django (3.1.2 -> 3.4.8)
https://github.com/pytest-dev/pytest-django/blob/3.4.8/docs/changelog.rst
This is the most recent version we can update to before tests fail.
=> Update pytest-django (3.1.2 -> 3.4.8)

kuma/core/templatetags/jinja_helpers.py, kuma/wiki/tests/conftest.py, kuma/wiki/tests/test_views.py
- The HTMLParser.unescape() method is a deprecated alias for html.unescape()
- base64.encodestring() is a deprecated alias for .encodebytes()
=> Fix two deprecation warnings

poetry.lock, pyproject.toml
AWS update treadmill:
- Updating botocore (1.14.12 -> 1.14.13)
https://github.com/boto/botocore/blob/1.14.13/CHANGELOG.rst
- Updating boto3 (1.11.12 -> 1.11.13)
https://github.com/boto/boto3/blob/1.11.13/CHANGELOG.rst
Dev/Test dependencies:
- Updating coverage (4.3.4 -> 4.5.4)
https://github.com/nedbat/coveragepy/blob/coverage-4.5.4/CHANGES.rst
- Updating pytest-cov (2.4.0 -> 2.8.1)
https://github.com/pytest-dev/pytest-cov/blob/v2.8.1/CHANGELOG.rst
- Updating pytest-rerunfailures (4.2 -> 5.0)
https://github.com/pytest-dev/pytest-rerunfailures/blob/5.0/CHANGES.rst
- Updating werkzeug (0.16.1 -> 1.0.0)
https://github.com/pallets/werkzeug/blob/1.0.0/CHANGES.rst
=> Straightforward Python dependency updates

.coveragerc, poetry.lock, pyproject.toml
- Updating coverage (4.5.4 -> 5.0.3)
https://github.com/nedbat/coveragepy/blob/coverage-5.0.3/CHANGES.rst
Lots of internals changed with the move to 5.0 (`.coverage` is now a
SQLite database!), but nothing that requires changes to our code.
Coverage 5 can also read settings from `pyproject.toml`, per PEP 518:
https://www.python.org/dev/peps/pep-0518/#tool-table
This lets us remove the separate `.coveragerc` file.
=> Update coverage (4.5.4 -> 5.0.3)

kuma/static/styles/components/wiki/intrinsic.scss
- Remove centering so video is inline with content: 
**Before:**
Larger screens: 
Smaller screens: 
**After:**
Larger screens: 
Smaller screens:
=> Align Youtube video embeds with content

kuma/scrape/scraper.py, kuma/wiki/tests/test_views.py, poetry.lock, pyproject.toml, pytest.ini
- Upgrading pytest (3.10.1 -> 4.6.9)
https://github.com/pytest-dev/pytest/blob/4.6.9/CHANGELOG.rst
- Upgrading pytest-rerunfailures (7.0 -> 8.0)
https://github.com/pytest-dev/pytest-rerunfailures/blob/8.0/CHANGES.rst
Pytest 4 newly depends on:
- Packaging: https://github.com/pypa/packaging
- PyParsing: https://github.com/pyparsing/pyparsing/
- Wcwidth: https://github.com/jquast/wcwidth
This commit also fixes warnings related to:
- The deprecation of `TestCase.assertEquals`
- The deprecation of `Logger.warn`
- Unregisterd PyTest markers
It also correctly classifies pytest as a dev dependency.
=> Upgrade pytest (3.10.1 -> 4.6.9)

kuma/wiki/tests/test_views_revision.py, kuma/wiki/views/revision.py, kuma/wiki/views/utils.py, scripts/revise/README.md, scripts/revise/revise.py
Fixes #6389 
Provides the following:
- Unified git-style diff of a results directory
- Uses the `Last-Modified`/`If-Unmodified-Since` headers instead of the `ETag`/`If-Match` headers for avoiding revision collisions, only to avoid issues associated with the `ETag` header (strong vs. weak, and that CloudFront strips the `ETag` header from responses handled by behaviors that do compression)
- Ensures that the wiki domain is used for requests even if the read-only domain is specified for the `site`
- Updated `scripts/revise/README.md` documentation
I did this on my own time (i.e., outside of sprint time) in order to get this feature to @wbamberg, @ddbeck, and @Elchi3 as quickly as possible.
=> Add unified git-style diff feature to revise script

kuma/wiki/tests/test_templates.py
Our entire test suite has one test marked as an expected failure.
It's been that way for nine years.
The functionality it's meant to test no longer exists in Kuma.
More details:
Once upon a time, Kuma documents used wiki syntax, where double brackets
create linkes to `[[Article Titles]]`.
There was a bug with this: if you were editing a page in Spanish, and
inserted a link to `[[Foo]]`, then when you previewed the document the
rendered link would point to the English version of Foo, rather than the
Spanish one. See: https://bugzilla.mozilla.org/show_bug.cgi?id=609680
Nine years ago, Ricky Rosario fixed that bug:
https://github.com/mdn/kuma/commit/2168a9aed8fbead0228cd6191ba208d1abf0bc17
Seven months later, when Luke Crouch was implementing a new page editor
template …
=> Remove deprecated wiki test

kuma/wiki/jinja2/wiki/translate.html, kuma/wiki/managers.py, kuma/wiki/models.py, kuma/wiki/views/translate.py
Fixes #6445
I just poked around to make sure I understood the issue. It was easy to find what the problem was. And it was equally easy to find a quick solution. 
However, because it's not super important, I didn't bother making this PR with a new test. Because,  reasons. 
Hey, at least this gets translated documents unstuck if their parent is soft-deleted.
=> ability to edit whose parent is deleted

.travis.yml, scripts/ci-docs, scripts/ci-python, test.txt
Small tweaks to our Travis config.
Notable changes:
1. Python linting is 75% faster (3:10 -> 1:20)
2. Two stages: lint then test.
3. Checks for missing migrations before starting the test suite, so you get earlier feedback there.
4. Fixes a broken lint for git conflict markers
5. Uses Node 12 for JS lints, just like our Docker images
There's still lots to do (our docker tests can still take 18 minutes to run and we're not doing anything to parallelize them), but this at least gets us in a better position to start addressing that.
Plus, having a separate linting stage lets us fail fast and freeing up Travis capacity for other in-flight pull requests, instead of always blocking everything for a further 15 minutes while the test suite runs.
I've also migrated us from using Travis via …
=> Small Travis improvements

kuma/settings/testing.py, kuma/users/apps.py, kuma/users/checks.py
Fixes #6405 
I decided to do a lot less than you did in [your system check pull](https://github.com/mdn/kuma/pull/5425) @peterbe, for two reasons:
- system checks are always run on server start and for migrations (in non-deployment mode)
- for deployments I'm entirely ignorant about what the best workflow would be
@escattone I'm really curious to get your take on this. I mistakenly said in the original issue that this an alternative to headless tests. What I meant to say was that it complements our offline tests in such a way that we might not need a stripe headless test (though to be fair what the headless test did test, that isn't checked anymore is whether we got the interaction with stripe itself right).
=> Add system check to verify stripe config

kuma/users/tests/test_views.py, kuma/users/views.py
Part of #6479
And CC @escattone 
This PR is only half the solution to #6479. Basically, our strategy is to confront the user, if they had revisions, so that they have to make a decision about them. Great. However, a user might not have done any DOCUMENT revisions. They might just have ATTACHMENT revisions. As in the case with [Gregor on Stage](https://sentry.prod.mozaws.net/operations/mdn-stage/issues/7271436/).
This PR just protects the Django side of things so the error can't happen. If you have EITHER document OR attachment revisions you now need to have a POST variable `attributions`. 
Once this is merge (or, can I perhaps start on it already??) I'll make it so that the two UIs (I hate that we have to maintain this in two different places!) doesn't decide whether or not to show the …
=> delete user with AttachmentRevisions

kuma/wiki/management/commands/render_document.py
I know it was my PR that introduced the `--slugsearch` and I said you didn't need to scrutinize it because it's not super important. 
Honestly, I don't know how it happened. I used to copy and paste this into `render_document.py` so I could re-render a subset. Don't know how I managed to mix up the `exclude` and `filter`. 
Because of my mistake I accidentally triggered `docker-compose exec web ./manage.py render_document --all --slugsearch=MDN/Jobs` and that caused re-render of 99% of the documents in my local db. Not the 1% I was interested in.
=> --slugsearch was wrong

docker/images/kuma_base/Dockerfile
Part of #6505
This takes away npm trying to announce that it can be upgraded. No more `npm update check failed` mentions in the CI logs. 
No idea if it has any impact on the build speed.
=> take it easy npm update in ci

kuma/static/js/stripe-subscription.js
Fixes #6472 
I also had to add code to re-disable the form when the form is submitted again, after the modal has been closed once. The original jQuery code sets some semi-hidden data, that I could only access if I made the code jQuery dependent:
https://github.com/mdn/kuma/blob/master/kuma/static/js/main.js#L69
I decided adding a line for explicitly disabling the form is the lesser evil.
1. Enable Stripe in Kuma: https://kuma.readthedocs.io/en/latest/installation.html#enable-stripe-payments-optional
2. Sign-in/up as a staff user (or make a user staff through Django Admin)
3. Go to user edit and scroll to the bottom
4. (optional) if you want to go through the flow again there's multiple options
1. delete your user (can also be found in user edit)
1. run `docker-compose exec web python …
=> Re-enable stripe subscription form when modal is closed

jinja2/500.html
fixes #6525 
Updates the URL https://github.com/mdn/kuma/issues/new/choose where users can choose an issue template.
=> Update issue URL to link to templates

pyproject.toml
Prior to this patch, our coverage reports only indicated whether a line
was covered or not. Now, they include additional metadata showing which
tests cover each line. Ned Batchelder calls this "Who Tests What:"
https://nedbatchelder.com/blog/201810/who_tests_what_is_here.html
=> Record which test functions cover each line

kuma/users/forms.py, kuma/users/views.py
When a user deletes their account, we ask if we should retain or
anonymize their prior contributions to the Wiki. This change displays
their current username as part of the deletion / anonymization prompt.
Fixes #6418
Alternative approach to #6517
=> Show username when deleting an account with edits

kuma/static/styles/minimalist/components/_auth-service-header.scss
Fix #6512 
I also removed the `.animate` class as we no longer use it.
=> Show decimal step numbers in signup header

kuma/static/js/components/user-signup/signup.js
As decided in #6511 we no longer show the second checkmark on the user avatar during the sign up process. This PR simply removed the piece of JavaScript that was responsible for adding it.
Fix #6511
=> Removes dynamic addition of checked class on user avatar

poetry.lock
- Updating bleach (3.1.0 -> 3.1.1)
https://github.com/mozilla/bleach/blob/v3.1.1/CHANGES
- Updating boto3 (1.12.0 -> 1.12.2)
https://github.com/boto/boto3/blob/1.12.2/CHANGELOG.rst
- Updating botocore (1.15.0 -> 1.15.2)
https://github.com/boto/botocore/blob/1.13.35/CHANGELOG.rst
- Updating regex (2020.1.8 -> 2020.2.18)
https://bitbucket.org/mrabarnett/mrab-regex/commits/42ec25056389df5ac6b06f599de130f17922db53
We don't use regex directly; it's a dependency of Black's.
=> Routine dependency updates

poetry.lock
Direct dependencies:
- Updating boto3 (1.12.2 -> 1.12.4)
https://github.com/boto/boto3/blob/1.12.4/CHANGELOG.rst
- Updating botocore (1.15.2 -> 1.15.4)
https://github.com/boto/botocore/blob/1.15.4/CHANGELOG.rst
- Updating requests (2.22.0 -> 2.23.0)
https://github.com/psf/requests/blob/v2.23.0/HISTORY.md
Sub-dependencies:
- Updating idna (2.8 -> 2.9)
https://github.com/kjd/idna/blob/v2.9/HISTORY.rst
- Updating regex (2020.2.18 -> 2020.2.20)
https://bitbucket.org/mrabarnett/mrab-regex/commits/2a0cb832d226204d13cc3d5eeda8455f51a28eba
=> Routine Python dependency updates

CONTRIBUTING.md, Makefile, README.rst, contribute.json, docs/deploy.rst, docs/installation.rst, docs/localization.rst
- travis-ci.com, not .org, for mdn/kuma
- remove requires.io badge; we'll be using Dependabot or Renovate
- remove unused `make install` target which referenced an old
requirements.txt that no longer exists
Fixes #6552
=> Minor corrections to docs and Makefile

kuma/settings/common.py, kuma/static/js/components/mathml.js, kuma/wiki/jinja2/wiki/react_document.html
This loads a CSS polyfill if MathML is not supported in the browser.
Tested with the following URLs:
- https://developer.mozilla.org/en-US/docs/Web/API/XRRigidTransform/matrix
- https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getTransform
Firefox supports this natively, Chrome does not.
fix #6391
=> Add CSS fallback for MathML

kuma/wiki/migrations/0007_view_document_permission.py, kuma/wiki/models.py
Django 2.1 introduces a new `view` permission on models, which conflicts with our legacy `view_document` permission. This is reported by `manage.py check` in Django 2 as:
> wiki.Document: (auth.E005) The permission codenamed 'view_document' clashes with a builtin permission for model 'wiki.Document'.
See: https://docs.djangoproject.com/en/2.2/releases/2.1/#model-view-permission
I took the step of manually deleting the legacy permission from the database to avoid unintentionally granting view-only access to the Django admin:
https://docs.djangoproject.com/en/2.2/releases/2.1/#new-default-view-permission-could-allow-unwanted-access-to-admin-views) to users with the former `view_document` permission.
The `view_document` permission was added to Kuma seven years ago in commit …
=> Remove legacy view_document permission

docker/images/kuma_base/Dockerfile
If we could use Docker instead of install node instead of manually installing it we could unleash [Renovate to take care of these things](https://github.com/mdn/kumascript/pull/1333/files).
=> Node 12.16.1

kuma/settings/common.py
Fixes #6550
It's a miracle this hasn't caused more bugs. Perhaps it has caused hundreds of thousands of bugs  due to the progressive-enhancement nature of non-reactive JS, people have simply not noticed and they just refresh and get luckier the next time. 
You should almost never use `async` on a script tag. The only time you should is when you're 101% comfortable with it potentially executing before other .js file has NOT been executed. 
For example:
```html
<script src="/jquery.js"></script>
<script src="/mdn.js"></script>
<script async src="/main.js"></script>
```
is dangerous, **if** the contents of `main.js` is something like this:
```javascript
$(function() { // hi! 
});
```
or...
```javascript
if (window.mdn.utils.getCookie('foo')) {
...
}
```
The only time you should use `async` …
=> don't use async scripts

kuma/users/utils.py
Fix #6583 
I don't have a great test plan, because I don't know how the old subscriptions were created. What I did was to grab the prod keys, Kadir's email and stripe customer ID and put it into my logged-in user's DB row.
But I also think this can be greenlit without testing it as it only makes the code more defensive.
Here's the docs for the [source object](https://stripe.com/docs/api/sources/object) and the [card object](https://stripe.com/docs/api/cards/object), where only the latter has an `address_zip`.
=> Allow for missing zip when retrieving stripe card info

jinja2/base.html, kuma/attachments/jinja2/attachments/edit_attachment.html, kuma/dashboards/jinja2/dashboards/macros.html, kuma/dashboards/jinja2/dashboards/revisions.html, kuma/dashboards/jinja2/dashboards/spam.html, kuma/landing/jinja2/landing/maintenance-mode.html, kuma/search/jinja2/search/results.html, kuma/settings/common.py, kuma/users/jinja2/users/ban_user_and_cleanup.html, kuma/users/jinja2/users/ban_user_and_cleanup_summary.html, kuma/users/jinja2/users/user_detail.html, kuma/users/jinja2/users/user_edit.html, kuma/wiki/jinja2/wiki/compare_revisions.html, kuma/wiki/jinja2/wiki/confirm_document_delete.html, kuma/wiki/jinja2/wiki/confirm_purge.html, kuma/wiki/jinja2/wiki/confirm_revision_revert.html, kuma/wiki/jinja2/wiki/create.html, kuma/wiki/jinja2/wiki/document.html, kuma/wiki/jinja2/wiki/edit.html, kuma/wiki/jinja2/wiki/list/documents.html, kuma/wiki/jinja2/wiki/list/revisions.html, kuma/wiki/jinja2/wiki/move.html, kuma/wiki/jinja2/wiki/preview.html, kuma/wiki/jinja2/wiki/revision.html, kuma/wiki/jinja2/wiki/translate.html
Fixes #6340
Sets `noindex, nofollow` for all wiki pages, hence also removes the block from all those jinja files. That also contained a check for `has_legacy_namespace` so I removed all related code. But I'm not super sure about that change, maybe there's future use for it?
=> Add noindex for the whole wiki but allow it in robots.txt

.gitignore, kuma/api/v1/tests/test_views.py, kuma/api/v1/views.py, kuma/javascript/src/article.jsx, kuma/javascript/src/document.jsx, kuma/javascript/src/document.test.js
Fixes #6536
If you're on a non-en-US page that is not fully translated, it now links to the wiki `$edit` URL, not the URL for choosing locale. Because, surely, if you're reading a non-en-US page (e.g. `sv-SE` in the current URL) then you shouldn't need to choose locale :)
This fix makes it so that that link works the same as the Wiki except in the read-only the link hops over to the Wiki.
=> translateURL should be based on parent

jinja2/includes/google_analytics.html, jinja2/includes/react_google_analytics.html
We suspect that this change is causing a drop in performance, from 3.4s to 3.7s for the 90th percentile. [Slack convo for reference.](https://mozilla.slack.com/archives/CLTBV3W9X/p1582711416043200)
This reverts commit 669ec0a87ddc44045d4593c986b4d102b6717668.
=> Revert "Switch to async GA tag (#6463)"

kuma/api/urls.py, kuma/api/v1/urls.py, kuma/attachments/urls.py, kuma/authkeys/urls.py, kuma/core/tests/logging_urls.py, kuma/dashboards/urls.py, kuma/health/urls.py, kuma/landing/urls.py, kuma/payments/urls.py, kuma/search/urls.py, kuma/urls.py, kuma/urls_untrusted.py, kuma/users/urls.py, kuma/version/urls.py, kuma/wiki/urls.py, kuma/wiki/urls_untrusted.py
Django 2.0 introduced a simplified URL routing syntax.
The previous, regex-based syntax is still supported, but under a new
name: `django.urls.re_path()`. The old name, `django.conf.urls.url()`, is
still available as an alias to help with backwards compatibility.
We might as well adopt the new name to match current documentation.
https://docs.djangoproject.com/en/2.2/releases/2.0/#simplified-url-routing-syntax
=> Use django.urls.re_path() instead of url()

kuma/core/decorators.py, kuma/wiki/models.py
The `available_attrs` function was originally added to Django 1 to work
around a bug in Python 2. When using Python 3, it returns a static
value: `functools.WRAPPER_ASSIGNMENTS`
The `available_attrs` function is removed in Django 3.0:
https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis
We only ever use `available_attrs` with `functools.wraps`, like this:
@wraps(viewfunc, assigned=available_attrs(viewfunc))
Which, under Python 3, is equivalent to `functools.WRAPPER_ASSIGNMENTS`:
@wraps(viewfunc, assigned=WRAPPER_ASSIGNMENTS)
And that's the default value for that kwarg, so we just need:
@wraps(viewfunc)
Hooray!
=> Remove django.utils.decorators.available_attrs

kuma/core/tests/test_views.py, kuma/landing/tests/test_views.py
Failing to consume or close a StreamingHttpResponse raises a
ResourceWarning: unclosed file.
This fixes that.
=> Fix a ResourceWarning: unclosed file in our tests

kuma/javascript/src/index.jsx
Change the behaviour of index.jsx from throwing an error when the component name is `default` to throwing an error if the component  name is not `SPA`, `landing` or `signupflow`, mirroring the logic in
ssr.jsx.
- this PR basically updates one of two duplicated switch statements, so they handle the same cases, and the todo comment can be address with a refactor.
=> Replace case default with default in index.jsx

scripts/revise/revise.py
Fixes https://github.com/mdn/kuma/issues/6625.
This adds the `--no-index` argument to `git diff`, which as far as I can tell [makes `git diff` compare two files or directories on disk rather than comparing the working tree with the index](https://git-scm.com/docs/git-diff).
=> In 'revise diff', pass '--no-index' to 'git diff'

kuma/users/jinja2/account/signup.html, kuma/users/jinja2/socialaccount/signup.html, kuma/users/tests/test_views.py, kuma/users/views.py
@peterbe This was a thought experiment for partly addressing #6623 (it doesn't address the failure to recover existing accounts, just the immediate server error) in a way that is more radical and cleans-up some code that has been bothering me for some time, but I'm not sure I like it. I'm submitting it as an example for discussion.
=> fix username keyerror (github kuma issue #6623)

jinja2/includes/google_analytics.html, jinja2/includes/react_google_analytics.html
Add back `ga` proxies that were missed in #6621. Fixes current production issue.
=> return missing ga proxy

.editorconfig, .travis.yml
This matches the most common practice, including what we do in mdn/infra.
=> Use two spaces for yaml, reindent .travis.yml

jinja2/404.html, jinja2/includes/config.html, jinja2/includes/login.html, jinja2/includes/style.html, jinja2/react_base.html, kuma/javascript/src/header/__snapshots__/header.test.js.snap, kuma/javascript/src/header/__snapshots__/login.test.js.snap, kuma/javascript/src/header/login.jsx, kuma/settings/common.py, kuma/settings/testing.py, kuma/static/js/components/user-signup/auth-modal.js, kuma/users/jinja2/account/login.html, kuma/users/tests/test_templates.py, kuma/users/tests/test_views.py, kuma/users/views.py, kuma/wiki/jinja2/wiki/react_document.html
Clean-up after enabling multi-auth (Google authentication) in production. See https://github.com/mdn/kuma/pull/6645 and https://github.com/mdn/infra/pull/378#issuecomment-595394057.
=> Multi auth cleanup

kuma/wiki/models.py
Fixes #6630
No tests because it's such a rare thing anyway and I speculate the worst that can happen is that for some documents there's no link to the other translation if that other translation lacks a `current_revision`. (All 3 of them)
=> avoid AttributeError inside build_json_data()

docker-compose.yml
I don't know else to test it but things seem to work just fine.
=> don't start the 'api' service in docker-compose

kuma/payments/jinja2/payments/management.html, kuma/payments/tests/test_utils.py, kuma/payments/tests/test_views.py, kuma/payments/utils.py, kuma/payments/views.py, kuma/settings/common.py, kuma/static/js/stripe-subscription.js, kuma/users/jinja2/users/includes/stripe_subscription.html, kuma/users/views.py
Fixes #6473, Fixes #6471 
- reuse old payment management view
- enable it based on a waffle flag instead of the env var
- handle multiple stripe source types when retrieving them. This is the yin to [this PR](https://github.com/mdn/kuma/pull/6528)'s yang
- link to the payment management view
1. go to the user edit view
1. create a subscription (at the bottom) if you don't already have one
1. click on the cancel subscription link
1. verify that you can see your subscription on the next page
1. cancel it
1. use the link on the page to go back to user edit
1. check if you can create a new subscription
=> Old payment management with new Stripe subscriptions

jinja2/react_base.html, kuma/javascript/src/payments/index.jsx, kuma/javascript/src/payments/list-item.jsx, kuma/javascript/src/payments/subheader.jsx, kuma/javascript/src/single-page-app.jsx, kuma/landing/jinja2/landing/react_homepage.html, kuma/payments/jinja2/payments/index.html, kuma/payments/jinja2/payments/payments.html, kuma/payments/tests/test_views.py, kuma/payments/urls.py, kuma/payments/views.py, kuma/static/styles/components/payments/_page.scss, kuma/urls.py
**Summary:** 
Convert existing FAQ page to the Subscription landing page in React. 
**To do:** 
**URLs** 
**/payments** is changing from wiki to non-wiki
**/contribute** currently redirects to /payments, is changing from wiki to non-wiki 
**/payments/recurring** is still on the wiki domain, same old Jinja page for now. Header says "Thank you for supporting MDN."
**To test:** 
Go to /payments (http://localhost.org:8000/en-US/payments): 
Make sure former /payments/recurring page still works by going to /payments/recurring:
Closes #6582
=> Create subscription page (copy of #6647 but with a clean commit history)

kuma/javascript/src/app.jsx, kuma/javascript/src/app.test.jsx, kuma/javascript/src/index.jsx, kuma/javascript/src/ssr.jsx, kuma/javascript/src/ssr.test.js
This commit just extracts the duplicate switch statement in index.jsx and ssr.jsx into it’s own thing, an App component.
As the default handling for an unknown prop `componentName` is different in index.jsx (throws an error) than in ssr.jsx (writes to console), the App component just returns null to indicate this condition. 
App also takes an optional second prop `data`, in index.jsx it comes from `window._react_data`, I can’t find a type for it anywhere, so have left it as `any` for now.
=> Extract duplicate switch statement into component

kuma/javascript/src/active-banner.jsx, kuma/javascript/src/active-banner.test.js, kuma/javascript/src/user-provider.jsx, kuma/javascript/src/user-provider.test.js
Fixes #6702
I didn't realize this but in our jsx files, we're converting the result of `/api/v1/whoami` into a brand new object and I didn't update that when I added the `is_subscriber` to Django. And the tests didn't notice :(
=> Subscription banner to be hidden to active subscribers

kuma/core/ga_tracking.py, kuma/settings/common.py, kuma/settings/testing.py, kuma/users/tests/test_stripe_subscription.py, kuma/users/views.py
Fixes #6698
Let me know if you need help on how to test this. After all *you* invented the tooling in the first place. 
Also, I slowly realized that https://github.com/mdn/kuma/issues/6654 can actually wait. Once *this* PR lands, I'll go back to https://github.com/mdn/kuma/issues/6654 and refactor some code so it starts to depend on `settings.CONTRIBUTION_AMOUNT_USD`. I'm not in love with the naming of that but it's a start and incremental progress.
=> ga tracking on server-side subscriptions

kuma/users/jinja2/users/includes/delete-user-content.html
Fixes #6696
1. Go to Edit Profile
2. Change username to an empty string
3. Press "Save profile"
Crash! 💥 🥵
=> NoReverseMatch on users.user_delete

kuma/wiki/tests/test_views_document.py, kuma/wiki/views/document.py
Fixes #6708
Steps to reproduce. 
Go to any en-US page on wiki.localhost.org:8000 and click to make a translation of it. Pick a language. When you edit, the only thing you change is the title and publish. Make a page like this for example: http://wiki.localhost.org:8000/sv-SE/docs/Web/HTML/Element/l%C3%A4nk
Now, once published, use the Wiki to delete it. That means you'll get a 404, in `curl`, on http://localhost.org:8000/sv-SE/docs/Web/HTML/Element/l%C3%A4nk
Now, enable this branch and that 404 will turn into a 302.
=> redirect to parent of deleted documents if possible

kuma/javascript/src/prism.js, kuma/static/js/syntax-prism.js
Fixes #6468
The [issue](https://github.com/mdn/kuma/issues/6468) is a lot to read but the killer insight is [this](https://github.com/mdn/kuma/issues/6468#issuecomment-603236872). The read-only site skips `<pre>` tags that have tags inside them. If you copy this into the jQuery code you get the same desired behavior on the wiki site too.
=> subscripts dropped in wiki post-processing

kuma/search/tests/test_views.py, kuma/search/views.py
Fixes #6350
To reproduce, make a search, on the read-only site, that yields few (less than 100) search results. You may or may not see a "Next" button at the bottom of the page. Click that till the "Next" button doesn't appear anymore. At the point increment the `page=NUMBER` to `page=NUMBER+1` 
E.g. http://localhost.org:8000/en-US/search?q=intersectionobserver&page=2
Before you would get an error inside SSR because the React code assumes there is a count. 
With this change you get this:
=> TypeError in search-results-page on overly big page

kuma/wiki/jinja2/wiki/confirm_document_delete.html, kuma/wiki/views/delete.py
If you stumble on a page that is actually a "parent" you get that red warning with no info about  how many children there are. So this can help in realizing "Oh there's only 2 children that might need to be deleted."
Looks like this:
=> list children when you can't delete a parent

kuma/wiki/tests/test_views_translate.py, kuma/wiki/views/translate.py
Fixes #6673
Here's how I tested it. First I went to a localized piece of content that works and exists. 
E.g. http://wiki.localhost.org:8000/sv-SE/docs/Mozilla/Add-ons/WebExtensions
Then I (soft) deleted it on http://wiki.localhost.org:8000/sv-SE/docs/Mozilla/Add-ons/WebExtensions$delete
Now, if I go back to http://wiki.localhost.org:8000/sv-SE/docs/Mozilla/Add-ons/WebExtensions it actually (rather sneakily) draws from the en-US document despite the locale in the URL. On that now English document (but with Swedish header & footer) I use the language drop-down and pick "Add translation". Then pick Swedish in the list. Then I just go ahead and try to create the new swedish translation. Should not crash :)
=> translation over a deleted translation

kuma/scrape/storage.py
If you had a document with the same slug and locale, locally, but it's soft-deleted, then this happens:
```
▶ docker-compose exec web ./manage.py scrape_document https://wiki.developer.mozilla.org/ko/docs/Learn
INFO: Scrape progress, cycle 1: 1 Initializing, 1 Gathering Requirements
INFO: Scrape progress, cycle 2: 2 Initializing, 1 Gathering Requirements, 1 Done
WARNING: On locale "ko", slug "Learn", got error (1062, "Duplicate entry '151137' for key 'PRIMARY'")
....
storage.save_document(doc_data)
File "/app/kuma/scrape/storage.py", line 111, in save_document
assert document is not None
AssertionError
```
=> ability to scrape over a deleted document

kuma/javascript/src/header/__snapshots__/header.test.js.snap, kuma/javascript/src/header/__snapshots__/login.test.js.snap, kuma/javascript/src/header/login.jsx, kuma/static/js/components/modal.js, kuma/static/js/components/user-signup/auth-modal.js
Fixes #6740
Fixes #6747
Here's how I tested it;
I future-guessed what it could be used for. In `subscription-form.jsx`. So I put this in
```javascript
function triggerAuthModal(event) {
// If window.mdn.triggerAuthModal is available, use that. But note, the
// 'event' here is a React synthetic event object, not a regular DOM
// event. So, we prevent *this* synthetic event and hand over to the
// global window.mdn.triggerAuthModal() function to take over.
if (window.mdn && window.mdn.triggerAuthModal) {
event.preventDefault();
window.mdn.triggerAuthModal();
}
}
...
<a href="later" onClick={triggerAuthModal}>Test sign in</a>
```
That triggers the auth modal. 
Now, as part of https://github.com/mdn/kuma/issues/6557 I'll be able to use this to display the subscription form to *everyone* but …
=> auth modal available outside login

kuma/static/styles/components/compat-tables/_bc-icons.scss, kuma/static/styles/components/compat-tables/_bc-table.scss
Fixes alignment of icons and other small table updates for RTL BCD tables
* http://localhost.org:8000/he/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray
* http://localhost.org:8000/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray
If you do not have those document locally, you can scrape them with:
```
make bash
./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray#Browser_compatibility
./manage.py https://developer.mozilla.org/he/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray#Browser_compatibility
```
@mindy r?
fixes #6710
=> BCD - Icons overlap labels for RTL locales

jinja2/includes/newsletter.html, kuma/javascript/src/__snapshots__/newsletter.test.jsx.snap, kuma/javascript/src/newsletter.jsx, kuma/static/js/newsletter.js
When JavaScript is disabled or failed to execute the privacy checkbox field is hidden. This makes submitting the form impossible as this is a required field, but is not accessible via the UI.
The pull requests address the issue:
@mindy r?
fixes #5977
=> Privacy checkbox hidden with JS disabled

kuma/landing/tests/test_views.py, kuma/landing/views.py, tests/headless/__init__.py, tests/headless/test_robots.py
Fixes #6340 
This PR opens up all of the endpoints on the production wiki domain (https://wiki.developer.mozilla.org) to robots. We already put `noindex, nofollow` in place for all of the wiki endpoints via #6502.
=> allow all for robots on prod wiki

kuma/javascript/src/article.jsx
Fixes #6727
How to review this? Basically, brew a thermos of tea and read through the notes in the issue. 
I do dare to speculate there's something rather rotten in the Kuma wiki code that sits between KS rendering and the saving of `rendered_html`. 
The whole idea of putting `class="new"` is a Wiki concept. In a traditional wiki, to make a new page you make a link to it and when you render it the first time, that link is now a link to the wizard for creating the page. I.e. I type:
```
I'm going to create a page about DocLegacy.
```
and when rendered it becomes:
```html
I'm going to create a page about <a href="/create.cgi?url=DocLegacy" class="new">DocLegacy(?)</a>.
```
On the MDN wiki we don't quite do it like that. You create a link like this:
```
I'm going to create a page about <a …
```
=> links to untranslated pages

kuma/static/js/components/account-management/delete-user-modal.js, kuma/static/styles/minimalist/atoms/_buttons.scss, kuma/static/styles/minimalist/components/user-settings/_delete-user.scss, kuma/static/styles/user-delete.scss, kuma/users/jinja2/users/includes/delete-user-content.html, kuma/users/jinja2/users/user_edit.html
- Change "Cancel" button to an anchor tag, which points to /edit 
- Make modal and /edit page look more like general designs in Abstract
- Buttons are aligned left
- Update delete text
- Remove border-radius and reduce border-width on positive / negative buttons 
**Modal**
Before:
After:
**Delete page**
Before:
After:
**Edit page**
Before:
After:
Make sure the modal cancel button still works: 
1. Go to http://localhost.org:8000/en-US/profiles/{username}/edit
2. Click on "Delete your account"
3. When modal appears, click on "Cancel" button, modal should close
Now check that the actual bug is fixed:
4. Go to http://localhost.org:8000/en-US/profiles/{username}/delete
5. Click on "Cancel", should be taken back to http://localhost.org:8000/en-US/profiles/{username}/edit
Closes #6495
=> Fix cancel button behavior, adjust button styles

.gitattributes
I once again ran into the problem that kuma will fail to run fairly cryptically if one has CRLF as line endings. Unfortunately git for Windows defaults to applying those for text on checkout (aka `autocrlf`). If one unsets it and updates git, it'll be set again. So this adds a `.gitattributes` file that tells git to use LF for all files, independently of system settings.
This should only affect Windows users and all editors I know of know how to read LFs, so currently I don't foresee any downsides to this.
=> Add .gitattributes for keeping LF EOL for all text

kuma/static/js/analytics.js
Fixes #6758
Before checking out this branch; go to the home page. Change your Firefox to disable tracking protection. I.e. clicking the little toggle so it looks like this:
(doing that will reload the page)
Now, try to click any link to a Hacks post on the home page.
=> fix all outbound links when Tracking Protection is off

kuma/javascript/src/landing-page.jsx
This turned out _much_ simpler than I anticipated 😸 
@atopal I only added this to the modern front-end as it does not really make much sense to me to have this on the retired `wiki`. Let me know if that was the wrong call.
@Gregoor r?
Fixes #6522
=> Add task completion survey to landing page

kuma/wiki/tests/test_ssr.py
Commit fcac45bcbb changed the switch statement on `componentName` in index.jsx and ssr.jsx from having a case for `document` to `SPA`.
=> Update componentName in SSR test

kuma/javascript/src/bcd-signal.jsx
Changes:
- Get feature name from first child, which excludes "Experimental" and "Deprecated" labels
Before:
After: 
Closes #6374
=> Remove "Experimental" or "Deprecated" from select dropdown on BCD table

jinja2/includes/auth-modal-content.html, jinja2/includes/login.html, kuma/core/context_processors.py, kuma/core/tests/test_misc.py, kuma/users/jinja2/socialaccount/snippets/provider_list.html, kuma/users/tests/test_views.py
Fixes #6805 
To test, start by being anonymous, then...
1. go to a page like http://localhost.org:8000/en-US/docs/Web/JavaScript and click "Sign in" clicking on either Google or GitHub will have the `?next=%2Fen-US%2Fdocs%2FWeb%2FJavaScript` thing on it/ 
2. instead of single-clicking the "Sign in" link, right-click and "Open link in a new tab". It should take you to a page like http://localhost.org:8000/en-US/users/account/signup-landing?next=/en-US/docs/Web/JavaScript Observe that the GitHub and Google buttons have `?next=%2Fen-US%2Fdocs%2FWeb%2FJavaScript` on it. 
3. go straight to the sign in landing page http://localhost.org:8000/en-US/users/account/signup-landing and note that the Google and GitHub buttons *don't* have a `?next=...` on them because it doesn't want to redirect back …
=> link to auth with next

.eslintrc.js, kuma/javascript/src/payments/feedback-form.test.jsx, package.json, yarn.lock
**Changes**
- Add `@testing-library/jest-dom` which provides more custom matchers
- Add recommened `eslint-plugin-jest-dom` plugin
**Reasons**
I've been wanting to add this package after `@testing-library/react`, but was afraid of messing up `package-lock.json`, and since we now use `yarn`, I thought I would try. 
I think some of the biggest benefits are readability, clarity, and better assertions. For example, I was writing tests like `expect(...).toBeTruthy(...)`, or `expect(...).toHaveLength(1)`, which both work but are vague. I think it's more meaningful to write, `toHaveTextContent()` or `toBeInDocument()`, for example. Create React App recommends using jest-dom in tandem with React Testing Library.
Here's a bit of code that `eslint-plugin-jest-dom` caught and fixed on commit (it …
=> Add @testing-library/jest-dom package 

kuma/core/context_processors.py, kuma/settings/common.py
Part of #6848
Instead of auditing our env vars in `infra`, here's how I checked that it has fully moved already:
In prod...
```
>>> from constance import config
>>> config.GOOGLE_ANALYTICS_ACCOUNT
'UA-36116321-5'
>>> from django.conf import settings
>>> settings.GOOGLE_ANALYTICS_ACCOUNT
'UA-36116321-5'
```
=> remove GOOGLE_ANALYTICS_ACCOUNT from constance

kuma/settings/common.py, kuma/wiki/views/create.py
Part of #6848
Here's how I checked the default on prod:
```
>>> from constance import config
>>> config.EMAIL_LIST_MDN_ADMINS
'mdn-admins@mozilla.org'
```
=> move constance EMAIL_LIST_MDN_ADMINS to settings

.github/merge-when-green.yml
I don't yet know why `merge when green` isn't working. Look at https://github.com/mdn/kuma/pull/6861 for example. 
Perhaps you need to have a config file. Either way, that's how I found out to change tell Merge-when-green to use the "Squash and merge" method.
=> merge-when-green config

kuma/javascript/src/payments/subscription-form.jsx, kuma/static/styles/minimalist/components/subscriptions/_subscription-form.scss
**Changes**
- Decrease form font size to 12px
- Set width of form to 470px
- Disallow wrapping of text around checkbox 
**To test**
Visit http://localhost.org:8000/en-US/payments/
**Before**
**After**
=> Visual edits to subscription form

kuma/payments/tests/test_views.py, kuma/payments/urls.py
@mindy I'm trying to get my sanity with these payments URLs. One thing I noticed is that the index page is used for any broken URL. E.g.
```
▶ curl -I https://developer.mozilla.org/en-US/payments/xxxxx
HTTP/2 200
...
```
As of this little PR, all of that is fixed. Hopefully it helps you on your crusade with the reactifying. Here's how I tested it:
```
▶ python ~/dummy.py https://developer.allizom.org/en-US
/payments                      EXPECT 301 GOT 301 YAY!
/payments/                     EXPECT 200 GOT 200 YAY!
/payments/XXX                  EXPECT 404 GOT 200 FAIL
/payments/terms                EXPECT 301 GOT 200 FAIL
/payments/terms/               EXPECT 200 GOT 404 FAIL
/payments/terms/xxxxx          EXPECT 404 GOT 200 FAIL
/payments/thank-you            EXPECT 301 GOT 200 FAIL …
```
=> tighten payments urls

kuma/javascript/src/active-banner.jsx, kuma/javascript/src/ga-provider.jsx, kuma/javascript/src/payments/subscription-form.jsx
Fixes #6827
- creating the analytics search params now also uses `URLSearchParams` (thanks for the reminder, Peter!) and the function accepts multiple params
- send new analytic events:
- `subscribe intent (unauthenticated)`
- `subscribe intent (authenticated)`
- `successful subscription (unauthenticated)`
- `successful subscription (authenticated)`
-  rename the `xStripeContinuation` functions using `sessionStorage` to `xStartedUnauthenticated` to
- reflect what users did and not what we're using it for
- reuse it to decide which of the new analytics events to send
Run through the subscription flow on http://localhost.org:8000/en-US/payments, once already logged-in and once logged-out (which will force you to login during the process).
=> Events for (un)authenticated user subscription conversion

kuma/api/v1/tests/test_views.py, kuma/api/v1/urls.py, kuma/api/v1/views.py, kuma/conftest.py, kuma/payments/tests/test_views.py, kuma/users/stripe_utils.py, kuma/users/tests/test_stripe_subscription.py, kuma/users/views.py
Part of #6892
Here's how I test it,
I open `payments/pages/index.jsx` and inject these lines:
```jsx
// TEMPORARY HACKY CODE TO TEST THINGS
useEffect(() => {
if (isSubscriber) {
fetch('/api/v1/subscriptions/').then((r) => {
console.log('RESPONSE:', r);
if (r.ok) {
r.json().then((data) => {
console.log(
'SUBSCRIPTION DATA:',
JSON.stringify(data, null, 2)
);
});
}
});
}
}, [isSubscriber]);
```
But you can also do the same with `curl` if you copy the cURL call from the dev tools Network panel as that will have the `Set-Cookie` in it.
I know the PR looks big. It's not that big. The changes to `kuma/api/v1/views.py` and `kuma/api/v1/urls.py` are the most important and most relevant. Everything else is just refactoring now that these subscription stuff things are spread across `kuma.payments`, …
=> subscription api to list subscriptions

kuma/static/styles/components/wiki/_toc.scss
Changes:
- Lower z-index of Table of Contents so it appears below Technologies dropdown 
To test: 
- Visit any page with a table of contents, like http://localhost.org:8000/en-US/docs/Web/CSS. 
- Hover over "Technologies" and ensure that it shows up above TOC
Before:
After: 
Closes #6942
=> Fix "Technologies" dropdown UI bug

kuma/users/tests/test_stripe_subscription.py, kuma/users/views.py
Fixes #6874 
Changes the invoice amount for the invoice email to be dynamic, based on what was actually paid. E.g. for my configured plan:
```
Thank you.
You supported MDN with a $23.00 monthly subscription.
Amount paid: $23.00
Payment method: Visa
Invoice number: 6DAEC331-0022
Date of issue: April 28, 2020
Date due: April 28, 2020
Your next payment of $23.00 (monthly) occurs on May 28, 2020.
Cancel any time. To cancel your subscription, please go to the manage monthly subscriptions page (http://localhost.org:8000/en-US/payments/recurring/management/). If you have quest
ions, please read the FAQ (http://localhost.org:8000/en-US/payments/) or you can also contact support (mdn-support@mozilla.com).
```
I also renamed `payment_intent` to `invoice` as the former was a misnomer, making it hard …
=> Read subscription invoice total from stripe object

tests/headless/test_endpoints.py, tests/headless/test_robots.py
Fixes https://github.com/mdn/kuma/issues/6918
Already tested against stage and prod using:
```python
docker-compose exec web pytest --base-url https://developer.allizom.org tests
docker-compose exec web pytest --base-url https://developer.mozilla.org tests
```
so with this PR all integration tests pass again.
=> fix robots and endpoints headless integration tests

kuma/users/stripe_utils.py
Fixes #6846 
Surprisingly little. It changes subscription retrieval to return the first subscription it finds, if there's none for the currently configured plan. Which means we'll also save subscriptions from other (old) plans to our caching table.
I honestly thought there would be more to do here, but I couldn't find any other unwanted interactions this change was creating 🤔 
1. Make sure you have an enabled webhook for the payment_suceeded event (https://dashboard.stripe.com/test/webhooks)
1. Subscribe to MDN in your local install
1. Create a new stripe subscription plan. For a test account you'll have to create it under a new product (https://dashboard.stripe.com/test/subscriptions/products).
1. Set the new plan in .env
1. Clear the users_usersubscription table
1. Restart docker
1. …
=> Retrieve any stripe subscription, not just for the current plan

.travis.yml, scripts/ci-codecovsubmit
Unfortunately, it sometimes happen that we get an error submitting this due to connection errors. 
Thankfully modern versions of `curl` allow the `--retry-connrefused` param. 
So I thought I'd add that. But it turns out we don't have a modern version of `curl` in TravisCI. 
Anyway, at least this uses the `--retry` which intelligently retries on bad HTTP error codes. And now it's a bash script instead.
=> codecov submission with retry

scripts/ci-python
This makes it so that coverage tests are only used if the PR build is a PR and has any changes to `.py` files. 
See comment below about the potential (hint: 1min faster builds)
=> CI python without coverage

kuma/javascript/src/breadcrumbs.jsx, kuma/javascript/src/breadcrumbs.test.jsx, kuma/javascript/src/document.jsx, kuma/javascript/src/document.test.js, kuma/static/styles/base/elements/_sectioning.scss, kuma/static/styles/minimalist/components/_breadcrumbs.scss, kuma/static/styles/minimalist/utils/_utility-mixins.scss
**Changes**
- On mobile and tablet screens, hide all but the immediate parent crumb 
- On mobile and tablet screens, breadcrumbs appear above title
- New arrow styles between breadcrumbs
- Add Sass mixin for caret-like arrows 
**To test**
Go to http://localhost.org:8000/en-US/docs/Web/HTML/Element/article and view breadcrumbs on various screen sizes.
**Before:**
_Desktop_
_Mobile_
**After:** 
_Desktop_
_Mobile_
Closes #6822
=> Make breadcrumbs mobile and tablet-friendly

kuma/javascript/src/user-provider.test.js
**Issue:** 
Running `jest` gives you this error in `user-provider.test.js`: 
```
console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:120
Warning: An update to UserProvider inside a test was not wrapped in act(...).
When testing, code that causes React state updates should be wrapped into act(...):
act(() => {
/* fire events that update state */
});
/* assert on the output */
This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
in UserProvider
in GAProvider
```
**Changes:**
Update test so it does not cause this error.
**To test:**
Run `jest` and ensure that no `console.errors` are logged and tests pass.
=> Fix Jest error in user-provider test

kuma/javascript/src/payments/pages/management.jsx, kuma/javascript/src/payments/pages/management.test.jsx, kuma/static/styles/components/payments/_page.scss
Must've had cached SVG files or something-- I did not notice this on the last review. 
Before:
After:
=> Fix icon size and pluralization on Payments Management page

kuma/javascript/src/footer.jsx
Fixes #6971
To test: Go to 
http://localhost.org:8000/en-US/docs/Web
Before: 
After:
We're still maintaining two footers :(
=> footer and .contentinfo

kuma/static/styles/components/compat-tables/_bc-table.scss
Changes:
- Align table body row headings to top-left of cell 
To test:
- Visit any page with a BCD table that has notes, such as http://localhost.org:8000/en-US/docs/Web/CSS/@media#Accessibility_concerns. 
- Toggle arrow and ensure that table row heading is still visible 
Before: 
After: 
Closes #6845
=> Fix BCD table row headings

kuma/javascript/src/header/__snapshots__/login.test.js.snap, kuma/javascript/src/header/login.jsx, kuma/javascript/src/header/login.test.js, kuma/static/styles/minimalist/components/_dropdown.scss, kuma/static/styles/minimalist/components/_login.scss, kuma/static/styles/minimalist/components/_main-nav.scss, kuma/static/styles/minimalist/components/_page-header.scss
I am breaking down the work on the optimized header as I have found a few things over and above the "actual" work that needs attention. So, instead of holding out for one *big* PR, I am thinking many small pull requests that progressively improve things ;)
@Gregoor r?
=> First iteration of responsive header improvements

.github/ISSUE_TEMPLATE/content-issue.md, docs/installation.rst, kuma/settings/common.py, kuma/users/apps.py, kuma/users/checks.py, kuma/users/management/commands/export_to_sendinblue.py, kuma/users/sendinblue.py
Fixes #6933 
Adds a command to export users who've opted-in to the "new" newsletter signup checkbox into sendinblue. It's currently done in two requests, since we want to bucket users into paying and non-paying lists. The docs for the API used are here: https://developers.sendinblue.com/reference#importcontacts-1
~I chose to not add the API key to our config files it yet, as we're still in the early testing phase of this. So in the future this command might have no arguments, but for now it has three (more below).~
Also there's a limit to the import CSV string size, which is ~8MB. My napkin math says we'll reach that once we try to import 400k users at once. Currently we're only importing the once who've checkedthe fairly new (signup-only) opt-in. So I opted for not complicating the code …
=> Add command for exporting subscribers to sendinblue

.eslintrc.js, jest.config.js, jest.setup.js, kuma/javascript/src/.eslintrc.js, kuma/javascript/src/article.jsx, kuma/javascript/src/breadcrumbs.test.jsx, kuma/javascript/src/header/search.jsx, kuma/javascript/src/payments/components/cancel-subscription-form.test.jsx, kuma/javascript/src/payments/components/errors.test.jsx, kuma/javascript/src/payments/components/feedback-form.test.jsx, kuma/javascript/src/payments/components/subscription-form.test.jsx, kuma/javascript/src/payments/pages/management.test.jsx, kuma/javascript/src/payments/pages/page.test.jsx, kuma/javascript/src/payments/pages/terms.test.jsx, kuma/javascript/src/payments/routes.test.jsx, package.json, yarn.lock
Changes:
- Add `eslint-plugin-testing-library` (thanks @peterbe for sharing this [article](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library)!) 
- Import `jest-dom` before test files - I think we use it enough that it makes sense to always have it available. 
- Clean up existing tests that imported jest-dom matchers individually
- Fix eslint errors
To test:
Run `jest`
=> Front-end testing cleanup and improvements

jinja2/base.html
Fixes #7046
Steps to tests:
1. Open http://wiki.localhost.org:8000 - no speedcurve in HTML source
1. Open http://wiki.localhost.org:8000/en-US/docs/Web - no speedcurve in HTML source
1. Open http://localhost.org:8000 - speedcurve still in HTML source
1. Open http://localhost.org:8000/en-US/docs/Web - speedcurve still in HTML source
=> Remove speedcurve from wiki

kuma/javascript/src/payments/components/incentives.jsx
**Changes** 
- Update copy on /payments to "20% _off at_ the MDN Merch Store"
**To test**
- Go to /payments and ensure text says "20% off at": 
Closes #7028
=> Fix typo on /payments

Jenkinsfiles/standby-push.groovy, Jenkinsfiles/standby-push.yml, Jenkinsfiles/utils.groovy
Add ability to push to multiple cluster for just the `eu-central-1` region, the `get_target_script` function in `utils.groovy` needed to be updated to be able to accept an argument. This allows the function to be able to use the  appropriate config file during deployments.
This goes hand in hand with mdn/infra#404 and this PR resolves #7049
=> Add ability to push to multiple clusters

tests/headless/test_cdn.py, tests/headless/test_endpoints.py
Removes two integration tests that we missed removing in https://github.com/mdn/kuma/pull/7045, and so fixes the integration tests such that they pass again. Has already been tested against https://developer.mozilla.org.
=> remove doc api calls from integration tests

CONTRIBUTING.md, README.rst, docs/deploy.rst, docs/installation.rst, kuma/users/jinja2/users/email/welcome/html.ltxt, kuma/users/jinja2/users/email/welcome/plain.ltxt
After a rightful comment of Kairo's on Matrix, I have updated files where IRC was mentioned.
This includes both welcome emails and code contribution docs to kuma.
@jmswisher: not a big deal but I would appreciate your review on kuma/users/jinja2/users/email/welcome/html.ltxt / kuma/users/jinja2/users/email/welcome/plain.ltxt
@escattone / @peterbe / @schalkneethling: I have removed some #mdn-dev IRC mentions and replaced some of them with #mdn when I found it relevant. Please tell me if `deploy.rst` (and `troubleshooting.rst` not touched in this PR) should be treated differently.
=> Replaced IRC mentions with Matrix equivalents.

kuma/settings/common.py
It ain't pretty but it's more important that it blocks launch than fails subtly in runtime. 
These work:
```python
from email.utils import parseaddr
EMAIL = "Janet Swisher - MDN Community Lead <mdn-admins@mozilla.org>"
assert parseaddr(EMAIL)[1].count("@") == 1, parseaddr(EMAIL)
EMAIL = "no-reply@mozilla.org"
assert parseaddr(EMAIL)[1].count("@") == 1, parseaddr(EMAIL)
```
This crashes:
```python
EMAIL = "Janet Swisher, MDN Community Lead <mdn-admins@mozilla.org>"
assert parseaddr(EMAIL)[1].count("@") == 1, parseaddr(EMAIL)
```
...with...
```
Traceback (most recent call last):
...
AssertionError: ('', 'Janet')
```
=> check the WELCOME_EMAIL_FROM before it's too late

kuma/javascript/src/hooks/useSubscriptionData.js, kuma/javascript/src/payments/pages/management.jsx
Subscription data is also needed on the account settings Subscriptions component, so rather than duplicate the code, create a hook that both of them can use. The data needed is for this view:
Changes:
- Move code that fetches subscription data into a custom hook 
To test:
- Management page should work just as it used to
- Tests in `payments/pages/management.test.jsx` should still pass 
Part of #7076
=> Create hook to fetch subscription data

kuma/core/utils.py, kuma/users/adapters.py
Fixes #6737
We actually already have retry on the welcome email. But I increased the retry'ing there a bit. 
The most important change is in the sending of verification emails. 
To test; set in your `.env` this:
```
EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
EMAIL_HOST=anything.for.testing
```
and then go to http://localhost.org:8000/en-US/users/account/email and try to trigger the sending of a verification email. It'll just sit there for ~30 seconds and eventually fail (because `anything.for.testing` won't actually work)
=> SMTPServerDisconnected sending confirmation email

kuma/health/tests/test_views.py, kuma/health/views.py, kuma/redirects/redirects.py, kuma/settings/common.py, kuma/urls.py, tests/conftest.py, tests/headless/map_301.py, tests/headless/test_redirects.py
This PR updates the way we handle "legacy" files, all of the really old, rarely accessed files under `/diagrams/*`, `/presentations/*`, and `/samples/*`. However, this PR is really the second step.
The first step, which is already in place, is that all of the files under `/diagrams/*`, `/presentations/*`, and `/samples/*` have been moved to the stage and production media S3 buckets and made available via `https://media.prod.mdn.mozit.cloud` and `https://media.stage.mdn.mozit.cloud`, but the files are exactly the same between stage and production, and always will be since the legacy files are frozen. Also, we've added two new behaviors to the primary stage and production CDN's that serve traffic intended for `/diagrams/*` and `/presentations/*` directly from the appropriate S3 bucket. …
=> fix legacy samples files

docker-compose.yml, kuma/conftest.py, kuma/core/tests/test_views.py, kuma/settings/common.py, kuma/urls.py, kuma/views.py, kuma/wiki/tasks.py, kuma/wiki/tests/test_tasks.py
This PR provides and enables the ability to save the sitemap files to S3. When enabled, it also serves the sitemap files from S3, but for stage and production, those requests will never reach Django but instead be routed (by the primary CDN) directly to S3. This is the last step in eliminating our reliance on EFS. Here are the steps forward regarding EFS:
This is related to our work on https://github.com/mdn/kuma/issues/7034 because that effort to move to EKS was intended to not only reduce the cluster-management burden but also to eliminate the common problem of "stuck" cluster nodes, which we've discovered to be related to our use of EFS.
=> add ability to save/serve sitemaps to/from S3

kuma/wiki/content.py, kuma/wiki/tests/test_content.py, kuma/wiki/tests/test_forms.py
Fixes #7101
I've tested this quite extensively using the Chrome extension and using https://translate.google.com and it works. Very satisfying. 
But what to be tested is the HTML our Python code produces. You can either sacrifice one of your Wiki docs in your docker-compose and just paste HTML snippets into it and hit save and see what it produces. Basically, these:
```html
<pre>something</pre>
<pre class="syntaxbox">something</pre>
```
...should become:
```html
<pre class="notranslate>something</pre>
<pre class="syntaxbox notranslate">something</pre>
```
Arguably, you can't argue with the unit test I wrote :)
What's important to observe is if the `pre` tags still look right. I.e. this new class doesn't interfere with Prism.
=> tell google translate to avoid pre tags

docs/installation.rst, kuma/api/v1/tests/test_views.py, kuma/api/v1/urls.py, kuma/api/v1/views.py, kuma/attachments/tests/test_models.py, kuma/authkeys/tests/conftest.py, kuma/authkeys/tests/test_views.py, kuma/settings/common.py, kuma/users/newsletter/checks.py, kuma/users/newsletter/utils.py, kuma/users/stripe_utils.py, kuma/users/tests/__init__.py, kuma/users/tests/test_forms.py, kuma/users/tests/test_tasks.py, kuma/users/tests/test_views.py
Fixes #7171 
- renames `STRIPE_WEBHOOK_HOSTNAME` to `CUSTOM_WEBHOOK_HOSTNAME`, to make it reusable with other webhooks
- adds a system check which creates a sendinblue webhook, listening to the `unsubscribe` event (analogous to what we did for Stripe)
- adds an associated view route for handling the webhook
- it differs from stripe in that sendinblue doesn't offer signing of the events, so we only interpret the hook being (correctly) called as a nudge, which we then use to contact sendinblue and check whether something did change
- currently we only do that for checking whether a given email is still in the system (and in the correct sendinblue list) and then set the associated user's `is_newsletter_subscribed` toggle accordingly
- start ngrok (proxiying to whatever port you run kuma on) …
=> Sendinblue unsubscribe webhook

kuma/api/v1/serializers.py, kuma/api/v1/tests/test_views.py, kuma/api/v1/urls.py, kuma/api/v1/views.py
Fixes #7246
Hopefully the "unit tests" speak for themselves. But what I did, to sanity check that it would work was this quick hack to user-details.jsx:
```diff
diff --git a/kuma/javascript/src/accountsettings/components/user-details.jsx b/kuma/javascript/src/accountsettings/components/user-details.jsx
index 72309db8a..1b5a908e8 100644
--- a/kuma/javascript/src/accountsettings/components/user-details.jsx
+++ b/kuma/javascript/src/accountsettings/components/user-details.jsx
@@ -1,7 +1,9 @@
// @flow
import * as React from 'react';
+import { useEffect } from 'react';
import { gettext } from '../../l10n.js';
+import { getCookie } from '../../utils';
import LanguageSelect from './language-select.jsx';
type Props = {
@@ -13,6 +15,32 @@ type Props = {
const UserDetails = ({ locale, userData, …
```
=> user_details v1 api

kuma/static/styles/components/compat-tables/_bc-table.scss, kuma/static/styles/components/compat-tables/_vars.scss
The **JavaScript** platform borders became outdated when **IE Mobile** was removed, and the **WebExtension** platform borders became outdated when **Safari 14** added support for **WebExtensions**.
I also merged the selector lists of the border declarations.
---
Fixes <https://github.com/mdn/kuma/issues/7274>
=> fix(compat‑tables): Update platform borders and merge selector lists

kuma/javascript/src/header/__snapshots__/header.test.js.snap, kuma/javascript/src/header/header.jsx, kuma/javascript/src/header/main-menu.jsx, kuma/wiki/templatetags/ssr.py
Fixes #7235
[@Gregoor is right](https://github.com/mdn/kuma/issues/7235#issuecomment-645530001). We can use a `useEffect` to override whatever happens on the server. 
It occurred to me that this value doesn't actually have to be correct in the server. Because it only ever purposes of that link to click it.
=> right current url in report a content problem

docker-compose.yml
Fixes #7270 
Currently, the stage and production Redis instances are running with version `5.0.6`. Let's use the same version within `docker-compose.yml`.
=> redis docker image version should match production

kuma/settings/common.py, kuma/users/adapters.py
Fixes #7331
Simply set 
```
ADDITIONAL_NEXT_URL_ALLOWED_HOSTS=localhost.org:3000
```
in your `.env` and start up `docker-compose`. Now, you can use `http://localhost.org:8000/users/github/login/?next=http://localhost.org:3000/en-US/docs/Web/HTML/Element/audio` and when it's done doing the auth-provider dance it should redirect to `http://localhost.org:3000/en-US/docs/Web/HTML/Element/audio`.
=> allow localhost.org:3000 in the 'next' URL

kuma/core/context_processors.py
(Not tying this to an issue because it's not production-important enough and it's a change that confidently only matters for local development for select few)
Easy to test:
1. Go to http://localhost.org:8000/en-US/users/account/signup-landing?next=http%3A%2F%2Flocalhost.org%3A3000%2F
2. Note that when you hover over GitHub and Google (inside the Sign-in box on the left) that the `?next=...` link is gone
Now, add `ADDITIONAL_NEXT_URL_ALLOWED_HOSTS=localhost.org:3000` to your `.env` and stop/start `docker-compose`. And check out the branch too (obviously 😉)
Now you'll get links like: http://localhost.org:8000/users/github/login/?next=http%3A%2F%2Flocalhost.org%3A3000%2F 
PS. Make sure that links like http://localhost.org:8000/en-US/users/account/signup-landing?next=/en-US/docs/Web/JavaScript …
=> next_url jinja helper to respect ADDITIONAL_NEXT_URL_ALLOWED_HOSTS

kuma/static/styles/components/compat-tables/_bc-signal.scss
Correctly hide and show the different panels of the BCD signaling component
for users using assistive technologies.
There are other much larger problems we need to address when implementing this in Yari, but this solve our immediate, ugly problem 😸 
@peterbe r?
fix #7309
=> correctly hide and show bcd signaling panels

kuma/javascript/src/header/main-menu.jsx
Only restore focus to the previous active element when a user
is using the keyboard as method of input.
fix #7423
=> search input broken due to main menu focus management

kuma/static/styles/minimalist/components/_search-widget.scss
Tested on Chromium 84.0.4147.135 (Official Build) Arch Linux (64-bit)
(notice the border)
This PR changes the search widget's input background to transparent, but it's safe because the parent `.header-search form` has a `#fff` background as well.
=> Fix search widget's border being cut off by input white background

.github/workflows/js-lints.yml
If a PR comes in that edits any `kuma/**/*.(js|jsx|scss)` the "JavaScript and SASS Lints" workflow kicks in. 
But if Dependabot upgrades something like `prettier` or `eslint` in the `yarn.lock` we wouldn't notice if our code is compatible with this. This change hopefully fixes it. 
I learned about this technique here: https://github.com/technote-space/get-diff-action/issues/111#issuecomment-681387855
=> run js lints when yarn.lock gets upgraded

kuma/javascript/src/active-banner.jsx
This adds a call to GA when CTA button to download the report PDF is clicked. Confirmed with GA testing that the following will be sent on click:
```
Running command: ga("send", {hitType: "event", eventCategory: "mdn_browser_compat_report", eventAction: "Browser Compat Report CTA clicked", eventLabel: "banner"})
```
@peterbe r?
fix #7516
=> Add GA to browser compat CTA

kuma/static/styles/minimalist/components/_main-nav.scss
Fix `z-index` for menu on mobile to ensure it is infront of page overlay
fix #7534
=> menu not usable on mobile

kuma/payments/tests/test_views.py, kuma/payments/views.py, kuma/settings/common.py, kuma/settings/pytest.py
Fixes #7537
Pardon the intrusion @escattone but I think this is a much simpler solution. Basically, a rock-solid simple Django setting that, by default, disables subscriptions. Combined with waffle flags, all traffic to anything "payments" will 404. And this way the tests don't have to change.
=> Disable the payments endpoint

kuma/landing/jinja2/landing/homepage.html, kuma/landing/jinja2/landing/react_homepage.html
Remove the smiley icon next to "Help improve MDN" on the homepage
fix #7642
=> fix: remove icon from help MDN

kuma/static/styles/components/users/_user-head.scss
Ensure submenu is fully visible on view profile page
fix #7620
=> fix: profile view - submenu obscured

kuma/settings/common.py
Change the language cookie name that we respect in Kuma to match what we use in Yari (`preferredlocale`), and also change the language cookie expiration period to match Yari as well (3 years). This PR allows locale-less URLs not handled by Yari's Lambda@Edge function, to be handled the same way when they hit Django. So this would cover requests like `/search`, `/profile`, `/profiles/...`, `/users/...`, `/account`, and `/events`, redirecting them by first trying the `preferredlocale` language cookie, then the `accept-language` header, and finally falling back to `en-US`.
This PR fills in the missing pieces from https://github.com/mdn/yari/issues/1889.
=> change language cookie to match yari

kuma/core/views.py, kuma/settings/common.py, kuma/users/views.py
If we just go with Django's default `LANGUAGE_COOKIE_DOMAIN` (which is `None`) we match the behavior of Yari (i.e., the current domain is specified as the cookie's domain, without any leading `.`).
=> use Django default cookie domain so it matches Yari

kuma/landing/jinja2/landing/react_homepage.html
Fixes #7683
I copied the renderd HTML with the Devtools and it becomes this:
```html
<li><a href="/en-US/docs/MDN/Getting_started">Getting started</a></li>
<li><a href="/en-US/docs/MDN/Contribute">Contributing to MDN content</a></li>
<li><a href="https://github.com/mdn/yari#readme">Contributing to the MDN codebase</a></li>
<li><a href="https://github.com/mdn/browser-compat-data">Updating browser compatibility data</a></li>
```
Looks like this:
=> MDN front page "Help improve MDN" links need updating

kuma/attachments/tests/test_views.py, kuma/attachments/views.py, kuma/settings/common.py
There are lots of images that we can't easily download and make as part of mdn/content, so we still rely on a Kuma serving URLs like `/files/3710/Test_Form_2.jpg` that are served via Kuma, which returns a 302 to a S3 URL. 
Increasing the cache-control will significantly increase the probability of an end-user getting a warm cache hit on those images.
=> longer caching on file attachments

kuma/api/v1/tests/test_views.py, kuma/api/v1/views.py
Part of #7734
We don't use it for anything. Perhaps we do/did somewhere in the Wiki, but certainly nowhere in Yari. Perhaps we will some day, but that's a different day and that day it wouldn't be hard to make a tiny change to Kuma.
=> remove use of waffle.Samples in api/v1/whoami

kuma/api/v1/search/__init__.py, kuma/api/v1/search/forms.py, kuma/api/v1/tests/test_search.py, kuma/settings/common.py, kuma/settings/pytest.py
Fixes #7754
Now, these work:
* http://localhost.org:8000/en-US/search?q=foo&locale=en-US
* http://localhost.org:8000/en-US/search?q=foo&locale=en-US&locale=Fr
(they didn't before)
and http://localhost.org:8000/en-US/search?q=foo still works.
=> search locale should be case insenstive

kuma/search/views.py
Fixes #7758
Because the testing is removed for this legacy Django app, I didn't bother with a new unit test. But to sanity check myself, I wrote a little script to check:
```python
import requests
def T(pathname, expect):
r = requests.get(f"http://localhost.org:8000{pathname}", allow_redirects=False)
assert r.status_code == 301, (pathname, r.status_code)
assert (
r.headers["location"] == expect
), f"WANTED: {expect}\tGOT: {r.headers['location']}"
T("/en-US/search.json?q=bar", "/api/v1/search?q=bar")
T("/en-US/search.json?q=bar&locale=fr", "/api/v1/search?q=bar&locale=fr")
T("/en-US/search.json", "/api/v1/search")
T("/en-US/search.json?locale=fr", "/api/v1/search?locale=fr")
T("/fr/search.json", "/api/v1/search?locale=fr")
```
=> Make /$locale/search.json redirect

kuma/health/tests/test_views.py, kuma/health/views.py, kuma/settings/pytest.py
Now http://localhost.org:8000/_kuma_status.json includes search. 
I tested it by doing things like turning off the elasticsearch server, or messing with the index name. 
This "undoes" some of the stuff that got dropped in https://github.com/mdn/kuma/pull/7747/files#diff-6ab9a23c58ba8e2eb4faf8a0031834d663a26064c6f03284f9b7e5145bed941a
But the old unit tests used to not just test the happy path, but also test things like `ConnectionError` and `NotFoundError` etc. I tried to do that too. But after 1h of trial-and-error and hair-tearing I couldn't get it to work. My mock-fu must be a bit lost. I'm not 100% sure but I suspect it's something related to the connection pooling. What I would find is that if I use `pytest .. -k test_status_missing_index` (for example), it would work and my mocking …
=> reinstate search health checks

poetry.lock
Part of  #7745
According to https://github.com/python-poetry/poetry/issues/3128#issuecomment-766295696 you have to do this so that the lock file is rewritten. Otherwise, when you run `poetry update some-single-package-name` will update everything else.
=> update the poetry lock file for poetry 1.1.4

.github/dependabot.yml
Fixes #7745
I just find `poetry` updating bewildering. I struggle to update just one package without it upgrading a bunch of other things. 
Considering that the worst that can happen is that Dependabot makes a PR that fails, let's give this a good start.
=> Let Dependabot upgrade poetry packages

kuma/api/v1/search/__init__.py, kuma/api/v1/search/forms.py, kuma/api/v1/tests/test_search.py
This is the precursor to be able to filter the site-search to specific tree(s). E.g. searching for the word `float` in the CSS reference doc. Or the word `fetch` in the Learning area. 
There's nothing using this yet. We won't add it to Kuma's UI and it's not the right time to add it to the not-yet-launch Yari site-search. But now it becomes possible. 
One interesting potential with this is that this could be a solution to those monster `Index` pages [E.g.](https://developer.mozilla.org/en-US/docs/Web/API/Index) For example, that macro could be made to only show the top 10 sub-pages but with a link at the bottom that is a search. Granted, our search currently always requires a search free-text input, but that's something we could build on. 
My hope is to add to the site-search UI some …
=> slug_prefixes

Jenkinsfiles/utils.groovy
Missed this in #7783. The Jenkins builds are currently broken because of this.
=> remove wait for elasticsearch service in jenkins

kuma/api/v1/search/__init__.py
Fixes #7793
Now 
```
curl "http://localhost.org:8000/api/v1/search?q=%E0%B8%95%E0%B8%B4%E0%B8%94%E0%B8%95%E0%B9%88%E0%B8%AD%E0%B8%AB%E0%B8%99%E0%B9%88%E0%B8%A7%E0%B8%A2%E0%B8%87%E0%B8%B2%E0%B8%99%E0%B8%9A%E0%B8%B1%E0%B8%87%E0%B8%84%E0%B8%B1%E0%B8%9A%E0%B9%83%E0%B8%8A%E0%B9%89%E0%B8%81%E0%B8%8E%E0%B8%AB%E0%B8%A1%E0%B8%B2%E0%B8%A2%E0%B9%83%E0%B8%99%E0%B8%9E%E0%B8%B7%E0%B9%89%E0%B8%99%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B8%82%E0%B8%AD%E0%B8%87%E0%B8%84%E0%B8%B8%E0%B8%93%E0%B8%AB%E0%B8%B2%E0%B8%81%E0%B8%A1%E0%B8%B5%E0%B8%9C%E0%B8%B9%E0%B9%89%E0%B8%95%E0%B8%81%E0%B8%AD%E0%B8%A2%E0%B8%B9%E0%B9%88%E0%B9%83%E0%B8%99%E0%B8%AD%E0%B8%B1%E0%B8%99%E0%B8%95%E0%B8%A3%E0%B8%B2%E0%B8%A2%E0%B9%80%E0%B8%89%E0%B8%9E%E0%B8%B2%E0%B8%B0%E0%B8%AB%E0%B8%99%E0%B9%89%E0%B8%B2" 
```
works.
And …
=> transport error on complex queries for suggestions

kuma/core/context_processors.py, kuma/users/adapters.py, kuma/users/providers/github/views.py, kuma/users/providers/google/views.py, kuma/users/views.py
Once this lands, we can start testing the `/en-US/sign-up` SPA in Yari. Even from prod. 
However, one thing that's a bit weird is that Django will still respond with a HTML page if your CSRF cookie expires or you manually muck around with it and not follow the happy-path.
=> support sign-up from Yari

kuma/settings/common.py
Update the `locale` sub-module. Just prior to this, I updated https://github.com/mozilla-l10n/mdn-l10n (see https://github.com/mozilla-l10n/mdn-l10n/commit/ad7768c807cb587fdac3d6f38be5c8c5a470c1ed).
=> update locale sub-module

kuma/api/v1/tests/test_views.py, kuma/api/v1/views.py
Fixes #7813
I copied these, without much deeper thought, from the existing `kuma/users/views.py` for last time we had to solve this. 
Another solution would/could have been to instead starting to delete these old Wiki models so the referenced foreign keys stop even being a thing. But I think for now this is quicker.
=> ProtectedError trying to close account through /api/v1/settings

kuma/users/views.py
Part of https://github.com/mdn/yari/issues/3377
At least the errors don't fly by silently in the redirect now. 
There's a PR coming for this on the Yari side too.
=> invalid form should yield a JSON 400 response

docker-compose.yml, mockga/Dockerfile, mockga/README.md, mockga/index.js
I think the culprit is myself. I wrote both the `mockga` service in `kuma` and the test server for `deployer/aws-lambda/content-origin-request` in Yari. They both use port `:7000` but default. That's annoying because every time I start up the `yarn serve` in `deployer/aws-lambda/content-origin-request` I get a conflict and I have to switch to the other window to kill kuma. 
Now, the default port numbers are sufficiently different that this annoying thing won't come up for us.
=> use port :7777 for mockga service

docker-compose.yml
I just recently upgraded to a MacBook pro with an M1 chip, and needed to do this.
=> fix for docker-compose on m1 macs

kuma/api/v1/views.py
Remember this? https://github.com/mdn/kuma/pull/7815
You can't rely on `request.META['CSRF_COOKIE']` on the initial load but technically this view function clearly checks, on line 129, that you can't even get that far if you're not signed in. 
But it just doesn't feel right relying on returning something that might be null. `get_token` feels like the more appropriate API to use.
=> use get_token for csrf instead of header

.github/dependabot.yml
Based on https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#package-ecosystem
Don't know if this is going to work. Or how to test it.
=> start Dependabot to check docker

kuma/api/v1/search/__init__.py
Fixes #4024
I tinkered and tinkered until I started getting much better relevance. 
Some documents' body contains certain keywords like `array` and `slice` very often (aka. term frequency), which makes Elasticsearch think they're very relevant. But the title is almost always more important and from my gut, what you'd expect to see higher up in the search results. 
This PR just adjusts the knobs very gently to give slightly more favor to the `title` matches instead of the `body` because `body` matches can get unrealistically high match score because they repeat certain keywords.
=> favor title a bit more in site-search

docker/images/kuma_base/Dockerfile
I suspect in the olden days we used to depend on a python lib, like [django-tidy](https://pypi.org/project/django-tidy/) to post-process HTML in the Wiki.
=> drop libtidy-dev from apt install

docker/images/kuma_base/Dockerfile
I have no idea why we had this. Either way, Kuma no longer deals with images. There are no more uploads going through. We do still deal with file attachments but Kuma doesn't go near the actual binary content. Just a matter of redirects to the S3 bucket.
=> drop libjpeg-dev from apt install

kuma/api/v1/subscription.py, kuma/api/v1/tests/test_subscription.py
Now all stripe related API endpoints depend on `subscription` waffle flag.
=> make subscription_config depend on subscription flag

docker-compose.yml, poetry.lock, pyproject.toml
We've been using `gevent` as our worker class for `gunicorn` for over a year now (it replaced `meinheld`), but forgot to switch the worker class in our `docker-compose.yml`.
- Use `--worker-class=gevent`
- Remove dependency on `meinheld`
=> match gunicorn worker-class with prod in docker-compose.yml

.github/workflows/python-lints.yml, kuma/users/tests/test_adapters.py
At some point, `pyproject.toml` and `poetry.lock` got a new version of black. 
E.g. https://github.com/mdn/kuma/commit/c705739a2596b0d8af7e47ad35a3c79f865bb4d6
What happened was that `.github/workflows/python-lints.yml` never ran. Now what happens is that the version of `black` you get inside the docker container *doesn't match the version* of `black` used in `python-lints.yml`. 
Worse, because it wouldn't even have noticed because a change to `pyproject.toml` our `.py` files no longer match that version that you get inside the docker container. So, when you run `black` inside `bash` on your docker container, it says some files aren't formatted even though nobody's touched them for ages. 
This PR solves both problems.
=> unbreak black and Dependabot upgrades

.github/dependabot.yml
It's just too chatty at the moment. 
There's too little value to upgrade these more frequently than weekly. 
And for the record, one can always push for a refresh by going to https://github.com/mdn/kuma/network/updates/175308387
=> calm down Dependabot

kuma/settings/common.py, kuma/users/auth.py
Limit authentication to users that have an active FxA account **and** an active `mdn_plus` subscription.
=> limit logins to subscribers

kuma/core/tests/test_validators.py
See: https://github.com/psf/black/releases/tag/22.1.0
> Black now normalizes string prefix order (https://github.com/psf/black/pull/2297)
=> style(python): reformat with Black 22.1.0

kuma/api/tests/test_admin.py, kuma/api/v1/plus/notifications.py, kuma/notifications/management/commands/extract_notifications.py, kuma/notifications/utils.py
Part of https://github.com/mdn/yari-private/issues/981.
1. `/update/` created only BCD Update Notifications.
2. `/create/pr/` created a single Content Update Notification independently.
1. `/update/` creates both BCD **and Content** Update Notifications.
2. `/create/pr/` creates a single Content Update Notification **by reusing the same logic**.
=> feat(notifications): process Content Updates via /update/ route
